### ISSUE TITLE
Formatting of multi line string

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1016]
Multi line string are stripping the common whitespace prefix. I think the formatter should maybe be aware of this to indent those string correctly.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=QHNlcnZpY2VUaXRsZSgiYWJjIikKbmFtZXNwYWNlIE15U8YgIHsKIM0BQGRvYygiIiLPFyAgYWJj0RRkZWbRFGdoadEUIiIiKc8VbW9kZWwgRm9v8QCCICBpZDogc3RyaW5nO88cfQoKICBvcCB0ZXN0KCk6xEA7Cn0K)

```cadl
              @doc("""
                abc
                def
                ghi
                """)
              model Foo {}
```

gets formatted to (Keeps the indentation of the string literal)
```cadl
@doc("""
                abc
                def
                ghi
                """)
model Foo {}
```

but maybe it should format to 

```cadl
@doc("""
  abc
  def
  ghi
  """)
model Foo {
  id: string;
}

```

**Comment by markcowl** [comment]
pri: 2
est: 2

**Comment by timotheeguerin** [comment]
After discussion of the following options for formatting, option 2 was the favorite

```tsp
namespace Foo {
  @doc("""
  Hello
  World
  """)
  model One {} // Closing aligned like a closing }

  @doc("""
    Hello
    World
    """)
  model Two {} // Closing aligned with Words

  @doc(
    """
    Hello
    World
    """)
  model Three {} // Aligned next line

  @doc("""
       Hello
       World
       """)
  model Four {} // Aligned with starting """


  @doc("""
    Hello
    World
  """)
  model Five {} // BREAKING: require change to intreptation of multi-line string
}
```
