### ISSUE TITLE
Suppress `x-cadl-name` output in OpenAPI emitters by default, turn on via option

### ISSUE THREAD

**Issue by daviwil** [microsoft/typespec#1029]
I received some feedback from the API Stewardship Board in August that the `x-cadl-name` metadata we attach to schemas in our OpenAPI emitter output is noisy and should not be added by default.  They see the value in having it for debugging purposes, though, so we should allow it to be enabled via an option.

**Comment by markcowl** [comment]
pri: 2
est: 2

**Comment by markcowl** [comment]
**Describe the breaking change**

The `x-cadl-name` extension, currently emitted by typespec-autorest for inline schema, will be omitted by default

**Back-compat design to avoid immediate breaking**
The feature can be turned on through TypeSpec emitter configuration

**Link to detailed breaking design**

**Impact**
This change affecting:

- [x ] ARM
- [x] Data-plane
- [x] Existing specs: approx. # of service/spec impacted ~16: https://github.com/search?q=repo%3AAzure%2Fazure-rest-api-specs%20x-typespec-name&type=code 
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: July 2023

**Additional information**
Add any other information about the change including fixes for here.

**Comment by abatishchev** [comment]
@timotheeguerin can you please update the doc with a better example how to turn it on back? which emitter with which option?

**Comment by abatishchev** [comment]
I see, so it must be `include-x-typespec-name`.

**Comment by timotheeguerin** [comment]
yes indeed `include-x-typespec-name: inline`, the release notes mention the new entry 
https://azure.github.io/typespec-azure/docs/release-notes/release-2023-07-11#azure-toolstypespec-autorest-emitter

**Comment by abatishchev** [comment]
Sorry, my bad, somehow incorrectly copy & pasted or overlooked the right name. Thanks!
