### ISSUE TITLE
VSCode extension has weird behavior for language server path

### ISSUE THREAD

**Issue by rynowak** [microsoft/typespec#1042]
I was running into a message about a mismatch of CADL compiler and language server versions. Following the guidance about how to fix that ran me into some weird problems.

## Issue 1 - settings page is out of date

The recommended guidance is out of date. `..../node_modules/.bin/cadl-server` is not the right path.

![image](https://user-images.githubusercontent.com/1430011/190274849-072e0bc7-e0ec-4196-8cc5-56d01ace1db4.png)

If I use this as the path, then the extension ignores it completely 
![image](https://user-images.githubusercontent.com/1430011/190274974-58166705-bd5e-4206-adfa-43ae1664a9af.png)

## Issue 2 - putting in a bogus path leads to a crash

At this point I had @nguerrera help me. We discovered the right path and tried that. For me it's `${workspaceRoot}/cadl/node_modules/@cadl-lang/compiler`.

However If I tweak this to be something invalid like `${workspaceRoot}/cadl/node_modules/@cadl-lang/compiler/foo` then the VS Code extension starts thrashing and crashes.

**Comment by markcowl** [comment]
- fix old way of specifying language server
- update docs
- better message / experience if path is invalid

**Comment by markcowl** [comment]
pri: 0
est: 5

**Comment by nguerrera** [comment]
Docs updated in #1099

Fixing old way and better experience still tracked by this.

**Comment by RodgeFu** [comment]
config has been updated to typespec.tsp-server.path. And if an invalid path is given. Proper error would be reported as below instead of crash. 


![Image](https://github.com/user-attachments/assets/69ac6a73-0952-4eef-8a2d-cf036a2fe284)
