### ISSUE TITLE
Document and enforce test naming pattern

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#1079]
In order to help with test explorer rendering or when seeing a test name out of context, top-level describe should be prefixed with project name. Over time, we stopped doing this consistently. I've just sent PRs to clean up but it would be nice to document this and enforce it in PR validation.

**Comment by timotheeguerin** [comment]
There is an eslint rule we can give a regex for it but guess that would apply to nested describe as well.
Might need to be a custom rule.

**Comment by markcowl** [comment]
pri: 1
est: 3

**Comment by timotheeguerin** [comment]
This is now unnecessary as vitest groups per file
