### ISSUE TITLE
Linter best practices and improvements

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1105]
As https://github.com/microsoft/cadl/pull/1030 added a new linter system as a separate package this uncover a few issues on how we were doing our linter rules. Should define some best practices for linter rules:
- [ ] rule name vs diagnostic names
   - Rule should tell what diagnostic code it will emit?

**Comment by allenjzhang** [comment]
Let's create a naming proposal and run it thru design meeting before updating the lining rules and docs.
