### ISSUE TITLE
Rest validation is not running if @cadl-lang/rest is not imported in cadl

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1139]
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=b3AgdGVzdCgpOiBzdHJpbmc7CscTMcQUaW50MzI7Cg%3D%3D)

```cadl
op test(): string;
op test1(): int32;
```
result in a single operation `test1` that overrode `test`

```json
"get": {
        "operationId": "test1",
        "parameters": [],
        "responses": {
          "200": {
            "description": "The request has succeeded.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "integer",
                  "format": "int32"
                }
              }
            }
          }
        }
      }
```

Think solution is to have openapi3 and autorest emitter require user to import `@cadl-lang/rest` using the required import.

This however feels like quite an edge case where you wouldn't have written any rest annotations(@route, @get, etc.)

**Comment by markcowl** [comment]
est: 3
pri: 2
