### ISSUE TITLE
Should nested @body be allowed

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1141]
Currently this fails 
```cadl
import "@cadl-lang/rest";

using Cadl.Http;

model Image {
  @header contentType: "application/octet-stream";
  @body body: bytes;
}

op doStuffWithBytes(data: Image): int32;
```
with 
```
Operation has a @body and an unannotated parameter. There can only be one representing the body
```

This error is a bit confusing, believe we should either disallow nested @body and give a relevant error or this should be working.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKbW9kZWwgSW1hZ2UgewogIEBoZWFkZXIoImNvbnRlbnQtdHlwZSIpIMcPVHlwZTogImFwcGxpY2F0aW9uL29jdGV0LXN0cmVhbSI7xENib2R5IMQFOiBieXRlczsKfQoKb3AgZG9TdHVmZldpdGhCxBgoZGF0YTrGfSk6IGludDMyOwo%3D)

**Comment by bterlson** [comment]
Nested @body seems like it should work, I think?

**Comment by kevinswiber** [comment]
This check doesn't take into consideration the impact of nested decorators on model properties.  It's failing because the `data` parameter on the operation isn't annotated, and in the flattened view, it's being seen as an implicit body parameter.

https://github.com/microsoft/cadl/blob/2c0cd0b85f5414ec3a22c57fbc60c66646132b58/packages/rest/src/http/parameters.ts#L115-L135

**Comment by kevinswiber** [comment]
Interesting to note that this _will_ work:

```cadl
import "@cadl-lang/rest";

using Cadl.Http;

model Image {
  @header("content-type") contentType: "application/octet-stream";
  body: bytes;
}

op doStuffWithBytes(@body data: Image): int32;
```

**Comment by kevinswiber** [comment]
One way around this is to introduce another decorator, `@inline` on the operation parameter. Otherwise, I think this error is correct. Even though it's empty, it's essentially saying it expects `data: {}` in addition to the `@body`-tagged property.

**Comment by kevinswiber** [comment]
Sorry for all the comments, but I suppose this should also work...

```cadl

import "@cadl-lang/rest";

using Cadl.Http;

model Image {
  @header contentType: "application/octet-stream";
  @body body: bytes;
}

op doStuffWithBytes(...Image): int32;
```

**Comment by timotheeguerin** [comment]
> Sorry for all the comments, but I suppose this should also work...
> 
> ```
> 
> import "@cadl-lang/rest";
> 
> using Cadl.Http;
> 
> model Image {
>   @header contentType: "application/octet-stream";
>   @body body: bytes;
> }
> 
> op doStuffWithBytes(...Image): int32;
> ```

Yeah that one would probably be the way you'd want to it in most cases. This wasn't really about the lack of ability to represent what I wanted but the behavior of that specific cadl spec that is not valid while not giving a great error message.

**Comment by nguerrera** [comment]
#1141 is out with the fix. The current behavior is an accident with "unannotated parameter" computation not accounting for this and hard-to-understand error. I believe at a prior design meeting the consensus was for folks to speak up here if they had concerns. Seeing none, I propose taking #1141. cc @bterlson
