### ISSUE TITLE
Better error message when node.exe isn't in path

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#1153]
Sometimes, for reasons, node.exe may not be in a users path. There should be a better error message.

Additionally, allowing users to configure an explicit node path so that they don't need node.exe in their environment would probably be welcome in exotic situations.

**Comment by timotheeguerin** [comment]
Is there not a way to use vscode node.exe?

**Comment by nguerrera** [comment]
There is a way. We stopped using it because at one point VS Code node was too old for us.

**Comment by nguerrera** [comment]
The way is to pass a `NodeModule` instead of an `Executable` to the `LanguageClient` constructor in extension.ts.

**Comment by mzhongl524** [comment]
Can provide better error message , verified
