### ISSUE TITLE
Should deprecated decorator be a directive instead

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1166]
Right now we cannot deprecate certain things including decorators as those are not decorable.

```
#deprecated "Reason"
```

other alternative could be a doc comment tag

```
/**
 * @deprecated Because XYZ
 */ 
```

Thing is it might be weird then having warnings emitted from a doc comment annotation but maybe that's a flag in the compiler so deprecated items are not blocking a `--warn-as-error` flow

**Comment by markcowl** [comment]
- decorators
- aliases

**Comment by timotheeguerin** [comment]
will be resolved by #2107
