### ISSUE TITLE
regen-samples should allow args to specify subset of samples to regen

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#1170]
Maybe a regex match or something. Working with @daviwil today I notice we both spend wasted effort to prune down the list of samples regen'ed. Would be nice to be able to pass some args rather than edit the script.

**Comment by markcowl** [comment]
est: 2

**Comment by nguerrera** [comment]
Just a note on something slightly non-trivial in implementation: this should only delete the output for the samples it regens.

**Comment by timotheeguerin** [comment]
Completed last sprint runnign `npm test -- -g '<name of sample>'`
