### ISSUE TITLE
Emitter context

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1177]
Update `onEmit` to take an `EmitterContext` as the first argument.

Functionality that would be good:
- `emitFile`/`writeFile`: Write the given content at the give path
   - Should recursively create the parent folders 
   - this would allow us to track which file was emitter by which emitter
- Could have the `output-dir` if we make `output-dir` a emitter options that every emitter can be provided.

**Comment by tjprescott** [comment]
Alternatively/addtionally the `@cadl-lang/compiler`'s `emitFile` helper should do the same thing to ensure the destination path exists instead of just erroring out.

**Comment by bterlson** [comment]
I think we should look more holistically across all emitters to determine what kinds of functionality we will need. I started such a proposal last week but haven't had a chance to pick it back up. I have a strong feeling something higher level than just `writeFile` is needed. Not that the low-level stuff isn't necessary, I would just rather ensure that we are putting the right low level primitives in if we're going to break emitters by changing the signature.

**Comment by timotheeguerin** [comment]
Believe this was done
