### ISSUE TITLE
The @useAuth decorator does not support security requirements at the operation level

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1210]
The Cadl Http library provides a `@useAuth` decorator that allows one or more security schemes to be defined and then applied globally to all operations. But some services need to define different security requirements for different operations, for example requiring a "read" scope for read operations but a "write" scope for write operations. Cadl should provide a mechanism to define security requirements at the operation level.

**Comment by timotheeguerin** [comment]
We decided that on purpose until we figured out a better way to have client level parameters.

**Comment by timotheeguerin** [comment]
Design proposal https://gist.github.com/timotheeguerin/56690786e61a436710dd647de9febc0f

**Comment by timotheeguerin** [comment]
implementation https://github.com/microsoft/typespec/issues/2624
