### ISSUE TITLE
Add library linter rule to make sure every decorator in JS also has an `extern` declaration

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1214]
Add to the library linter that a library can use to verify they are following the best practice when publishing a cadl library.

**Comment by markcowl** [comment]
est: 5

**Comment by timotheeguerin** [comment]
Doing this now as we have too many decorators without and it makes it hard to do the `valueof` migration. Having the linter rule was easier than finding manually what was missing.
