### ISSUE TITLE
Implement backticks for escaping identifiers in Cadl

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#1221]
Implementation issue for: https://github.com/microsoft/cadl/issues/869

Allow escaping identifiers using backticks:

```cadl
op `import`(): void;

model `this is my mode name` {...}
```

Need to remove the string literal for model property keys and enum. Could do this as a transition where the formatter formats automatically

**Comment by markcowl** [comment]
est: 8

**Comment by nguerrera** [comment]
@leni-msft Can we sync up on this one? I can provide a lot of hints on how to approach this since I happened to have thought about it a lot.
