### ISSUE TITLE
`@renamedFrom` should ensure the old property isn't still present in definition

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#1244]
https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CtIZdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR070BtIdHRw0RVSZXN0OwoKQMdVZWQox0JzKQpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCmVudW0gyFAgxEYidjEiLMUIMsQ7Cgptb2RlbCDHVcQiQGtleSBpZDogc3Ry5QDGICB3ZWlnaHQ6IGludDMyxBFjb2xvcswiQHJl5ACEZEZyb23pAMEudjIsICLFLCIpIHNoYWRlyjR9CgpAZXJyb3LnAIJFxAzlAIFjb8QoyWxtZXNzYWfOOmludGVyZuQA8OYAuecA8iBleHRlbmRzIFJlc291cmNl5AFexQlPcGVyYXTkAJU8xjIsxnE%2BxXJAYWRk6wF5LnYyKcQWZ2V0xAdyb3V0ZSgiY3VzdG9tR2V0IsQdyQ4oKTrnAIXkAJo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

**Comment by allenjzhang** [comment]
Need to add a linting rule to avoid confusion.

pri: 3

**Comment by tjprescott** [comment]
@nguerrera I'm confused why your multi-version spec only produces a single openapi.yaml file. In this case, I don't think `@renamedFrom` should remove the definition on line 23. Instead, the compiler should complain that the property is defined twice on a model when projecting v1. The correct syntax should be:

```
model Widget {
  @key id: string;
  weight: int32;
  @renamedFrom(Versions.v2, "color") shade: string;
}
```

This would produce color in v1 and shade in v2.

**Comment by nguerrera** [comment]
>  confused why your multi-version spec only produces a single openapi.yaml file

I think maybe there's a separate bug unrelated to this. Even the API versionining sample is only showing one output file.

> The correct syntax should be:

This bug report was about giving an error in this incorrect usage case.

**Comment by nguerrera** [comment]
Filed https://github.com/microsoft/cadl/issues/1503

**Comment by nguerrera** [comment]
> the compiler should complain
This was what the bug is asking for

**Comment by tjprescott** [comment]
@markcowl why is this marked required for DPG 1.0? This is also blocked by #1500.

**Comment by tjprescott** [comment]
For the record, this would not be a "linting rule". This would be an error.
