### ISSUE TITLE
Considering have a way to dump the configurations for cadl compiler and all emitters

### ISSUE THREAD

**Issue by jianyexi** [microsoft/typespec#1259]
Since we're going to support the interpolations or variables in the cadl-project.yaml , https://github.com/microsoft/cadl/issues/1252 , it might become hard to get know the concrete configuration when running cadl compiler manually, it will be useful if we want to check if the cadl-project.yaml is expected without running the cadl compiler, as I know autorest have a similar function

**Comment by markcowl** [comment]
@jianyexi Can you suggest specific updates to `cadl info` ?
