### ISSUE TITLE
[BUG] The Share and Open Issue buttons do not work

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#1265]
If you navigate to the cadl playground from the main page [here](https://microsoft.github.io/cadl/docs/setup/installation/) you get this location [here](https://microsoft.github.io/cadl/play/), and the `Share` and `Open issue` buttons do not work.

If instead you navigate to `aka.ms/trycadl` directly you get to [this location](https://cadlplayground.z22.web.core.windows.net/) and the buttons work as expected.

**Comment by timotheeguerin** [comment]
Seems to be problem with having the playground in an iframe

**Comment by timotheeguerin** [comment]
Think ulitmately we could just have the playground bundled on the website instead as an iframe but as a quickfix seems like we can just give permission https://stackoverflow.com/questions/61401384/can-text-within-an-iframe-be-copied-to-clipboard

**Comment by timotheeguerin** [comment]
This has been fixed
