### ISSUE TITLE
Emitter and errors recommended behavior

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1309]
Taking the design part of this issue https://github.com/Azure/cadl-azure/issues/2281

We should decide a recommendation on what emitter should be doing when they get to a cadl concept they cannot represent:
- emit error and don't emit
   - prevent breaking changes if emitter end up supporting a more granular type
- always emit to the best of ability and emit warning
   - should be able to take any spec and be able to emit it
   - without that user has to restrict his spec to the common denominator of all emitters supported features

**Comment by markcowl** [comment]
Note that this has already been done for types, and is implicit for decorators.  What other concepts might they need to account for?

**Comment by markcowl** [comment]
@timotheeguerin Can you clarify what else we need to discuss in a design meeting on this issue?

**Comment by timotheeguerin** [comment]
@markcowl what do you mean by "already been done for types,"

**Comment by markcowl** [comment]
Per discussion, this will be covered as part of this: https://github.com/microsoft/typespec/issues/1705  with a discussion of the 'unknown' type
