### ISSUE TITLE
Do we still want the format decorator in core

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1329]
Now that we have `scalar` and there is a relationship between them it means that we dont loose the model name like with `model foo is uri`

If you have `scalar MyUri extends uri` we are able to figure out its an `uri` without the `@format` decorator.  Question is then do we really need it. It feels like a copy of openapi `format` property but we don't really need to have it in cadl.

To me this seems redundant to have `@format` which is not typed and doesn't let us have levels of formats like:

```cadl
scalar uuid extends string;  // @format("uuid")
scalar uuid4 extends uuid;  // @format("uuid4") would have no relation to uuid
```

**Comment by bterlson** [comment]
Don't we still want this for things like serialization hints for dates?

**Comment by timotheeguerin** [comment]
well I think we never made a descision on this for date. That being that `@format` on a string meant the opposite, it meant that this is a string over the wire but it might be treated as a unique type. (`uri`, `uuid`)

For date we want to say how to serialize this date type. We could repurpose it also to be that exact meaning.

**Comment by allenjzhang** [comment]
Agreed to close.
