### ISSUE TITLE
Documentation for @query, @header, @path decorators should describe optional parameters

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1343]
Parameters of the `@query`, `@header`, and `@path` decorators should be documented in the [README.md of the REST package](https://github.com/microsoft/cadl/blob/main/packages/rest/README.md).

**Comment by timotheeguerin** [comment]
The rest doc in the website has them https://microsoft.github.io/cadl/standard-library/rest/decorators#header

We should maybe cleanup the readme to point to the website instead or make sure we are in sync.

**Comment by markcowl** [comment]
validate the generated docs have this and README points at them

est: 1

**Comment by mikekistler** [comment]
Just checked and it appears that the "format" option is not described in the doc. This may be simply that the "QueryOptions" model is not described.

https://microsoft.github.io/cadl/standard-library/rest/reference/data-types#Cadl.Http.QueryOptions

**Comment by tjprescott** [comment]
> Just checked and it appears that the "format" option is not described in the doc. This may be simply that the "QueryOptions" model is not described.
> 
> https://microsoft.github.io/cadl/standard-library/rest/reference/data-types#Cadl.Http.QueryOptions

This seems to be because the model parameters were documented with TypeScript doc comments instead of the `@doc` decorator.

**Comment by tjprescott** [comment]
> Just checked and it appears that the "format" option is not described in the doc. This may be simply that the "QueryOptions" model is not described.

This seems to be true of all the generated docs for models. They document the model itself but not the properties contained within.

**Comment by tjprescott** [comment]
@mikekistler the problem with "format" is true across all of our packages. I created this issue to document the deficiencies: https://github.com/microsoft/typespec/issues/1749
