### ISSUE TITLE
Emit error when attempting to target augment decorators at an instantiated template

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#1354]
Implementation issue for: https://github.com/microsoft/cadl/issues/1160

Cadl like:

```cadl
model Test<T> {
  testProperty: T;
}

op stringTest() : Test<string>;
op intTest(): Test<int32>;

@@doc(Test<string>, "This is a string instantiation of the template")
@@doc(Test<int32>, "This is a 32-bit integer instantiation of the template")
```
Do not actually differentiate between instantiations of the template.  The diagnostic should indicate that you cannot decorate a template instantiation

**Comment by markcowl** [comment]
est: 3

**Comment by tjprescott** [comment]
PR https://github.com/microsoft/typespec/pull/1744 has a significant limitation that it won't let you target any symbol with template arguments. This prevents it from being used in certain scenarios that _should_ work. Arguably, we could proceed with this PR to block the bug behavior, accepting the limitation, and have a follow-up issue and PR to resolve the limitations. cc/ @timotheeguerin @markcowl
