### ISSUE TITLE
Decide on representation of enum values in OpenAPI3

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#1371]
We should be crisp about the meaning of enums in Cadl in general:
- enum is a fixed set of values that can be updated in a new api-version
- We may need additional patterns for
  - enums that will never add values
    - is this really a pattern?
  - enums that may add values without changing api-version
    - can this be represented using example values?
- Decide on how enums should be represented in OpenAPI3
  - Should we bring over any part of x-ms-enum?

**Comment by mikekistler** [comment]
I don't mind deferring the work to document how `@knownValues` is used by the OpenAPI emitter _if_ this design issue is taken up quickly.  But if this design discussion does not happen until March (as the milestone seems to indicate), that means that our documentation is incomplete / incorrect for at least 3 months, and that seems too long to me. Can we move up the date for this design discussion to at least Feb (i.e. we'd discuss in a design meeting in January)? If that's not possible, then I think we should either document the current behavior or remove it so that our docs accurately reflect the behavior of the code.

**Comment by stefan-schweiger** [comment]
Just to have it here as well for better visibility for this discussion

https://github.com/microsoft/cadl/issues/189#issuecomment-1362578168

> It's kind of hard to follow all the discussion around the topic of extensible enums. What would actually be generated for those extensible properties? I've seen mentioned a few times the x-ms-enum pattern or using anyOf.
> 
> For example there is the "zalando" way of doing it like this, which is what I would like to do:
> 
> ```
> DeliveryMethod:
>   type: string
>   x-extensible-enum:
>     - Parcel
>     - Letter
>     - Email
> ```
> 
> There is an ongoing discussion in the OpenAPI specification about this topic. Maybe some comments in there could be a good inspiration for what people are currently using to define extensible enums, and it would be great if at least a few of the more common ones could be achieved with cadl.
>
> https://github.com/OAI/OpenAPI-Specification/issues/1552

**Comment by mikekistler** [comment]
This is resolved. The openapi3 emitter generates enums and unions of string values as `enum`.

**Comment by stefan-schweiger** [comment]
@mikekistler how would one generate one of the alternative extensible formats? write a custom emitter?

**Comment by mikekistler** [comment]
I don't think you need a custom emitter -- you can just add the extension by hand.

[Playground example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZb3BlbmFwaSI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwO8cVT3BlbkFQSTsKCkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAogIHZlcnNpb246ICIxLjAuMCIsCn0pCm5hbWVzcGFjZSBEZW1vxy87Cgptb2RlbCDHRsRZQHZpc2liaWxpdHkoInJlYWQiLCAidXBkYXRlIinEIHBhdGgKICBpZDogc3RyaW5nOwogIHdlaWdodDogaW50MzLEEUBleHRlbuQAiCgieC1tcy1lbnVtIizFYyAgIuQAjyLpAL9Db2xvcuUAvCAgIuUAkkFzU8VcIjogdHJ1ZQogIH3EfWPEKTogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcucAz0XEDMVrY29kZesAlm1lc3NhZ2XqALrEOnJvdXRlKCIvd%2BUAjHMiKQpAdGFnKOcAnMQQaW50ZXJm5AE9xxTFXEDkATPkASIo5QEU6wESKTrHKSB85gCMxGk%3D)
