### ISSUE TITLE
Enhance the existing documentation on the Record type

### ISSUE THREAD

**Issue by claudiababescu** [microsoft/typespec#1427]
We are in the process of writing CADL emitters to Python, Java and C#. 

Is it possible to add some more documentation of using Record in CADL ? 

We looked at the documentation but it wasn't completely clear on how they'd translate to the different languages and more so when we'd use it to write good CADL models. 

A clarification of the fact that the key is always a default string would be very useful as well (ie. explain that Record<string> is basically Record<string, string>) 

More examples in the playground with how best to model using Record would be much appreciated.

**Comment by markcowl** [comment]
est: 2
