### ISSUE TITLE
Tracing should work in the IDE

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1437]
Right now don't think there is a way to enable the compiler trace and have the output show up in vscode. This makes it hard/impossible to debug costumer issues

**Comment by markcowl** [comment]
est: 5 (timebox)

**Comment by chunyu3** [comment]
When config trace in tspconfig.yaml like following to enable trace in all area 
```
emit:
  - "@typespec/openapi3"
trace: "*"
options:
  "@typespec/openapi3":
```

The compiler trace log will show in the vs code output  as following:
![Image](https://github.com/user-attachments/assets/7a8dd04e-f20a-410a-b4b1-d1ccbfb24854)

But the log level is not correct. it mistakenly displayed as `debug` level. It may be the inconsistent log-level between compiler and VS code.

tsp compiler only has 3 log level ( trace, warning, error), but vs code has 5 log level (trace, debug, info, warning, error)
