### ISSUE TITLE
Dev doc and @doc consolidation

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1501]
After discussion around consolidating the doc comment and `@doc` decorator

1.  If `@doc` is provided use that

2. Given a doc comment

```cadl
/**
 * Some doc
 * @param abc Doc for param
 */
``` 

- Extract non tagged content (`Some doc` ) and pass it to `@doc`
- Extract param tag and assign it to operation parameters(Call `@doc` with the value on each of the parameter)

**Comment by markcowl** [comment]
/*
 * The doc for this model
 * /
model Foo {
 /*
 * The doc for this property
 * /
  modelProp: string;
}

**Comment by markcowl** [comment]
pri: 2
est: 5

**Comment by nguerrera** [comment]
This is the implementation issue for the unification proposal linked in #927

**Comment by nguerrera** [comment]
Direct link to original proposal: https://gist.github.com/nguerrera/a48a3d8f005eb5322683fc5ddc48c363
