### ISSUE TITLE
Can't pass EnumMember from template param to decorator

### ISSUE THREAD

**Issue by daviwil** [microsoft/typespec#1525]
While working on `Azure.Core` decorators I ran into a problem where passing a template argument to an `extern dec` defined decorator which expects an `EnumMember` raises an error.

When I define a decorator and model type like so:

```cadl
extern dec addTraitProperties(
  target: unknown, 
  traitModel: unknown, 
  traitLocation: EnumMember
);

@addTraitProperties(Traits, Location)
model TraitProperties<Traits, Location> {}
```

I receive this error:

```
/home/daviwil/Projects/Code/cadl/service-traits/packages/cadl-azure-core/lib/foundations.cadl:154:37 - error invalid-argument: Argument 'Location' is not assignable to parameter of type 'Cadl.Reflection.EnumMember'
> 154 | @Private.addTraitProperties(Traits, Location)
```

Obviously this is because I can't constraint the `Location` template parameter to an `EnumMember` so the decorator param checker complains because it doesn't know what type to expect from `Location`.

Perhaps we need to make it possible to express template types for things other than models?

I should note that I didn't encounter this problem until I switched from using `createDecoratorDefinition` to `extern dec` for defining my decorator function.

**Comment by nguerrera** [comment]
Does this not work?
```
model TraitProperties<Traits, Location extends Reflection.EnumMember> {}
```

**Comment by tjprescott** [comment]
![image](https://user-images.githubusercontent.com/5723682/215829822-cbec142e-b6fe-42ec-a010-4c59e839a935.png)

I had to make Traits extend object to get rid of one squiggle, but then making Location extend EnumMember didn't work (and neither did Reflection.EnumMember)

**Comment by nguerrera** [comment]
That squiggle looks like a bug where it says Location is not assignable to Cadl.Reflection.EnumMember, seems it's not considering the constraint.

**Comment by nguerrera** [comment]
Separately, there's not much point to `EnumMember | Union | unknown` as this is the same as simply `unknown` which already includes everything.

**Comment by nguerrera** [comment]
I believe the bug might be covered by https://github.com/microsoft/cadl/pull/1543#issuecomment-1384655362

**Comment by tjprescott** [comment]
> Separately, there's not much point to EnumMember | Union | unknown as this is the same as simply unknown which already includes everything.

The actual signature said `EnumMember | Union | UnknownType` but there's not a `Cadl.Reflection` for `UnknownType` so I assumed `unknown` was the closest.

**Comment by nguerrera** [comment]
Oh I don't think we can express that. This is another case where subtype and value-of-type conflation is biting us. But that is a bit of a weird signature. When is the UnknownType case used? Maybe we can use `null` instead?

**Comment by tjprescott** [comment]
@daviwil can you comment?
