### ISSUE TITLE
Subtyping: overriding property that is a union of literal values with a property that has a type of one of the literal values in the union is rejected

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#1538]
```cadl
model Number {
  value: "one" | "two";
}

model One extends Number {
  value: "one"; // <-- error override-property-intrinsic Model has an inherited property named
                         // value of type one which can only override an intrinsic type on the parent property, 
                        //not one | two
} 
```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgTnVtYmVyIHsKICB2YWx1ZTogIm9uZSIgfCAidHdvIjsKfQoKxipPbmUgZXh0ZW5kc9g2Owp9)

**Comment by bterlson** [comment]
+1 this should be allowed based on our subtyping rules.

**Comment by markcowl** [comment]
@johanste what is the urgency of this?

**Comment by nguerrera** [comment]
I think maybe we should implement the full subtyping rule we envisioned for overrides where overridden property is allowed in all casses where overridden property type is a subtype of base property type.

**Comment by johanste** [comment]
We can solve the problem I ran into by fixing `@overload`s. So not URGENT/blocking.

**Comment by markcowl** [comment]
est: 13

**Comment by johanste** [comment]
I'm running into this again. Reminding myself that the next time we discuss relative priorities, I should argue slightly stronger for this than I previously did....

**Comment by timotheeguerin** [comment]
What was the decision on this issue, are we expanding to allow just this specific case, open it to override as long as its a subtype or something in between?

**Comment by nguerrera** [comment]
I believe we decided to implement the full thing of "open it to override as long as it's a subtype".

**Comment by timotheeguerin** [comment]
Ah ok, i was confused because of the estimate, i thought we already checked for subtype but had extra check to limit

**Comment by nguerrera** [comment]
I think we just estimated blindly there. Great if this is easy. :)
