### ISSUE TITLE
OpenAPI3 file-type emitter option not documented

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1547]
The OpenAPI3 emitter recently added support for output to yaml, with a new 'file-type' emitter option that lets the user choose to emit either json or yaml (defaults to yaml). This new emitter option is described in the [January release notes](https://microsoft.github.io/cadl/next/standard-library/openapi/overview#emitter-options) but not in the [website documentation for the OpenAPI3 emitter options](https://microsoft.github.io/cadl/standard-library/openapi/overview#emitter-options).

**Comment by mikekistler** [comment]
I should add that the doc in the January release notes could be improved. The yaml examples should be explained -- they would be added to `cadl-project.yaml` to specify json-formatted output.  Also, I think the `@cadl-lang/openapi3` string in these examples must be quoted, e.g.:
```
options:
  '@cadl-lang/openapi3':
     file-type: json
```

**Comment by markcowl** [comment]
est: 1

**Comment by markcowl** [comment]
Fixed
