### ISSUE TITLE
Documentation missing for built-in decorators

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1550]
I discovered a neat trick for checking for missing decorator docs. If you compile any cadl file and specify `--trace bind.js.decorator` cadl will print diagnostics that show all the bound decorators in known namespaces.  Filtering this by the "Cadl" namespace and cross checking with the [Built-in decorators](https://microsoft.github.io/cadl/standard-library/built-in-decorators) page on the website shows that the following decorators are missing from the docs:

- [ ] @discriminator
- [ ] @indexer
- [ ] @list
- [ ] @maxValueExclusive
- [ ] @minValueExclusive
- [ ] @overload
- [ ] @projectedName (misspelled - @projectedNames)

**Comment by bterlson** [comment]
These are all manually documented right now. @allenjzhang is looking into auto-generating stdlib docs (along with compiler API docs which are also missing).

**Comment by nguerrera** [comment]
I think for decorators, these should be moved to `extern dec` declarations if only documented in .ts now. That would get picked up by the existing infrasructure and the IDE. I believe we planned to filter out the $-prefixed decorator functions from the JS API docs?

**Comment by markcowl** [comment]
Please find the duplicate issue

**Comment by markcowl** [comment]
verify: are we generating docs from the core library?

**Comment by tjprescott** [comment]
`@serviceVerson` and `@serviceTitle` have been removed... so that's two down 😄
