### ISSUE TITLE
Add versioning to the Cadl Rest library

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1567]
The Cadl Rest library should define versions so that a versioned Cadl file can explicitly specify the Rest library version for each API version with `@useDependency`.

**Comment by markcowl** [comment]
handle with: https://github.com/Azure/cadl-azure/issues/2332

**Comment by markcowl** [comment]
Closing as duplicate for https://github.com/Azure/cadl-azure/issues/2332

**Comment by markcowl** [comment]
Discussion here: https://gist.github.com/markcowl/ac8eea262f670254a948dc8ef2ecfba4

**Comment by markcowl** [comment]
Takeaways from discussion:
- Generally positive about versioning these libraries
- Consuming libraries should not require useDependency, and the behavior without dependency pinning should be as expected (latest) and well-defined
- Need to be explicit about problematic versioning decorations for consuming libraries with pinned and unpinned versions
