### ISSUE TITLE
Add documentation on versioning library to website

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1568]
Add documentation for the versioning library to the "Cadl Standard Library" section of the website docs.

**Comment by markcowl** [comment]
@mikekistler Are you looking for reference documentation or usage documentation (or both)?

**Comment by mikekistler** [comment]
Reference documentation at a minimum.

**Comment by markcowl** [comment]
add section for versioning in library reference, and generate docs there
est: 5
