### ISSUE TITLE
`object` should be inlined in OpenAPI

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#1570]
This feels like a regression, but maybe it's always been this way. It seems pointless to emit an `object` schema like this.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKQHJvdXRlKCIvIikKb3AgdGVzdCgpOiBvYmplY3Q7)

**Comment by nguerrera** [comment]
Ah you're right, I must have been remembering `{}`

**Comment by timotheeguerin** [comment]
object is deprecated now so don't think this matter
