### ISSUE TITLE
Declaring integer

### ISSUE THREAD

**Issue by claudiababescu** [microsoft/typespec#1579]
Hi CADL team,

I noticed that on the 0.39.0 version of the CADL complier you can declare something like this:

```
model Error {
  code: integer; 
}
```

When this gets emitted to Open API I can see code is now {}

```
Error:
      type: object
      properties:
        code: {}
      required:
        - code

```

I noticed that behaviour both with integer and numeric. 

Is this a bug ?

**Comment by markcowl** [comment]
Need to think a bit about how to handle non-leaf types in this instance
- always throw?
- always use the nearest type and issue a warning?
- always use the nearest type and remain silent?

**Comment by mikekistler** [comment]
I'm seeing this issue in Azure APIs so I added the `DPG Impact` label.

**Comment by bterlson** [comment]
I think for OA3 we can use `type: "integer"` for integer. For numeric maybe the best we can do is `type: "number"`, while this may not be a good choice if you intend to support a wider range of precision than floats allow, I'm not sure there's a better choice.

**Comment by markcowl** [comment]
// always use the nearest type and issue a warning diagnostic
  // recommend types to use as part of a documentation
     - most inclusive type
// typespec-azure-core should require leaf types

**Comment by markcowl** [comment]
- Write into the emitters documentation that in this situation, emitters should use the nearest logical type and issue a warning diagnostic, urging the user to select a leaf type
- As part of the documentation, recommend a substitute leaf type and how to choose an emitter-specific representation (for example, c# int/long)
- Ensure that we have an issue for a linter requiring leaf types in cadl-azure-core
- Update the OpenAPI3 and AutoRest emitters to implement this guidance

**Comment by markcowl** [comment]
Design issue complete
