### ISSUE TITLE
Allow default value to be specified even for non-optional properties.

### ISSUE THREAD

**Issue by garethj-msft** [microsoft/typespec#1583]
For the Microsoft Graph use case, optionality isn't specified in CADL's standard `foo? `form, as it's a little too misleading given that every property on Graph is optional via `$select`.  Instead, a decorator `@requiredForCreate` is used for properties that are NOT optional on POST/PUT/some PATCHes.

Currently this also removes the option to specify default values using standard CADL `foo: int=3` syntax.

We'd prefer to be able to specify defaults on non-optional properties, in this case where we're choosing to assert the semantics of optionality in our domain, rather than having the core language choose to make its semantic choices for optionality and default coupled and binding.

**Comment by markcowl** [comment]
Concern: Azure client interpretation of defaults
- params:  use as default client values when no value is specified
- properties:  do nothing
- We should have recommendations for client emitters on how to use default values

**Comment by markcowl** [comment]
@markcowl: create impl issue

**Comment by markcowl** [comment]
Design issue complete, implementation will be in impl issue referenced above
