### ISSUE TITLE
Need Better Instructions for when CADL is not in path for VS extension

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/typespec#1585]
When installing the VS extension, the documentation doesn't really provide any information beyond how to install it. When I open a CADL file after installation it really doesn't look any different than any other Typescript file. Some direction here would be useful.

But the underlying problem in my case is that CADL isn't in the path even though I followed the steps in the instructions to install the tool globally in NPM. If I wait a few seconds after loading a CADL file then I see a message saying the path is invalid. The documentation mentions this and about adding a custom path value to the `.vs` directory. But these instructions are vague and don't work (or at least I'm not doing it right). There is no file in the `.vs` directory matching the name given in the documentation. Is it supposed to be in the `.vs` directory of my projects where my API actually lives or in a `.vs` directory where the cadl project was inited too?

I created the file and named it based upon the docs but, again, the docs are vague and provide no example of what this should really look like. It reminds me of VS Code settings. For the path it says to use the path to `cadl-compiler` but that is inside the directory where the project was inited to so it seems like it should be found there already. Still I added the path and it didn't resolve the error. I tried forward and backward slashes in path just in case.

Some clearly documentation on how to resolve this issue would be nice. At this point the VS extension doesn't really seem to do anything at all even though I open a CADL file. Making this just "install and work" would be the best option of course.

**Comment by markcowl** [comment]
est: 1

**Comment by markcowl** [comment]
The instructions in the README work OK, but these need to be on the website, either in the doc on installing language server extensions, or in the troubleshooting doc
