### ISSUE TITLE
Implementation: Diagnostic for conflict between using and in-scope references

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#1588]
Implementation issue for https://github.com/microsoft/cadl/issues/1162

Make [this](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgTSB7fQoKbmFtZXNwYWNlIEIgewogIMscfQoKdXNpbmcgQjsKCsYYUSBleHRlbmRzxiI%3D) start issuing a diagnostic just like [this](https://cadlplayground.z22.web.core.windows.net/?c=bmFtZXNwYWNlIEEgewogIG1vZGVsIE0ge30KfQoKyh5C0x51c2luZyBBO8cJQjsKCsYhUSBleHRlbmRzxis%3D).

~~NOTE: Design is only tentatively approved pending @bterlson's review. Don't start on this without his approval.~~

**Comment by bterlson** [comment]
I am +1 on the design issue. Feel free to implement!

**Comment by nguerrera** [comment]
That looks different. The openapi emitter is stripping the service namespace out of type names which then conflicts with the global type. The compiler has it straight, I think.

**Comment by tjprescott** [comment]
Ah, got it. I missed that this error came from the openAPI emitter.
