### ISSUE TITLE
Implementation: Allow configuration and enable file path interpolation in emitter configuration for individual emitted files

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#1589]
Implementation issue to support https://github.com/Azure/cadl-azure/issues/2341

Allows configuration of individual file paths for emitted artifacts, using a set of well-known variables
version
version-status
filename

This would enable a relative-path configuration for individually emitted files, starting from the emitter output path:

```yaml
@cadl-autorest:
  openapi-file: {version-status}/{version}/{fileName}.json
```

To support:
- [ ] allow 'version', 'version-status', and 'fileName' to be included in emitter configuration without warnings
- [ ] Add new helper 'interpolateConfiguration' that emitters can use to resollve the configuration.  This would interpolate any known variables in the configuration, and allow the emitter to provide values for 'version', 'version-status', 'fileName' (and potentially, other, future values)

  ```javascript
  interpolatieConfiguration(configValue: string, values: object) : string
  ```
  - configValue is the emitter configuration
  - values are the values to be interpolated for a particular file
- [ ] (can be deferred) implement OpenAPI output file path configuration using the new feature

**Comment by markcowl** [comment]
est: 5

**Comment by serbrech** [comment]
Could you provide an example of how that would work for service group folder structure?
so for serviceGroup folder structure support, we would have:

```
azure-resource-provider-folder: {cwd}/..
openapi-file: serviceGroup/{version-status}/{version}/{fileName}.json
```

thanks

**Comment by markcowl** [comment]
it depends on how it is executed.  It could either be

`open-api-file: <service-group>/{version-status}/{version}/{filename}.json`

or
`open-api-file: <namespace>/<service-group>/{version-status}/{version}/{filename}.json` depending on the value for the emitter output directory.
