### ISSUE TITLE
Implementation: Support RemainingProperties type

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#1590]
Implementation issue for: https://github.com/microsoft/cadl/issues/763

- [x] throw an error diagnostic for a model that extends a record with an incompatible value type
  ```cadl
  model Foo extends Record<string> {
    bar: int32;
  }
  ```
- [x] In OpenAPI3, use `additionalProperties: true` for a model that extends `Record<unknown>`

**Comment by markcowl** [comment]
est:5

**Comment by tjprescott** [comment]
> For constrained additional Properties, a separate model is required.
> ```
> model Foo {
>   bar: int32;
>   additionalStuff: Record<string>;
> }
> ```

@markcowl in this scenario you describe in #763, should the OpenAPI3 emitter do anything special here in regards to `additionalProperties: true`?

**Comment by tjprescott** [comment]
I created this gist to track the scenarios. @markcowl @mikekistler could you take a look and confirm that this is correct, and suggest any additional scenarios:
https://gist.github.com/tjprescott/733cdb1723ecb2a7b791c8eac0cd5058

**Comment by markcowl** [comment]
@tjprescott No, the right thing here is to have a property called 'stuff' is defined as an object with additional properties of type string.  Linting rules should already stop us from having an inline type like this.
