### ISSUE TITLE
CADL Azure Playground shows warnings & links to different documentation than the Try CADL Page. 

### ISSUE THREAD

**Issue by tobybaratta** [microsoft/typespec#1595]
## Description

The Azure Playground shows warnings on the empty template & the Azure Core Data Plane template, links to different documentation than the CADL documentation (links to old Azure docs?), and still shows as using the `@azure-tools/cadl-autorest` emitter rather than the new core packages. 

I am presuming the Azure Playground at some point is going to be merged just into the normal playground or be under some sort of version testing, so I apologize for multiple issues from that same Playground - just thought it'd be good to have them all in one place for anyone else who might stumble upon that Playground. 

I filed a separate issue on the wrong GH account for the "file bug" button being broken, just on the wrong GH account. 

**Reproduction**

1. Go to https://microsoft.github.io/cadl/.
2. Click on the Azure Playground.
3. See warning message on page load.
4. Click on "Azure Core Data Plane" sample. See 31 errors in the upper right hand corner.
5. Click on "docs". See that you are sent to different documentation than you started at without any context or clarification between the azure-cadl and the general cadl docs. (Links to: https://azure.github.io/cadl-azure/).

That page itself also links to playgrounds with broken links to file bugs and documentation overall. Neither are in-line or directly synced with the README here, I believe?

**Comment by markcowl** [comment]
The links in the playground link to repos in a private organization for Azure developers, if you don't have access, they will show up as NotFound.  I think we may consider removing these links from the core package documentation, just to avoid confusion.  Using this issue to track that.

**Comment by markcowl** [comment]
est: 1

**Comment by timotheeguerin** [comment]
This has been resolved, in the embedded playground in the docs website there is no more a link and in the standalone playground the link is correct now
