### ISSUE TITLE
Map Cadl.Reflection types to canonical types for documentation and error messages?

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#1596]
**OLD** 
This was the old behavior where the decorator was validating the target type internally with a helper method.
`Cannot apply @lroStatus decorator to Interface`

**NEW**
After adding the `extern dec` version of this decorator, the error message is now:
`Cannot apply @lroStatus decorator to foo since it is not assignable to Cadl.Reflection.Enum | Cadl.Reflection.ModelProperty`

The new message is better in that it clearly describes what you _can_ do instead of just telling you what you can't. However, the `Cadl.Reflection.` prefix seems verbose and confusing. Spec authors aren't really decorating a "reflection" object (or if they, they aren't thinking of it that way!) and I think it will invite questions like "What's a Cadl.Reflection.Operation? Oh, it's just a regular Operation. Cool."

Right now we have a weird convention where `Type` and `Model` have to be used in `extern dec` as `unknown` and `object`, which results in things like:

**Model**
`Cannot apply @foo decorator to bar since it is not assignable to Cadl.object`

**Type**
`Cannot apply @foo decorator to bar since it is not assignable to Cadl.unknown`

These messages are _really_ confusing.

### Proposal

There seem to be design reasons why we can't just expose `Type` and `Model` in `Cadl.Reflection`, so perhaps a suitable compromise would be to use an internal mapping when these errors are generated.

```
const nameMap = {
  "Cadl.Reflection.ModelProperty": "ModelProperty",
  ...
  "Cadl.object": "Model",
  "Cadl.unknown": "Type"
}
```

Of course, if these don't really map 1:1 then this could make error messages harder to diagnose than easier.

**Comment by tjprescott** [comment]
These reflection types also appear in our generated docs:
![image](https://user-images.githubusercontent.com/5723682/215552037-0f89b223-4b55-433e-a13d-39a5bbe07bfe.png)

**Comment by tjprescott** [comment]
But it does look like the docs do render "Cadl.object" as "model Cadl.object":
![image](https://user-images.githubusercontent.com/5723682/215553743-b02fccea-2268-4276-b150-146fe5d7707f.png)

**Comment by markcowl** [comment]
est: 5
