### ISSUE TITLE
Comments inside blockful namespace with more than one part not auto-formatted correctly

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#1598]
In order for decorators to be documented in our generated docs, we have to put doc comments on the `extern dec` statements. However, some kind of auto-formatting rule relocates these doc comments anytime you save so that ALL the doc comments are put above the first `extern dec` statement.

![image](https://user-images.githubusercontent.com/5723682/215198151-cf5207cf-ce04-49a5-a6f2-5179c5414c30.png)

This doesn't make sense to me, but if the docs can figure it out then okay, whatevs. However, it looks like our ref doc generation does NOT figure it out, giving nonsense output:

![image](https://user-images.githubusercontent.com/5723682/215198627-366c0696-75d9-400d-92e7-0cc495943696.png)

**Comment by nguerrera** [comment]
Yikes, this is bad. I will tak a look right away.

**Comment by nguerrera** [comment]
Are those declarations inside a blockful `namespace Foo { ... }` rather than under blockess `namespace Foo;`. That's the repo I see right now. I happened upon it quickly because I noticed this weirdness in comments on extern decs in .Private namespace last week but thought somebody manually moved them up because they didn't want to document the .Private stuff.

**Comment by tjprescott** [comment]
Yeah, it's a block because there's Azure.Core, Azure.Core.Foundations and Azure.Core.Foundations.Private. I could put them in separate files if that's a suitable workaround.

**Comment by nguerrera** [comment]
It's a reasonable workaround, but I'd like to get this fixed. So far, I am not succeeding though.

**Comment by nguerrera** [comment]
Another workaround seems to be not using `.` in namespace but explicitly declaring hierarchy like this:

```
namespace Azure {
  namespace Core {
     /** ... */
     extern dec a();
     /** ... */
     extern dec b();
     
     namespace Foundations {
       /**... */
       extern dec c();
     }
   }
 }
 ```
 
This one might be better in that you don't have to change the number of files involved when you revert the workaround after a fix.
 
Something about the way we represent those dots is making prettier's life miserable. The way we represent the AST is a little special in that case and I'm not entirely surprised that prettier is confused. There are some overrides in comment-handler.ts, but in this case, it seems the info we need to fix things up is lost so I might need to change the AST. :(

**Comment by tjprescott** [comment]
Thanks @nguerrera I'll go with the second to confine the decorator definitions to one file.

**Comment by nguerrera** [comment]
OK removing my assignment and putting back onto "needs triage" pile since there is a workaround at least. This still seems pretty severe though.

**Comment by nguerrera** [comment]
It impacts more than extern dec and doc comments, basically all comments inside `namespace X.Y { ... }` are vulnerable.

Here's a repor with only regular comments and model statements:

https://cadlplayground.z22.web.core.windows.net/?c=bmFtZXNwYWNlIFguWSB7DQogIG1vZGVsIE0ge30NCsQQLy8gQW5vdGhlcsYbyiRaxSR9DQo%3D

Hit alt+shift+F to format in playground.

**Comment by markcowl** [comment]
est: 8 (timebox)

**Comment by timotheeguerin** [comment]
Hotfixed in 0.45.1
