### ISSUE TITLE
make docs preview link target vNext automatically

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#1599]
I'm working on PR https://github.com/Azure/cadl-azure/pull/2489 that updates our docs.

I can see from the diff that our docs generation scripts are updating the decorator index:
![image](https://user-images.githubusercontent.com/5723682/215201918-ad960f78-02f5-4477-baac-4b8818cab239.png)

However, when I go to the docs preview website for this PR, I don't see any change:
![image](https://user-images.githubusercontent.com/5723682/215202053-1a5e2cef-6ac2-4c9c-9bad-065b88563386.png)

And if I try and refresh that URL, I get a 404.

It _seems_ like it is navigating to the actual live (un-updated) version of the page while partially updating the URL to make it look right. That would explain why I don't see my change and why trying to actually load the printed URL gives an error.

**Comment by markcowl** [comment]
est: 5

**Comment by tjprescott** [comment]
Actually, this turns out to be super easy. The link to the website does not specify vnext, which apparently it needs to for this to work. It will default to whatever you had before, which for me was the live docs. By selecting Next from the dropdown, I see the expected docs.

I think the fix here is that the bot should only give you the full link with vnext.

**Comment by nguerrera** [comment]
I think the second thing is that our staging hosting of the website requires .html on links.

https://cadlwebsite.z1.web.core.windows.net/cadl-azure/prs/2489/docs/next/intro.html

**Comment by tjprescott** [comment]
Awesome, I changed the title to reflect this. The current link has tripped up several folks, so making this simple fix would be good.

**Comment by timotheeguerin** [comment]
we updated teh preview links to point to the next docs
