### ISSUE TITLE
Should we allow multiple path segments or  `@key` properties in a model definition?

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#160]
This came up as part of #110 

Currently, multiple path segments designated on a model is disallowed.  Is there a need to allow multiple path segments for a key:
- For composite keys (i.e. when there are multiple keys, but no parent resource)
  - possible example: Compute VM Gallery
  - How do we express ordering in the path segments without a route string (for autoroute)?
- If there are alternate paths to accessing the resource
  - this is a common pattern for ODATA APIs

Additionally, should we separate '@key' from path segments, and should we allow multiple `@key' properties in a model
- This comes up in arrays of complex types.  The 'id' of a particular instance may be made up of multiple properties (e.g. firstName, lastName)
  - should we allow this
  - Is there any important ordering in keys (last name, first name, for example) that we want to preserve?

**Comment by markcowl** [comment]
- links to specs with this issue

**Comment by markcowl** [comment]
Need to collect data on how many specs would benefit from this

**Comment by timotheeguerin** [comment]
Examples:
- [Device update today](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVWyXLIG0HEWS5Db3Jl0hIuVHJhaXRzOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiQ29udG9zbyBXaWRnZXQgTWFuYWdlciIsCn0pCkDnANxlZCjHJy7GJ8cm6ACKcykKbmFtZXNwYWNlINUqxH5kb2MoIlRoySLPcyDnAJ4gx3UuIikKZW51bSDIZSDkALfGRscTIDIwMjItMDgtMzEiKcQddXNlRGVwZW5kZW5jeSjrAQTIRC52MV8wX1ByZXZpZXdfMsQ1YMlFMGAsCn0KCm1vZGVsIFVwZGF0ZcV0LyoqyA9pZGVudGl0eS4gKi8KICB1xRZJZDrHIElkOwrOMWRlc2NyaXB05ACu5AIEaWZpZWQgYnkgY3JlYXRvcsdJyyc/OiBzdHLlAd19CgrRfGZpZcY17ACnSWTwAKlwcm92aWTHKyDJD8pczi/kAb/HK8QL2CfoAZvGKscOyi19CgpAcm91dGUoIi9kZeQBzcY4L3tpbnN0YW5jZUlkfS/mATVzL+gAlHMve8gLfS/EfnMve8QHfegDW3Mve8cKfSIpCkBnZXQKb3AgZ2V0xl4gaXPsAu9Gb3VuZGHkAUpzLk9wZXLFCzwKIOUBIuYAzuQChUTlAKDoANlmb3IgSW9UIEh1YiBhY2NvdW50IOgAtPABecRGQHBhdGjFCsgm5AIF6wE1/AGNzD/1AZn4AZvMOfEBp/sBqcw48QG1ICB9LAogxzkKPjsK&e=@azure-tools/typespec-autorest&options=%7B%22linterRuleSet%22:%7B%22extends%22:%5B%5D%7D%7D) -> [Potential idea](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVWyXLIG0HEWS5Db3Jl0hIuVHJhaXRzOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiQ29udG9zbyBXaWRnZXQgTWFuYWdlciIsCn0pCkDnANxlZCjHJy7GJ8cm6ACKcykKbmFtZXNwYWNlINUqxH5kb2MoIlRoySLPcyDnAJ4gx3UuIikKZW51bSDIZSDkALfGRscTIDIwMjItMDgtMzEiKcQddXNlRGVwZW5kZW5jeSjrAQTIRC52MV8wX1ByZXZpZXdfMsQ1YMlFMGAsCn0KCkByZXNvdXJjZSgiIikKbW9kZWwgVXBkYXRl5QCCLy8gLyoqyBJpZGVudGl0eS4gKi%2FGHUBrZXkgdcUeSWQ6xyhJZDsKxB%2FKOXByb3ZpZGVyxzlAc2VnbWVudCgiyBlzIinGTMgROiBzdHLlAfXOSuQBe9FGxBXJQsQN2D7oAW7QQccYyUTHENhHZGVzY3JpcHTkAZbkAuxpZmllZCBieSBjcmVhdG%2FoAOfLJz%2FKS30KCvEBU2Zp5wEc7AGBSWTmAYP%2FAUf%2FAUf%2FAUf%2FAUfWPv8BR%2FoBR30KCm9wIGdldMdJaXPsA7xS5wKLUmVhZDzGIj47xDHlAVdl3TRDxSPKNg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%5D%7D%7D)
- [General scenarios](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdCI7Cgp1c2luZyBIdHRwO8cMUmVzdDsKCkByZXNvdXJjZSgixBdsZSIpCm1vZGVsIFPFD0tleSB7CiAgQHNlZ21lbnQoImlkcyIpxBJwYXRoxAhrZXkKICBpZDogc3RyaW5nOwp9CgpAYXV0b1JvdXRlCm9wIMZbS2V5KC4uLslZKTogdm9pZO4Ahm11bHRp6QCFTcQO%2FwCE9gCEzTBuYW1l1TLEGfsAuOUAjecAt%2BgAi%2FUAtuYA4S1uZXN0ZWTvAUNOxRXpAMVrZXnlAKnEDfEA1OYAoO8AlyAgffkBVMld6gFayRPpAKo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%5D%7D%7D)
