### ISSUE TITLE
How do I support multiple API key auth?

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#1614]
Services may either support one of many API keys (e.g. you have to specify key with name1 or key with name2), or can require many keys (you have to specify keys named name1 *and* name2). I believe we only support the former today. 

The text translator services requires the second format.

**Comment by markcowl** [comment]
investigate:  Is this currently supported, if not, propose a mechanism for specifying multiple authentication keys.  Implement if fits in the timebox

est: 3
pri: 0

**Comment by markcowl** [comment]
@johanste The semantics of key combination are as follows:

- If you use a union of auth schemes, the schemas are joined with OR (this shows up as a list of objects in Security requirements
- if you use a tuple of authentication schemes, the the schemes are joined with AND

so, this typespec using a union of schemes
```typespec
@versioned(Contoso.WidgetManager.Versions)
@useAuth(Key1 | Key2)
namespace Contoso.WidgetManager;

@doc("Key 1 Auth")
model Key1 {
  type: "apiKey"; 
  in: "header";
}

@doc("Key 2 (query) auth")
model Key2 {
  type: "apiKey"; 
  in:"query"; 
}
```

results in this security (one of these security definitions should be used):

```json
"security": [
    {
      "Key1": []
    },
    {
      "Key2": []
    }
  ],
```

but  this typespec using a tuple of schemes
  ``` typespec
  @useAuth([Key1, Key2])
  namespace Contoso.WidgetManager;

  @doc("Key 1 Auth")
  model Key1 {
    type: "apiKey"; 
    in: "header";
  }

  @doc("Key 2 (query) auth")
  model Key2 {
      type: "apiKey"; 
      in:"query"; 
  }
  ```

results in this security configuration (all of these security schemes must be used:
```json
"security": [
    {
      "Key1": [],
      "Key2": []
    }
  ],
```

**Comment by markcowl** [comment]
The only real issue is that you need to use named models, you really cannot use inline models, as `model::name` is used as the key in  security schemas

**Comment by markcowl** [comment]
@johanste Closing as resolved.  Please reopen if you continue to see an issue.
