### ISSUE TITLE
`@action` decorator silently ignores empty string parameter.

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#1629]
It should either give me an error or it should honor the empty name (and thus omit the route suffix). Honoring the empty name can be useful for custom actions/verbs on resources/collections. E.g. bulk-update for PATCH operations against a collection:

```cadl
using Cadl.Http;
using Cadl.Rest;

using Azure.Core;

@resource("rooms")
model Room {
  @key
  @visibility("read")
  roomId: string;
}

@parentResource(Room)
@resource("participants")
model Participant {
  @key
  @visibility("read")
  participantId: string;
};


@action("") // <-- (low priority) bug - empty action name should either work (be honored) or yield an error
@doc("Update participants in bulk.")
@patch op bulkUpdateParticipants is Azure.Core.ResourceCollectionAction<Participant, { @header contentType: "application/merge-patch+json", participants: Record<Participant>}, {}>;
```
(see [playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrJGmF6dXJlLXRvb2xzL8UmxhFjb3JlIjsKCnVzaW5nIENhZGwuSHR0cDvMEVJlc3TJI0HENy5Db3JlOwoKQHJlc291cmNlKCJyb29tcyIpCm1vZGVsIFJvb20gewogIEBrZXnEB3Zpc2liaWxpdHkoInJlYWQiKQogIMQ0SWQ6IHN0cmluZzsKfQoKQHBhcmVudFLIWMRJKdpoUGFydGljaXBhbnTfbwogIHDKLc12OwoKCkBhY3Rpb24oIiIpIC8vIDwtLSAobG93IHByaW9yaXR5KSBidWcgLSBlbXB0eSDGLSBuYW1lIHNob3VsZCBlaXRoZXIgd29yayAoYmUgaG9ub3JlZCkgb3IgeWllbGQgYW4gZXJyb3IKQGRvYygiVXBkYXRl7ACVcyBpbiBidWxrLiIp5AEJdGNoIG9wxRLGLesA7nMgaXPrAYzkAaTlASFDb2xsZeUAnkHFBjzLNCwgeyBAaGVhZGVyIGNvbnRlbnRUeXBlOiAiYXBwbGljYcQxL21lcmdlLcV%2BK2pzb24iLO0ApDogUmVjb3JkzFk%2BfSwge30%2BOw%3D%3D))

**Comment by DominikMe** [comment]
nit: the second `@resource` in the sample should be
```typescript
@resource("participants")
model Participant {
```

**Comment by markcowl** [comment]
est: 3

**Comment by nguerrera** [comment]
Let's make it an error. We can always turn error into works without breaking, but not vice versa.

**Comment by johanste** [comment]
If error, we need to add some other way to support the scenario described in the issue.
