### ISSUE TITLE
Make interface extension available in the model

### ISSUE THREAD

**Issue by garethj-msft** [microsoft/typespec#1636]
When an interface extends another interface, the type relationship is not directly available in the model for emitters to consume.
This makes it clumsy for the Graph CSDL emitter, which is relying on seeing

interface Item<T>{ ... }
interface MyInterface extends Item<EducationClass> { ... }

to parameterize operations contained in the interface with 'EducationClass' (or whatever T is in any given example.)

I understand that interface relationships aren't really true type inheritance, despite the syntax, but as it's fairly inconvenient, we'd like to have access to the causative relationship, please.

**Comment by bterlson** [comment]
I think this is fair to do. Likewise we should include spread sources in the type graph.

**Comment by markcowl** [comment]
proposal is ready

**Comment by tjprescott** [comment]
`isSource` would be a great addition as well

**Comment by markcowl** [comment]
Design issue complete
