### ISSUE TITLE
Add offsetDateTime and instant scalars

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#1637]
We are presently using zonedDateTime for scenarios where no time zone information is expected. Offsets can be seen as a degenerate form of time zone (and are often used as such in e.g. maritime shipping domains) but usually date-times with offsets are just instants with offset.

To illustrate a key difference: an offset date time maps cleanly to an instant on the global timeline, but does not allow for time zone aware conversions or arithmetic that take into account e.g. daylights savings time. For example, adding 24 hours to `2022-03-12T12:00:00-07:00` is `2022-03-13T12:00:00-07:00`, however the time you would want to display to a user in America/Boise would be `2022-03-13T13:00:00-06:00` because of the DST transition (but a user in America/Phoenix would still want to see `2022-03-13T12:00:00-07:00` as they have jettisoned DST).

From a serialization perspective, I think it helps clarify things to have three types:

* `instant`: an instant on the global timeline, represented in UTC, with unspecified granularity, generally serialized as either an integer or ISO8601/RFC3339 with a Z suffix and without the time zone or calendar extensions.
* `offsetDateTime`: an instant with an offset, generally serialized as ISO8601/RFC3339 without the time zone or calendar extensions
* `zonedDateTime`: an exact date and time from the perspective of a particular location on Earth, generally serialized as RFC3339 with time zone and possibly calendar extensions.

We could bikeshed whether `instant` or `timestamp` are better names, but I like `instant` for its specificity whereas `timestamp` is a more general term (the UTC-bound one we know and love is specifically a unix timestamp).

**Comment by markcowl** [comment]
@markcowl link in instant / timestamp

**Comment by markcowl** [comment]
notes:

- immediately need utcDataTime (preferred) and offsetDateTime (some brownfield scenarios) types. both shoule extend the string scalar
- add known format decorator values for RFC3339, RFC1123, and unixTimeStamp (the last it only applicable to utcDateTime types)
- add linting rules to azure.core or azure.clientgenerator to   require usage of utcDateTime and discourage use of RFC1123 format outside of headers

- Need to discuss the transition, we could
  - write a migration script to immediately change existing types
  - allow zonedDateTime to automatically be treated as an existing type until there is a standard for date-time + time zone

**Comment by markcowl** [comment]
Design issue completed
