### ISSUE TITLE
OpenAPI3 emitter should support intersection of model and Record<T>

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#1649]
Essentially we need syntax that will support the following OpenAPI3 output (also relevant for Autorest):
```json
"SomeModel" {
  "type": "object",
  "properties": {
    "count": {
      "type": "integer"
    }
  },
  "additionalProperties": {
    "type": "string"
  }
}
```

Naturally one might try the following:
```
model SomeModel extends Record<string> {
  count: int32;
}
```

However, this won't work because the integer property violates the constraints of Record\<string>

One suggested syntax was something like
```
model SomeModel {
  count: int32;
}
op foo(): SomeModel & Record<string>;
```

However, this doesn't work right now. The emitter ignores the intersection and just uses the first model (see [playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKbW9kZWwgx0bEWUB2aXNpYmlsaXR5KCJyZWFkIiwgInVwZGF0ZSIpxCBwYXRoCiAgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsd5RcQMxXhjb2Rly0BtZXNzYWdlymTEOnJvdXRlKCIvd%2BUAr3MiKQpAdGFnKOcBBcQQaW50ZXJm5ADnxxTFXEDkAN3kAMwo5QC%2B6wC8KTrHKSAmIFJlY29yZDzGGT4gfOYAncR6))

**Comment by bterlson** [comment]
The latter seems to do the right thing - assuming that's an ok solution, isn't it just emitter work that needs to happen? Or am I missing cadl core work?

**Comment by mikekistler** [comment]
Agreed that `&` looks like the right solution.

**Comment by qiaozha** [comment]
Sorry, I am trying to figure out how to express additionalProperties with a few known properties and found this issue, should we also allow some syntax like this ? 
```
model SomeModel  {
  count: int32;
} & Record<string>;
```
The dfference is this one has a name and `SomeModel & Record<string>` would require the emitter or compiler give it a new name ?

**Comment by qiaozha** [comment]
Another issue, not sure if it's the same.  if we spread the alias into a Model, it will only lose the Record intersection [playground](https://cadlplayground.z22.web.core.windows.net/?c=YWxpYXMgU29tZU1vZGVsID0gew0KICBjb3VudDogaW50MTY7DQp9ICYgUmVjb3JkPHN0cmluZz4gJsspMzogxhfEKzsNCg0KbcVNQcYkLi4uyWENCn0NCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)
```
alias SomeModel = {
  count: int16;
} & Record<string> & {
  count3: string;
};

model A {
  ...SomeModel
}
```

**Comment by timotheeguerin** [comment]
I believe the original issue has been fixed, I think that was related to just ignoring the properties when there was an indexer.

However the spread of a Record on a model doesn't carry over the indexer as @qiaozha pointed out

[Playground showing current behaviors](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgQmFyIHsKICAvL8ULaGFzIHRoZSByaWdodCB0eXBlIG5vdwogIGJhcjrFKSAgaTogaW50MzI7CiAgfSAmIFJlY29yZDxzdHJpbmc+Owp9CgrGXEZvb8UzzDEuLi7SMA%3D%3D&e=@typespec/openapi3&options=%7B%7D)

Then spread of record might need some design issue, for example what do we do in this case:
```
model Foo {
 ...Record<string>
 ...Record<int32>
}
```

There is this issue to discuss also if we should allow merging/overriding when intersection/spread https://github.com/microsoft/typespec/issues/1292

**Comment by timotheeguerin** [comment]
Created an new issue about the spread https://github.com/microsoft/typespec/issues/2442
