### ISSUE TITLE
CADL should include scopes (aka RBAC actions) for endpoints

### ISSUE THREAD

**Issue by nicneate** [microsoft/typespec#1652]
(I couldn't find any guidelines on best practices for raising issues in this project - please let me know if more information is needed.)

For APIs with RBAC, the scope that a user needs to hold in order to call each endpoint is part of the API definition. It should be included in the CADL API definition.

The required scopes can then be included in auto-generated API documentation and validated in any auto-generated server stub code as well.

In the context of Azure 1P services which use Azure RBAC for their API(s), the scopes are called RBAC actions and they need to be passed to the Azure RBAC service. Control plane APIs derive the RBAC actions automatically from the endpoints in the form "Microsoft.{service}/{urlpath}/{action}" (where the "action" of read/write/delete is determined based on the HTTP method). We could adopt a similar approach for data plane APIs as well, but if so I still think it needs to be specified/enabled in the CADL API definition.

**Comment by markcowl** [comment]
link in with the other scopes issues

**Comment by timotheeguerin** [comment]
Design proposal https://gist.github.com/timotheeguerin/56690786e61a436710dd647de9febc0f

**Comment by timotheeguerin** [comment]
Implementation #2624
