### ISSUE TITLE
Support cadl install from package-lock.json

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1654]
We need a way to do an install of a cadl project that uses package-lock.json rather than package.json, for reproducible builds. npm provides `npm ci` for this. We could add the equivalent support to the cadl command or we could make `npm ci` the accepted way to do this (which would still involve documentation updates).

**Comment by markcowl** [comment]
document how to use package-lock with npm

**Comment by markcowl** [comment]
est: 1

**Comment by markcowl** [comment]
Closing as duplicate of https://github.com/Azure/typespec-azure/issues/2267
