### ISSUE TITLE
Add Cadl.Reflection.Model/Scalar

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#1655]
Implementation issue for #1536

- [x] Add Cadl.Reflection.Model and Cadl.Reflection.Scalar models
- [x] Add to ReflectionNameToKind
- [x] Add tests
  - [x] Include coverage for distinction between object and Model discovered during design review: union of models is assignable to `object` but not `Model` 
- [ ] Update our own decorator signatures to use `Model` instead of `object`

**Comment by markcowl** [comment]
est: 5
