### ISSUE TITLE
Cannot add Min/Max/MinLength/MaxLength to extensible enums

### ISSUE THREAD

**Issue by Petermarcu** [microsoft/typespec#1663]
From KeyVault Keys.

![image](https://user-images.githubusercontent.com/8228359/219847413-8e0a699e-b86e-4395-8090-a5eb5609f8ea.png)

**Comment by timotheeguerin** [comment]
One way that works today is to keep using the `@knownValue` 
https://cadlplayground.z22.web.core.windows.net/?c=ZW51bSBLbm93bkFsZ28gewogIFBTMjU2LMUJMzg0LAp9CgpAbWluTGVuZ3RoKDEpCnNjYWxhciDEMXJpdGhtIGV4dGVuZHMgc3RyaW5nOwo%3D&e=@typespec/openapi3&options=%7B%7D

Which I feel like make a lot more sense in that case that allowing length restriction on a enum that from typespec point of view is not extensible.

**Comment by timotheeguerin** [comment]
Yeah basically, was just going through some of the old design issue and feel like maybe we can close this one for this existing solution.

**Comment by bterlson** [comment]
Yeah I think this is pretty well solved, but @Petermarcu feel free to re-open if you agree!
