### ISSUE TITLE
All install / build instructions related to npm broken since project rename

### ISSUE THREAD

**Issue by MikeRalphson** [microsoft/typespec#1667]
I'm sure TPTB are aware, just logging an issue to track for interested parties as I couldn't find an existing one. Instructions at this [point in the commit history](https://github.com/microsoft/typespec/tree/bc230ad7bb122fbdf912794c2502133074d12edd) still seem to work.

**Comment by markcowl** [comment]
@allenjzhang Please close when the packages are released.

**Comment by markcowl** [comment]
Packages are released, this issue should be resolved.
