### ISSUE TITLE
search not working in main docs

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/typespec#1688]
This might be a temporary part of the migration because the main docs are still showing `cadl`, but search functionality is not working anymore in the [docs](https://microsoft.github.io/typespec/). For example, you can try searching "visibility".

**Comment by markcowl** [comment]
@markcowl link to rename issue

**Comment by timotheeguerin** [comment]
This didn't seem to actually have fixed the issue as it hardcode the original url. We'll need support to allow the new typespec application or update that one https://discourse.algolia.com/t/process-redirects-or-add-change-domain-on-an-open-source-site/14696
