### ISSUE TITLE
Provide mechanism to format identifiers

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#1693]
PR #1551 removed the ability to distinguish between a quoted and unquoted identifier. From discussion, it was suggested that we expose something from the formatter to format an identifier.

An example of the signature would be:
`formatIdentifier(id: IdentifierNode)`

It would return what the formatter does on identifiers.

**Comment by markcowl** [comment]
@markcowl Add the post-dpg tag to this repo

**Comment by tjprescott** [comment]
Here's the existing functionality that would do this, but it doesn't look like it is ultimately exported:
https://github.com/microsoft/typespec/blob/main/packages/compiler/formatter/print/printer.ts#L1006
