### ISSUE TITLE
Website preview links not working for PRs

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#1704]
PR https://github.com/microsoft/typespec/pull/1700 adds versioning docs. I'm trying to preview those docs from the PR via the bot link, but it doesn't seem to work right. Apparently this works fine the `typespec-azure` repo.

Link: https://cadlwebsite.z1.web.core.windows.net/prs/1700/

When I click the link to TypeSpec Standard Library I get a 404 error and it uses this link:
https://cadlwebsite.z1.web.core.windows.net/standard-library/built-in-types

I have to manually update it to this and then it works, but I have to do this for each link:
![image](https://user-images.githubusercontent.com/5723682/225425466-4021a252-4087-4a40-8d85-bf54d22764c3.png)

**Comment by timotheeguerin** [comment]
This used to work, the issue before was that if you shared the link then it wouldn't load because it was mising the `.html` but you could still navigate. Wondering if maybe something was missed with the rename
