### ISSUE TITLE
Add a property to Interface metadata to indicate extending another interface

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#1708]
Implementation issue for: https://github.com/microsoft/typespec/issues/1636

- Add a property to interface metadata to rindicate extending another interface
- Property should be similar to properties in model metadata for extending models
- Documentation should make it clear that the property does not imply the idea of inheritance for the interface

**Comment by markcowl** [comment]
est: 5

**Comment by nguerrera** [comment]
taking this now because I think I need it for pre-projection.
