### ISSUE TITLE
Add new datetime scalars

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#1709]
Implementation issue for: https://github.com/microsoft/typespec/issues/1637

- Add new scalars 'utcDateTime' and 'offsetDateTime', both should extend string
- Add unixTimeStamp format to format decorator: https://github.com/microsoft/typespec/issues/282
- support types in OpenAPI3 and typespec-autorest emitters

**Comment by bterlson** [comment]
Having this rattling around in the back of my head for a bit, I'm beginning to doubt whether extending string for the date scalars is well motivated. I believe @m-nash had similar feedback during the discussion. This relationship with string seems like something that is unlikely to be represented in target languages, and even in TypeSpec proper it seems unlikely that we would want to allow assigning dates to strings without some kind of explicit coersion. The fact that a utcDateTime could be integer timestamp or some string serialization is more cause for concern (and even integer timestamp, could be int32 or int64 depending on granularity and supported time range).

**Comment by bterlson** [comment]
Sorry I don't necessarily want to reopen the design debate but if others feel similarly I wouldn't be opposed to making these scalars that don't extend anything.

**Comment by markcowl** [comment]
I am 100% on board with not extending string types.  Set up a meeting so we can discuss this as needed, and triage the related issues

**Comment by markcowl** [comment]
scalar utcDateTime;
scalar offsetDateTime;

scalar zonedDateTime;
