### ISSUE TITLE
Versioning projections should respect version enums from other namespaces involved in the projection

### ISSUE THREAD

**Issue by daviwil** [microsoft/typespec#1714]
There are useful cases where a version enum of one versioned namespace (`A`) may appear on a property of a type from another versioned namespace (`B`).  

Today, the versioning projection logic ignores version enum members that don't belong to the type's own versioned namespace.  We would like to expand this logic to allow the `A` version to be respected when applied to a type owned by namespace `B`.

A description and example of this issue affecting service trait versioning can be found here: https://gist.github.com/daviwil/9360133b01f388df24404d2fa856bcfd

Travis had an open PR where he was working on this previously: https://github.com/microsoft/typespec/pull/1686

**Comment by markcowl** [comment]
Should resolve the issue in: https://github.com/Azure/typespec-azure/issues/2422

**Comment by timotheeguerin** [comment]
Repro of the issue without external library 
https://cadlplayground.z22.web.core.windows.net/cadl-azure/prs/2555/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwO9AVVskyOwoKQHNlcnZpY2UKQMdJZWQoxyFzKQpuYW1lc3BhY2UgTXlTxikgewogIGVudW0gyCfFEiAgQHVzZURlcGVuZGVuY3koT3JnLkxpYnJhcnnIcnMudjIpxSx2MjAyMl8wOF8zMTogIsQNLTA4LTMxIiwK30zWTDNfMDJfMDfGTDMtMDItMDciLAogIH3EUC8vIE9wZXJhdMQ4IC%2FTAcQmYWxpYXMgUGFyYW1zID0gzHRDb25kacQ%2BYWxSZXF1ZXN0SGVhZGVyczzrAI7pAIY%2BOwogICNzdXBwcmVzcyAiQGF6dXJlLXRvb2xzL%2BgBuC3GFWNvcmUvdXNlLXN0YW5kYXJkLW%2FpAKoiICJOby4iCiAgQGRvYygiVGhpcyBpcyBhIHRlc3QuIuQA%2F29wxQ0oLi4u5gC6KTogdm9pZDsKfQr%2FAdPsAOL5AdV2MeQBRuQBZekBTm1vZGVsIPoBE1QgZXh0ZW5kc%2BoCclJlZmxlY8QuLkVudW1NZW1iZXI%2Bx2NAySfkAq4uaMVHzxrqArMuYWRkZWQoVOYB%2FGN1c3RvbUHEEz86IHN0cuUC1eQAqX0K

Seems to be reproducing if the v1 of the service is dependant on v2 of the library.
