### ISSUE TITLE
Non-nullable and optional  for OA 3

### ISSUE THREAD

**Issue by mahomedalid** [microsoft/typespec#1715]
I am trying to model the default `dotnet new webapi -o TodoApi`. The openapi produced in the models have all properties as optional and non-nullable. After a quick search (ex. https://github.com/OAI/OpenAPI-Specification/issues/1775) seems that is the default for openapi unless it is specified (for example, with the `[Required]` annotation). 

When trying to model the TodoApi in TypeSpec I cannot get the properties optional and non-nullable, probably there is an option in the emitter or a decorator I am missing. 

What I have is:

```
import "@typespec/rest";
import "@typespec/openapi3";

@service({
    title: "TodoApi Service",
})
@doc("This is a sample server TodoApi server.")

namespace TodoApiService;
  
using TypeSpec.Http;
using TypeSpec.Rest;
  
using OpenAPI;


@summary("WeatherForecast model")
model WeatherForecast
{
    date: DateOnly;

    temperatureC: int32;

    @visibility("read")
    temperatureF: int32;

    summary?: string;
}

model DateOnly
{
    year: int32;

    month: int32;

    day: int32;

    dayOfWeek: DayOfWeek;

    @visibility("read")
    dayOfYear: int32;

    @visibility("read")
    dayNumber: int32;
}

enum DayOfWeek
{
    Monday: 0,
    Tuesday: 1,
    Wednesday: 2,
    Thrusday: 3,
    Friday: 4,
    Saturday: 5,
    Sunday: 6
}

interface WeatherForecastController {
    @route("/WeatherForecast")
    @get GetWeatherForecast(): WeatherForecast[];
}
```

However the non-nullable properties gets generated as required in the openapi.

I was checking the emitter code, and seems the only reference to the required is **if the property is not optional**. However I can't find how the property is set as optional. The closer I get was to this code sample, which seems to indicate that to make a property optional **it needs to be nullable**.

https://github.com/microsoft/typespec/blob/56c87fe8d6e0bce1ffd1a36958f53d1a2e744de5/packages/samples/optional/optional.tsp

```
import "@typespec/rest";

using TypeSpec.Http;

@service({
  title: "Optional sample",
})
namespace OptionalSample;

model HasOptional {
  optionalNoDefault?: string;
  optionalString?: string = "default string";
  optionalNumber?: int32 = 123;
  optionalBoolean?: boolean = true;
  optionalArray?: string[] = ["foo", "bar"];
  optionalUnion?: "foo" | "bar" = "foo";
  optionalEnum?: MyEnum = MyEnum.a;
}

@route("/test")
namespace OptionalMethods {
  @get op read(
    @query queryString?: string = "defaultQueryString",
    @body queryNumber?: int64 = 123
  ): HasOptional;
}

enum MyEnum {
  a,
  b,
}
```

What I am missing?

**Comment by bterlson** [comment]
I can't say I understand what the problem is here, exactly. Can you give a minimum repro with TypeSpec and the OpenAPI output you expect?

Note that like JSON and OpenAPI, TypeSpec has a notion of optional properties which is distinct from nullability. See this example that shows how nullability and optionality are orthogonal:

```
model Test {
  requiredNotNullable: string;
  requiredNullable: string | null;
  optionalNotNullable?: string;
  optionalNullable?: string | null;
}
```

Looking at the [playground output for this example](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgVGVzdCB7DQogIHJlcXVpcmVkTm90TnVsbGFibGU6IHN0cmluZzvNIM8dIHwgbnVsbMUkb3B0aW9uYWzLRD%2FNRckh0B7KRn0%3D), the output seems correct.

**Comment by mahomedalid** [comment]
I think that solves my issue, thanks. It was my misunderstanding of how notnullable works. I think this would benefit of some examples, I can create a PR if you think that would be useful.
