### ISSUE TITLE
tsp compile with output-file will output in the incorrect directory

### ISSUE THREAD

**Issue by mahomedalid** [microsoft/typespec#1721]
## Description

I have a main.tsp in the directory `/workspaces/typespec-workflow-samples/design/api-contracts/todo`, if I run the command:

```
$ tsp compile main.tsp --output-dir "openapi-output" --option "@typespec/openapi3.output-file=test.json"
TypeSpec compiler v0.42.0

Compilation completed successfully, output files are in /workspaces/typespec-workflow-samples/design/api-contracts/todo/openapi-output.
```

The generated file is on `./openapi-output/@typespec/openapi3/test.json`

## Expected Behavior 

Generated file should be in `./openapi-output/test.json`

![image](https://user-images.githubusercontent.com/952392/226217928-a3cfd7e6-2ff1-4fe0-bc39-4d2e3845327d.png)

# Details

```
 $ tsp --version
TypeSpec compiler v0.42.0

0.42.0
```

```
 $ uname -a
Linux codespaces-441721 5.4.0-1104-azure #110~18.04.1-Ubuntu SMP Sat Feb 11 17:41:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Omitting the output-dir has a similar effect:

```
$ tsp compile main.tsp --option "@typespec/openapi3.output-file=test2.json"
TypeSpec compiler v0.42.0

Compilation completed successfully, output files are in /workspaces/typespec-workflow-samples/design/api-contracts/todo/tsp-output.
```

```
 $ find ./tsp-output/
./tsp-output/
./tsp-output/@typespec
./tsp-output/@typespec/openapi3
./tsp-output/@typespec/openapi3/test2.json
```

**Comment by timotheeguerin** [comment]
This is by design as there could be multiple emitters at the same time to limit conflict by default. It does seem like our documentation might not make this clear however.

What you want to do to change the openapi3 emitter output-dir in particular is 

```bash
--option "@typespec/openapi3.emitter-output-dir=foo"
# or relative to the base output-dir
--option "@typespec/openapi3.emitter-output-dir=${output-dir}/foo"
```

you can also set this in the `tspconfig.yaml`

```bash
options:
   @typespec/openapi3:
      emitter-output-dir: foo
```

**Comment by markcowl** [comment]
Tracking fix in: https://github.com/Azure/typespec-azure/issues/2799
