### ISSUE TITLE
Adding decimal as an intrinsic type

### ISSUE THREAD

**Issue by marron-at-work** [microsoft/typespec#1733]
It would be useful to have a `decimal` intrinsic type available. While it is possible to define a custom one (using scalar extends) this seems like a frequent (and high value) enough numeric type to include in the built-in set.

For the purposes of modeling I don't think we need to worry about rounding modes or similar. However, I think it is worth discussing if the design should be a fixed size -- say like the [dotnet decimal](https://learn.microsoft.com/en-us/dotnet/api/system.decimal?view=net-7.0) or an unbounded size that the emitters can limit as desired.

**Comment by bterlson** [comment]
A concrete proposal might be adding:

```
scalar decimal extends numeric; // unbounded, big decimal
scalar decimal128 extends decimal;
scalar decimal64 extends decimal128;
scalar decimal32 extends decimal64;
```

I tend to agree that these should be built in.

**Comment by bterlson** [comment]
Add decimal and decimal128. No to decimal64 and 32 for now, but chime in if you have feedback on this point!

**Comment by stephengoldbaum** [comment]
Excellent!

**Comment by markcowl** [comment]
- add linting rules to prevent usage in azure.core based specs

**Comment by markcowl** [comment]
Closing as completed
