### ISSUE TITLE
Mechanism for emitter or library to hook into dependent library's diagnostics

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#1743]
I think it would be useful to have a mechanism for an emitter or library to be able to process diagnostics from another library. Essentially to implement logic like:
```
try {
 ...
} catch SomeDiagnostic err {
  if (handled) {
    return
  } else {
   rethrow err
  }
}
```

Some scenarios:
1. See (https://github.com/Azure/typespec-azure/pull/2565#discussion_r1146396251). Here, the `property-name-conflict` warning generated by `Azure.Core` should not need to be suppressed if it is marked with the `@excluded` decorator. However, because the warning lives in `Azure.Core`, which knows nothing about the DPG library, this is currently impossible. However, if the DPG library could simply intercept this diagnostic, it could handle the warning by seeing that the symbol is marked `@excluded` and squash the warning without a suppression; otherwise, it would emit the diagnostic. Generally speaking, this would give emitters the ability to develop decorators and logic to handle warnings and errors from their dependencies.
2. An emitter wants to intercept a specific warning diagnostic from a library and repackage it into an error diagnostic without having to duplicate the logic in the underlying library to detect the condition. For example, in the above-mentioned `property-name-conflict` scenario, `Azure.Core` simply emits a warning, since this is problematic for some languages but not all. However, the C# emitter might want to upgrade this warning to an error. It could simply intercept the diagnostic, change the code from warning to error and re-emit the mutated diagnostic. In this way, it does not need to have its own logic to detect this scenario, which might evolve.

**Comment by iscai-msft** [comment]
@tjprescott I like this! I don't have specific examples, but I think this design is more consistent with any other kind of language error, where you can always catch and process the error

**Comment by markcowl** [comment]
I think we have several related issues around changes to linter design, some of which might resolve this issue in a different way, or that could benefit from a similar mechanism (for example, allowing rules to be included or excluded in an execution, and potentially by libraries and emitters, with configurable severity), we should consider them together, I think.

**Comment by timotheeguerin** [comment]
Pointing to this issue that would solve this problem in a clean way https://github.com/microsoft/typespec/issues/1785

**Comment by markcowl** [comment]
I believe this is resolved with the completion of https://github.com/microsoft/typespec/issues/1785
