### ISSUE TITLE
Allow the "shared = true/false" option to be set independently of route... including for `@autoRoute`:ed routes

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#1747]
Setting shared to true from a sidecar (teaspoon) or making auto-routed operation templates share a route requires overriding all of th e autoroute logic. Which is problematic/undoes the value that autoroute provides. Maybe @daviwil has some ideas here?

**Comment by markcowl** [comment]
- also make sure there is a pattern for actions sharing a route
