### ISSUE TITLE
Inadequate generated docs for models

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#1749]
Example:
![image](https://user-images.githubusercontent.com/5723682/228059907-6ce8bf8b-6e1a-41cf-8945-c782f2d2fd39.png)

Results in generated docs like this:
![image](https://user-images.githubusercontent.com/5723682/228059992-b46fae5b-04d0-4111-a740-de65a93dd9b5.png)

Note that:
- No documentation is generated for the type itself (perhaps because the `@doc` string is templated?
- None of the template parameters have any descriptions
- None of the properties of the model are documented

**Comment by markcowl** [comment]
/**
 * This is the doc for this model
 *  @template TResource this is a resource
 * /

**Comment by markcowl** [comment]
@tjprescott Please try and document any of this that isn't working

**Comment by tjprescott** [comment]
Closing. Docstrings do work for models. It seems bizarre that we would have to use docstrings in cases where the parameter is documented with `@doc` (especially since the linter spams you to include them everywhere) but such as things go.
