### ISSUE TITLE
[Feature REQ] Add syntax highlighting to github

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#1752]
In github you can add code snippets and [declare the language](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) of the snippet which github then highlights the syntax accordingly.  We should add `typespec` or `tsp` as an option.

**Comment by timotheeguerin** [comment]
Dup of https://github.com/microsoft/typespec/issues/1040 we need to have more usage across github to request a  new language to be added

**Comment by markcowl** [comment]
Cloaing as dup of #1040
