### ISSUE TITLE
Namespace is not being emitted to openapi

### ISSUE THREAD

**Issue by darshanbhoir07** [microsoft/typespec#1762]
When I have a below sample model created in typespec then when we run the npx cadl compile command to emit this model to open api I have noticed the namespace is not being emitted.

_namespace test.test1.test2 {

model user {
	s: string;
	}

}_

However when we specify a file based namespace (sample below) then the namespace is being emitted to open api

_namespace test.test1.test2;

namespace test.test1.test2 {

	model user {
	s: string;
	}

}_

**Comment by timotheeguerin** [comment]
Hey @darshanbhoir07  do you have `@service` on your namespace? This is how it discover how to include a namespace or not for an http service.
If you are still having issue can you send a repro using the playground https://cadlplayground.z22.web.core.windows.net/
