### ISSUE TITLE
Error with unassignable template default shows up at the wrong place

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1763]
Here the default is not assignable to the template constraint but instead of showing the error on the default it shows it on `Array<T>` inside the compiler lib making it impossible to find the issue.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=CgpzY2FsYXIgVGVzdDxUIGV4dGVuZHMgc3RyaW5nW10gPSB7fT7PFzsKCgpvcCB0ZXN0KCk6xTs7)

This only seems to be happening when targeting an array

**Comment by markcowl** [comment]
pri: 0
