### ISSUE TITLE
Add runtime check to prevent tsp from trying to run on unsupported Node version

### ISSUE THREAD

**Issue by lmazuel** [microsoft/typespec#1778]
It happened I tried by mistake to install TSP on Node 12 (default on my current Ubuntu). The installation didn't fail, but the first usage did:

![image](https://user-images.githubusercontent.com/1050156/229571374-8e9afc87-4f65-47f1-a4aa-fda12d272fe1.png)

I would expect that it fails to install on old Node, as it can be confusing

**Comment by markcowl** [comment]
Not sure what we can do beyond this: https://github.com/microsoft/typespec/blob/main/packages/compiler/package.json#L46-L48

This *should* produce warnings (but not errors) on the initial install

**Comment by mikeharder** [comment]
I do see warnings on install:

```
$ node --version
v14.21.3

$ npm install -g @typespec/compiler
/home/mharder/.nvm/versions/node/v14.21.3/bin/tsp ->
/home/mharder/.nvm/versions/node/v14.21.3/lib/node_modules/@typespec/compiler/cmd/tsp.js

/home/mharder/.nvm/versions/node/v14.21.3/bin/tsp-server -> 
/home/mharder/.nvm/versions/node/v14.21.3/lib/node_modules/@typespec/compiler/cmd/tsp-server.js

npm WARN notsup Unsupported engine for @typespec/compiler@0.42.0:
wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})

npm WARN notsup Not compatible with your version of node/npm: @typespec/compiler@0.42.0
```

If you want an even stronger check, you can inspect `process.versions.node` at runtime, and fail fast if the version is incompatible.

**Comment by nguerrera** [comment]
It turns out adding this runtime check is actually complicated and I don't think it's worth going beyond the npm warning. See discussion on #1954 where I attempted it.
