### ISSUE TITLE
Add linter rule to prevent usage of `object` as a type

### ISSUE THREAD

**Issue by lmazuel** [microsoft/typespec#1780]
Right syntax is `Record<unknown>`. `object` is likely incorrect in all scenarios.

See[ this team discussion for more context.](https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1680545541959?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1680301179595&teamName=Azure%20SDK&channelName=TypeSpec%20(Cadl)%20Discussion%20%F0%9F%90%AE&createdTime=1680545541959&allowXTenantAccess=false)

**Comment by markcowl** [comment]
@lmazuel  Can we move this into the typespec-azure repo?

**Comment by lmazuel** [comment]
@timotheeguerin asked me to put it here

**Comment by markcowl** [comment]
Closed in favor of: https://github.com/Azure/typespec-azure/issues/2796
