### ISSUE TITLE
Have a `sourceIs` property on models and operations

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1810]
Currently we cannot trace back  in `model Foo is Bar` the reference between Foo and Bar.

This could be useful in linter which might want to prevent `model is` of certain types.

**Comment by nguerrera** [comment]
This would match what was just done to see interface extends, so makes sense to have.

**Comment by daviwil** [comment]
Added operations to the list too, we might need that for client sidecars.

**Comment by nguerrera** [comment]
I think naming is the only question. I suggest `Model.sourceModel`, `Operation.sourceOperation` to go alongside `ModelProperty.sourceProperty` and `Inteface.sourceInterfaces`.

**Comment by timotheeguerin** [comment]
I like those names, `sourceIs` was definitely not a great choice
