### ISSUE TITLE
[IDE] Don't require main file to be in-workspace

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#1819]
I forget the full rationale for why we have this limitation, but it leads to a poor experience if your setup is something like this:

- You have your node_modules shared in a parent folder like the repo root
- You open a single subfolder/"project" deeper down
- You click go-to-definition on something you imported from a lib

Stuff is squiggled when the lib file is opened.

![Animation](https://user-images.githubusercontent.com/75470/231562559-f6be66aa-f4b4-496b-8376-41b9eb1a2c97.gif)

This is how things are setup in the Azure/rest-api-specs repo now and it's a reasonable setup that shouldn't have this experience degradation.

I think all that is required to fix this is to replace the inWorkspace check here and keep going up to root of FS in search of entry point:

https://github.com/microsoft/typespec/blob/d8677f2b66399a55782067ece4681b7b1c051532/packages/compiler/server/serverlib.ts#L1129

But I forget why I originally felt it was necessary to constrain the search to the workspace.

**Comment by markcowl** [comment]
epic: end-to-end

**Comment by markcowl** [comment]
est: 3

**Comment by nguerrera** [comment]
The only reason I can see so far for limiting to in-workspace is that files outside the workspace will not be watched and our caching system wouldn't refresh the contents ever. But just being broken in this case seems much worse than that so I would still change it. We can still tell people if they intend to *modify* code, the code should be in workspace. 

Another more conservative change would be a single warning/info that file is out of workspace and refusing to compile it and just coloring it. I'm planning to go ahead and loosen this but keeping a record of other options, potential future issues here in case we ever decide to revisit.
