### ISSUE TITLE
Playground add a way to auto import a library/linter

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1833]
Morgan stanley would like to have a linter always enabled in their playground.

## Option 1: Expose `additionalImports`
One option is to expose `additionalImports` to the playground manifest. 

Cons:
- If adding a library (e.g. `@typespec/http`) copy and pasting code from the playground could not work without those imports
  - This could be mitigated with adding additional UI exposing that information + maybe a way to copy the full code.

## Option 2: Linter specific solution

With the pending redesign of linter #1785 we might want to think of a solution like this where you decide which linter to enable and which ruleset/rule to enable.

**Comment by markcowl** [comment]
est: 3

**Comment by timotheeguerin** [comment]
This should be possible today by providing `compilerOptions`
