### ISSUE TITLE
Operations referenced from an instantiated template interface do not get cached correctly

### ISSUE THREAD

**Issue by daviwil** [microsoft/typespec#1834]
I randomly walked into this issue recently and it seems pretty serious, definitely affects Azure.Core mainline scenarios around `ResourceOperations<Traits>` interface.

Here's the repro:

- Define a templated interface which contains an operation that spreads the template parameter directly into the parameter list
- Use aliases to create two instances of the same interface with different model types for the template parameter
- Define operations which reach through the two aliases to use the contained operation signature
- The second operation will have the same parameters spread in as the first

This example should help clarify it:

[Playground repro](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKbW9kZWwgRm9vIHsKICBuYW1lOiBzdHJpbmc7Cn3IH0V4dHJhUGFyYW1zxSdAcGF0aAogIGNsYXNzSWTKMsscYXNzaWdubWVudMwhfQoKaW50ZXJmYWNlIFN0YW5kYXJkT3BzPFTMZGV4dGVuZHMgb2JqZWN0ID0ge30%2BxXlvcCBHZXQ8VFJlc291cmNlPiguLi7MOyk6IMkdxW5hbGlhcyBPcHNOb8xiPcx9O8omQnlD5gDUQesAv84uPMtIPjsKCkByb3V0ZSgiZm9vIikKb3AgZ2V0IGnSdC7kALpGb2%2FPNC%2FlAUVlcy97xQlJZH0v6gE7cy97yg1JZH3JYVdpdGjGV8dr9QC5y3M%3D)

```
import "@typespec/http";

using TypeSpec.Http;

model Foo {
  name: string;
}

model ExtraParams {
  @path
  classId: string;

  @path
  assignmentId: string;
}

interface StandardOps<TExtraParams extends object = {}> {
  op Get<TResource>(...TExtraParams): TResource;
}

alias OpsNoExtraParams = StandardOps;
alias OpsByClassIdAssignmentId = StandardOps<ExtraParams>;

@route("foo")
op get is OpsNoExtraParams.Get<Foo>;

@route("foo/classes/{classId}/assignments/{assignmentId}")
op getWithParams is OpsByClassIdAssignmentId.Get<Foo>;
```

The `@route` decorator here complains that `classId` and `assignmentId` are not found in the parameter list of the operation.  If you check the `getWithParams` operation in the type graph, you'll see that it is missing those two parameters when it should have them from the `OpsByClassIdAssignmentId`'s interface instantiation.

**Comment by markcowl** [comment]
epic: tcgc/dpg
