### ISSUE TITLE
Dcoument peerDependencies recommendation

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1843]
Logic
- use peerDependencies for all TypeSpec libraries(+ compiler) that you use in your own library/emitter	
- use devDependencies for the other typespec libraries used only in tests 	
- use dependencies/devDependencies for any other packages depending if using in library code or in test/dev scripts

**Comment by markcowl** [comment]
For specs, it would be appropriate to use dependencies though, correct?

**Comment by timotheeguerin** [comment]
For specs yes, this is more for a library or emitter

**Comment by timotheeguerin** [comment]
Though maybe not if we are planning to use the spec as a dependency too?

**Comment by markcowl** [comment]
est: 2
