### ISSUE TITLE
Remove dependency on node-fetch

### ISSUE THREAD

**Issue by mikeharder** [microsoft/typespec#1846]
Package `@typespec/compiler` currently has a dependency on `node-fetch@3.2.8`:

https://github.com/microsoft/typespec/blob/a5d648c95699ab4f6220f8adc17a30102b0ae386/packages/compiler/package.json#L83

This dependency cannot be updated, since later versions include TypeScript errors: https://github.com/node-fetch/node-fetch/issues/1617

We think the best approach is:

1. Update `engines` to require node `>=18.0.0`.
2. Remove the dependency on `node-fetch`, and rely on the built-in implementation of `fetch` in Node 18.

**Comment by timotheeguerin** [comment]
Small hiccup here, fetch is not being exposed by typescript nodes types yet. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60924

We are only using it in one place though so we could cheat the type
