### ISSUE TITLE
Doc-string terminates mid-sentence

### ISSUE THREAD

**Issue by eddyashton** [microsoft/typespec#1849]
The documentation for the built-in `@format` decorator from the standard library is incomplete, and cuts off mid-sentence:

https://github.com/microsoft/typespec/blob/main/docs/standard-library/built-in-decorators.md?plain=1#L108-L111

> For example uuid, uri, etc. This differ from the

I haven't found the source implementation of this decorator, so I don't know if the error is in the original source or how that's extracted to the docs.

**Comment by timotheeguerin** [comment]
Seems to be because the doc has this `@pattern` that is not escaped https://github.com/microsoft/typespec/blob/a5d648c95699ab4f6220f8adc17a30102b0ae386/packages/compiler/lib/decorators.tsp#L99
