### ISSUE TITLE
raise if version specified through `@versioned` and `@service.version`

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/typespec#1866]
There should be a linter rule / error thrown when you specify a version for a service both through the `@versioned` decorator and as a `version` in the `@service` decorator.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR07CgpAxytlZCjHGHMpCkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAogIMc8OiAidjMiCn0pCm5hbWVzcGFjZSBEZW1vxys7CgplbnVtIMhgIMRWdjHFQTIsCn0K)

**Comment by timotheeguerin** [comment]
oh I thought we did that already

**Comment by timotheeguerin** [comment]
This was the original issue but I don't think it was fixed really https://github.com/microsoft/typespec/issues/1010

**Comment by tjprescott** [comment]
Yeah, not sure why I closed this. I will get this fixed this sprint.
