### ISSUE TITLE
linting rule for duplicate enum values in versioning enums

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/typespec#1868]
I think there should be some kind of linting rule in tsp that will prevent users from using enums with the same value as a versioning input

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR07CgpAxytlZCjHGHMpCkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAp9KQpuYW1lc3BhY2UgRGVtb8cbOwoKZW51bSDIUCDERnYxOiAidjEiLMQMMsgMfQ%3D%3D)

**Comment by markcowl** [comment]
est:2
