### ISSUE TITLE
[tcgc]: http query format should support ssv, tsv, pipes

### ISSUE THREAD

**Issue by tadelesh** [microsoft/typespec#1870]
Current format typing has some limitation for emitter: https://github.com/microsoft/typespec/blob/a75d6f946c0d48b35520496fe126f49ccf3c0fff/packages/http/src/types.ts#L215

**Comment by timotheeguerin** [comment]
hhm I fixed that already in a hotfix. Maybe it didn't get merged back

**Comment by timotheeguerin** [comment]
ah I see, thats the type of the accessor, that was missed. If you are blocked you should be able to cast to `as any` and it should still have other values

**Comment by darrelmiller** [comment]
We dropped support for tab separated values in OpenAPI v3 and I do not believe anyone has complained.
