### ISSUE TITLE
Scaffolding templates library version

### ISSUE THREAD

**Issue by MaximRouiller** [microsoft/typespec#1874]
## Problem definition 

Scaffolding templates are extremely useful to prepackage your emitters and their dependencies to reduce setup time for end-users. 

As the emitter is evolving, new versions of the emitter may have breaking changes which may involve breaking the templates if not built properly. 

## Possible solution

Ensure that libraries can have their version specified. To ensure backward compatibility of the schema, the current array can be kept and assume `latest` as the version of a library. `libraries` could also be an object with a similar structure found in `package.json`:

```json
{
   "packageId": "~1.0.0"
}
```

Where the version can use the same [version semantic used by `package.json`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#dependencies).

## Relevant links

[Scaffolding Templates docs](https://microsoft.github.io/typespec/extending-typespec/writing-scaffolding-template)

**Comment by timotheeguerin** [comment]
Propsoal https://gist.github.com/timotheeguerin/2c51928f6792ec166ffde53a5e8ec434

**Comment by timotheeguerin** [comment]
Proposal is good(including `latest` replacement), create implementation issue

**Comment by timotheeguerin** [comment]
Created implementation issues 
- https://github.com/microsoft/typespec/issues/1934
- https://github.com/microsoft/typespec/issues/1919
