### ISSUE TITLE
[protobuf] Support omit-unreachable-types

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#1879]
The OpenAPI3 emitter has the option `omit-unreachable-types` which can be used to not emit models that aren't connected to any operation's type graph. This can sometimes be useful when using models purely for composition (and when aliases of model expressions won't do). The protobuf emitter should support the same option.

**Comment by witemple-msft** [comment]
To clarify, I think the behavior change here would be that we'd skip the `@message` decorator and the heuristic test for message inclusion with this option enabled. Right now, we emit a model as a message if it is:

- referenced directly or indirectly by an operation
- explicitly decorated with `@Protobuf.message`
- declared in an `@Protobuf.service` namespace and has `@Protobuf.field` on its fields

So my expectation is that with the option proposed here set, we'd only check the first condition. That sound right?

**Comment by bterlson** [comment]
I think it's only the 3rd one that would change with this option - if you explicitly say something should be a message we would emit it, but we wouldn't assume that every model with field on it should be emitted (it might just be spread around).
