### ISSUE TITLE
[protobuf] Empty signature should behave the same as spreading Empty

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#1881]
The samples show that when you take no arguments, you spread the well-known empty type. I think this should be implicit when you provide no arguments, instead of the current behavior of creating an empty message type.

**Comment by witemple-msft** [comment]
Is it safe to just check if the parameters model is empty? Can the parameters of an operation extend a model or be named?

**Comment by bterlson** [comment]
It is not possible today. The oft-discussed syntax for just passing in the parameter model would make both of these a possibility but we can handle that when the time comes.
