### ISSUE TITLE
default of JSON null

### ISSUE THREAD

**Issue by cataggar** [microsoft/typespec#1883]
This is a follow-up to a TypeSpec office hours discussion regarding optional and JSON null support. It is not currently possible to set JSON null as the default.

![image](https://user-images.githubusercontent.com/87583576/235552813-2c47618f-74f4-4dce-a3a1-a47b95792cbe.png)

This works:
```
testOptional?: string | null = "abc";
```

This does not:
```
testOptional?: string | null = null;
```

This is related to https://github.com/Azure/autorest.csharp/issues/2340#issuecomment-1530612358 .

**Comment by markcowl** [comment]
@cataggar Is there aa Azure service that requires this?

**Comment by cataggar** [comment]
For Azure, there shouldn't be. There is not one that I know about. If an example is found, this can be reopened.

**Comment by bterlson** [comment]
This feels like a bug we should fix regardless of if we know of a need right now. it just may not be highest priority.
