### ISSUE TITLE
Document ordering of model properties

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1884]
Issue #948 was intended establishing ordering guarantees for model properties and have guarantees be clearly articulated in the public documentation. While the fix for #948 does seem to establish a clear ordering, I don't think this was actually described in any public documentation.

**Comment by markcowl** [comment]
est: 2

**Comment by nguerrera** [comment]
I did document the ordering in the public reference documentation for the API that return member collections. 

For example, 

properties of a model:
https://microsoft.github.io/typespec/standard-library/reference/js-api/interfaces/Model#properties-2

enums of an interface
https://microsoft.github.io/typespec/standard-library/reference/js-api/interfaces/Namespace#enums

My thinking was that it's really the callers of this code that need to know about ordering. That said, it's totally fine to also put this somewhere more prominent, but please make sure the docs are consistent if so.

**Comment by nguerrera** [comment]
This also made me spot a copy/paste issue in ref docs for namespace members. Fix here: #1923

**Comment by mikekistler** [comment]
I thought the documentation was missing because I didn't see any docs include in #1737 which was the PR that closed #948.

But I also think that this should be documented as a basic characteristic of models, e.g. on the Language Basics/Models page, probably with the Record section. Users simply writing TypeSpec need to know this to know that the order of the parameters spread from a model into a parameter list is well defined.

**Comment by nguerrera** [comment]
Yes, it makes sense to add the info there too.

(The docs I linked were in #1737 as doc comments in the typescript that now generate into the reference docs.)
