### ISSUE TITLE
tsp: 11: exec: node: not found

### ISSUE THREAD

**Issue by StefanLecho** [microsoft/typespec#1889]
When I install tsp according to the instructions on https://microsoft.github.io/typespec/introduction/installation, I'm getting this error when executing "tsp code install": "tsp: 11: exec: node: not found". Can I get help to solve this issue ?

- npm --version: 9.6.5
- npm install -g @typespec/compiler has been executed
- OS: Ubuntu 5.15.90.1-microsoft-standard-WSL2

**Comment by timotheeguerin** [comment]
Hey @StefanLecho  do you have node installed and which version is it `node --version`?

**Comment by StefanLecho** [comment]
That solved of course the problem.
