### ISSUE TITLE
Cannot use 'in' operator to search for 'stack' in No Route for service

### ISSUE THREAD

**Issue by cataggar** [microsoft/typespec#1891]
I'm interested in just generating the models. There are no routes since I'm not writing a spec for a http service.

``` 
// import "./routes.tsp";
import "./models.tsp";
```

Here is the error.
```
PS C:\Users\cataggar\ms\avs\src\conveyor\ConsumptionWorker\client> tsp compile .
TypeSpec compiler v0.43.0

Internal compiler error!
File issue at https://github.com/microsoft/typespec
TypeError: Cannot use 'in' operator to search for 'stack' in No Route for service ConsumptionWorker    at runEmitter (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/program.js:537:25)       at async compile (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/program.js:238:9)     at async Object.handler (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/cli/cli.js:118:25)
```

[MS internal Teams thread](https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1683108216859?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1683108216859&teamName=Azure%20SDK&channelName=TypeSpec%20(Cadl)%20Discussion%20%F0%9F%90%AE&createdTime=1683108216859&allowXTenantAccess=false)

**Comment by timotheeguerin** [comment]
Hhm, which version of node are you using, some weird thing is happening where this error is not an object.

**Comment by cataggar** [comment]
node --version
v18.15.0

**Comment by cataggar** [comment]
Moved to https://github.com/Azure/autorest.csharp/issues/3347.
