### ISSUE TITLE
Incorrect information in decorator-wrong-target error message for @format

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1892]
If the `@format` decorator is applied to a target of the wrong type, the error message displayed is

> Cannot apply @format decorator to type it is not one of: string

But `@format` can actually be applied to either `string` or `bytes`, so the error message is incorrect.

I think the problem is in the `validateDecoratorTargetIntrinsic`, and specifically the value for`to` passed to 

```
    createDiagnostic({
        code: "decorator-wrong-target",
        format: {
          decorator: decoratorName,
          to: `type it is not one of: ${typeof expectedTypeStrs.join(", ")}`,
        },
        target: context.decoratorTarget,
      })
```

and even more specifically the `typeof` in the inline expression.

**Comment by timotheeguerin** [comment]
As we want to deprecate other usage than string anyway(as part of `@encode` change #282) I wouldn't fix that one.

**Comment by mikekistler** [comment]
That's fine for `@format`, but what about other decorators that use `validateDecoratorTargetIntrinsic`, now or in the future? Don't we want the message to be correct for them?
