### ISSUE TITLE
Generated reference docs must enumerate interface operations

### ISSUE THREAD

**Issue by daviwil** [microsoft/typespec#1901]
Looking at the Azure Core reference documentation, I see that the `ResourceOperations` interface section does not describe the operations that this interface contains:

https://azure.github.io/typespec-azure/docs/libraries/azure-core/reference/interfaces#Azure.Core.ResourceOperations

The list of operations following `ResourceOperations` are actually the old deprecated signatures that we don't want people to use anymore.

Perhaps we should only describe operations of templated interfaces?

**Comment by markcowl** [comment]
est: 5
