### ISSUE TITLE
Update peerDependencies of openapi package to allow dev dependencies

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#1914]
The peerDependendencies for the openapi package should be updated to allow dev versions of its dependencies, something like:
```
      "peerDependencies": {
        "@typespec/compiler": "~0.43.0 || >=0.44.0-dev <0.44.0",
        "@typespec/http": "~0.43.1 || >=0.44.0-dev <0.44.0",
        "@typespec/rest": "~0.43.0 || >=0.44.0-dev <0.44.0"
      }
```

**Comment by timotheeguerin** [comment]
I don't think we should do that for the stable versions to have that kind of range.  

The only scenario this covers if the http lib lets say has a new dev version and the openapi doesn't have one at all.
This can always be bypassed with `--force`.

If we really want to cover this use case, I think the solution instead is for every stable release to also release a `-dev.0` version with those ranges

**Comment by timotheeguerin** [comment]
As talked offline the exact problem here was using `next` which didn't force an update and cause versions to not be updated.

I think the only thing more we can do now is to prevent those warnings and the need for `--force`. And we have 2 options:
- Have the stable version use that range ` "~0.43.0 || >=0.44.0-dev <0.44.0"`
  - Issue with this is that we are now polluting the stable versions
- For every stable version always release a dev version `-dev.0`
  - Issue here is this might not be compatible with hotfixes

**Comment by markcowl** [comment]
clonsing as we awere able to resolve the issue with --force
