### ISSUE TITLE
Document default interpretation of http layer

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1920]
The http library assume a lot of defaults for encoding, status code etc. I don't believe we have a documenation on that

## Encoding
- `bytes` does base64 when inside of json payload
- `utcDatetime` and `offsetDateTime`, use `rfc3339` unless in header and then use `rfc7231`
- `duration` use `iso8601`

## Other
- default  status code is: 
  - `400-5xx` if `@error`
  - `200` otherwise

**Comment by lmazuel** [comment]
Random thoughts:
- collection format for array in query ?

**Comment by darrelmiller** [comment]
I just ran into this error after upgrading to 0.44

> 53:5 - error @typespec/http/query-format-required: A format must be specified for @query when type is an array. e.g. @query({format: "multi"})
> 53 |     @query id: string[]
     |     ^^^^^^

I'm hoping we can find an alternative to bringing bad OpenAPI v2 design forward and confusing it with JSON Schema "format".
