### ISSUE TITLE
"tsp compile path/to/spec" resolves tspconfig.yaml relative to cwd rather than entrypoint

### ISSUE THREAD

**Issue by mikeharder** [microsoft/typespec#1935]
`tsp compile path/to/spec` ignores the file `path/to/spec/tspconfig.yaml`, since it tries to resolve `tspconfig.yaml` relative to the directory where `tsp` was run, rather than relative to `path/to/spec`.

## Correct
```
~/azure-rest-api-specs/specification/contosowidgetmanager/Contoso.WidgetManager$ npx tsp compile .
TypeSpec compiler v0.43.0

Diagnostics were reported during compilation:

warning emitter-not-found: Emitter with name @azure-tools/typespec-python is not found.
warning emitter-not-found: Emitter with name @azure-tools/typespec-csharp is not found.
warning emitter-not-found: Emitter with name @azure-tools/typespec-ts is not found.
warning emitter-not-found: Emitter with name @azure-tools/typespec-java is not found.

Found 4 warnings.
```

## Incorrect
```
~/azure-rest-api-specs$ npx tsp compile specification/contosowidgetmanager/Contoso.WidgetManager
TypeSpec compiler v0.43.0

Compilation completed successfully, output files are in /home/mharder/azure-rest-api-specs/tsp-output.

No emitter was configured, no output was generated. Use `--emit <emitterName>` to pick emitter or specify it in the typespec config.
```

https://github.com/Azure/azure-rest-api-specs/tree/719eeab635fd4c21d6e849bb3b64e60423fbee2f/specification/contosowidgetmanager/Contoso.WidgetManager

**Comment by markcowl** [comment]
@mikeharder Is this blocking setting up the ci or other tooling?  I can't think of lots of other tools that have localized config, but, for example `dotnet format --include` looks in the cwd for a project file

**Comment by timotheeguerin** [comment]
@markcowl yeah it is blocking and is definitely a bug, I had a branch fixing it thursday before leaving but didn't get to finish it.

The rule of thumb for our compiler is the `cwd` should not be used for anything past the cli resolution of compiler options and config options(and here only if explicitly using `{cwd}`)

**Comment by mikeharder** [comment]
In fairness, I wouldn't call this "blocking" because the workaround is just `cd path/to/spec; tsp compile .`.  But I agree it was a bug and I'm glad to see it fixed.
