### ISSUE TITLE
[question] can tsp support passing in decorator args by name?

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/typespec#1948]
Right now, decorator args can only be passed in positionally, not by names. We worry in this scenario that when we later add optional arguments to a decorator, users will be forced to put in values for all of the optional parameters before hand. Is this something that tsp can support? Thanks!

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=QGRvYyhkb2M9Im15IGRvY3VtZW50YXRpb24iKQpvcCB2YWxpZCgpOiB2b2lkOw%3D%3D)

**Comment by tjprescott** [comment]
I was looking for the issue where I had raised this previously, but the short answer was "no, this isn't Python--this is TypeScript". The suggested solution was to make the decorator accept a dictionary:

**What you want**
```
@myDec(name: "blah", age: 21)
```

**What you get**
```
@myDec({name: "blah", age: 21})
```

It's not great from an Intellisense perspective, but it's kind of what you want.

**Comment by markcowl** [comment]
@markcowl look for design issue on named params

**Comment by markcowl** [comment]
Closing as duplicate of #513
