### ISSUE TITLE
Message about output files being in certain directory can be misleading

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#1957]
Depending on configuration or emitter, it is possible for you output files to land somewhere other than where tsp says they are upon tsp compile as in:

```
Compilation completed successfully, output files are in C:/Temp/repro/tsp-output.
```

Perhaps we should break this down one line per emitter used with each emitter output dir?

Or maybe we should go even further and check all the directories that get a file written through the host and list them all?

Or maybe we shouldn't output this anymore at all?

**Comment by bterlson** [comment]
Frankly, I don't find this output useful in its present form. It's just echoing your project config, and as you say there are some scenarios where emitters output elsewhere (e.g. when generating a configuration file or something that has to be at the root of the project).

My feeling is we shouldn't output anything, but also have a flag we can pass to log all files that are written to disk. The latter would actually be quite useful sometimes.

**Comment by nguerrera** [comment]
I like that. Very easy to add a trace flag for that.

**Comment by markcowl** [comment]
I agree with Brian on both counts

**Comment by timotheeguerin** [comment]
dup here https://github.com/microsoft/typespec/issues/1450

**Comment by nguerrera** [comment]
> Very easy to add a trace flag for that.

Not exactly very easy. Tracing is tied to the program right now. I was going to add this to NodeHost.writeFile.

#1450 decision was to just remove the message and file another issue to log. I'm repurposing this one to track logging. And will send PR to remove and close #1450 now.

**Comment by nguerrera** [comment]
Actually easier to file a new issue.

**Comment by nguerrera** [comment]
Duplicate of #1450

**Comment by allenjzhang** [comment]
We could remove it for now, given it is incorrect. But it would definitely be a nice have if we can get that information correctly output. 

Since we have added interpolation and files are generated outside the current folder, having a piece of clear confirmation information would go a long way to help spec writers.
