### ISSUE TITLE
Need usage document on discriminators

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#1960]
The only documentation I can find on a search is just the decorator documentation.

We need general documentation on how to model using discriminators, and canonical examples in typespec-azure-core as well.

**Comment by markcowl** [comment]
est: 5

**Comment by timotheeguerin** [comment]
Existing http doc that could be expended https://microsoft.github.io/typespec/standard-library/http/operations#polymorphism-with-discriminators
