### ISSUE TITLE
`getEffectiveModelType` cannot reconstruct the name of a model type with only metadata properties

### ISSUE THREAD

**Issue by daviwil** [microsoft/typespec#1971]
I ran into an issue with `getEffectiveModelType` while working on PR https://github.com/Azure/typespec-azure/pull/2903 to move the `no-inline-models` linting rule into Azure Core.

If you define a named metadata-only model type like so:

```
@doc("An Accepted response with an Operation-Location header.")
model AcceptedResponse {
  @doc("The status code.")
  @statusCode
  statusCode: 202;

  @doc("Operation result URL.")
  @header("Operation-Location")
  operationLocation: string;
}
```

Passing that type into `getEffectiveModelType` will return the original type.  However, if you intersect `AcceptedResponse` with the empty model, the type now becomes an anonymous model type and `getEffectiveModelType` can no longer recover the name `AcceptedResponse`.

Check out the type graph in this [playground sample](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKbmFtZXNwYWNlIFRlc3Q7CgpAZG9jKCJBbiBBY2NlcHRlZCByZXNwb25zZSB3aXRoIGFuIE9wZXJhdGlvbi1Mb2PFCSBoZWFkZXIuIikKbW9kZWzJPVLIPHsKICDGW1RoZSBzdGF0dXMgY29kZcQ0ICBAxhJDb2RlCiDHH8QNOiAyMDI7Csk9yXvkAJZ1bHQgVVJMx0LmAIPLI%2BkAnsUgb8gXyBY6IHN0cmluZzsKfQoKYWxpYXMgTWVyZ2VkID3yAL8mIHt9OwoKb3AgdGVzdCguLi7GLCk6IHZvaWQ7).  The operation `test` has parameters that come from an anonymous type, not from `AcceptedResponse`.

The problem here seems to be that when metadata property filtering is completed, the original model type (the anonymous model) is returned when no properties remain.

This issue is blocking the resolution of https://github.com/Azure/typespec-azure/issues/2367 (PR ).

**Comment by markcowl** [comment]
Underlying issue for: https://github.com/Azure/typespec-azure/issues/2993

**Comment by tjprescott** [comment]
After discussion with @nguerrera  and @timotheeguerin we believe the appropriate course of action to cover this situation is for Azure Core templates to wrap their body parameters with the `Body<T>` template. In our tests this seems to produce the desired result and requires no new decorators or logic, which we would strongly prefer.

@daviwil please try this approach on https://github.com/Azure/typespec-azure/pull/2903 and report back whether this works or not.

**Comment by timotheeguerin** [comment]
Underlying solution in the compiler https://github.com/microsoft/typespec/issues/2818
