### ISSUE TITLE
Do we need the `@list` decorator in compiler 

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1978]
We have this decorator with no signature and documentation
https://github.com/microsoft/typespec/blob/01b75f905de93c844a8a01449d9b5bb062ebeeec/packages/compiler/lib/decorators.ts#L776

**Comment by markcowl** [comment]
move with lifecycle operation decorators (rest?)

**Comment by markcowl** [comment]
est: 5

**Comment by markcowl** [comment]
**Describe the breaking change**

The core `@list` decorator is being deprecated in favor of the `@listsResource` decorator from the http library

**Back-compat design to avoid immediate breaking**
Deprecation

**Link to detailed breaking design**

**Impact**
This change affecting:

- [ ] ARM
- [ ] Data-plane
- [ ] Existing specs: approx. # of service/spec impacted: 0
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: July 2023

**Additional information**
Add any other information about the change including fixes for here.
