### ISSUE TITLE
Dev version release should include patch versions

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1984]
I think we have a problem right now where if we do a hotfix it won't get included in any of the dev versions until there is an additional change

Proposing the following logic for the dev version:

Given a version `0.x.y` and a number of changelog `c` the dev version would be `0.(x+1).0-dev.(y + c)`

Currently it is `0.(x+1).0-dev.c`

- [x] Other change would be to still release with 0 changes `-dev.0`  (this has been compled in #1986)

**Comment by markcowl** [comment]
est: 3
