### ISSUE TITLE
Infrastructure: Better changelog management

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#1987]
Using `rush change`, we haven't done the best job at keeping track of good release notes on an ongoing basis. The command line prompt doesn't encourage or make it very easy to put good notes, and the resulting JSON file isn't in a format that's easily reviewed and we will often miss a chance to review it well.

Ideally we would use something where it's natural to write good content in Markdown that gets a good review as the change is made so that there is less manual work at release time to gather the content and less need to re-review it all to catch issues when the release is put together.

**Comment by timotheeguerin** [comment]
Completed, using https://github.com/timotheeguerin/chronus
