### ISSUE TITLE
dev doc comments does not consistently set @doc for Azure libs

### ISSUE THREAD

**Issue by allenjzhang** [microsoft/typespec#1994]
It seems dev doc comments are not setting @doc consistently for Azure libraries. Not reproing on OSS playground. Not sure if it is emitter specific issue. 

[Playground link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGnZlcnNpb25pbmfNIGF6dXJlLXRvb2xzL8gsLXByb3ZpZGVyaHVi3y1lYy3GFWNvcmXfLMkscmVzb3VyY2UtbWFuYWdlcsQ4DQp1c2luZyBUeXBlU3BlYy5IdHRwO9EWUmVzdNIWVukA3MkcQcRqLkNvcmXPE1LHfU3GfMV7QGFybVDnAPROYW1lc3BhY2UNCkBzZXJ2aWNlKHsNCiAgdGl0bGU6ICJDb250b3NvyDBIdWJDbGllbnQiLMQm5wFnOiAiMjAyMS0xMC0wMS1wcmV2aWV3xCJ9KQ0KQHVzZURlcGVuZGVuY3ko9QCY6ADUcy52MV8wX1DGQl8xKQ0KLyoqIOcAhSDINiDoAI8g5gFUbWVudCBBUEkuICovDQpu6ADUIE1pY3Jvc29mdC7yAMflAQvEXUHIX8sdIOgBtcVRbW9kZWwgRW1wbG95ZWUgaXMgVHJhY2tlZOgAkDzIHFByb3BlcnRpZXM%2BIOUBR8Rh5AFkIG9mIGXIQcRUICBAZm9ybWF0KCJeW2EtekEtWjAtOS1dezMsMjR9JCIpxSNrZXkoIsg4xEjHGHBhdGjFCXNlZ%2BQA%2Fcolc8Yi5AEEOiBzdHLmAiZ96ADt6QDFcOkAqvMA4%2BoAx%2BoAxkFn9ADFYWdlPzogaW50MzLlAVHGLENpdHnTLWNpdHk%2F6wCWyC9Qcm9maWzUX0BlbmNvZGUoImJhc2U2NHVybOYA33DGMj86IGJ5dGVzy0xUaGUgc3RhdHVzxE90aGUgbGFzdCDkANBhdGlvbuYCIyAgQHZpc2liaWxpdHkoInJlYWTJWcQZ5QNeU3RhdMRj5QIYzBTsAVHEcMw1xX3lAMth6QJFxnRAbHJvxD91cw0KZW51bdJY5gFtLi7pAx7RIizuAOnIYeQCk2JlxH7pAItlZMV1IM1m2z91cGRhdMRCxjZVxw%2FfcWcgZGVsZXTJbUTEDts3Y3Jl5ADocmVxdWVzdCBoYcRHZW4gYWNjZXDKR0HHD%2BQEQsRKaW50ZXJm5APST%2BgByHMgZXh0ZW5kc%2FYE6S7LKXvFROQE9sglyh3MXOgC%2Fspb7wPnyjfpA%2FEs8wM0PsVy)

- Line 20 On namespace 
- Line 23 on Employee Tracked resource

**Comment by timotheeguerin** [comment]
First one seems like a bug, second one I think is related to #1946 and the fact that `@doc` takes priority

**Comment by markcowl** [comment]
related to #1946 in the second case (overriding an `@doc` from an `is`)

**Comment by markcowl** [comment]
Use this issue to fix the issue with namespaces

**Comment by timotheeguerin** [comment]
So this is actually a problem because the doc comment is in between the decorators and the namespace
