### ISSUE TITLE
[Breaking Change]: OpenAPI emitters do not place description in schema for `model MyModel is OtherModel[]` 

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#2002]
This was working in version 0.44

Playground: https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgRm9vIHsNCiAgcDI6IEJhcjsNCn0NCg0KQGRvYygiVGhlIGJheiBndXkiKQ0KxjNCYXrHMzE6IHN0cmluZ9A2aXMgaXMgYSB0ZXN0zDlyxBdCYXpbXTs%3D

The schema for `Bar` should have a description

**Comment by timotheeguerin** [comment]
think this might have been due to a special case I added when adding doc comment to exclude std types from having doc but this then applies to model is array too, will fix

**Comment by timotheeguerin** [comment]
hhm no something else, that only applied to scalars

**Comment by timotheeguerin** [comment]
hhm are you sure this was actually working? I do this the doc showing up in 0.44.0 openapi3 emitter either

**Comment by timotheeguerin** [comment]
ok so that was the doc comment pr in typespec-azure that did break this, autorest emitter was doing something else for types

**Comment by timotheeguerin** [comment]
Ok have a pr fixing in both emitter 
https://github.com/Azure/typespec-azure/pull/3110
https://github.com/microsoft/typespec/pull/2004
