### ISSUE TITLE
versioning dependency issue in global namespace causes unhelpful diagnostic message

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#2030]
Diagnostic is:  `@typespec/versioning/using-versioned-library: Namespace '' is referencing types from versioned namespace 'Azure.Core' but didn't specify which versions with @useDependency`

referencing the global namespace as `Namespace ''` is less than helpful.

Also, the issue in this case is that you probably don't want types in the global namespace at all, with the mitigation being moving them inside a named namespace and adding the `@useDependency` decorator.

We should update the message in the case of the global namespace to refer to the namespace as the global namespace, and change the action the user should take as moving these types into a named namespace

**Comment by timotheeguerin** [comment]
Dup of https://github.com/microsoft/typespec/issues/1953?

**Comment by markcowl** [comment]
Closing as duplicate of https://github.com/microsoft/typespec/issues/1953
