### ISSUE TITLE
Add extra description and/or documentation page for errors/warnings

### ISSUE THREAD

**Issue by l0lawrence** [microsoft/typespec#2032]
When compiling typespec code sometimes there are warnings that can be hard to initially understand from the warning how to go about fixing it (even when given what to fix).  A doc page that shows common warnings and example typespec code for each warning could be helpful in this situation.

**Comment by markcowl** [comment]
- need a design on how to generate this page / what it should like

**Comment by markcowl** [comment]
With the new library documentation on rules, this is resolved.
