### ISSUE TITLE
Versioning/requirements of init template

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2042]
Right now template validation is strict which is great for helping writing a template but not very useful for a user of `tsp init` that might get this unexpected property error because the compiler is old.

We should have a way to say that this template requires the compiler `>=0.44.0`.
Either that or we need a `templateVersion` and a compiler can keep a map of version it support.

That way if user is using a template not supported by installed compiler it would prompt them with a warning saying it might fail or not generate the full template. 

I think if we have this then the schema validation for the template can be optional(or just required if using a valid compiler) or maybe just log warnings 

## Proposal 

Add a new entry to teh template 
```json
{
 "engines": {
   "typespec": "<semver range>"
 }
}
```

When loading a template with a version of the compiler that doesn't match the range prompt user with a warning

```
Looks like this template need tyepspec version `<range>` but you are currently using `x.y.z`. Please update.
Press Y to ignore and continue
```

and make the schema errors warnings with a prompt

```
Templates doesn't match:
-extra property `foo` ...
Press Y to ignore warnings and continue.
```

**Comment by allenjzhang** [comment]
I would still suggest we have less restrictive schema validation, which gives us the flexibility to make fixes and not have to time the release of templates after the supported compiler releases.

There are some other things I would like to add to the list of init templates as well.
1. Template versioning msg. It should be displayed first when running tsp init. Value could be date based  versions.
2. Ability to download to local. With locally downloaded copies, the user has the ability to give aliases for shorter CLI.  for example:
```
   tsp init install azure=https://aka.ms/azure-init
   tsp init graph azure=https://aka.ms/graph/typespec-init

Then:
   tsp init  --> will output or allow scroll selection to drill in on the template needed.
       Installed templates:
           default:   include empty, rest, open API          |    0.45   |
           azure:  Azure TypeSpec projects                     |  2023-03-01 |
           graph:  MS Graph CSDL project templates     | 2023-06-01 |

   tsp init azure
   tsp init graph
 
```

**Comment by timotheeguerin** [comment]
> I would still suggest we have less restrictive schema validation, which gives us the flexibility to make fixes and not have to time the release of templates after the supported compiler releases.

This to me sounds like it doesn't bring any value and more brings negative value, if you make a fix that can't be used by the compiler it will not work anyway and just get silently ignored and confuse the user which will then file an issue because something wasn't generated correctly.

For the other improvements this feels quite separate we should file new issues:
1. I guess why not, only thing is we don't hose them anywhere so not its just more of an information
2. Not sure there is a real use case for this. Do we expect teh same person to need to create the same template over and over again? And then this will also mean that they probably have an outdated template forever

**Comment by allenjzhang** [comment]
Sure. I was hoping to easily add some none critical changes such as some optional messaging. I suppose if we strongly tie any schema changes to requiring the updated toolset, this is not strictly necessary. 

1. Template versioning is only for display and information purposes. So if we make adjustments to template content, it may be clearer to user and us diagnosing issues. Should be a low low hanging fruit.
2. I will turn the question around, Do we expect TypeSpec user to only create TypeSpec projects infrequently? Not having to remember the URL definitely makes it simpler to use. In terms of freshness, template version in 1 can be used to detect updates like npm packages etc.
3. Featurewise, I would like to add specific messages (Pre and Post creation) to give ways to describe and give instructions post- creation.

I will open separate issue to track them.

**Comment by allenjzhang** [comment]
#2045

**Comment by markcowl** [comment]
small group discusssion

**Comment by allenjzhang** [comment]
Discussion completed:

1. Will add `minimalCompilerVersion`.
```
flowchart TD;
  User((::))-->A
  A[> minimalCompilerVersion]--Yes-->B
  B[Parse, strict validation]--Yes-->C[Generate]
  B--No-->D
  A--No-->D[Warn and ask to Proceed]
  D--Yes-->E[Parse, relaxed validation]
  D--No-->Terminate
  E--Yes-->C
  E--No-->Terminate

```
2. Will add skipGeneration to files
3. Will add Welcome and PostGenerationMessage

**Comment by markcowl** [comment]
**Breaking Change Status**
Approved
