### ISSUE TITLE
Schema for tspconfig.yaml to help with authoring in IDE

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#2049]
It would be nice if the user got some basic completion and docs when editing tspconfig.yaml. I am not sure, but it's possible that our extension can provide a schema to the yaml extension. 

It would be fun if we defined this schema in TypeSpec and built it into JSON schema in the build process. :)

**Comment by nguerrera** [comment]
Seems it is possible. See "Mapping a schema in an extension" in https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

**Comment by markcowl** [comment]
- it would be nice if we could figure out a way to pick up schema for included emitters outside the core set

**Comment by RodgeFu** [comment]
we should be able to do it by registering our schema to json schema store [https://www.schemastore.org/json/](url)

more investigation needed for the emitter's config

**Comment by timotheeguerin** [comment]
I think schema might not be the right solution here, instead of depending on another extension, we already parse the config as ast so we should be able to provide our own autocomplete there as well
