### ISSUE TITLE
Document header decorator auto naming

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2053]
The header decorator convert a property called`camelCase` to a header `camel-case` unless specifying the header name explicitly. But this behavior doesn't seem to be documented anywhere

https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKb3AgdGVzdChAaGVhZGVyIGNhbWVsQ2FzZTogc3RyaW5nKTogdm9pZDsK

**Comment by markcowl** [comment]
est: 1
