### ISSUE TITLE
Parser should require semicolon after augment decorator statement

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2059]
I think the augment decorator should technically require it(though this is a breaking change - fixable by the formatter)

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgRm9vIHsKICBwcm9wOiBzdHJpbmc7xxAyyhF9CgoKQEBkb2MoRm9vLCAiQmFyIinNEk1vcmUiKQ%3D%3D)

**Comment by markcowl** [comment]
## Breaking Change Review
**Describe the breaking change**
Augment decorators currently make the ending semi-colon optional.  The formatter always adds the semi-colon.  The semi-colon should be required for consistency with other statements.

```json
@@doc(MyModel.myProperty, "Added doc comment");
```

**Back-compat design to avoid immediate breaking**
Any back-compat design: None

**Impact**
This change affecting:

- [ ] ARM
- [ ] Data-plane
- [x] Existing specs: 0 (formatter has added to existing specs)
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: August (release: 8/8)

**Additional information**

**Comment by bterlson** [comment]
Discussion in design meeting: no concerns moving forward with this PR.
