### ISSUE TITLE
Single line comments between operations in dotted namespace get all moved to the top

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2060]
```
namespace Foo.Bar {
// comment 1
  op one(): string;
// comment 2
  op two(): string;
}
```
formats to
```
namespace Foo.Bar {
// comment 1
// comment 2
  op one(): string;
  op two(): string;
}

```

if namespace is single identifer `Foo` then it works fine. Just an issue for nested namespaces

[Playground Link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=bmFtZXNwYWNlIEZvcm1hdENvbW1lbnRzIHsKLy8gY8YOIDEKICBvcCBvbmUoKTogc3RyaW5nO8whMsYhdHdvzCF9Cg%3D%3D)

**Comment by mikeharder** [comment]
As discussed, I think we should try to hotfix this and upgrade the specs repo.

**Comment by timotheeguerin** [comment]
Hotfixed in 0.45.1
