### ISSUE TITLE
Diagnostic for additional unannotated properties that are ignored due to `@body`

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#2075]
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQHJvdXRlKCJ0ZXN0IikKb3AgxAooKTogewogIGE6IHN0cmluZzsKICBAYm9keSBiyhN9Ow%3D%3D)

Notice how the property `a` disappears from the output entirely. I believe `@body` has always had this effect on responses and it can be observed on parameter with nested `@body` too after #2029. See discussion there.

We have long had a check against having unannotated top-level parameters and `@body`, but perhaps it should be generalized to find any unannotated property that gets subsumed by a sibling or sibling-descendant `@body`.

**Comment by markcowl** [comment]
single warning diagnostic for both request and response bodies, emitted from http library

**Comment by timotheeguerin** [comment]
gets fixed as part of `#2945`
