### ISSUE TITLE
[Json schema] crash on `Record<unknown>`

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2091]
```
Error: Emitter "@typespec/json-schema" failed! File issue at https://github.com/microsoft/typespec/issues Error: Can't get a declaration name for non-declaration typ
```
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOwoKdXNpbmcgSnNvblPFFDsKCkDEI8YOCm5hbWVzcGFjZSDGEXM7Cgptb2RlbCBQZXJzb24gewogIHJlYzogUmVjb3JkPHVua25vd24%2BOwp9Cg%3D%3D)

**Comment by bterlson** [comment]
I have a fix for this in progress, tho hadn't considered the intrinsic case. For intrinsics we can map to a name but for things like Record<A|B> we need a different strategy.
