### ISSUE TITLE
[Formatter] Comment gets added in weird place when between decorator and scalar statement

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2094]
```
@format("x")
/**
 * Desc is NOT working
 */
scalar bar extends string;
```

Formats to 
```
@format("x")
scalar /**
 * Desc is NOT working
 */
bar extends string;
```

Pretty sure this formatting issue happened before on other types and needs the same special  handling for scalars
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=QGZvcm1hdCgieCIpCi8qKgogKiBEZXNjIGlzIE5PVCB3b3JraW5nCiAqLwpzY2FsYXIgYmFyIGV4dGVuZHMgc3RyaW5nOwo%3D)

**Comment by markcowl** [comment]
est: 2
