### ISSUE TITLE
[Formatter] Should the doc comment be formatted above the decorators

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2095]
Apart from the fact that it is bugged right now if you use a doc comment in between teh decorators and the statement it feels like the good formatting order of something should be

1. Doc comment
2. Directives
3. Decorators
4. Statmenent

```tsp
/**
 * Doc comment
 */
#suppress "no-x" "X is needed"
@dec1
@dec2
model Foo {

}
```

Regular comments can still be inserted anywhere

Note: that `directives` and `decorators` are already being formatted in that order. Not that it mattered before https://github.com/microsoft/typespec/pull/2096 allowed them to be in a different order in the parser.

**Comment by nguerrera** [comment]
I think this is the only order that works now and it's the subjectively nicest order to me, so we should format this way. But I also separately think we should handle any order in the language and compiler.

**Comment by markcowl** [comment]
est: 5
