### ISSUE TITLE
Append suffix to package versions published from PRs

### ISSUE THREAD

**Issue by mikeharder** [microsoft/typespec#2098]
Packages published from PRs have the same version as the latest package on npmjs.com, which makes it harder to verify you are using a pre-release package.
 
Packages published from PRs should have a different version number, say by appending the suffix `-pr.{build-number}`.

**Comment by timotheeguerin** [comment]
Also probably part of this issue would be to include the publish artifact step in this repo too.

**Comment by mikeharder** [comment]
I created this one issue for both repos `typespec` and `typespec-azure`.  I can open a second issue for `typespec-azure` if needed.

**Comment by timotheeguerin** [comment]
No one is good, was just pointing out we needed to copy that into this repo to
