### ISSUE TITLE
Add new deprecated directive 

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2107]
Implementation for issues #2006, #1166
Proposal https://gist.github.com/timotheeguerin/f525f392a5d39e3d3d92260167e62c3e

### Syntax

Parameters:

- `message: valueof string`: [REQUIRED] Deprecation message

```tsp
#deprecate "<message">
```

### Unify with `@deprecated`

Current `@deprecated` decorator should align to have the same behavior. And don't recommend using it.

### Reporting

A type that has been marked as deprecated will report itself as deprecated in the IDE(strikethrough ~~`Foo`~~) and emit a `warning` diagnostic
A flag `--ignore-deprecation` will prevent those from being reported but still show the strikethrough in the IDE.

This way we can ensure deprecation are not breaking if you want it to not be and are using `--warn-as-error`

### Carry over

A deprecation does NOT carry over to models and op using `model is` or `op is`

```tsp
#deprecated "Don't use Foo"
model Foo {}

model Bar is Foo {}
             ^ warning: deprecation Don't use Foo

model Baz is Bar {}  // no issue here
```

However an operation included via `extends` will carry over the deprecation. (Same for model properties)

```tsp
interface Foo {
  #deprecated "Don't use foo"
  foo(): void;
}

interface Bar extends Foo {

}

op baz is Bar.foo;
              ^ warning: deprecation Don't use foo
```

## Deprecating service types(operation, models, etc.)

That directive should be able to work in the same way to deprecate emitted types.

Having another decorator(or something else) for that would only add confusion on when to use which.

```tsp
#deprecated "Service deprecated read operation in 2022-01-01"
op read(): void;
```

[See Azure extended deprecation](#azure-extended-deprecation) for a more detailed azure deprecation experience

## Emitter changes

When the new directive is added, the existing decorator and api should still work as they were. To add support for the new directive and you should be able to just use the new API.
As the `@deprecated` decorator will be calling to the same logic(on top of the legacy one) you should just have to worry about that and not have to keep checking both.

### Note about clients:

Because the deprecated status doesn't carry over in `op is` if using a client that is redefining the structure of the service with many `op is` the emitters will have to be checking the sourceOperation as well for deprecation. Or the client operation will also need to be marked as deprecated(Probably the better idea)

**Comment by markcowl** [comment]
est: 8
