### ISSUE TITLE
Implementation: Doc comment order of injection for `model is` and `op is`

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2127]
From design discussion https://github.com/microsoft/typespec/issues/1946

Change: move logic to inject the doc comment as a decorator  to `checkDecorators` instead of finishType should just solve all those problems.

The following cases (Same for `op is`) should be the expected resolved doc
```tsp
/** Doc comment */
@doc("@doc1")
model Foo {} // win: @doc1

/** Doc comment */
model FooWithAugment {} // win: @doc1
@@doc(FooWithAugment, "@doc1");

/** Override */
model IsBase is Foo; // win: Override

```

**Comment by markcowl** [comment]
**Describe the breaking change**

Doc comments on `model is` and `operation is` statements were previously ignored, now they will override inherited doc comments, new behavior:

```TypeSpec
/** Doc comment */
@doc("@doc1")
model Foo {} // win: @doc1

/** Doc comment */
model FooWithAugment {} // win: @doc1
@@doc(FooWithAugment, "@doc1");

/** Override */
model IsBase is Foo; // win: Override
```

**Back-compat design to avoid immediate breaking**
None: this changes descriptions of models and operations in specs to be inline with author intentions.

**Link to detailed breaking design**

**Impact**
This change affecting:

- [ ] ARM
- [ ] Data-plane
- [x] Existing specs: approx. # of service/spec impacted : 0
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: July 2023

**Additional information**
Add any other information about the change including fixes for here.
