### ISSUE TITLE
Generate readme from refdoc.

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2130]
Right now ref docs are generated with 
- entrypoint: Basic install instruction
- options: Emitter options
- data types
- operations, interfaces
- decorators
- etc.

Would be good to have a readme generated from it as well might. Might need an extra `guide.md` that gets merged in the entryopoint of the doc and in the readme 

Readme should probably include those concactenated:
- entrypoint
- guide.md
- options
- decorators

**Comment by bterlson** [comment]
I think we could also consider whether we're being too granular in the refdocs. At least I believe emitter usage instructions should be included in the overview as this is very very likely to be a common thing to look up.
