### ISSUE TITLE
Need a way to set query version globally

### ISSUE THREAD

**Issue by pshao25** [microsoft/typespec#2134]
From SDK perspective, api-version parameter could be defined as a query parameter or a path parameter. To declare it as a path parameter, we could define it globally:
```
@versioned(Versions)
@server(
  "{Endpoint}/anomalydetector/{ApiVersion}",
  ".",
  {
    Endpoint: string,
    @path
    ApiVersion: APIVersion
  }
)
enum APIVersion {
  v1_1: "v1.1",
  v1_2: "v1.2",
}
```

However, to declare it as a query parameter, we have to define it at every operation as an operation parameter. We hope it could be defined globally.

**Comment by markcowl** [comment]
@daviwil Please link to documentation on setting traits for api-version

**Comment by markcowl** [comment]
@pshao25 Closing this old issue, please let us know if you are still having this difficulty
