### ISSUE TITLE
JsonSchema emitter crashes when user declares an enum

### ISSUE THREAD

**Issue by adam-pawlowicz** [microsoft/typespec#2135]
Hi,

I am trying to write a model factory which requires an enum as input. Later I would like to use the json-schema emitter to generate my models. But the emitter is throwing an error:

`Internal Compiler error
File issue at https://github.com/microsoft/typespec
Error: Emitter "@typespec/json-schema" failed! File issue at https://github.com/microsoft/typespec/issues Error: Unexpected non-code result from emit reference at JsonSchemaEmitter.modelPropertyLiteral (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/json-schema/index.js:3924:19) at https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-0cba22bd.js:17751:55 at withTypeContext (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-0cba22bd.js:17866:9) at invokeTypeEmitter (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-0cba22bd.js:17741:9) at Object.emitModelProperty (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-0cba22bd.js:17698:20) at JsonSchemaEmitter.modelProperties (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/json-schema/index.js:3916:41) at Object.emitModelProperties (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-0cba22bd.js:17689:37) at JsonSchemaEmitter.modelDeclaration (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/json-schema/index.js:3872:38) at https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-0cba22bd.js:17751:55 at withTypeContext (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-0cba22bd.js:17866:9) at runEmitter (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-0cba22bd.js:19777:19) at async Module.compile (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-0cba22bd.js:19451:9) at async SZ (https://cadlplayground.z22.web.core.windows.net/assets/index-8990b2a6.js:652:942) at async https://cadlplayground.z22.web.core.windows.net/assets/index-8990b2a6.js:648:10450`

Sample is in that playground link: 
[https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOwoKdXNpbmcgVHlwZVNwZWMuSnNvblPFHTsKCgplbnVtIFJlc291cmNlxCQgewogICAgQ2FsZW5kYXI6ICLICyIKfQoKbW9kZWzJMURlc2NyaXB0aW9uIDzkAIAgZXh0ZW5kc81TPsdUQHZpc2liaWxpdHkoInJlYWQiKSBpZDogc3RyaW5nO8UkbmFtZc4SZMpkzhkvL9VSIGNyZWF0b3LOLdUqc3BhY89udGFnc8gSW13aPOQA7TrFBuQBFkDkAXPmAVUK5ADCxVkgxhFz5AD95gE36AFK7AE3aeoBLMsXPMgU5AFALsg4PjsKfQo%3D](url)

Currently I am using typespec/compiler@0.45.2 and typespec/json-schema@0.45.0

**Comment by bterlson** [comment]
Min repro:

```
import "@typespec/json-schema";

using TypeSpec.JsonSchema;

@jsonSchema
namespace Schemas;

enum ResourceType {
    Calendar: "Calendar"
}

model CalendarDescription {
  type: ResourceType.Calendar;
}
```

Will look in to it, suspect we're not emitting enum members properly.
