### ISSUE TITLE
Union types must be globally unique in OpenAPI3 emitter

### ISSUE THREAD

**Issue by DMaro28** [microsoft/typespec#2136]
Hi!
I've observed the following behavior on Typespec compiler version 0.45.2. Please have a look if it's expected or a bug?

I have the following spec in file sample_model.tsp:

```
import "@typespec/rest";
import "@typespec/openapi3";

using TypeSpec.Http;
using OpenAPI;

namespace Space1;

model Description {
  name: string,
  code: string,
  ...Properties
  }

model Properties {
  property1: Duration[]
}

@oneOf
union Duration{
  integer: int32,
  half: HalfDay
}

model HalfDay{
  startTime: string,
  endTime:string
}
```

my main.tsp looks like this:

```
import "@typespec/rest";
import "@typespec/openapi3";

import "./sample_model.tsp";

using TypeSpec.Http;
using OpenAPI;


@service({
  title: "Test",  
  termsOfService: "http://swagger.io/terms/",
})
@server("https://example.com", "Single server endpoint")

namespace Space1API {
  using Space1;

  @route("/")
  interface Sample {
    @post create(...Description) : {id: string}}
}`
```

OpenAPI specification generated with this setup generates Duration object outside of Space1 namespace. Is this expected behavior? 

![image](https://github.com/microsoft/typespec/assets/64359249/58c16ad4-95f3-4d63-9b9c-407d185e42ff)

**Comment by markcowl** [comment]
Here is a playground, showing a potential issue: https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7DQrSGm9wZW5hcGkzxB4NCnVzaW5nIFR5cGVTcGVjLkh0dHA7yBZPcGVuQVBJxShuYW1lc3BhY2UgU8QGMSB7xBZtb2RlbCBEZXNjcmlwdGlvbsQXxCs6IHN0cmluZywNCmNvZMwPLi4uUHJvcGVydGllcw0KfcpHyhfERnDGDnkxOiBGb29bXccrQG9uZU9mDQp1bsRuRm9vew0KaW50ZWdlcjogaW50MzIsDQpoYWxmOiBIYWxmRGF5xznIZscWew0Kc3RhcnRUae0ArWVuZMUSxhHFO8Z3c2VydmljZSh7DQp0aXRsZTogIlTkAWMsDQp0ZXJtc09mU8YiOiAiaHR0cDovL3N3YWdnZXIuaW8vxSMvxC19KcdNZXIoxSlzOi8vZXhhbXBsZS5jb20iLCAiU2luZ2xlIMYmIGVuZHBvaW50Iin0AYhBUEnsAYtGb2%2FEDyAg5AE%2FMegA2TvoAMZyb3V0ZSgiL8RM5AE2cmbFSsV%2BxDhAcG9zdCBjcmVhdGUoLi4uxmQu6wHhKSA6IHtpZMhafeQBIQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D
