### ISSUE TITLE
`tsp compile . --watch` only watches the entry point and not imported files within the same project

### ISSUE THREAD

**Issue by MaximRouiller** [microsoft/typespec#2139]
I have the following file at the root of my project:

* main.tsp
* uncommon.tsp
* common.tsp

The entrypoint is `main.tsp`. 

# `main.tsp` content

```typescript
import "./uncommon.tsp";
import "./common.tsp";
```

# Expected behavior

Changes to local `tsp` files that are imported in `main.tsp` triggers the watch of `tsp compile . --watch`.

# Actual behavior

Only changes to `main.tsp` cause the compilation to occur.

# Environment

Tested in vscode, npm script, and purely from `tsp compile` to avoid 3rd party interaction.

> \> tsp -v
> TypeSpec compiler v0.45.2

**Comment by markcowl** [comment]
- which files to watch?
  - imported tsp files
  - javascript files

**Comment by markcowl** [comment]
est: 8
