### ISSUE TITLE
Design: template parameter usage should allow named parameters to be specified (to skip default values)

### ISSUE THREAD

**Issue by garethj-msft** [microsoft/typespec#2142]
When providing values for templated elements with multiple template parameters, it's much clearer to authors and reviewers to be able to specify only the template parameter values that diverge from the defaults.  This is a resuscitation of #379, but Graph has found the same requirement.  Azure and Graph will both be able to add cleanliness and enhanced reviewability with this feature.

Example from Graph library:
```
interface GraphOps {
 @get op GetPagedCollection<
    TResource = Automatic.CalculatedResourceType,
    TParams =  {... Automatic.GraphRouteParams},
    TResponse = PagedCollectionResponse<TResource>,
    TErrorResponse = CollectionErrorResponse>(
       ...TParams): TResponse | TErrorResponse;
}
```

When this templated operation is consumed the defaults are often fine, like so:
```
@graphRoute("/users/{id}")
interface usersById extends EntitySet<user> {
  get is GraphOps.GetPagedCollection;
}
```

However, when the author wants to vary ONE of the template parameters, and it's not the first, they have to provide values for more/all, as only positional specification is supported. 
This means the author must refer to the Graph library deeply to build the parameters.
It also means reviewers cannot see immediately what the author is varying from the standard.
Let's examine the worst case example where the author wants to return a customized error response:
***Today's code***
```
@graphRoute("/users/{id}")
interface usersById extends EntitySet<user> {
  get is GraphOps.GetPagedCollection<
            user,
            {... Automatic.GraphRouteParams},  // or worse, { "id" : string }
            PagedCollectionResponse<user>,
            CollectionErrorReponse<409>>;
}
```

***Desired code***
```
@graphRoute("/users/{id}")
interface usersById extends EntitySet<user> {
  get is GraphOps.GetPagedCollection<TErrorResponse = CollectionErrorReponse<409>>;
}
```

**Proposal**
New syntactic sugar is added to support the syntax in the desired code above.

* Allow referencing template args with their name Foo<T = [value]>
* Allowed for all parameters optional(with default) and required
* (P2) Allow mix of positional and named args
* (P2) Positional MUST be located before the 1st named parameter
* (P2) CANNOT specify again the value for one of the positional argument already provided earlier
* Order of evaluation should be unchanged, i.e. in the positional order from the templated element definition, unchanged by the arbitrary order provided in the template usage via named params.

**Comment by bterlson** [comment]
Previously, we had hoped that options bags would be a palatable alternative, but this turned out to not be the case. The primary issue is that, without conditional types, it's impossible to apply defaults to options in the bag that are not provided. So you end up having to provide all the options in the options bag anyway. And arguably, even with conditionals, the result is more verbose than desired.

**Comment by witemple-msft** [comment]
We discussed and accepted a design that meets this proposal, and its implementation is tracked by the following issue: https://github.com/microsoft/typespec/issues/2340
