### ISSUE TITLE
[Json Schema] transitively referenced model emitted twice

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2146]
[See playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOw0KdXNpbmcgVHlwZVNwZWMuSnNvblPFHTsNCm5hbWVzcGFjZSBUZXN0Ow0KDQptb2RlbCBBIHt9yAxCIHsNCiAgcmVmQTogQTsNCn3EKEDEZ8ZJyClDySlCOiBC2ylE0yk%3D&e=%40typespec%2Fjson-schema&options=%7B%22%40typespec%2Fjson-schema%22%3A%7B%22file-type%22%3A%22json%22%2C%22bundleId%22%3A%22%22%7D%7D).

Schema `D.json` has two defs for `A`, but should only have one. Only applies to the default output option where non-schema references are bundled, and when A and B are not marked with the JsonSchema decorator.

**Comment by markcowl** [comment]
Fixed
