### ISSUE TITLE
`tsp compile --option emmitterName.optionName={value}` can't handle `boolean` value for cli options

### ISSUE THREAD

**Issue by MaryGao** [microsoft/typespec#2148]
In typescript emitter we have a boolean option named `enableOperationGroup` and we want to get a `true` or `false` in emitter code, but currently it treated as a string `"true"` not boolean.

```
tsp compile  --option @azure-tools/typespec-ts.enableOperationGroup=true
```

I checked relevant code https://github.com/microsoft/typespec/blob/main/packages/compiler/src/core/cli/args.ts#L132 and found there is no any type checking or coverting when getting values from it.

**Comment by timotheeguerin** [comment]
@MaryGao can you show how you have defined this option?


This works just fine in the openapi3 emitter. The type conversion happens later when we resolve the options against the emitter.
![Image](https://github.com/microsoft/typespec/assets/1031227/3a5498c9-d236-4d7e-a0ea-6883116c3d97)

**Comment by timotheeguerin** [comment]
To note the problem was that `$lib` wasn't exported by the package so typespec compiler couldn't find it.
