### ISSUE TITLE
Let's Make a Website

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2151]
We're making progress on a website, though the details are as yet to be determined. Currently working on:

* Graphic design
* Content strategy
* Tech stack (likely Astro-based)

As more items become clear we can split this into sub-issues.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/typespec/issues/2287
- [ ] https://github.com/microsoft/typespec/issues/2292
```

**Comment by timotheeguerin** [comment]
Closing this in favor of  #2252
