### ISSUE TITLE
VSCode extension does not recognize .tsp files but works when renamed with .cadl file extension

### ISSUE THREAD

**Issue by binoychitale** [microsoft/typespec#2152]
Hi team,

I am trying to install the VsCode extension for Typespec. However, I do not get any syntax highlighting in my .tsp files.
If I rename them with the .cadl extension it starts working properly.

Also after reverting the file extension to .tsp , the syntax highlighting continues working correctly.

Steps to recreate:
1. `tsp code install`
2. Open `.tsp` file

Other information:
- I am running it on WSL (Ubuntu)
- compiler version - `0.45.0`

Let me know if any other info is required from me.

**Comment by timotheeguerin** [comment]
Hi @binoychitale coule you double check you have uninstalled the old Cadl extension and installed the typespec one instead?
