### ISSUE TITLE
Is it allowed to have the same model name with different shapes under global namespace and its sub namespace

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2155]
[Cadl Playground link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CskZYXp1cmUtdG9vbHMvyCUtxhVjb3Jl3ytjLWNsaWVudC1nZW5lcmF0b3LINgp1c2luZyBUeXBlU3BlYy5IdHRwO9AVUmVzdMgVQcReLkNvcmXPEsVhR8hg0URWZXJzaW9uaW5nOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiTXVsdGnGRyIsCiAgdsYyOiAiMS4wLjAiLAp9KQpAdXNlRGVwZW5kZW5jeSjHfG9yZchhcy52MV8wX1ByZXZpZXdfMSkKbmFtZXNwYWNl6gCNy2s7Cgptb2RlbCBSZXNvdXJjZSDkAJRAdmlzaWJpbGl0eSgicmVhZCIpCiAgaWQ6IHN0cuYAxCAgQGtlecQHc2VnbWVudMQpxkNzxS7RRCBjcmVhdGXFHeQAlc1NZGVzY3JpcHRpb24%2FyhkgIOQBwsoQffAArkFycmF5IGlzyRFbXTsKCi8vIG9w5AGJaW9uIPABuApA9QGyxRwu5gIo5QGY5gCjIkZvb%2BsBlecBuTr1AUzmAaJyb3V0ZSgiL2NhZGwtZm9vIikKQGRvYygiQ2FkbCBGxRHqAZRGb29PcOUBdPMBh%2FgBifEBi%2BkBjfoBj%2F8BkfMBk%2FoBlfABl8QSbG9j5QFwzBZ95AIH5gD8xWpzIGEgbmV3IOgAmiBvciB1cGTGGm4gZXhpc3TkAa1vbmUu5QCWb3DnAKRPclXFKOwB68ZUT3JSZXBsYWNlPMgYPuYCnsV4R2V0cyB0aGUgZGV0YWlscyBvZiBh6QCAyWVnZXTMWlJlYWTVT0RlbGXmAMfRQ2TFG8xGxi3VSExpc%2BcAmOkA9MhRc8lSbGlz7QCWxDXMTn0K%2FwLL8ALLQmFy%2FwLL7wLL5QCsQmFy5ALD7QLXYsUU6gLGQmFy5wLGLy8gYmluYXLlBBrINGdldC3GFuYEGmdldOkBeELFGCgpOiBPa1Jlc3BvbnNlICboAv9oZWFkZXIoImNvbnTkBcHkAngiKSDHD%2BQAujogImltYWdlL3BuZyLmAotAYm9keSDEBTogYnl0ZXPEF33lAX%2FGdOUENsRz7QRHxSEvL%2BQBiuYAhndpdGgg5gCCc%2BwAz%2BYCky3EHy3HH%2BYA2HB15wDYxiJXaXRoSMYgxG3mArBk%2BgDl6QS0LegDTcVXxFLHGUzHGOoAusgS7wJn5wEFxQrECcox6gEM6QDQ5gK78wDQxhnsAuDvANNOb0PmAYr%2FANX%2FANX%2FANXlANXlALZ9Cg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

In this example, we have model `Resource` defined in the global namespace `TypeSpec.MultiClient` and we also have model `Resource` defined with a different shape (eg. with an extra properties of `location`) in the sub namespace `FooOp`.  

From the generated openapi.json I found the `Resource` under  `FooOp` sub namespace has been referred to `FooOp.Resource`. I wonder if this is expected.  In theory I would image this should report compile errors. Because we actually don't use NameSpace as the model name prefix in the emitter side now. Also, is this expected to use `FooOp` as the prefix in the language emitters side if we consider it as a valid case ? 

For now, this will end up with model name conflicts in emitters. See relevant discussion in this [teams channel](https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1685421765498?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1685421765498&teamName=Azure%20SDK&channelName=TypeSpec%20(Cadl)%20Discussion%20%F0%9F%90%AE&createdTime=1685421765498)

FYI, this teams discussion is more focus on the same model being referred in different namespaces. but each language emitter has confirmed that in cases like this issue, it will be a problem for them.

**Comment by qiaozha** [comment]
Thanks @bterlson for the explanation and hint.  I can not see the transfer issue button, probably need help to move it to typespec-azure repo :)

**Comment by markcowl** [comment]
@qiaozha Please close this issue and copy the contents into a new issue in https://github.com/Azure/typespec-azure/issues
