### ISSUE TITLE
Hard to find docs for scalars in the TypeSpec standard library

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#2158]
Docs for all other libraries have a "Data Types" section, but the TypeSpec standard library does not. As such, there's nowhere to point people for documentation on, say, TypeSpec scalars. There is a "Langauge Basics" article on scalars, but it just has info on how to work with them. There's no documentation of the supported scalars.

**Comment by timotheeguerin** [comment]
Not this? https://microsoft.github.io/typespec/language-basics/built-in-types

**Comment by tjprescott** [comment]
Oh, nice, yeah, that's what I was looking for.

Is this generated? I expected to find it under the TypeSpec Standard Library like it is for other libraries (under Data Types). Perhaps we could inlclude the Data Types heading and just have it link to this?

**Comment by timotheeguerin** [comment]
It is manually written, idea was for the built-in types we have a nicer and easier to read doc for all those scalars.

So it used to be there originally but @mikekistler felt like we should expose those types earlier so it would make sense for the language basics docs which kinda reference some of those sometimes.

But yeah maybe having a link back to it would be ok.

**Comment by tjprescott** [comment]
For discoverability, I think a link-back makes sense. I went to the Scalar section and didn't find it. Never thought to look in Language Basics, so others may encounter the same problem.
