### ISSUE TITLE
The applied name conversion is not consistent for header apiVersion parameter and query apiVersion parameter

### ISSUE THREAD

**Issue by chunyu3** [microsoft/typespec#2165]
When I defined two operations, the apiversion parameter in one operation is a header,  in other operation, it is a query parameter

```
namespace Pets {
  @post op apiVersionInQuery(@body pet: Pet, @query apiVersion: "2022-07-09"): Pet | Error;
  @put op apiVersionInHeader(@body pet: Pet, @header apiVersion: "2022-07-09"): Pet | Error;
}
```

When typespec compile, for header parameter, the name of HttpOperationParameter will be updated to `api-version`, but for query parameter, it maintain as `apiVersion`.

Does typespec applies some name conversion for apiVersion paramerter, if so, can apply to query parameter also to keep consistent?

**Comment by markcowl** [comment]
Closing as by design
