### ISSUE TITLE
No import of GRPC models possible

### ISSUE THREAD

**Issue by danielkocot** [microsoft/typespec#2166]
Hi, 

I want to use the import functionality for models which works for http and openapi3 also to work for grpc. According to the use of decorators this seems not to work right now. Can anybody elaborate on this?

Thanks,
Daniel

**Comment by timotheeguerin** [comment]
Hi @danielkocot could you share a little more on what is the issue? Are you you trying to import models that are defined in another file?

There shouldn't be any difference really if you `import` the other file or define in the same one. The main thing to watch out for is the namespace, models in the other file should probably be in the same namespace or have their own namespace with a `@pacakge` on it.

**Comment by danielkocot** [comment]
Hi @timotheeguerin, 
I tried to import models that are defined in a different files and I used also decorators like @field or @id. I just used a plain model description file.

**Comment by witemple-msft** [comment]
@danielkocot could you share a small example file that demonstrates the bug, and can you share what you're trying to accomplish, what you expect it to do, and what the compiler actually does instead (throws an Error, or doesn't emit what you expect it to)? I'm having some difficulty understanding what exactly isn't working.

**Comment by danielkocot** [comment]
HI @witemple-msft, can some code.

customer.tsp:
`
model Customer {
    @field(1) id: string;
    @field(2) firstName: string;
    @field(3) lastName: string;
    @field(4) email: string;
    @field(5) phone: string;
}
`

main.tsp:
`
import "@typespec/protobuf";
import "../models/customer.tsp";

using TypeSpec.Protobuf;

@package({
    name: "customer",
    version: "1.0.0"
})
namespace RetailCustomer;

@Protobuf.service
interface RetailCustomer {

    createCustomer(...Customer): Customer;

    listCustomers(...WellKnown.Empty): {
        @field(1) customers: Customer[];
    }
}
`

Some terminal stuff ;)
`
tsp compile . --emit=@typespec/protobuf
TypeSpec compiler v0.46.0

Diagnostics were reported during compilation:

/Users/daniel/_new_ideas/typespec-playground/retail/models/customer.tsp:2:6 - error unknown-identifier: Unknown identifier field
> 2 |     @field(1) id: string;
    |      ^^^^^
/Users/daniel/_new_ideas/typespec-playground/retail/models/customer.tsp:2:5 - error unknown-decorator: Unknown decorator
> 2 |     @field(1) id: string;
    |     ^^^^^^^^^
/Users/daniel/_new_ideas/typespec-playground/retail/models/customer.tsp:3:6 - error unknown-identifier: Unknown identifier field
> 3 |     @field(2) firstName: string;
    |      ^^^^^
/Users/daniel/_new_ideas/typespec-playground/retail/models/customer.tsp:3:5 - error unknown-decorator: Unknown decorator
> 3 |     @field(2) firstName: string;
    |     ^^^^^^^^^
/Users/daniel/_new_ideas/typespec-playground/retail/models/customer.tsp:4:6 - error unknown-identifier: Unknown identifier field
> 4 |     @field(3) lastName: string;
    |      ^^^^^
/Users/daniel/_new_ideas/typespec-playground/retail/models/customer.tsp:4:5 - error unknown-decorator: Unknown decorator
> 4 |     @field(3) lastName: string;
    |     ^^^^^^^^^
/Users/daniel/_new_ideas/typespec-playground/retail/models/customer.tsp:5:6 - error unknown-identifier: Unknown identifier field
> 5 |     @field(4) email: string;
    |      ^^^^^
/Users/daniel/_new_ideas/typespec-playground/retail/models/customer.tsp:5:5 - error unknown-decorator: Unknown decorator
> 5 |     @field(4) email: string;
    |     ^^^^^^^^^
/Users/daniel/_new_ideas/typespec-playground/retail/models/customer.tsp:6:6 - error unknown-identifier: Unknown identifier field
> 6 |     @field(5) phone: string;
    |      ^^^^^
/Users/daniel/_new_ideas/typespec-playground/retail/models/customer.tsp:6:5 - error unknown-decorator: Unknown decorator
> 6 |     @field(5) phone: string;
    |     ^^^^^^^^^

Found 10 errors.
`

**Comment by bterlson** [comment]
You need to put `using TypeSpec.Protobuf;` in `customer.tsp`, or else fully qualify the `@field` decorator as `@TypeSpec.Protobuf.field`. `using`s are per-file.

**Comment by markcowl** [comment]
@danielkocot Did this fix your issue?

**Comment by danielkocot** [comment]
Hi @markcowl and @bterlson,

it helped. But I had also to put the namespace into the `customer.tsp`. Thanks for the helping hands.

**Comment by bterlson** [comment]
Ahh yes, sorry I didn't notice that. Namespaces and usings are both per-file!
