### ISSUE TITLE
Openapi3 emitter should not populate version to `0000-00-00` by default

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2167]
Version is not a required field in openapi3 we shouldn't just set some blank version in a format that probably have no meaning to users.

https://cadlplayground.z22.web.core.windows.net/?c=QHNlcnZpY2UKbmFtZXNwYWNlIE5vVmVyc2lvbjs%3D&e=@typespec/openapi3&options=%7B%7D

**Comment by markcowl** [comment]
est: 2

**Comment by mikekistler** [comment]
It looks to me like version is actually required in OpenAPI v3:

https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/versions/3.0.3.md#fixed-fields-1

![image](https://github.com/microsoft/typespec/assets/85643503/280295fb-672c-4c47-be51-7e26f21c1222)
