### ISSUE TITLE
Should openapi3 provide a better default title

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2168]
Right now we have the `title` as `(title)` if not specified. It is a required field so we can't just omit it but maybe using the namespace name would give us a better name.

https://cadlplayground.z22.web.core.windows.net/?c=QHNlcnZpY2UKbmFtZXNwYWNlIE5vVmVyc2lvbjs%3D&e=@typespec/openapi3&options=%7B%7D

**Comment by markcowl** [comment]
Closing as we have the capability to set this directly
