### ISSUE TITLE
Augment decorator should apply to derived operations

### ISSUE THREAD

**Issue by jasonmueller** [microsoft/typespec#2178]
When documenting APIs that compose interfaces and operations, I should be able to document the derived interfaces independently.  The only way to do this is through augment decorators.

For example, if I want to reuse a `Collection` interface, I should be able to provide documentation for operations on each interface that extends that interfaces.  If I can't, then the base interface is much less useful because emitting OpenAPI or other outputs require post-processing in order to generate the desired documentation.

Currently, when using augment decorators (@summary, in this case), the decorator is applied to targets that are directly defined on the target's parent, but not on those that are part of the parent through `extends` even though they are both reachable through type ahead and it compiles fine.  This is confusing.

In this [Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CnVzaW5nIFR5cGVTcGVjLkh0dHA7CgpAc2VydmljZSh7dGl0bGU6ICJEZW1vIn0pIApuYW1lc3BhY2UgxBM7Cgptb2RlbCBBbmltYWwgewogIMQiOiBzdHJpbmcsCn0KCmludGVyZsQzQ29sbGVjdGlvbjxUSXRlbT7FMUBnZXQgb3AgbGlzdCgpOiDFG1tdO848xmLKQiBleHRlbmRzzFXGJMdWcm91dGUoImNsb25lIinLaMUSxGnGL1tdxGlAQHN1bW1hcnko0Gku5ACYLCAiTGlzdCBhxR1zIincMcVhLCAiQ8QIyzM%3D&e=%40typespec%2Fopenapi3&options=%7B%7D), I would expect the summary for both operations to be emitted, but only the one for the non-inherited operation is emitted.

**Comment by bterlson** [comment]
Possibly related: https://github.com/microsoft/typespec/issues/2123.

**Comment by markcowl** [comment]
Looks like this [was fixed](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CnVzaW5nIFR5cGVTcGVjLkh0dHA7CgpAc2VydmljZSh7CiAgdGl0bGU6ICJEZW1vIiwKfSkKbmFtZXNwYWNlIMQUOwoKbW9kZWwgQW5pbWFsIMQ0xCI6IHN0cmluZzsKfQoKaW50ZXJmxDNDb2xsZWN0aW9uPFRJdGVtPsUxQGdldCBsaXN0KCk6IMUYW13POcZfyj8gZXh0ZW5kc8xSxiTHU3JvdXRlKCJjbG9uZSIpx2UKICDFEcRoxi7HaUBAc3VtbWFyeSjQaS7kAJgsICJMaXN0IGHFHXMiKTvcMsVjLCAiQ8QIzDQ%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)
