### ISSUE TITLE
Documentation of responses

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2185]
There is a few issues with documenting responses: 
- how can you actually document the operation return type
- how can you document each operation indivually with doc comment

## Case 1: Documenting a single response
This is the syntax I'd expect to work but we can't actually target the returnType. This would document the `Pet[]` type instead of the response return type.
This means we probably need a `ReturnType` or `OperationOutput` type.

```tsp
/**
 * @returns return list of pet in store
 */
op list(): Pet[];
```

## Case 2: Documenting  response union

```tsp
/**
 * @returns return list of pet in store or error
 */
op list(): Pet[] | Error;
```

## Case 3: Documenting  each response union

Maybe we can just allow multiple `@returns` which applies to the response union in the same order. If there is a single `@returns` but many responses it could apply either to the first one only or apply the the returnType

```tsp
/**
 * @returns return list of pet in store or error
 * @returns error
 */
op list(): Pet[] | Error;
```

**Comment by timotheeguerin** [comment]
# Documentation of responses

## Cases

```tsp
// Case 1: Return a single type
op read(): Pet;

// Case 2: Return multiple types
op create(): PetCreated | PetAccepted;

// Case 3: Return type or error
op read(): Pet | NotFound;

// Case 3: Return multiple types and errors
op create(): PetCreated | PetAccepted | BadRequest | Unauthorized;
```

There will also be some more complexity when involving `op is` which we'll get to later.

## Current issues

1. There is no `ReturnType` type on the operation which means that in `case 1` the `readOp.returnType === PetModel` and adding documentation there would also put the documentation on the `Pet` model which would be wrong.
2. Do we want to be able to document the operation `returnType` as well as all the possible `variants`.
3. We currently cannot augment union variants

## Current ways that should work

### Each response is its own model with the documentation on it

```tsp
@doc("Pet Created") model PetCreated {
  @statusCode code: 201;
}

@doc("Pet accepted") model PetAccepted {
  @statusCode code: 202;
}

op created(): PetAccepted | PetCreated;
```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQGRvYygiUGV0IENyZWF0ZWQiKSBtb2RlbCBQZXTHEyB7CiAgQHN0YXR1c0NvZGUgY29kZTogMjAxOwp9zENhY2NlcM9EQccU2UUyxUVvcCBjxm4oKTrNOHzrAIo7&e=@typespec/openapi3&options=%7B%7D)

### Documenting the union variants

If documenting the union variants it should document the responses. (This would require being able to reference an unamed union variant)

```tsp
import "@typespec/http";

using TypeSpec.Http;

model PetCreated {
  @statusCode code: 201;
}

model PetAccepted {
  @statusCode code: 202;
}

// We cannot augment unions variants yet but this represent an equivalent behavior if we had this functionality
union CreatedResponses {
  created: PetCreated,
  accepted: PetAccepted,
}

op created(): CreatedResponses;

@@doc(CreatedResponses.created, "Pet Created");
@@doc(CreatedResponses.accepted, "Pet accepted");
```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKbW9kZWwgUGV0Q3JlYXRlZCB7CiAgQHN0YXR1c0NvZGUgY29kZTogMjAxOwp9yy9BY2NlcNwwMsUwLy8gV2UgY2Fubm90IGF1Z21lbnQgdW5pb25zIHZhcmlhbnRzIHlldCBidXQgdGhpcyByZXByZXPEJ2FuIGVxdWl2YWzEDmJlaGF2aW9yIGlmIHdlIGhhZMYwZnVuY3Rpb25hbGl0eQrFWyDnAMxSZXNwb25zZXPlAKVjxhU66wDtLAogIGHnAMnFGOgA1izkALxvcMg0KCk60VQ7CgpAQGRvYyjQGS7HNSwgIlBldMg4Iik72DDoAILHMcgPIik7&e=@typespec/openapi3&options=%7B%7D)

## Doc comment solution

With the previous information we could imaging having the `@returns` tag on the operation doc comment have the following behavior:

Each instance of @returns document the union variant in order

```tsp
/**
 * Case 1: Return a single type
 * @returns a Pet
 */
op read(): Pet;

// Case 2: Return multiple types

/**
 * Document each option
 * @returns a PetCreated
 * @returns a PetAccepted
 */
op create(): PetCreated | PetAccepted;

/**
 * Document only one, PetAccepted variant is not documented
 * @returns a PetCreated
 */
op create(): PetCreated | PetAccepted;

/**
 * Case 3: Return type or error
 * @returns a Pet
 * @returns a NotFound
 */
op read(): Pet | NotFound;

/**
 * Case 4: Return multiple types and errors
 * @returns a PetCreated
 * @returns a PetAccepted
 * @returns a BadRequest
 * @returns a Unauthorized
 */
op create(): PetCreated | PetAccepted | BadRequest | Unauthorized;
```

There is 2 issues with this approach:

1. We cannot document the union of return types just each variants

This maybe could be solved by having a different tag for the union of return types and one for the variants. (e.g. `@returns` and `@returnsVariant`) as well as having a `ReturnType` exposed on the operation where this information could be tagged on.

2. This becomes quite confusing when using `op is` where the variants response are hidden.

```tsp
op ResourceCreate<T, E>(): T | E;
/**
 * @returns a Pet
 * @returns a Error
 */
op create is ResourceCreate<Pet, Error>;
```

On top of this we probably wouldn't need to make sure that with `op is` the union is cloned so documenting an instance of `op is` doesn't apply the doc to each parent.

## Alternative solution: Http specific decorators

An alternative could be to have an http specific decorator that can be used to document the right variant. The decorator would take the status code used to discriminated the response(Or union of them).

```tsp

@httpResponseDoc(201, "Pet Created")
@httpResponseDoc(202, "Pet Accepted")
op create(): PetCreated | PetAccepted;
```

**Comment by timotheeguerin** [comment]
Created issues https://github.com/microsoft/typespec/issues/2384 or bugs #2383

**Comment by bitfl0wer** [comment]
As I understand it, this current implementation does not allow me fine-grained control of what my response descriptions will read. I personally liked the approach ["Doc comment solution"](https://github.com/microsoft/typespec/issues/2185#:~:text=Doc%20comment-,solution,-With%20the%20previous). On another note, the `@errors` and `@docErrors` operators seem to be overridden by `@statusCode`. As such, as thankful as I am for this amazing description language and the changes made, I am still unsatisfied with documenting individual status code responses.

Another idea would be to modify the `@statusCode` operator as such:

```typespec
@statusCode("Reason") statusCode: 401
```
