### ISSUE TITLE
Implement `@parameterVisibility` and `@returnVisibility` in TypeSpec core

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#2186]
Implementation issue for https://github.com/Azure/typespec-azure/issues/3214

Add the following decorators:
- [x] `TypeSpec.@parameterVisibility` that applies to operations
- [x] `TypeSpec.@returnVisibility` that applies to operations
- [x] **BREAKING** Update HTTP `getRequestVisibility` to use this.
- [x] Update OpenAPI3 emitter to make use of this.

Companion PR in Azure.Core:
- [x] Update Autorest emitter to make use of this.
- [ ] Update `AzureCore.ResourceCreateOrUpdate` template to use `@parameterVisibility` to fix 3214.

**Comment by markcowl** [comment]
Feels like we should have the resource operation decorators set a default for these (which would likely resolve the issue in the current Azure.Core ResourceCreateOrUpdate template without having to add these decorators explicitly.

https://github.com/microsoft/typespec/blob/main/packages/rest/lib/rest-decorators.tsp#L61-L121

**Comment by bterlson** [comment]
I think `@parametersVisibility` (plural).

I also think `@returnTypeVisibility`. Verbose but, I think rarely used.

**Comment by markcowl** [comment]
est: 8
