### ISSUE TITLE
How many operations should we generate for this case in the OpenAPI3 emitter ?

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2193]
[Typespec Playground link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3ytjLWNsaWVudC1nZW5lcmF0b3LINgp1c2luZyBUeXBlU3BlYy5IdHRwO9AVUmVzdNEVVukAqMgbQcR5LkNvcmXSEi5UcmFpdHPPGeUAlUfoAJTHOwpAdXNlQXV0aCgKICBBcGlLZXnEDjzGC0xvY2F0aW9uLmhlYWRlciwgImFwaS1rZXkiPiB8IE%2FEKjLFL1sKICAgIHvFBiAg5AEJOscfRmxvd%2BQAxy5pbXBsaWNpdCzHJWF1dGhvcml6xWFVcmw6ICLkAcBzOi8vbG9naW4uY29udG9zby5jb20vY29tbW9uL2%2FENTIvdjIuMC%2FIQGUiyFJzY29wZXM6IFvJSXdpZGdldM1KLmRlZmF1bHQiXcY3fQogIF0%2BCikKQHNlcnZpY2Uo5ADGdGl0bGU6ICJDxjogV8VJIE1hbmFnZXIiLAp9xzFlcuQBOSJ7ZW5kcG9pbnR9x3TlAJXQP0FQSXPFGcRjICBAZG9jKCIiIgpTdXDkAk9lZMgpU%2BYAi3MgyFdzIChwcm90b2NvbCBhbmQgaG9zdG5hbWUsIGZvciBleGFtcGxlOgrpAPhlc3R1cy5hcGku8gEDKS4KIiIiKeUAg8hgOiBzdHJpbmfkAJ195AEN5wMZZWQo5wDELuYAm%2BcBAugCkXMpCuQAh3NwYWNlINUq5AJj5QDoVGjJIu8BTyDnAXogx3UuIikKZW51bSDIZeUBMMZGxxMgMjAyMi0wOC0zMeUAyuQCxkRlcGVuZGVuY3ko6wMLyEQudjFfMF9QcmV2aWV3XzLENWDJRTBgLAp96ACpQSDnATQiKQpAcmVzb3VyY2UoIsYVcyIpCm1vZGVs6ADE5QCba2V5yCFOYW1l5gCT6QD2xhkg5AEpxFQgIEB2aXNpYmlsaXR5KCJyZWFkxRbEIOgBiDsKzUJJRCBvZiB0yUwncyBtYW51ZmFjdHVyZXLGVswSSWTNSi4uLkV0YWdQcm9wZXJ0eTvkAO0vLyBPcOQEDOUBYi%2FTAQphbGlhc%2BgCjeYEVCA9IOcCrnNSZXBlYXRhYmxlUmVxdWVzdHMgJgogyR9Db25kacRdYWzWIOUEkMcbSWQ7Csdv6wCVPewE1FLnAYrKIDztAJo%2BOwoKaW50ZXJm5AKM5gGe5gI67ADqIFN0YXR1c%2BkBXkfEJXPFFOQBY2HHOSDkASnFMeYBXGdldMYZyUnGSCBp7ACxLkdldPEAp8YpPMY%2FPuUBewpA5gYi5QRr6AH5IkxvYWRUZXN0QWRtaW5pc3TGP%2BYBJ%2BcE5OcDKTr2A2vlBJbqAQNB6AD9QSAiZ2xvYmFsIiBSUEPqANvkAQVyb3V0ZSgix1kt5gEK6wLAUmVzcG9uZHMgd2l0aOgBKWluZm9ybcVEIGFib3V05QKbb3ZlcmFsbOgApeYBOccN6gEuUnBj6QEbPOYGNn3mAN3oBj7GZVPlAr7qAsbEGscp7QH3CiAgPsQe%2FwDr%2FwDr%2FwDr%2FwDr8wDrMuQA7OcChS74Aj47Cgp9&e=%40typespec%2Fopenapi3&options=%7B%7D)

In this example, I have defined something like 
```
interface Widgets {
  // Operation Status
  @doc("Gets status of a Widget operation.")
  getWidgetOperationStatus is Operations.GetResourceOperationStatus<Widget>;
}


@client({
    name: "LoadTestAdministrationClient",
    service: Contoso.WidgetManager,
})
interface A {
  // A "global" RPC operation
  @route("service-status")
  @doc("Responds with status information about the overall service.")
  serviceStatus is RpcOperation<
    {},
    {
      statusString: string;
    },
    ServiceTraits
  >;
  
  // A "global" RPC operation
  @route("service-status")
  @doc("Responds with status information about the overall service.")
  serviceStatus2 is Widgets.getWidgetOperationStatus;
}
```
It turns out the openAPI3 emitter generated 3 operations, and in the `serviceStatus2` operation, it actually respect the renaming that is defined by the interface where @ client decorator is decorated on. does this mean it somehow respects the client customization from client.tsp if we feed the entry point as client.tsp even for OpenAPI3 emitters ? 

Also, Should we allow to define an independent operation in the interface that @ client is decorated on ?  Similar issue in https://github.com/Azure/typespec-azure/issues/3309

**Comment by qiaozha** [comment]
@markcowl  sorry, I am kind of getting confused, Are openAPI emitters not in this repository ? 
I know that client.tsp is not used in creating openAPI, but I am think more of we should technically ignore client.tsp even if we pass it as the entry point, not by asking customer to not using it as an entry point.

**Comment by markcowl** [comment]
@qiaozha The POR is to use client.tsp for client generation only
