### ISSUE TITLE
[compiler] Standard library types for `usize` and `isize`

### ISSUE THREAD

**Issue by witemple-msft** [microsoft/typespec#2194]
I'm proposing the following additions to the TypeSpec core library:

- scalar **usize**, analogous to `size_t` from stdint.h, representing the size of entities and indexes into arrays, memory buffers, etc.
- scalar **isize**, analogous to `ssize_t` from stdint.h, representing an offset over `usize`

```tsp
/**
 * An unsigned integer representing a size or index value.
 * 
 * The actual size of this type is platform-dependent, where it is large enough to reference any location in memory.
 */
scalar usize extends integer;

/**
 * A signed integer representing a size or index offset value.
 * 
 * The actual size of this type is platform-dependent, where it is large enough to reference any location in memory.
 */
scalar isize extends integer;
```

**Why is this necessary**:

Many programming languages have a concept of a `size` type. For example, C's `size_t`, Rust's and Zig's `usize`, etc. These languages use these types to ensure that indices/sizes are large enough to reference the whole virtual memory of the platform, but they also have a conceptual purpose of separating integers that represent application data from integers that represent offsets/sizes in type space.

In order to comprehend and faithfully represent this distinction in emitters, we need corresponding types in TypeSpec.

**Notes about size**:

Every modern CPU architecture I'm aware of commonly uses 48-bit virtual addressing or less. This is standard, for example, on x86_64 and aarch64. Even extended addressing modes on these platforms do not exceed the size of a `safeint`, so even though this type is represented as 64-bits wide on most platforms, I believe it is safe to encode as a `safeint` in JSON. This is also another argument for introducing a separate type, as `size` values are _generally_ safe to encode as safeint, but `int64`/`uint64` are not.

CC @bterlson

**Comment by witemple-msft** [comment]
Design discussion outcomes:

- Some investigation is needed to determine whether or not moving from u32/i32/u64/i64 to usize/isize is breaking for common APIs.
- There's some hesitation that it will be too easy to forget about these types and not use them in APIs, and for the same reason that we need this type in the first place it isn't easy to lint/annotate places where it may have been forgotten.
- There is concern about whether or not usize/isize should extend `integer` or `safeint` and what the implication is for JSON serialization.

**Comment by timotheeguerin** [comment]
Closing in favor of implementation  #2398
