### ISSUE TITLE
Should report on use of deprecated type in template constraint

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2216]
```
#deprecated "Don't use this"
model Foo{
  
}

model Bar<T extends Foo> {
        
}
```
This should have emitted a deprecated diagnosostic at `extends Foo`
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=I2RlcHJlY2F0ZWQgIkRvbid0IHVzZSB0aGlzIgptb2RlbCBGb297CiAgCn0KxxFCYXI8VCBleHRlbmRzxB8%2BIMYh&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by markcowl** [comment]
Note that this is true of constraints in aliases as well

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=I2RlcHJlY2F0ZWQgIkRvbid0IHVzZSB0aGlzIgptb2RlbCBGb297CiAgCn0KxxFCYXI8VCBleHRlbmRzxB8%2BIMghYWxpYXMgQmF6PFXOIT3FNlU%2BOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by daviwil** [comment]
It looks like we delay checking of template parameters in model declarations until the first time that another type instantiates it (either partially or fully).  That's not the only issue preventing diagnostics to be raised for the use of a deprecated type here, but it's the first thing that might need to be dealt with to ensure that a diagnostic gets raised even if the type isn't being used somewhere else yet.

I didn't have enough time today to debug this further so I won't be able to get a PR out before I go on leave :(

**Comment by timotheeguerin** [comment]
Have a fix for that, there was 2 issues:
1. The check to make sure it wasn't reporting in template instance was preventing it from reporting for template constraint in instances
2. As you found out, we were not checking the template parameters of a template declaration but only when we start using it (that never worked before either)
