### ISSUE TITLE
OpenAPI3 can't handle null

### ISSUE THREAD

**Issue by heycalmdown** [microsoft/typespec#2217]
```typespec
@service({})
namespace Test {
  op get(): null;
}
```

shows `<unknown location>:1:1 - error @typespec/openapi3/invalid-schema: Couldn't get schema for type null` error

based on `tsp` and `@typespec/openapi3` version -> v0.46.0

**Comment by bterlson** [comment]
This should be fixed, but just to check, do you want void instead? That signature would imply sending a json body with null in it.

**Comment by heycalmdown** [comment]
You're right. The above example was too simplified. The following will be closer to the my original intention:

```typespec
model Result {
  count: int32;
  list: string[];
}

model EmptyResult {
  count: 0;
  list: null;
}

@service({})
namespace Test {
  op get(): Result | EmptyResult;
}
```

**Comment by mikekistler** [comment]
There's actually a good reason for the openapi3 emitter not handling `null`. The [OpenAPI 3 spec](https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/versions/3.0.3.md#data-types) says:
> `null` is not supported as a type (see nullable for an alternative solution).

So while the TypeSpec you posted just above gives an error, this does not:
```typespec
model Result {
  count: int32;
  list: string[];
}

model EmptyResult {
  count: 0;
  list: null | string[];
}

@service({})
namespace Test {
  op get(): Result | EmptyResult;
}
```

**Comment by markcowl** [comment]
fix error location for this diagnostic

**Comment by heycalmdown** [comment]
@mikekistler Thank you for the workaround. I believe that all plugins should respect a valid TypeSpec syntax. While it's understandable that they may not support certain specifications.
