### ISSUE TITLE
Improve the doc/intellisense for @info decorator

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2228]
The doc/intellisense for `@info` should be more helpful in guiding users on the content and format of its arguments. Currently the help just says:

> Specify OpenAPI additional information. The service `title` and `version` are already specified using `@service`.

<img width="572" alt="Pasted Graphic 1" src="https://github.com/microsoft/typespec/assets/85643503/63edfb50-aa27-43a9-94bb-a6cad2a689be">

More helpful would be something like the `@server` help that names each value and its contents.

<img width="582" alt="Pasted Graphic" src="https://github.com/microsoft/typespec/assets/85643503/113b7722-ab3b-4ec1-8a04-60f2eb3170fe">

The difference here may be that `@info` takes a model as a parameter whereas `@server` takes discreet parameters -- so perhaps changing `@info` to take discreet parameters is the easiest fix.  But if we want decorators that accept models to have good help/intellisense, we should figure out how to do that.

**Comment by markcowl** [comment]
- improve tooling to provide help for the underlying model in these scenarios (OpenAPI.AdditionalInfo)
