### ISSUE TITLE
Special case of encoding for utcDateTime blocks desirable use cases

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2231]
The openapi3 (and autorest) have the following special case for `@encode`:

> - encoding a `utcDateTime` or `offsetDateTime` will produce this format `date-time-<encoding>` (e.g. `date-time-rfc7231` for `rfc7231` encoding)

While this special case might be handy for the `date-time-rfc7231` format, it prevents the use of `@encode` for the `http-date` format and possibly other date formats in the [OpenAPI Format Registry](https://spec.openapis.org/registry/format).

The existing behavior can be preserved by simply special casing "rfc7231" -- just as "unixTimestamp" is currently special cased.

**Comment by markcowl** [comment]
- look to make sure current mappings are in the openapi3 registry as well

**Comment by markcowl** [comment]
est: 2

**Comment by mikekistler** [comment]
I'm going to try to knock this one out myself.

**Comment by mikekistler** [comment]
Here's an interesting wrinkle: the "Next" version of the [docs for the HTTP library](https://microsoft.github.io/typespec/next/standard-library/http/encoding#utcdatetime-and-offsetdatetime) says:

<img width="577" alt="image" src="https://github.com/microsoft/typespec/assets/85643503/f6a21e1f-ed52-4b4f-9175-fac8087728f4">

I interpret this to mean that the openapi3 emitter should render a utcDateTime in a header with "format: http-date-rfc7231" (changing to "http-date" with the fix for this issue), but this is not the behavior I see in the playground.

[Playground example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKbW9kZWwgx0bEWUB2aXNpYmlsaXR5KCJyZWFkIiwgInVwZGF0ZSIpxCBwYXRoCiAgaWQ6IHN0cmluZzsKCiAgd2VpZ2h0OiBpbnQzMjsKICBjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsd6RcQMxXljb2Rly0BtZXNzYWdlymXEOnJvdXRlKCIvd%2BUAsHMiKQpAdGFnKOcBBsQQaW50ZXJm5ADoxxTFXEDkAN7kAM0o5QC%2F6wC9LCBAaGVhZGVyIGlmTW9kaWZpZWRTaW5jZTogdXRjRGF0ZVRpbWUpOsdPIHzmALI7Cn0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

Should I fix this?
