### ISSUE TITLE
Share Open API type across specs

### ISSUE THREAD

**Issue by maggiepint** [microsoft/typespec#2239]
Hi folks,

Forgive me if this is possible and I'm just bad at reading the docs. I currently have a Node.js 'front door' service/public API that calls into a Go core service. The APIs on the Go service are mostly not public, and are defined as OpenAPI v2 specifications (and protos if that in any way makes this easier).

For a limited subset of complex types, I want to 'forward' the types from the Go service's Open API definition into the public API, as a property of another type. Simplified, it would look something like this:

```
model Service {
  @visibility("read", "update")
  @path
  id: string;
  customerId: string;
  name: string;
  metadata?: TypeFromOtherAPISpec;
}
```

Ideally, there would be to make an almost 'virtual type' from another open API specification, something like:
```
model Service {
  @visibility("read", "update")
  @path
  id: string;
  customerId: string;
  name: string;
 @fromOpenApi("/filePathToOtherTypeInOpenApiSchemaFormat")
  metadata?: unknown;
}
```

Is there a good way to do something like this? Otherwise I can make a build step to do a bunch of string replacement.

**Comment by timotheeguerin** [comment]
Yes you can use `useRef` from the openapi3 emitter. However seems like we have a bug and it doesn't generate correctly.

https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvb3BlbmFwaTMiOwoKbW9kZWwgRm9vIHsKICBiYXI6IEJhcjsKfQoKQE9wZW5BUEkudXNlUmVmKCIuL2NvbW1vbi%2FFSi5qc29uI2NvbXBvbmVudHMvc2NoZW1hcy9CYXIiKcdZQmFyyllzdHJpbmfEXA%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

However be careful on the use of it. The value is taken as it is right now so it needs to account where the openapi is going to be emitted.

**Comment by maggiepint** [comment]
This should just generate a standard ref with an exact copy of that string right? without the `kind` and `isFinished` it is currently generating?

Is there any work around for this? Unfortunately it's a little hard to understand what work-around options are available just from the API ref, so I"m sorta down to using a regex replace on the incorrect outputs or something to get around this.

**Comment by timotheeguerin** [comment]
Indeed, that is the bug right now, we have a release next tuesday, this should be easy enough to fix and make it for that release.

I can't think of any workaround for it unfortunately
