### ISSUE TITLE
update http library documentation for `@encode` to explicitly call out encoder intent

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2256]
The "Next" version of the [docs for the HTTP library](https://microsoft.github.io/typespec/next/standard-library/http/encoding#utcdatetime-and-offsetdatetime) says:

<img width="577" alt="image" src="https://github.com/microsoft/typespec/assets/85643503/f6a21e1f-ed52-4b4f-9175-fac8087728f4">

I interpret this to mean that if a TypeSpec definition imports the `http` library, then any emitter, including the openapi3 emitter, will treat a utcDateTime in a header as `rfc7231`. For the openapi3 emitter, that means the header will be rendered with "format: http-date-rfc7231", but this is not the behavior I see in the playground.

[Playground example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKbW9kZWwgx0bEWUB2aXNpYmlsaXR5KCJyZWFkIiwgInVwZGF0ZSIpxCBwYXRoCiAgaWQ6IHN0cmluZzsKCiAgd2VpZ2h0OiBpbnQzMjsKICBjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsd6RcQMxXljb2Rly0BtZXNzYWdlymXEOnJvdXRlKCIvd%2BUAsHMiKQpAdGFnKOcBBsQQaW50ZXJm5ADoxxTFXEDkAN7kAM0o5QC%2F6wC9LCBAaGVhZGVyIGlmTW9kaWZpZWRTaW5jZTogdXRjRGF0ZVRpbWUpOsdPIHzmALI7Cn0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by timotheeguerin** [comment]
Yeah the doc is correct, the openapi3 emitter should be fixed.

**Comment by timotheeguerin** [comment]
I think autorest does it correctly

**Comment by mikekistler** [comment]
I think the key concern for me is that this doc is for http library -- not the emitters. I don't think the http library currently does any defaulting of encode values for any type.  We _could_ change the openapi3 and autorest emitters to implement this behavior, but it would still be incorrect to document this for the http library.

**Comment by timotheeguerin** [comment]
I disagree, the http libraries makes some assumption of what the typespec means in many ways. If we have this default then it has to be set by http library. You can’t have every emitter interpret it their own way and then be incompatible with each other.

If we don’t want to have this default at all we can discuss it but as far as I remember dpg emitters already respect this behavior

**Comment by mikekistler** [comment]
Sorry if I wan't clear. I did not mean to imply that the http library shouldn't do this.

My point was that to make the doc accurate we need to change the http library and not the openapi3 and autorest emitters.

**Comment by markcowl** [comment]
est: 1

Update documentation to indicate emitters should interprest these values this way

**Comment by mikekistler** [comment]
Should I open a separate issue to fix the autorest and openapi3 emitters?

**Comment by timotheeguerin** [comment]
Yeah maybe be good

**Comment by markcowl** [comment]
@mikekistler yes
