### ISSUE TITLE
Deprecate/remove `watchForChanges` compiler options

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2264]
This option is not used and does nothing. It used to be used by the CLI in the way it resolved the compiler options but that was some internal details to the CLI. By the time it makes it to `compile()` which is where the compiler options would get used.

**Comment by markcowl** [comment]
**Describe the breaking change**


**Back-compat design to avoid immediate breaking**


**Link to detailed breaking design**

**Impact**
This change affecting:

- [ ] ARM
- [ ] Data-plane
- [ ] Existing specs: approx. # of service/spec impacted
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: September 2023

**Additional information**
Add any other information about the change including fixes for here.
