### ISSUE TITLE
[regression][compiler] `--config` doesn't work in `0.47.0`

### ISSUE THREAD

**Issue by archerzz** [microsoft/typespec#2277]
## Problem

In `0.47.0`, specifying a `--config` through CLI doesn't work, and it will parse the `main.tsp` as config YAML which will result in errors like below:
```
C:/Users/xxxxxxxxxxx/autorest.csharp/node_modules/@azure-tools/cadl-ranch-specs/http/type/model/inheritance/enum-discriminator/main.tsp:1:2 - error file-load: end of the stream or a document separator is expected (15:9)

 12 | @doc("extensible enum type for discrimi ...
 13 | enum DogKind {
 14 |   @doc("Species golden")
 15 |   Golden: "golden",
--------------^
 16 | }
 17 |
> 1 | import "@typespec/http";
```

The problem is in the https://github.com/microsoft/typespec/blob/42d00cef2bd13ec70407ea77d5a0249cdaa3f154/packages/compiler/src/config/config-to-options.ts#L49-L52
Due to operator precedence，`options.configPath ?? entrypointStat.isDirectory()` is calculated first. So you'll always get `options.entrypoint` if `--config` is specified.
That can be confirmed by the transpiled codes:
> const configPath = ((_b = options.configPath) !== null && _b !== void 0 ? _b : entrypointStat.isDirectory())
        ? options.entrypoint
        : getDirectoryPath(options.entrypoint);

**Comment by timotheeguerin** [comment]
Hotfixed in 0.47.1
