### ISSUE TITLE
Should `--config` allow a directory

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2282]
I was under the impression that `--config` was supposed to be the path to a config file but it seems like(minus this bug https://github.com/microsoft/typespec/pull/2278) that if you pass a directory it will lookup for `tspconfig.yaml` at that path as well as looking up if there is none.

This feels like an unexpected behavior to me

**Comment by archerzz** [comment]
@timotheeguerin Right now it's by design. See here: https://github.com/microsoft/typespec/blob/42d00cef2bd13ec70407ea77d5a0249cdaa3f154/packages/compiler/src/core/cli/cli.ts#L109

> If a folder is specified, the CLI will attempt to search for 'tspconfig.yaml' by moving up the folder hierarchy.

**Comment by timotheeguerin** [comment]
Yeah but that logic was meant to resolve from the entry point. If you pass —config explicitly I ran pretty sure it wasn’t planned that it would follow this logic as well. And from bringing this up in dpg meeting today, seems to have been a surprise to everyone that knew. 

So more wondering if anyone depends on it or we will remove.

**Comment by tjprescott** [comment]
Here's the PR that added this. The behavior is stated pretty clearly.
https://github.com/microsoft/typespec/pull/1690

Is this causing some kind of issue?

**Comment by timotheeguerin** [comment]
Not causing issue but is unexpected, from the PR there was a comment from Brian about it too


> Is it common for such command line options to crawl upwards to find a config file? I find this behavior somewhat surprising and it could result in confusing behavior when a parent folder's config file is resolved unintentionally due to a typo or whatever.

@markcowl also seems to feel like this should not be working that way.

The idea for the traversing is if you run tsp compile /to/path it would try to resolve a config up but if you want to be explicitly it does feel weird to me that we would follow the same logic and not force checking that file.

**Comment by tjprescott** [comment]
@timotheeguerin the current behavior is if a config file isn't found, it loads a default, and we have test cases that look for that behavior. If you supply `--config {folder}` that doesn't have a `tspconfig.yaml`, what do you want it to do? Should it load the default? Should it error?

**Comment by timotheeguerin** [comment]
My opinion is we should do something similar to typescript.

1. By default we traverse up and use that default config otherwise(Already doing that)
2. If you pass `--config`
   - To a file:
     - Emit error if it doesn't exists 
   - To a directory
     - Emit error if directory doesn't exists
     - Emit error if it contains no tspconfig.yaml (And don't lookup)


Example of what `tsc` does
1. Can't find tsconfig.json
2. Try to build from subdir, still lookup
<img width="652" alt="image" src="https://github.com/microsoft/typespec/assets/1031227/c16f153b-3e64-4f36-a635-6e1a053d6b6b">

3. If you pass a dir that doesn't exists 
<img width="632" alt="image" src="https://github.com/microsoft/typespec/assets/1031227/8933c4de-42fb-43ef-a317-e39f9e46559c">

**Comment by markcowl** [comment]
**Describe the breaking change**


**Back-compat design to avoid immediate breaking**


**Link to detailed breaking design**

**Impact**
This change affecting:

- [ ] ARM
- [ ] Data-plane
- [ ] Existing specs: approx. # of service/spec impacted
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: September 2023

**Additional information**
Add any other information about the change including fixes for here.
