### ISSUE TITLE
Load config yaml as ast to be able to report errors position

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2298]
Currently when loading the config we are not able to report where in the config file is the invalid property/value.

We can switch from `js-yaml` to `yaml` which provides an AST presentation and would allow us to give a better error reporting.

This would also set the groud for an emitter to report a diagnostic on its emitter options and we'd be able to track back where that option is defined.

**Comment by markcowl** [comment]
**Describe the breaking change**


**Back-compat design to avoid immediate breaking**


**Link to detailed breaking design**

**Impact**
This change affecting:

- [ ] ARM
- [ ] Data-plane
- [ ] Existing specs: approx. # of service/spec impacted
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: September 2023

**Additional information**
Add any other information about the change including fixes for here.
