### ISSUE TITLE
[Language Server] Semantic highlighting does too much

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2307]
If we look at typescript server the semantic highlighting is limited to adding information like this is a certain type not rerendering the entire Highlighting

https://github.com/microsoft/TypeScript/blob/main/src/services/classifier.ts

I believe the reason we have it this way is so that the playground can get the fully syntax highlighting as well but this feels a little bit like a misuse of the functionality. 

Wondering if we can not split the semantic versioning in 2 version:
- Full (Does everything) This would be used in the playground
- Partial (only the additional information is added) This would be used in vscode where the tmlanguage already provides most of the necessary highlighting

This would just be to reduce unnecessary overhead in the editor. It wouldn't give better or worse syntax highlighting in vscode.

**Comment by daviwil** [comment]
Sounds like a good idea to me as long as it doesn't make the code a lot more complicated.

**Comment by timotheeguerin** [comment]
i don't think this is necessary anymore as we can do the semantic highliughting with just syntax parsing and not a full compilation
