### ISSUE TITLE
Add documentation of "Doc comments" (and non-doc comments)

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2312]
TypeSpec supports JS Doc style comments as an alternative (and preferred) to `@doc`.

![image](https://github.com/microsoft/typespec/assets/85643503/7d6a0c34-93a6-4685-9370-920ad6f9511b)

But I don't think this is documented in the public docs. What's more, I also don't see normal comments ("//") documented anywhere.

I think both of these should probably be added as a section in the "Language Basics / Overview" page.

https://microsoft.github.io/typespec/language-basics/overview

**Comment by markcowl** [comment]
est: 3
