### ISSUE TITLE
Docs: Compare to Smithy

### ISSUE THREAD

**Issue by connorjs** [microsoft/typespec#2315]
I'm exploring design-first API approaches for Dot NET services/APIs. I came across TypeSpec via [Steven Mizell’s book](https://smizell.com/language-oriented-approach/case-studies) and figure TypeSpec would make the most sense given Microsoft/Dot NET ecosystem.

However, [Smithy (by AWS)](https://smithy.io) also exists and seems more mature (although that may be my own bias since I've used Smithy before). The Dot NET services may or may not run on Azure.

Could you include an FAQ or page that compares TypeSpec to Smithy (and maybe other, similar approaches)?

**Comment by markcowl** [comment]
@connorjs I don't think we are lilkely to provide a comparison between TypeSpec and other technologies, but if you have specific questions about TypeSpec capabilities and usage, we would be happy to help.
