### ISSUE TITLE
Using version in namespace route

### ISSUE THREAD

**Issue by rboylesDev** [microsoft/typespec#2322]
For our APIs, we are using the version in our API routes. i.e. "/api/v1/Person", "/api/v2/Person", etc. We are also using TypeSpec to output OpenAPI3 files. This works well to give us a version per file, however, the routes do not work.

I expected to be able to do the below

``` javascript

@versioned(Person.Versions)
@route("/api/{version}")
namespace Person;

enum Versions{
  v1,
  v2
}

```

However, this does not work and have TypeSpec saying that it can't find the parameter "version" in the endpoints. Obviously, I don't really want version to be a parameter like that, but it highlights that this does not work. Is there another way to have the version number included in the route?

**Comment by mikekistler** [comment]
I think the versioning library is designed to version an entire service and not just a namespace.

I cooked up a [playground example] that uses an `apiVersion` parameter in the server definition. This avoids the error you reported but it has some "warts". The openapiv2.yaml is a bit misleading --it seems to say "you can use v1 or v2 in the server url" but some of the paths don't work for v1.

[playground example]: https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZb3BlbmFwadUcdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwO8cVT3BlbkFQScgPySRWyUE7CgpAc2VydmljZSh7CiAgdGl0bGU6ICLKIiIsCn0pCi8vIE11bHRpcGxlIMQwZXJzIGNhbiBiZSDkAJNpZmllZMZKZXIoIuQA1nM6Ly93aWRnZXRzLmNvbnRvc28uY29tL2FwaS97YXBpx2J9IiwgInByb2R1Y3Rpb24iLCDkAIcuLi5BySNQYXRoUGFyYW1ldGVyO%2BQAjkDnAQJlZCjHJHMpCm5hbWVzcGFjZSBJbmZvQW5kU%2BYAqDsKCmVudW0gyCrFYXYxLMQGMiwKfQoKQGRvYygiVGhlIMp1IHBhdGggcMh3LiIpCm1vZGVsyyPtAJjFVkDENSgiYXBpLecAoiIpxBfKYFBJIMcaIG9mIHRo5gFOaWNlxSnqARc66gCvPckLLnYxO%2BQAsOYAiVflAV3GeGtleSBpZDogc3Ry5QHVICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSLEGUBhZGTrAUkudjIpIOQBTMpO5AEjcm91dGUoIugB0yLsAXDmAIrmAVlA5ACUb3AgZ2V0KOUBD%2BsAmCk6xys7CtZ4x0DEB8hwY3VzdG9tR2V05QEhb3AgyRHcX30K&e=%40typespec%2Fopenapi3&options=%7B%7D

**Comment by rboylesDev** [comment]
The playground example doesn't have too many warts, and really isn't that bad. Ultimately I really do want to version my entire service. I would just expect that if I am doing version as part of the URL, that it would live on the path definition of the endpoint rather than a server definition. It feels weird as if someone pulled the outputted spec, but had a different hosted base URL, I would expect them to be able to swap out the server URL and not have to be concerned with ensuring version matches.

So, like below is a snippet of what I'd want. This really means the server is just the bad URL for my API hosted service, where the path defines 

``` yaml
openapi: 3.0.0
info:
  title: Versioning
  version: v2
tags: []
paths:
  /api/v2/widgets/customGet/{id}:
    get:
```

**Comment by markcowl** [comment]
I think this idea of having a placeholder for version that can be referenced in api elements like routes is covered by [this design issue](https://github.com/microsoft/typespec/issues/2819), so closing this issue in favor of that
