### ISSUE TITLE
Improve Getting Started doc

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2333]
User feedback on [Getting Started doc](https://microsoft.github.io/typespec/getting-started):

- I found it difficult to follow the “Getting Started” doc. It does a good job introducing TypeSpec concepts and builds upon the previous section(s) but it didn’t get me to running code like I was expecting.
- For example, it didn’t include any instructions on creating the TypeSpec project, compiling the project, or using emitters to produce OpenAPI output.
- I ended up using a combination of the playground, GitHub repo, and docs to get up and running with my first project.
- Suggestion: E2E doc on getting started, building a simple TypeSpec API, compiling, and emitting to OpenAPIv3

**Comment by markcowl** [comment]
est: 5
