### ISSUE TITLE
[compiler] Crash due to heap exhaustion 

### ISSUE THREAD

**Issue by witemple-msft** [microsoft/typespec#2338]
Inside of a model, union, or enum (but not a namespace), a doc comment can lead to a deadlock that eventually exhausts the JS heap if the doc comment doesn't have anything to annotate.

Be careful about typing any of the following examples into the TSP playground, as they'll hang your browser tab.

Minimal repro:

```typespec
model Foo {
  /** */
}
```

Other repros:

```typespec
model Foo {
  /**
   * Test
   */
   */
  bar: string;
}
```

These examples appear to deadlock the compiler, eventually terminating the JS engine. Tested in Node & Safari on Apple M2.

**Comment by witemple-msft** [comment]
We are stuck in the `while (true)` loop of `parseList`. It parses the same item over and over again, never advancing the token until it eventually exhausts the heap by appending too many items to the list.

**Comment by qiaozha** [comment]
I just want to point out there's really a service is using '*/read' in their description [swagger link](https://github.com/Azure/azure-rest-api-specs/blob/0c4762d037f0d00d4e384add4e3d7200a2993b2c/specification/resources/resource-manager/Microsoft.Resources/preview/2022-08-01-preview/deploymentStacks.json#L1093) . So if the solution is to have a linter rule, it might not work for this service, when they starting to use TypeSpec.

**Comment by witemple-msft** [comment]
We will definitely fix this. If `*/` occurs inside a documentation comment it must be escaped one way or another. This is a deadlock that can occur in several cases not just with `*/`. For example the following will also deadlock the parser:

```typespec
model X {
  /** */
  +
  y: string;
}
```
