### ISSUE TITLE
Support for title in schemas

### ISSUE THREAD

**Issue by norelina** [microsoft/typespec#2339]
Is there a way to add a title in the schemas when generating the OpenAPI spec using TypeSpec?

<img width="759" alt="image" src="https://github.com/microsoft/typespec/assets/54459761/021fd0bf-936a-436f-a6ba-175a101cd5ab">

**Comment by bterlson** [comment]
There is presently no way to set title, it should be added (to both OpenAPI and Json Schema).

**Comment by timotheeguerin** [comment]
Title can be provided with `@summary` now(since a 0.50.0)
https://typespec.io/playground?c=QHN1bW1hcnkoIk15IHRpdGxlIikKbW9kZWwgQSB7fQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D
