### ISSUE TITLE
[compiler] Named instantiation of template arguments

### ISSUE THREAD

**Issue by witemple-msft** [microsoft/typespec#2340]
Per a previous design discussion, we've decided to move forward with the following implementation of named instantiation of template arguments (known as "Option 3" in the discussion):

## Implicit Naming of Template Arguments

We will allow all template arguments to be specified by name, using `<Identifier> = <Type>` syntax.

We will allow template arguments to be specified positionally for all or part of a template instantiation, with the following rules:

- A positional argument instantiation cannot follow a named instantiation.
- If an argument is instantiated by name before all required positional arguments are instantiated, all remaining required arguments must be instantiated by name.
- A named instantiation may not bind the same argument name as a prior positional instantiation (i.e. it may not override or merge with a previous positional instantiation).

For example, given the following template:

`model Foo<T1, T2, T3 = string, T4 = number> { ... }`

We will allow all of the following:

1. All positional, like we currently do:

    `Foo<I1, I2, I3, I4>`

2. All _required_ arguments positional, with some or all of the defaultable arguments omitted, like we currently do:

    `Foo<I1, I2>`
    `Foo<I1, I2, I3>`

3. Some or all of the defaultable arguments specified by name, in or out of order:

    `Foo<I1, I2, T4 = I4>`
    `Foo<I1, I2, I3, T4 = I4>`
    `Foo<I1, I2, T3 = I3, T4 = I4>`
    `Foo<I1, I2, T4 = I4, T3 = I3>`

4. Some or all of the mandatory arguments specified by name or position, in or out of order:

    `Foo<I1, T2 = I2>`
    `Foo<T2 = I2, T1 = I1>`
    `Foo<T3 = I3, T1 = I1, T4 = I4, T2 = I2>`

But we will **disallow**:

1. Positional instantiation following a named instantiation

    ```
    Foo<T1 = I1, I2>
                 ~~ <-- Positional template arguments cannot follow named arguments.
    ```

    **Error Recovery**: Positional arguments that occur after named arguments will themselves be checked, but not bound to any arguments in the template. `T2` will be treated as if it is unspecified.

2. Named instantiation that omits a mandatory argument:

    ```
    Foo<T2 = I2>
    ~~~~~~~~~~~~ <-- Template argument 'T1' is mandatory and not specified in this instantiation.
    ```

    **Error Recovery**: We will instantiate all missing mandatory arguments with `ErrorType`.

3. Named instantiation of previously-specified positional argument:

    ```
    Foo<I1, T1 = I1, T2 = I2>
            ~~~~~~~ <-- Cannot specify template argument 'T1' by name, as it was already specified by position.
    ```

### Implementation Considerations

When evaluating template argument intantiations, we will perform evaluation (such as decorator evaluation) in the order specified by the template argument _definition_, not the order of the template argument _instantiation_, to ensure that template evaluations are deterministic and not dependent upon the order in which an API consumer has written the arguments.

## Conceptual Breaking Change

Template parameter names were not previously part of an API's contract. With this change we will be making the names of template parameters part of the API surface. No existing code will break, as we will still allow parameters to be specified positionally, but existing template contracts will be strengthened. After this feature is merged, changing the name of a template parameter will be an API breaking change, where it is not a breaking change to do so currently.

### Breaking Change Mitigation

Prior to merging and releasing this feature, we should conduct a review of all core templates and ensure the names are suitably descriptive (i.e. not just `T` unless we're certain that's enough).

## Future Considerations

We may in the future decide to support additional syntax to indicate that a template argument may _only_ be specified by name.

**Comment by daviwil** [comment]
@markcowl @allenjzhang It seems this issue might have missed triage somehow?  It doesn't seem to be assigned to the project or any milestone.
