### ISSUE TITLE
is bytes[] a valid syntax ? 

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2344]
bytes already means byte array, I wonder what would bytes[] mean in actual user scenario ?  Does it mean a two dimension byte array ? but I feel like bytes has the implication of stream data, which should not be delimited by stream length ?

**Comment by bterlson** [comment]
It is valid syntax, it might mean a two dimensional byte array or some other collection of collection of bytes, depending on context. Unsure what the last part means but closing this for now as answered 😁

**Comment by qiaozha** [comment]
sorry I mean binary data. I just figured that bytes[] should be able to allow each bytes to have different length ? so it makes sense to me now. Thanks for the explaination. 😊
