### ISSUE TITLE
should we discourage non-discriminated unions ?

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2345]
For non-discriminated unions, it's kind of difficult to do serailize and deserialize if any variants has a different interpretation over the wire layer and SDK layer. 

We have several cases for unions that would cause problems
1. scalar union, but more than one union variants have the same type over the wire layer.  For example, 
    ```
    model Widget {
      data: utcDateTime | string;
    }
    ```
    
    for the `utcDataTime` type, it's a string in the wire layer, but it's a `Date` in the SDK layer. If I get a string, I actually don't know if I should deserialize it as a `Date` or not.  Other similar cases like `bytes | string`, or even strings with different formats.

2. model union.
     1) more than one union variants have the same required properties, but service team intend to distinguish them by non-required properties.
          ```
          model Foo {
             name: string;
             @projectedName("json", "foo_prop") // here the projected name added just to make sure this union variant is different between the SDK layer and wire layer as such deserialization and serialization is required for this union.
             fooProp?: int32;
          }
          
          model Bar {
            name: string;
            @projectedName("json", "bar_prop")
            barProp?: boolean
          }

          model Widget {
            data: Foo | Bar;
          }
          ```
          
           The problem here is, if I get an object `{ name: "some name", bar_prop: false }` and I can assign it to the deserialize function for Foo, without any error.  see [typescript playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt0CUIGczIDeAUMmciHALYQBcy+UoA5gNynkyYD6ADlOl4B+eiACuVAEbR2AX2LFQkWIhQAhOFBz4iHMpRr1GLduWSTNfAcNETpUOQoToQO9JIBWyALxEDdZAAiXHQaCmoIQIAac0t+QXoARgAmeWIYMRAEMGAXZAATPGhgOAAbYAAvCAx0AAooPDAAWXRC0voa7TAASl1iNMLcYrLK6sxa9w9u1iA) One argument here is that because we treat unions as anyOf, we could just deserailze as long as we found any variants match, so after deserialized as variant Foo, I still get `{ name: "some name", bar_prop: false }` and I can continue to find if there's other variants match, in this case, we found that it matches Bar as well, so after deserialize as variant Bar, I get a `{ name: "some name", barProp: false }` , which seems to be working the same as we correctly recognize it as Bar at first. But we will see another case see this way is also problematic.

     2) more than one union variants have different required properties, and service team also tend to distinguish them by those required properties. 
          ```
          model Foo {
             @projectedName("json", "name")
             fooName: string;
          }
          
          model Bar {
            name: string;
            @projectedName("json", "bar_prop")
            barProp: boolean
          }
          ```
           In this case, if I get an object `{ name: "some name", bar_prop: false }` and I can also assign it to the deserialize function for Foo, without any error.  see [typescript playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt0CUIGczIDeAUMmciHALYQBcy+UoA5gNzEC+xxoksiKAEJwoOfEVLlKNeoxbtyyAEYiA+gAco6dQH56IAK5Ul0dl2IJ0IceiUArZAF4i0usgBEudDQrUI7gBplNU1tegBGACZzGAMQBDBgK2QAEzxoYDgAG2AALwgMdAAKKDwwAFl0NKz6QrEwAEoJTm403AzsvILMIts7BtYgA) but if we adopt the previous strategy that if we found any variants match, we will just deserialize as that variant. we will get `{ fooName: "some name", bar_prop: false }` after handle it as Foo, and that object is not assignable to Bar any more, therefore, this is our final result. but if we found Bar first, we will get `{ name: "some name", barProp: false }` and we continue to find it matches Foo, in the end we will get `{ fooName: "some name", barProp: false }` and in this case, either way is not what we want.

     3) model union duplicate with itself.
          ```
          model Foo {
            @projectedName("json", "name")
            fooName?: string;
          
            @projectedName("json", "fooName")
            fooFooName?: string;
          
            @projectedName("json", "fooFooName")
            fooFooFooName?: string;
          }
          
          model Widget {
            data: Foo | Foo;
          }
          ```
          In this case, the instinct would be this is just the same `data: Foo`, but actually it's not, if we get an object of `{name: "some name", fooName: "some foo name"}`, we will get an `{fooName: "some name", fooFooName: "some foo name"}` after we handle the first union variant, then we found it still matches Foo, then we will get `{fooFooName: "some name", fooFooFooName: "some foo name"}`

3. model and Record union when model has property type that is the same as the Record.
    ```
    model Foo {
       @projectedName("json", "name")
       fooName: string;
       @projectedName("json", "prop")
       fooProp?: string;
    }
    
    model Widget {
      data: Foo | Record<string>
    }
    ```
    In this case, I will get any object with property type string, I actually don't know if I should deserialize it as Foo even if the key is name and prop, because Record<string> can also take those keys.

If we decide to still encourage people to use non-discriminated unions, could we add some linter rules to error out those ambiguous cases ? But I am a little doubt we can enumerate all the possible bad cases.

**Comment by markcowl** [comment]
closing in favor of: https://github.com/Azure/typespec-azure/issues/468
