### ISSUE TITLE
Whacky oneOf generated in operation response

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2347]
The following model
```
@doc ("This is a custom unauthorized response")
model CustomUnauthorizedResponse {
  @statusCode _: "401";
  @body body: UnauthorizedResponse;
}
```

when specified as the return type of an operation
```
@get list(): PetList | CustomUnauthorizedResponse;
```

Produces a response definition with `oneOf` with two identical entries:
```
        '401':
          description: This is a custom unauthorized response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/TypeSpec.Http.UnauthorizedResponse'
                  - $ref: '#/components/schemas/TypeSpec.Http.UnauthorizedResponse'
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CtIZb3BlbmFwaTMiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDsKCkBzZXJ2aWNlKHsKICB0aXRsZTogIsglIC0gUGV0IFPGIyIsCiAgdmVyc2lvbjogIjAuMS4wIiwKfSkKbmFtZXNwYWNlIE1hZGUuQXBpOwoKbW9kZWzFQHt9CgpAZG9jKCJQZXRzIHJldHJpZXZlZCBzdWNjZXNzZnVsbHkiKcoyTGlzdCDkAJFAc3RhdHVzQ29kZSBfOiAiMjAwIjvEGGJvZHkgxAU6xDBbXTsKfeQAzWRvYyAoIlRoaXMgaXMgYSBjdXN0b20gdW5hdXRob3JpemVkIHJlc3BvbnNlyXFDxSVVyyRSxyP1AIQ0MDHxAITUPTsK5AD3cm91dGUgKCIvYXBpL3BldHMiKQpAdGFnIOYBDSIpCmludGVyZuQBPcQRSckOxXxnZXQgbGlzdCgp5QDp5QEZfPsAssR1&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by qiaozha** [comment]
wonder when to use oneOf and when to use anyOf ? According to the code here https://github.com/microsoft/typespec/blob/f2a5424752a07b12b18d73f2ed24f0dbdc2a99b5/packages/openapi3/src/openapi.ts#L1400, it seems by default we will use anyOf for union unless it has a oneOf decorator. 

But I wonder how exactly are we going to deserialize an object if it matches more than one schemas of the union in the anyOf scenario ?

**Comment by timotheeguerin** [comment]
Weird one, doesn't even need a union, simpler repro:
https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CtIZb3BlbmFwaTMiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDsKCm1vZGVsIEN1c3RvbVVuYXV0aG9yaXplZFJlc3BvbnNlIHsKICBAc3RhdHVzQ29kZSBfOiA0MDE7xBZib2R5IMQFOiDUOzsKfQoKb3AgbGlzdCgpOttlOwo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D
