### ISSUE TITLE
Long comments add additional empty lines into the output

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2350]
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgptb2RlbCBGb28gewogIC8qKgogICAqIGHGB2LfAt8CxgLFSy8KICBzdHI6xAVpbmc7Cn0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

Notice how the description has an additional blank line on line 18.

**Comment by timotheeguerin** [comment]
I think this option from the yaml emitter 
```
 /**
     * Maximum line width (set to `0` to disable folding).
     *
     * This is a soft limit, as only double-quoted semantics allow for inserting
     * a line break in the middle of a word, as well as being influenced by the
     * `minContentWidth` option.
     *
     * Default: `80`
     */
    lineWidth?: number;
```
