### ISSUE TITLE
OpenAPI has incorrect namespace

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2351]
It's part of our standard library so it should be under the TypeSpec namespace. Unfortunately, it is under the root namespace.

**Comment by mikekistler** [comment]
👍 to this. This has always bugged me but never enough to open an issue for it.

**Comment by markcowl** [comment]
est: 3

**Comment by lmazuel** [comment]
Unless I misunderstand something, it feels DPG is not even in the path of resolution here? (I'm here since it was tagged as possible DPG impact)

**Comment by tjprescott** [comment]
What about `Autorest`?  This is part of azure-tools, so should it be `Azure.Autorest`?
