### ISSUE TITLE
OpenAPI3 generates allOf for properties with references to another schema and a doc

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2352]
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQHNlcnZpY2UKbmFtZXNwYWNlIERlbW9TxhY7Cgptb2RlbCBGb28gewogIHg6IEJhcjsKCiAgLyoqCiAgICogZG9jxQkvCiAgeccgfcg5QmFyIHsKCn0Kb3AgZ2V0KCk6xEw7&e=%40typespec%2Fopenapi3&options=%7B%7D)

Is this necessary? I could see it being necessary for a some $ref semantics, but I don't see this being used in the wild, so I suspect tools will be fine without the `allOf`

**Comment by mikekistler** [comment]
I think the Spectral linter will complain if the `$ref` is not wrapped in `allOf`.

https://meta.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#no-ref-siblings
