### ISSUE TITLE
Compiler crash when assigning default to nullable numeric types

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2354]
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgRm9vIHsKICB4OiBzYWZlaW50IHwgbnVsbCA9IDE7Cn0K&e=%40typespec%2Fopenapi3&options=%7B%7D)

```
model Foo {
  x: safeint | null = 1;
}
```

Oddly enough, it works fine with strings.

**Comment by timotheeguerin** [comment]
Fixed in https://github.com/microsoft/typespec/pull/2449
