### ISSUE TITLE
tsp init does not create tspconfig.yaml

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2357]
Creating a new TypeSpec project with `tsp init` should create a new `tspconfig.yaml` file but it does not.
```
[mikekistler@Mikes-MacBook-Pro] ~/Projects>mkdir typespec-bug
[mikekistler@Mikes-MacBook-Pro] ~/Projects>cd typespec-bug
[mikekistler@Mikes-MacBook-Pro] ~/Projects/typespec-bug>ls -la
total 0
drwxr-xr-x   2 mikekistler  staff    64 Sep  2 08:50 .
drwxr-xr-x  32 mikekistler  staff  1024 Sep  2 08:50 ..
[mikekistler@Mikes-MacBook-Pro] ~/Projects/typespec-bug>tsp init
TypeSpec compiler v0.47.1

✔ Please select a template › Generic Rest API	min compiler ver: 0.47.1
Create a project representing a generic Rest API
✔ Project name … typespec-bug
✔ Update the libraries? › @typespec/rest, @typespec/openapi3
TypeSpec init completed. You can run `tsp install` now to install dependencies.
Project created successfully.

Found .
[mikekistler@Mikes-MacBook-Pro] ~/Projects/typespec-bug>ls -la
total 16
drwxr-xr-x   4 mikekistler  staff   128 Sep  2 08:51 .
drwxr-xr-x  32 mikekistler  staff  1024 Sep  2 08:50 ..
-rw-r--r--   1 mikekistler  staff    54 Sep  2 08:51 main.tsp
-rw-r--r--   1 mikekistler  staff   217 Sep  2 08:51 package.json
[mikekistler@Mikes-MacBook-Pro] ~/Projects/typespec-bug>
```

If for some reason we decided not to create a tspconfig.yaml, then [the docs](https://microsoft.github.io/typespec/introduction/installation#create-first-typespec-project) need to be changed to reflect that.

**Comment by timotheeguerin** [comment]
I think this is because it will only write the config file if the template has config information. But I guess we could create a blank config file(or with commented out options like typescript does)

**Comment by mikekistler** [comment]
If the user selects `@typespec/openapi3` when creating the project, I think we should create a `tspconfig.yaml` that at minimum contains:
```
emit:
- '@typespec/openapi3'
```

**Comment by timotheeguerin** [comment]
That's a good point but the problem is it might be hard to know automatically if a library is an emitter at init time. We have to install it first. But maybe for this template we can just provide our tspconfig.yaml

**Comment by timotheeguerin** [comment]
Ok so we did already specify that so there is actually a bug well
