### ISSUE TITLE
Use `@maxLength()` decorators inside string array?

### ISSUE THREAD

**Issue by sebader** [microsoft/typespec#2362]
How can I add `@maxLength()` (and `@minLength()`) restrictions for elements inside a string array?

I have the following model:

```
model MyModel {
    @maxItems(50)
    foo: string[];
}
```

I'd like to put constraints on the values inside the array.

**Comment by mikekistler** [comment]
You can define the item type as a scalar with the desired decorators, e.g.
```
@minLength(1)
@maxLength(50)
scalar string50 extends string;

model MyModel {
    @maxItems(50)
    foo: string50[];
}
```

[Playground link](https://cadlplayground.z22.web.core.windows.net/?c=QG1pbkxlbmd0aCgxKQpAbWF4xw41MCkKc2NhbGFyIHN0cmluZzUwIGV4dGVuZHPHETsKCm1vZGVsIE15TcUIewogICAgxERJdGVtc8VDxBJmb286yUVbXTsKfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by sebader** [comment]
great, thanks! that works :)
