### ISSUE TITLE
Deprecated operations should be able to refer to deprecated models without a warning

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2368]
It's very hard to define an API with deprecations without getting warnings. For example, the following should not result in a warning, it's a cromulent declaration of deprecated API surface:

```
#deprecated "bad"
op Foo(): Deprecated;

#deprecated "bad"
model Deprecated {}
```

**Comment by markcowl** [comment]
est: 5

**Comment by daviwil** [comment]
@bterlson Can you help me enumerate the cases where we don't want a deprecation-on-usage to be raised inside of a deprecated "container"?

### Don't emit deprecation in these case:

- Deprecated model used in deprecated operation
- Deprecated model used in operation defined in deprecated interface
- Deprecated operation used in deprecated interface
- Deprecated model used as `is`/`extends` type in deprecated model
- Deprecated operation used as `is` type of deprecated operation

Anything else?
