### ISSUE TITLE
Include `unixTimestamp` in stdlib

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2371]
I know we discussed this previously and decided its just a `utcDateTime`, but I am not sure if we discussed the possibility of adding a declaration like:

```
@encode("unixTimestamp", int32)
scalar unixTimestamp extends utcDateTime;
```

Timestamps may be common enough to justify this addition. Also, it wouldn't preclude customizing the encoding to a different form of timestamp in the future (e.g. around the year 2038, say 😂)

**Comment by timotheeguerin** [comment]
Add to compiler std lib
Add `32` suffix to leave room for a 64bit `unixTimestamp` later
```
@encode("unixTimestamp", int32)
scalar unixTimestamp32 extends utcDateTime;
```

**Comment by timotheeguerin** [comment]
Implementation created https://github.com/microsoft/typespec/issues/2543
