### ISSUE TITLE
The array type is not recognized correctly in template model

### ISSUE THREAD

**Issue by chunyu3** [microsoft/typespec#2372]
In a template model, when we define an property whose type is an array of the templated model, e.g.

```
model NumericValuesFacet<T extends numeric> extends Facet {
  @doc("The facet ranges to produce. The values must be listed in ascending order to get the expected results. For example, values=10,20 produces three buckets: one for base rate 0 up to but not including 10, one for 10 up to but not including 20, and one for 20 and higher.")
  values: T[];
}
```

The typespec compiler does not recognize it as an array, Following is the return from compiler, it is not array as expected
![image](https://github.com/microsoft/typespec/assets/10458143/6323c176-a075-4fec-8d06-2238b79ba4f1)

**Comment by chunyu3** [comment]
> I see the model says `isfinished: false` which means decorators have not run(including the indexer) how are you gettting that type? Are you sure it is not a template instance but a declaration

Yes, the model `NumericValuesFacet` is not finished, it is a generic type.  When I define models as following, the typespec compiler will return the model definition of `NumericValuesFacet`, and in the information returned, the type of `values` is not correct. 
It is expected that the type of `values` is array. 

```
@doc("Facet")
model Facet {
   @doc("A field to facet by, where the field is attributed as 'facetable'")
   field: string;  
}

model NumericValuesFacet<T extends numeric> extends Facet {
  @doc("The facet ranges to produce. The values must be listed in ascending order to get the expected results. For example, values=10,20 produces three buckets: one for base rate 0 up to but not including 10, one for 10 up to but not including 20, and one for 20 and higher.")
  values: T[];
}

@doc("Facets an int32 field by the specified value ranges.")
model Int32ValuesFacet extends NumericValuesFacet<int32> {
  @doc("The facet type.")
  kind: "Int32Values";
}
```

**Comment by timotheeguerin** [comment]
Yes but template will be marked as finished for template instances and you shouldn't really be seeing the template declaration or if you do for some reason you need to ignore them in general unless you do actually want to keep generic types as generic in the emitted code and then yeah we might have an issue for arrays
