### ISSUE TITLE
TypeSpec doesn't accept some default values for float64

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2377]
The TypeSpec compiler errors for certain default values for a `float64` property. The linked playground shows that the values `0.1` and `42.0` work fine but `0.0` and `-42.0`generate compiler errors.

[Playground link](https://cadlplayground.z22.web.core.windows.net/?c=Cm1vZGVsIERlZmF1bHRzIHsKICAvLyB0eXBlOiBudW1iZXIsIGZvcm1hdDogZmxvYXQsIGTGLTogMAogIGZvbz%2FHGjMyID0gMC4wOwogINxHZG91YmxlzEguMQogIGJhcshKNjTFSjE7Ct9Izkg0MsVHes1HNDLkAJLGSGVycm9yOiBUeXBlICcwJyBpcyBub3QgYXNzaWduYWJsZSB0b8VtICfHQSfFOWJ1ZzDNVeUA5tNULTQy31bGVuYBIGJ1ZzQyzVgt5gCufQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by timotheeguerin** [comment]
Oh and this is really only float64, float32 works fine

**Comment by timotheeguerin** [comment]
Problem was that the range check for float64 was 

```
[Number.MIN_VALUE, Number.MAX_VALUE]
```

But Number.MIN_VALUE is not the largest negeative number but the smallest positive number closest to 0;

From docs
```
The closest number to zero that can be represented in JavaScript. Equal to approximately 5.00E-324.
```
