### ISSUE TITLE
Implementation: Documentation of responses

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2384]
Design https://github.com/microsoft/typespec/issues/2185

- Add `@returnsDoc` and `@errorsDoc` decorators to apply that data on the operation
- Add `@returns` and `@errors` on doc comment that document all success and errors variants and calls decorators above
- Update openapi3, autorest emitters to read that data.

```tsp
/**
 * @returns PetCreatedOrAccepted or PetNotContent
 * @errors NotFound or ServerError
 */
op create(): PetCreatedOrAccepted | PetNotContent | NotFound | ServerError;
// Equivalent to
@returnsDoc("PetCreatedOrAccepted or PetNotContent")
@errorsDoc("NotFound or ServerError")
op create(): PetCreatedOrAccepted | PetNotContent | NotFound | ServerError;
```

**Comment by markcowl** [comment]
est: 8

**Comment by lmazuel** [comment]
What is the format of the string inside those decorator? Random MD? Strict `type1 or type2` ?
