### ISSUE TITLE
[Bug?] Multiline doc comments newlines

### ISSUE THREAD

**Issue by connorjs** [microsoft/typespec#2389]
### TL;DR

Multiline comments currently emit a double newline in the Open API 3 YAML. Instead, it should preserve the doc comment exactly as is, minus the leading `*` when using the doc comment form.

### Overview

Support emitting multiline doc comment "correctly" (as expected by `/**` TypeDoc/TSDoc/JSDoc conventions).

### Current state

```
/**
 * My multiline
 * doc comment.
 */
```

becomes

```yml
description: >-
  My multiline

  doc comment.
```

### Expected state

I would expect it to become this instead.

```yml
description: >-
  My multiline
  doc comment.
```

Note the single newline (no blank line).

**Comment by markcowl** [comment]
closing as duplicate of #2350

**Comment by connorjs** [comment]
Thanks all!
