### ISSUE TITLE
Should `/rest` have a peer dependency on `/http`

### ISSUE THREAD

**Issue by connorjs** [microsoft/typespec#2391]
The [Getting started](https://microsoft.github.io/typespec/getting-started) docs mention

> The following examples assume you have imported both `@typespec/openapi3` and `@typespec/rest`

However, I needed to import (and install) `@typespec/http` also.

**Should `@typespec/rest` have a `peerDependency` on `@typespec/http`?** It has it as a `devDependency` right now.

**Comment by timotheeguerin** [comment]
Yes, this seems like something that was missed when http and rest got split.

**Comment by connorjs** [comment]
I can submit the PR if y’all want, but I do not know how y’all consider dependency changes on the version, so I will wait for now. If I should submit the PR, just let me know.

**Comment by timotheeguerin** [comment]
For now we release once and month and every package is bumped with a minor version so it doesn't matter as long as it is not a breaking change. Would gladly accept a pr adding the dependency.

**Comment by connorjs** [comment]
I’ll submit one this week. I will take a look at the other dependencies too just in case, but the rest/http split means probably just this one. 👍🏻

**Comment by connorjs** [comment]
I recommend that we also remove `@typespec/rest` from the `peerDependency` graph of `@typespec/openapi` and `@typespec/openapi3`. The OpenAPI packages only depend on HTTP functionality (not the higher level REST ones).

My PR will have two commits: one for adding (the original issue here) and another one for this proposed removal. Y’all can choose to drop the second commit if desired then.
