### ISSUE TITLE
error msg of unixTimestamp encoding is misleading

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2394]
When I write something like below in the playground,
```
model Foo {
  @encode(DateTimeKnownEncoding.unixTimestamp)
  prop1: utcDateTime;
}
```
I got an error message like
<img width="459" alt="image" src="https://github.com/microsoft/typespec/assets/55688292/53aa19cd-5f03-41fe-a03a-6f2de664b80f">

But the actual fix is that we need an encodedAs scalar as the second parameter for encode in the case of unixTimestamp.
```
model Foo {
  @encode(DateTimeKnownEncoding.unixTimestamp, int64)
  prop1: utcDateTime;
}
```

Also, should we consider set a default encodedAs scalar for unixTimestamp encoding ?

**Comment by qiaozha** [comment]
The same thing happens in duration seconds encoding 
```
model Foo {
  @encode(DurationKnownEncoding.seconds, int16)
  prop1: duration;
}
```

**Comment by timotheeguerin** [comment]
for unixtimestamp Brian filed an issue to create a bult-in type #2371. For the duration I don't think this is worthy enough be be a type so we need to improve the error message. Maybe it can show an example of what to do?
```
Encoding 'unixTimestamp' on type 'utcDateTime' is expected to be serialized as an 'integer' but got 'string'.  Set `@encode` 2nd parameter to be an integer. e.g. `@encode("unixTimestamp", int32)`
```

**Comment by qiaozha** [comment]
oh, I didn't know this two issues are connected 😄.  but I want to point out, I was not trying to find a type for unixtimestamp when asking for a default encodedAs for unixTimestamp. I just don't feel quite natural to have some encodings only ask for one parameter, and some others ask for two parameter for the same type. 

For the error message, I think serialization info belongs to compiler details and maybe not very helpful to show them to TypeSpec users ? when I read this, I know encoding unixTimestamp should be serialized as an 'integer', but I actually don't understand how it got a 'string' if I miss the second parameter. And I still didn't know how to fix the error after reading this. 

Maybe something like this would be helpful ?  
`Encoding 'unixTimestamp' on type 'utcDateTime' is expecting a specific number scalar as the encoded format`

**Comment by timotheeguerin** [comment]
The encode decorator always default to string as the encoding type unless specified as this is the most common thing used for serialization. And the format being open ended we can’t really just special case things without being inconsistent. 

But yeah we can work to improve the error message.
