### ISSUE TITLE
How to express a model inherits from multiple parent models 

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2411]
I tried something like this 
```
    model Creature {
      life: int64;
    }
    model Animal {
      name: string;
    }
    model Pet extends Animal, Creature {
      weight?: float32;
    }
    model Cat extends Pet {
      kind: "cat";
      meow: int32;
    }
```

but it doesn't seem to be able to parse it. [playground link](https://cadlplayground.z22.web.core.windows.net/?c=ICAgIG1vZGVsIENyZWF0dXJlIHsNCsQWICBsaWZlOiBpbnQ2NDvGFH3GB8YxQW5pbWFsyi9uYW1lOiBzdHJpbmfUMFBldCBleHRlbmRzxzws03V3ZWlnaHQ%2FOiBmbG9hdDMy1EpDYcpKxFbJPWtpbmQ6ICJjYXQixzggIG1lb3flAMbKTA%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by timotheeguerin** [comment]
You can only extend a single model. You can use spread `...` if you want to compose from multiple models.

**Comment by qiaozha** [comment]
I might not be very fond of this way, Inheritance is suppose to be an allOf in OpenAPI and swagger? and I guess there's a lot of services are having more than one scheams in their allOf list.  

Spread just put those properties into the Pet Schema. [playground link](https://cadlplayground.z22.web.core.windows.net/?c=ICAgIG1vZGVsIENyZWF0dXJlIHsNCsQWICBsaWZlOiBpbnQ2NDvGFH3GB8YxQW5pbWFsyi9uYW1lOiBzdHJpbmfUMFBldCBleHRlbmRz0TwuLi7oAIAsyBR3ZWlnaHQ%2FOiBmbG9hdDMy1FRDYcpUxGDJUWtpbmQ6ICJjYXQixzggIG1lb3flANDKTA%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D) To me, spread is kind of like there's a property with a x-ms-client-flatten ?

**Comment by timotheeguerin** [comment]
Allod being extends is an interpretation of the swagger. Most language don’t support multiple inheritance. Most of those swagger probably didn’t actually want inheritance as it has 0 value without discriminators in service communications but just try to reuse things

**Comment by qiaozha** [comment]
Well, I don't have a real case for now, but is it a little weird that allOF in the OA3 schema is an array, and we can never provide more than one element in it ? 
```yaml
      allOf:
        - $ref: '#/components/schemas/Animal'
```

**Comment by timotheeguerin** [comment]
You can but allof in Openapi doesn’t really meant inheritance it means composition we just happen to treat it like inheritance.

i believe if you did provide multiple the first one was treated as the inheritance and the other were flattened

**Comment by qiaozha** [comment]
Do you mean we have a way to provide more than one element in allOf from TypeSpec OA3 emitter ? Can you show me how ?

**Comment by timotheeguerin** [comment]
No no, I meant if you did in openapi3 and passed it to autorest.

**Comment by qiaozha** [comment]
Interesting, I never noticed that. I guess in that way the spread makes sense to the downstream emitters at least. 
Also, I just read something about inheritance and allOf https://github.com/json-schema-org/json-schema-org.github.io/issues/148 , and may have some more understandings about why TypeSpec found inheritance obnoxious.

**Comment by bterlson** [comment]
If the question in the original issue is "how can I have multiple allOfs in a JSON Schema/OpenAPI doc", the answer is you can't. There are three reasons:

1. Multiple allOfs is a challenge for codegen (multiple inheritance is widely supported)
2. If multiple allOfs show up in a JSON Schema, it's most likely being used as composition rather than intending to be inheritance. In TypeSpec, you can just use spread for that.
3. We haven't been asked to do it, so probably not very common.

If the question is "how can I compose multiple models", yeah, just use spread 😁

**Comment by qiaozha** [comment]
Thanks Brian, I do have mixed up this two questions along the thread. 😊  
Maybe we can pick this up if there's a real request from services.
