### ISSUE TITLE
Json schema emitter crash for tuples

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2460]
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOwoKdXNpbmcgVHlwZVNwZWMuSnNvblPFHTsKCkDELMYOCm5hbWVzcGFjZSDGEXM7Cgptb2RlbCBGT28gewogIGE6IFtzdHJpbmcsIGludDMyXQp9&e=%40typespec%2Fjson-schema&options=%7B%7D)

```
ExternalError: Emitter "@typespec/json-schema" crashed! This is a bug. Please file an issue at https://github.com/microsoft/typespec/issues Error: TypeEmitter doesn't have a method named tupleLiteralValuesContext 
at compilerAssert (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-6402b6df.js:360:11) 
at setContextForType (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-6402b6df.js:21659:17) at withTypeContext (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-6402b6df.js:21691:9) 
```

**Comment by bterlson** [comment]
This likely means that the `TypeEmitter` class is missing this method.

**Comment by tjprescott** [comment]
Well, the test file here was empty. When I added @timotheeguerin's example, I get the following failure:
`Error: TypeEmitter doesn't have a method named tupleLiteralValuesContext`

However, it seems like `tupleLiteralValuesContext` _does_ exist.

**Comment by timotheeguerin** [comment]
I think they need to be added to the `TypeEmitter` the Json schema emitter shouldn't have to implement it

**Comment by tjprescott** [comment]
> So both those methods are missing from the `TypeEmitter` they are in the child class `CodeTypeEmitter` but jsonschema emitter depends on `typeemitter`
> 
> should just move those from codeemitter up to typeemitter

Yep, that was part of the problem. I still had to implement `tupleLiteral` and `tupleLiteralValues` in the JSON Schema emitter itelf.
