### ISSUE TITLE
Using fully qualified names allows to omit the TypeSpec namespace 

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2466]
```
import "@typespec/openapi";

using OpenAPI; // error

model A {
  @OpenAPI.extension("x-foo", "foo") // works
  a: string;
}
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvb3BlbmFwaSI7Cgp1c2luZyBPcGVuQVBJOwoKbW9kZWwgQSB7CiAgQMcXLmV4dGVuc2lvbigieC1mb28iLCAixAcpCiAgYTogc3RyaW5nOwp9&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by bterlson** [comment]
We automatically `using` the TypeSpec namespace, which is why you don't need to type `TypeSpec.string`. `using` doesn't understand this, however, but only in the case of `TypeSpec` - if you have a blockless namespace, usings will be relative to that namespace for example. I swear there's a bug on the backlog for this, but maybe not. It's been annoying me for so long I've just grown used to it 😂

**Comment by allenjzhang** [comment]
Seems the best course of action is to enable `using` to test if `TypeSpec.xxx` is valid whenever see an invalid `using xxx` and internally tracked as such.

- If `using xxx` is valid, keep the current behavior. If there are duplicate `xxx` and `TypeSpec.xxx` (from different libs), it is up to the user to correctly state the intended one.
- If both`using xxx` & `using TypeSpec.xxx` are invalid, report as such. 
- If `using xxx` is invalid, `using TypeSpec.xxx`, internally track as `TypeSpec.xxx`.

**Comment by timotheeguerin** [comment]
If you do that with custom namespace it works. So I think `using OpenAPI` should work really.
```tsp
namespace A.B {
  model Test {}
}


namespace S {
  using A; // Here we have this using implicitly 
  using B;

  model Bar {

    test: B.Test;
    test1: B.Test;
  }
}
```

https://cadlplayground.z22.web.core.windows.net/?c=bmFtZXNwYWNlIEEuQiB7CiAgbW9kZWwgVGVzdCB7fQp9CgoKyiRTxSJ1c2luZyBBO8kLQjsKyTlCYXIge8QPICB0ZXN0OiBCLsRMxC3GEjHME30KfQ%3D%3D&e=@typespec/openapi3&options=%7B%7D

**Comment by bterlson** [comment]
Yeah, I think @allenjzhang is basically describing how all usings work except for the TypeSpec namespace in this one case, so I think we're agreed that it should just work.

**Comment by timotheeguerin** [comment]
decided in design meeting that `TypeSpec.Xyz` namespace should not need the `TypeSpec.` prefix in `using`
