### ISSUE TITLE
VSCode colorization incorrect following single-line comment

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2471]
![image](https://github.com/microsoft/typespec/assets/11236/119e08b8-fd77-4e18-81fe-3d9ea3ea3f78)

The first model is sad and gray but should be happy and colorful like the second model.

**Comment by timotheeguerin** [comment]
I don't repro locally nor in the [playground](https://cadlplayground.z22.web.core.windows.net/?c=Ly8gYWJjCm1vZGVsIEZvbyB7CiAgYTogc3RyaW5nOwp9Ci8qKgogKiByZXNldCBhZnRlciBibG9jayBjb21tZW50CiAqL89AYshAIHwgbnVsbMRH&e=@typespec/openapi3&options=%7B%7D) 

<img width="439" alt="image" src="https://github.com/microsoft/typespec/assets/1031227/2a585591-b4c4-4e2c-b06b-6bed1e06907d">


do you maybe have an older version of the extension installed?

**Comment by bterlson** [comment]
Actually, I have the latest nightly installed! Could be a recent regression maybe?

**Comment by timotheeguerin** [comment]
ah so I repro until the language server loads, think its a problem with the tmgrammar. Could it be because of hte other issue you filed where the lanugage server crashed

**Comment by bterlson** [comment]
Yes that makes a lot of sense! I guess low pri then, but we'll want to fix this before we do #1040 probably.
