### ISSUE TITLE
Consider deducing true|false to boolean

### ISSUE THREAD

**Issue by pshao25** [microsoft/typespec#2475]
Currently, when I define a type of `true | false`, the type compiler gives me is a union of two constant. Is it possible that compiler just gives me a type of `boolean`?

**Comment by bterlson** [comment]
Can you say more about how this helps your scenario? It is possible and probably makes sense but I want to understand your needs better.

**Comment by pshao25** [comment]
I don't have real case, just adding tests. So it is a proposal because we think `true | false` is equivalent to `boolean`.

**Comment by timotheeguerin** [comment]
I would also say that if someone wrote `true | false` for some reason I am not sure it should be the job of the compiler to lose that information. Even though I don't see how it would be of value I think in general it is good that typespec lets you keep as much of the detail

**Comment by markcowl** [comment]
won't fix - we can't anticipate what the user will do with this type in the future
