### ISSUE TITLE
openapi3 emitter produces invalid OpenAPI for shared routes

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2486]
The openapi3 emitter will produce invalid OpenAPI for some cases using `@sharedRoute`.

The emitted openapi has a `statusCode` field in the response that is not allowed.

[Playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKbW9kZWwgx0bEWUB2aXNpYmlsaXR5KCJyZWFkIiwgInVwZGF0ZSIpxCBwYXRoCiAgaWQ6IHN0cmluZzsKCiAgd2VpZ2h0OiBpbnQzMjsKICBjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsd6RcQMxXljb2Rly0BtZXNzYWdlymXEOnJvdXRlKCIvd%2BUAsHMiKQpAdGFnKOcBBsQQaW50ZXJm5ADoxxTFXMg5e2lkfS9hbmFseXrnAM5zaGFyZWRSxB%2FED3Bvc3QgxyExKOUA7OsA6inICSB85gC55ACp31zWXDLUXOQAvGdlcspdfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

**Comment by tjprescott** [comment]
@mikekistler is the statusCode property the only issue?
