### ISSUE TITLE
@summary should support parameterized strings just like @doc

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2495]
The text of the @doc decorator can use string interpolation to customize the text, e.g.
```
@doc("Get a {name}", Widget)
```
results in the doc string "Get a Widget"

TypeSpec should provide this same capability for @summary. 

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKbW9kZWwgx0bEWUB2aXNpYmlsaXR5KCJyZWFkIiwgInVwZGF0ZSIpxCBwYXRoCiAgaWQ6IHN0cmluZzsKCiAgd2VpZ2h0OiBpbnQzMjsKICBjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsd6RcQMxXljb2Rly0BtZXNzYWdlymXEOnJvdXRlKCIvd%2BUAsHMiKQpAdGFnKOcBBsQQaW50ZXJm5ADoxxTFXC8vQHN1bW1hcnkoIkdldCBhIHvkARF9IizHJ%2BUA2mRvY9sfb3Ag5AEPKOUBAesA%2Fyk6xyUgfOYAzuQAqw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

**Comment by timotheeguerin** [comment]
I would say we shouldn't do to this one, the `@doc` parameterized string is completely broken right now anyway and we should just support string interpolation instead  https://github.com/microsoft/typespec/issues/1591

**Comment by markcowl** [comment]
We should use the existing proposal for parameterized strings

**Comment by markcowl** [comment]
Closing in favor of #1591
