### ISSUE TITLE
@added decorator does not work when applied to a namespace

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2497]
The `@added` decorator does not work when applied to a namespace.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR07CgpAxytlZCjHGHMpCkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAp9KQpuYW1lc3BhY2UgRGVtb8cbOwoKZW51bSDIUCDERnYxLMQGMiwKffEAkUh0dHA70BVSZXN0OwoKbW9kZWwgx3zESUBrZXkgaWQ6IHN0cuUAwyAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUiO8R6QGFkZOsA6y52MinHY0dh32PWY3llbGxvd8VmcHVycGzIaGVycm9yx1tFxAzFWmNvZGXLRW1lc3NhZ2XKacQ6cm91dGUoIi935QD0cyIpCkDkAJlvcCByZWFk5gEKKEBwYXRo6wCkKTroASR8xm%2FkAdvzAOzqAbHmAPDmAZ3JdGfGFSIpxBXLdsYt1HbGGsp2fQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

**Comment by markcowl** [comment]
Other versioning decorators should also be considered (@removed,  @renamedFrom, @changedTypeFrom)

**Comment by markcowl** [comment]
- for this, narrow the target for these decorators
- file a design issue for versioning containers

**Comment by markcowl** [comment]
- mark as breaking change

**Comment by markcowl** [comment]
**Describe the breaking change**
Narrow possible targets of `@added` to exclude namespaces - specs with `@added` decorating a namespace will throw an error.

**Back-compat design to avoid immediate breaking**
Any back-compat design:  None

**Link to detailed breaking design**


**Impact**
This change affecting:

- [ ] ARM
- [ ] Data-plane
- [x] Existing specs: 0
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: November

**Additional information**
