### ISSUE TITLE
Type constraints check property reference types incorrectly

### ISSUE THREAD

**Issue by daviwil** [microsoft/typespec#2498]
I noticed this issue while working on a design prototype:

```typespec
model Props {
  name: string;
}

model Foo<T extends Props> {
  ...T
}

alias UseFoo = Foo<{ name: Props.name; }>;
```

In this case, `Foo` sets a type constraint on `T` to match the properties of `Props`.  The usage of `Foo`, `UseFoo`, provides an inline model with a property `name` which uses a property reference to `Props.name`.

It seems that the constraint checker doesn't resolve the type of a property reference during its check, it instead compares the reference itself against the expected type.

[Playground example](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgUHJvcHMgewogIG5hbWU6IHN0cmluZzsKfQoKxiFGb288VCBleHRlbmRzxi8%2BxTAuLi5UxCdhbGlhcyBVc2VGb28gPcUwyk%2FFMC7EDDsKfT47&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by markcowl** [comment]
@daviwil Copy over to design issue

**Comment by markcowl** [comment]
Closing as resolved by .inked isue
