### ISSUE TITLE
Should `#deprecated` operations set `deprecated: true` in OpenAPI emitters?

### ISSUE THREAD

**Issue by daviwil** [microsoft/typespec#2499]
While working on a design prototype, I noticed that setting an operation as `#deprecated` cause the OpenAPI emitter to emit `deprecated: true` for that operation.

[Playground example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7CtIfcmVzdCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwO9AVUmVzdNEVVslgOwoKQMduZWQoTGlicmFyecggcykKbmFtZXNwYWNlIMccIHsKICBlbnVtIMglxRIgIHYxLMYIMsQIfQoKICBpbnRlcmbEPU9wZXJhdMsuI2RlcHJlY2F0ZWQgIlRoaXMgb8gjIGlzIHJlbW92ZWQgaW4gdjIuIsUzQMcVKMh5LnYyKcUaZ2V0KOQAqTogc3RyaW5nKTogdm9pZDvlAIh9CgpAc2VydmljZSjEfHRpdGxlOiAiRXhhbXBsZSBTxhwiLAp9KewBDMcY9QEMxxz5AQxAdXNlRGVwZW5kZW5jefEBVy52MeYAuXYyMDIzXzA2XzAxX3ByZXZpZXc6ICLEFS0wNi0wMS3HFSIs5AFP31jrARHHWDlfMjjRWDktMjjLWPEBq0TnAZlpb27oASPmANVnZXTkAZvIdeoB0y5nZXToAWw%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

My expectation here is that `#deprecated` is meant to indicate to a spec author that this library operation has been deprecated in a newer version of the library.  Instead, the operation is marked as deprecated in the OpenAPI output and its greyed out in the Swagger UI for the spec output.

Should we be marking these operations as "deprecated" in OpenAPI output?  The operation really isn't deprecated at the time of the first spec version so it's misleading to anyone consuming the OpenAPI spec.  In my opinion, the deprecation should only be directed toward a consumer of the TypeSpec library.

```
import "@typespec/versioning";
import "@typespec/rest";

using TypeSpec.Http;
using TypeSpec.Rest;
using TypeSpec.Versioning;

@versioned(Library.Versions)
namespace Library {
  enum Versions {
    v1,
    v2,
  }

  interface Operations {
    #deprecated "This operation is removed in v2."
    @removed(Versions.v2)
    get(name: string): void;
  }
}

@service({
  title: "Example Service",
})
@versioned(Service.Versions)
namespace Service {
  enum Versions {
    @useDependency(Library.Versions.v1)
    v2023_06_01_preview: "2023-06-01-preview",

    @useDependency(Library.Versions.v2)
    v2023_09_28_preview: "2023-09-28-preview",
  }

  interface DeprecationExample {
    get is Library.Operations.get;
  }
}
```

**Comment by mikekistler** [comment]
Interesting! I think we have several slightly different uses for `#deprecated`. The scenario you mention is certainly valid, but we also want a way to mark operations (and parameters and model properties for that matter) as deprecated.

I'll also note that the behavior of the openapi3 emitter is clearly documented:

https://microsoft.github.io/typespec/standard-library/openapi3/openapi#deprecated

**Comment by timotheeguerin** [comment]
That was part of the design, it was weird that we'd have 2 concept of deprecated depending if you meant for a reference in typespec or in an emitter.

If you deprecate that operation it is deprecated, you shouldn't use it in `op is` or in the emitter code as well.

This is why part of the design was that if you have `op x is deprecatedOp` it wouldn't carry over the deprecation to x(which the old decorator would)

**Comment by markcowl** [comment]
@daviwil please take a look at what scenarios this may complicate

**Comment by mikekistler** [comment]
We should have a means of adding `deprecated: true` in a particular version -- maybe `@deprecatedIn()` decorator in the versioning library.
