### ISSUE TITLE
Fix `using Xyz` without `TypeSpec.` prefix

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2501]
From design issue #2466

```
import "@typespec/openapi";

using OpenAPI; // error, this should work

model A {
  @OpenAPI.extension("x-foo", "foo") // works
  a: string;
}
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvb3BlbmFwaSI7Cgp1c2luZyBPcGVuQVBJOwoKbW9kZWwgQSB7CiAgQMcXLmV4dGVuc2lvbigieC1mb28iLCAixAcpCiAgYTogc3RyaW5nOwp9&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by mikekistler** [comment]
This needs to be fixed this sprint, or there will be a breaking change from the prior release.

cc: @allenjzhang @markcowl

**Comment by timotheeguerin** [comment]
Ok so it seems like this was a relatively easy change to do
