### ISSUE TITLE
How do I get linter messages to show up in VSCode ?

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2521]
I've written a linter and I want to see the problems it finds squiggled in my VSCode window. How do I do that?

**Comment by mikekistler** [comment]
I have it enabled in tspconfig.yaml:

<img width="769" alt="image" src="https://github.com/microsoft/typespec/assets/85643503/6e0a667f-c090-4fc6-8b79-c30ef4487884">

and this works to get `tsp compile .` to produce linter messages:
```
>tsp compile .
TypeSpec compiler v0.48.1

Diagnostics were reported during compilation:

/Users/mikekistler/Projects/mikekistler/contoso-fiber/Projects/contoso-fiber/main.tsp:173:6 - warning @contoso/typespec-library/version-policy: Operation does not define an "api-version" query parameter.
> 173 |   op getStatus(): string;
      |      ^^^^^^^^^

Found 1 warning.
```

But no squiggle in VSCode:

<img width="287" alt="image" src="https://github.com/microsoft/typespec/assets/85643503/0b59dd6b-60b0-4468-a16f-f9327439ece4">

**Comment by timotheeguerin** [comment]
Ah yeah seems like we have a bug, looking at the code, the ide does its own config loading, I'll see if I can unify that
