### ISSUE TITLE
Missing meta properties of ModelProperty

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#2522]
```typespec
model ThingWithNested {
  nested: {
    name: string;
  }
}

model Spreaddie {
  ...ThingWithNested;
}

@@doc(Spreaddie.nested::type, "Yeaj");
```

> error
invalid-ref
ModelProperty doesn't have meta property type

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgVGhpbmdXaXRoTmVzdGVkIHsKICBuxQs6xQwgIG5hbWU6IHN0cmluZzsKICB9Cn0KCsY9U3ByZWFkZGllxSsuLi7PTjvEK0BAZG9jKMkrLsdeOnR5cGUsICJZZWFqIik7&e=%40typespec%2Fopenapi3&options=%7B%7D)

The list of meta properties seem to be... lacking...

**Comment by daviwil** [comment]
I believe this is a dupe of another issue I filed: https://github.com/microsoft/typespec/issues/2213

**Comment by markcowl** [comment]
Closing as duplicate of #2213
