### ISSUE TITLE
Json schema exlcusivemax set exclusivemin instead

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2531]
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOwoKdXNpbmcgVHlwZVNwZWMuSnNvblPFHTsKCkDELMYOCm5hbWVzcGFjZSDGEXPEIG1pblZhbHVlRXhjbHVzaXZlKDEpCkBtYXjPFjIpCnNjYWxhciBUZXN0IGV4dGVuZHMgaW50MzI7Cg%3D%3D&e=%40typespec%2Fjson-schema&options=%7B%7D)

**Comment by bterlson** [comment]
Terrible.
