### ISSUE TITLE
Deprecate (or at least clarify) the intent of the `version` parameter to the `@service` decorator.

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#2532]
Given that we also have the versioning decorators, it is not clear what the relationship between the two are. It's use in the OpenAPI emitter implies that it is the spec version, in which case the name is very unclear.

My suggestion:
- deprecate the use of the property in the `service` decorator
- Add a new decorator in the openapi emitter(s) to specify the spec version
- use the versioning decorator in typespec for service versioning.

**Comment by timotheeguerin** [comment]
I believe we had this discussion a while back and it came down to we shouldn't require user to use the versioning library just to specify the service version and we'd have an error if you specify both 
<img width="849" alt="image" src="https://github.com/microsoft/typespec/assets/1031227/b91644ef-51ba-4458-a585-773794bda7c4">

**Comment by markcowl** [comment]
Potentially related to AzureService decorator?

**Comment by markcowl** [comment]
W ehave decided to remove this property, closing
