### ISSUE TITLE
Type 'true' is not assignable to type 'boolean'

### ISSUE THREAD

**Issue by witemple-msft** [microsoft/typespec#2533]
```tsp
import "@typespec/http";

using TypeSpec.Http;

@route("/test")
op test(@query p: boolean): void;

@overload(test)
op test_true(@query p: true): void;
```

https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQHJvdXRlKCIvdGVzdCIpCm9wIMQKKEBxdWVyeSBwOiBib29sZWFuKTogdm9pZMQzb3ZlcmxvYWQoxCrJM190cnVlyzjED8g1&e=%40typespec%2Fopenapi3&options=%7B%7D

`true` should be assignable to `boolean` in an overload. The point of this is to be able to define a root operation but overload it with separate logical operations that imply setting the parameter to a particular value.

**Comment by timotheeguerin** [comment]
Intrestingly enough it only applies to overload 

```
model WithBool<T extends boolean> {
  t: T;
}

model Test {
  a: WithBool<true>;
}
```
this works [playground](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgV2l0aEJvb2w8VCBleHRlbmRzIGJvb2xlYW4%2BIHsKICB0OiBUOwp9CgrGL1Rlc3TFGGE6yjt0cnVlPjsKfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by timotheeguerin** [comment]
ah must be then an additional check done in the openapi3 emitter to see if it can represent the overload
