### ISSUE TITLE
Model spreading itself, should it be allowed

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2548]
```tsp
model Foo  {
  ...Foo, // no error
  name: string;
}

model Bar  {
  name: string;
  ...Bar, // error as dup prop
}
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgRm9vICB7CiAgLi4uRm9vLCAvLyBubyBlcnJvcgogIG5hbWU6IHN0cmluZzsKfQoKxjZCYXLGNs4gxUZCYXLFRsVDIGFzIGR1cCBwcm9wCn0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by daviwil** [comment]
I can't think of a reason why someone would want or need to do this, so I believe it should be an error.

**Comment by markcowl** [comment]
pri: 1

**Comment by tjprescott** [comment]
Fixed in https://github.com/microsoft/typespec/pull/2588
