### ISSUE TITLE
Migrate openapi3 emitter to use emitter framework

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2563]
First step is to migrate the schema emitter to use the emitter framework

**Comment by tjprescott** [comment]
What is the rationale for migrating to emitter framework?

**Comment by timotheeguerin** [comment]
The current implementation is very messy, using the emitter framework will allow us to extend it much easier for making openapi3.1 emitter

**Comment by tjprescott** [comment]
@markcowl if this is "In Progress" who is working on it? Shouldn't it have an assignee?

**Comment by timotheeguerin** [comment]
Sorry didn't assign myself, I am working on it I have a PR, it is just blocked on some missing features of the emitter framework.
