### ISSUE TITLE
Provide a suppression mechanism for @typespec/http/no-routes

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2573]
The `#suppress` directive does not work on some kinds of diagnostics, e.g. @typespec/http/no-routes.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiQWxsT2YiLAogIHZlcnNpb246ICIwLjQ3LjEiLAp9KQojc3VwcHJlc3PQaC9uby1yb3V0ZXMiCm5hbWVzcGFjZSBOb1LFFDsKCm1vZGVsIFBldCDEcMQjOiBzdHJpbmc7Cn0K&e=%40typespec%2Fopenapi3&options=%7B%7D)

It should either be made to work or some other mechanism provided to suppress these messages.

**Comment by markcowl** [comment]
- do not emit the warning if there is `@service`

**Comment by markcowl** [comment]
est: 3
