### ISSUE TITLE
Is it possible to pass generic types to decorator definitions

### ISSUE THREAD

**Issue by Onokaev** [microsoft/typespec#2576]
I am implementing a new decorator that should accept an array of primitive types. The primitive values can be of any type.
Here's a quick example:
@myDecorator(1,2,3)
@myDecorator("string", "string2")

These are just two examples, but it could also take other types. I need to know the type that was passed downstream.

Is it possible to define this in the decorator definition like so:
`extern dec myDecorator<T>(target: ModelProperty, ...values: valueof <T[]>)`? This doesn't work, but is there an alternative to achieve this?

**Comment by bterlson** [comment]
We don't support generics for decorator defs, but that is interesting. I think the best alternative is to define values as `valueof unknown[]`, and then in your decorator ensure that all the values are the same type, and if not, emit a diagnostic manually, e.g. something like:

```ts
export function $myDecorator(context: DecoratorContext, target: ModelProperty, ... values: unknown[]) {
  if (values.length > 1) {
    const expectedType = typeof values[0]; 
    for (const i = 1; i < values.length; i++) {
      if (typeof values[i] !== expectedType) {
        reportDiagnostic({
          code: "non-homogeneous-types",
          target: context.getArgumentTarget(0),
        });
      }
    }
  }
}
```

**Comment by Onokaev** [comment]
Awesome! Thank you

**Comment by markcowl** [comment]
Closing as answered
