### ISSUE TITLE
linter warning enforcing extension for polymorphic models

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/typespec#2583]
Right now, tsp definers are able to splat a polymorphic base class into their defined child class. I feel this scenario warrants a linter, because splatting gets rid of the hierarchical nature of this relationship, and polymorphic models are inherently hierarchical. The openai emitter (and other emitters too, i.e. python), are not able to recognize that this is a polymorphic inheritance, and then kind is this weird pseudo-discriminator / pseudo-normal-property

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=QGRpc2NyaW1pbmF0b3IoImtpbmQiKQptb2RlbCBCYXNlIHsKICBmb286IHN0cmluZzsKfQrHH1NwbGF0dGVkQ2hpbGTFKC4uLsQ0OwogIMRJOiAibXlLxFLLNkV4dGVuZMg2ZcUOc8prxzhoZWxsbyIKfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by markcowl** [comment]
I think this is covered by this issue in Azure: https://github.com/Azure/typespec-azure/issues/3510 (particularly the issue comment: https://github.com/Azure/typespec-azure/issues/3510#issuecomment-1710610544)

Closing this as a duplicate.
