### ISSUE TITLE
Should discriminator emit a warning oif property does not exist

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2589]
Could kinda solve this issue too #2583

We didn't use to require the discriminator property on the base type originally because we didn't have property override but now we do it feels like you should describe that property.

```
//bad
@discriminator("kind") model Pet {}

// good
@discriminator("kind") model Pet { kind: string }
```

**Comment by markcowl** [comment]
- core: require property?
- azure:  suggest enum value for property?
