### ISSUE TITLE
The documentation generated from the generated swaggers don't include response shapes

### ISSUE THREAD

**Issue by deyaaeldeen** [microsoft/typespec#2598]
The documentation generated from the OpenAI swagger (that was generated from the TypeSpec) doesn't include the response shape and here is the explanation I received from the documentation team:

> there was feedback shared about incomplete response "type" columns. For example "type" is missing from "200 OK".
[Completions - Create - REST API (Inference) | Microsoft Learn](https://review.learn.microsoft.com/en-us/rest/api/default/inference/completions/create?branch=pr-en-us-6#response)
> This is a result of the response type format in the specification provided. IF "type" was a value you would like to display, the format would need to be updated to include it.

Is there something missing in the generated swagger?

We want to have links generated to the response shapes, similar to [this](https://learn.microsoft.com/en-us/rest/api/language/2023-04-01/text-analysis-runtime/analyze-text?tabs=HTTP#response).

**Comment by mikekistler** [comment]
@deyaaeldeen Can you please link to a PR with the TypeSpec so I can diagnose the issue?

**Comment by deyaaeldeen** [comment]
Thanks @mikekistler. This is using the swagger in the main branch:
- [TypeSpec](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/OpenAI.Inference)
- [Swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-03-15-preview/inference.json)

**Comment by timotheeguerin** [comment]
@deyaaeldeen is this still an issue?

can you point to what is missing a `type` I am not sure I see here? 

Does the doc generation support openapi3? THis is an openapi3 spec.
