### ISSUE TITLE
Cannot specify assertions on array/record elements

### ISSUE THREAD

**Issue by bojunehsu** [microsoft/typespec#2599]
In Swagger 2, we can specify constraints on array/additionalProperty elements via:

```json
"fieldConfidence": {
  "additionalProperties": {
    "maximum": 1,
    "minimum": 0,
    "type": "number"
  },
  "polygon": {
    "items": {
      "minimum": 0,
      "type": "number"
    },
    "type": "array"
  }
```

I do not believe there is a way to express the same concept in TypeSpec.  We can define a new scalar, but that would also create a new intermediate definition in the Swagger and SDK. which is not desirable.  Perhaps we can do something similar to:
```typescript
  @itemMinValue(0) @itemMaxValue(1)
  fieldConfidence: Record<float32>;

  @itemMinValue(0)
  polygon: float32[];
```

**Comment by markcowl** [comment]
@marcowl discuss with DPG devs

**Comment by markcowl** [comment]
Cllosing as by design
