### ISSUE TITLE
Could not get correct decorators when add decorator for model from an external library

### ISSUE THREAD

**Issue by tadelesh** [microsoft/typespec#2600]
For the following TSP, emitter could get the `@access` decorator info for `ContentFilterSeverity` model when compiling, but loose it for `Error`. I wonder if it is bc `Error` is from an external library.
```
@@access(Azure.OpenAI.ContentFilterSeverity, Access.public);
@@access(Azure.Core.Foundations.Error, Access.public);
```

**Comment by timotheeguerin** [comment]
Super weird, trying to repro this with `@@doc` it seems to ignore @@doc when importing azure core

```tsp
import "@typespec/http";
import "@azure-tools/typespec-azure-core"; // Comment to make the doc work

model Foo {}

op test(): Foo | TypeSpec.Http.AcceptedResponse;

@@doc(Foo, "Foo doc"); // This works
@@doc(TypeSpec.Http.AcceptedResponse, "AcceptedResponse doc"); // This doesn't work if importing Azure.Core

```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CskZYXp1cmUtdG9vbHMvyCUtxhVjb3JlIjsgLy8gQ29tbWVudCB0byBtYWtlIHRoZSBkb2Mgd29yawoKbW9kZWwgRm9vIHt9CgpvcCB0ZXN0KCk6xRN8IFR5cGVTcGVjLkh0dHAuQWNjZXB0ZWRSZXNwb25zZTsKCkBAZG9jKEZvbywgIsQzZG9jIinFeFRoaXPFZXPHJd5MLCAi0BPQTWRvZXNuJ3TFVSBpZiDmAQhpbmcgQeQA9C5Db3JlCg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Comment by timotheeguerin** [comment]
Repro taking azure core out of the equation, seems to be some issue when referencing a model in a template interface 



[Playground Link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgptb2RlbCBGb28ge30KCm9wIHRlc3QoKTrFE3wgVHlwZVNwZWMuSHR0cC5BY2NlcHRlZFJlc3BvbnNlOwoKQEBkb2MoRm9vLCAixDNkb2MiKTsgLy8gVGhpcyB3b3Jrc8cl3kwsICLQE9BNZG9lc24ndMVVIGlmIOYA1mluZyBBenVyZS5Db3JlCgovLyBDb21tZW50IHTENnRvIG1ha2UgacY5CmludGVyZmFjZSBSZXNvdXJjZU9wZXJhdGlvbnMgewogIExvbmdSdW5uaW5nyCJDcmVhdGVXaXRoU2VydmljZVByb3ZpZGVkTmFtZTxUyCcgZXh0ZW5kc%2BoBN1JlZmxlY8RcLk3kAWo%2BKAogICk6%2FwFYOwp9CgphbGlhcyBTdGFuZGFyxBvwAKw98wDBO%2BUBxO4At09yUmVwbGFj%2FwCp7wCpIGncfS7%2FASX7ASU%2BOwo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Comment by timotheeguerin** [comment]
My guess on what is happening, when we resolve the symbol tree early, when resolving alias symbol we do call `getAliasedSymbol` which does compuite the alias type so what must happen is we compute the type for `ResourceOperations` which cause the type of `AcceptedResponse` to be computed before the augment decorator works

**Comment by timotheeguerin** [comment]
fixed in https://github.com/microsoft/typespec/pull/2603
