### ISSUE TITLE
resource keys as OpenAPI parameters

### ISSUE THREAD

**Issue by cataggar** [microsoft/typespec#2612]
I'm working on https://github.com/Azure/azure-rest-api-specs-pr/pull/15631 and the OpenAPI definitions do not put the resource keys as parameters. It was considered best practice for API authoring to use parameters. The PR is being flagged for breaking changes for https://github.com/Azure/openapi-diff/blob/master/docs/rules/1007.md .

![image](https://github.com/microsoft/typespec/assets/87583576/c538ee77-72fb-4735-861c-c60673b97e42)

In the OpenAPI, the functions should reference  a named parameter like before:
``` json
          {
            "$ref": "#/parameters/privateCloudName"
          },
```

I'm not sure how this could be changed to indicate that behavior:
``` tsp
@doc("A private cloud resource")
model PrivateCloud is TrackedResource<PrivateCloudProperties> {
  @doc("Name of the private cloud")
  @pattern("^[-\\w\\._]+$")
  @key("privateCloudName")
  @path
  @segment("privateClouds")
  name: string;
}
```

May be a `@parameter("privateCloudName")`.

**Comment by markcowl** [comment]
Closing in favor of the azure issue
