### ISSUE TITLE
Template parameter constraints based on other template parameter has issues

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#2616]
```typespec
model Base {
  a: string;
}

model SubtypeOf<TBase, T extends TBase> {
   ...T;
}

model ExtensionFoo is SubtypeOf<Base, { a: string; }> {}; // <-- error unassignable Type '(anonymous model)' is not assignable to type 'TBase'

model SubtypeOfBase<TBase, T extends Base> { <-- works if I use the explicit type
   ...T;
}

model ExtensionBar is SubtypeOfBase<Base, { a: string }> {};
```

[Playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=bW9kZWwgQmFzZSB7CiAgYTogc3RyaW5nOwp9CgrGHVN1YnR5cGVPZjxUxCgsIFQgZXh0ZW5kcyDFET7FOiAuLi5UyzZFxCNzaW9uRm9vIGlzy0bGRXvLbCB9PiB7fTsgLy8gPC0tIGVycm9yIHVuYXNzaWduYWJsZSBUeXBlICcoYW5vbnltb3VzIMVlKSfEWm5vdCDLK3RvIMRpICflAJ0n8QDGxBbyAMr%2FAMnkAMlCYXLtAMnFSfEAze8AzHdvcmtz&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Comment by timotheeguerin** [comment]
As talked offline I think this is a bug in our assignment checker, the following works great in typescript
```ts
interface Base {
  a: string;
}

interface SubtypeOf<TBase, T extends TBase> {
  t: T;
}

type ExtensionFoo = SubtypeOf<Base, { a: string }>;

```
