### ISSUE TITLE
Should we continue to allow `?` query in `@route`

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2618]
OpenAPi3 emitter complains about it but not rest library so autorest lets you do that

https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQHJvdXRlKCIvZm9vP3F1ZXJ5PTEiKSBvcCB0ZXN0KCk6IHZvaWQ7Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D

If yes we need to add test covering this in typespec-autorest with sharedRoute

**Comment by markcowl** [comment]
closing in favor of https://github.com/Azure/typespec-azure/issues/3416
