### ISSUE TITLE
Type assignment checks are order-dependent for union with `valueof` member

### ISSUE THREAD

**Issue by daviwil** [microsoft/typespec#2632]
It appears that type assignment checks are order-dependent for union types when a `valueof` is used.  In my specific case, I had a union where `valueof string` came before a couple of other types in the union and it caused an otherwise valid check to fail.  Moving the `valueof string` to the end of the union caused it to succeed.

Here's an example (also on the [Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CgpAc2VydmljZSh7IHRpdGxlOiAiVGVzdCBTxhcifSkKbmFtZXNwYWNlIMQaxxk7Cgp1c2luZyBUeXBlU3BlYy5IdHRwO9AVUmVmbGVjdGlvbjsKCm1vZGVsIEZvbyB7CiAgxFc6IHN0cmluZzsKfQoKQHJvdXRlKCIvYmFkIikKb3AgYmFkT3A8VCBleHRlbmRzIHZhbHVlb2bHNSB8IE3EUj4ocGFyYW06IFQpOiB2b2lk5ADXyExnb2%2FHTcQKzU7FPSB8z1bUTmFsaWFzIHRlc3RCYWQgPecAmEZvbz47yxxHb2%2FEHcdoxh4%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)):

```typespec
import "@typespec/http";

@service({ title: "Test Service"})
namespace TestService;

using TypeSpec.Http;
using TypeSpec.Reflection;

model Foo {
  name: string;
}

@route("/bad")
op badOp<T extends valueof string | Model>(param: T): void;

@route("/good")
op goodOp<T extends Model | valueof string>(param: T): void;

alias testBad = badOp<Foo>;
alias testGood = goodOp<Foo>;
```

The `badOp` usage gets marked with the following error:

```
error: unassignable: Type 'TestService.Foo' is not assignable to type 'valueof string | Model'
```

**Comment by timotheeguerin** [comment]
I don't think it is that its value dependent but that it reads it as `valueof (string | Model)`

**Comment by markcowl** [comment]
- fix formatter issue removing parentheses
