### ISSUE TITLE
Implementation `@encodedName` decorator

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2650]
design https://github.com/microsoft/typespec/issues/2506

## Signature

```tsp
extern dec encodedName(taget: unknown, mimeType: valueof string | EnumMember, name: valueof string);
```

Parameters:

| Name       | Description                                                                                                                              |
| ---------- | ---------------------------------------------------------------------------------------------------------------------------------------- |
| `mimeType` | Encoding target, following the known mime types https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types |
| `name`     | Name under that encoding                                                                                                                 |

**Why mimeType?**
This makes it consistent with some already established value so we don't have to have some parallel meaning. The mimeType parameter can also take an enum which is a enum containing the known mime types

## Only allow top level mime types(no `+`)

Content type case 1: `{category}/{type}`
Content type case 2: `{category}/{subtype}+{type}` -> `{category}/{type}`

Example: `application/merge-patch+json` -> `application/json`

- encodedName validate format that doesn't have a `+`

```
@encodedName("application/merge-patch+json", "exp-patch")
             ^ error cannot use subtype
```

- helper to convert case 2 -> case 1

## Example usage

```tsp
model Certificate {
  // @encodedName("application/merge-patch+json", "exp-patch") // error
  @encodedName("application/json", "exp")
  expireAt: string;
}
// contentType: application/json               {exp: "abc"}
// contentType: application/merge-patch+json   {exp: "abc"}
```

## Helpers to add

````ts
/**
 * Resolve the name to use for the given mime type.
 * (in compiler)
 * @example
 * ```tsp
 * model Certificate {
 *   @encodedName("application/json", "exp")
 *   expireAt: string;
 * }
 * ```
 *
 * ```ts
 * getEncodedName(type, "application/json")             // "exp"
 * getEncodedName(type, "application/merge-patch+json") // "exp"
 * getEncodedName(type, "application/xml")              // "expiry"
 * getEncodedName(type, "application/yaml")             // "expireAt"
 * ```
 */
function getEncodedName(type: Type, mimeType: string): string;

/**
 * Resolve all the mime types involve for this model
 * (in http lib?)
 */
function getMimeTypes(type: Type): string[];
````

## Later behavior

Right now as shown above providing a mime subtype is an error but adding such behavior could be added later wihtout breaking existing spec and emitters should get the feature for free as long as they use the `getProjectedName` helper.

```tsp
model Certificate {
  @encodedName("application/json", "exp")
  expireAt: string;
}
// contentType: application/json               {exp: "abc"}
// contentType: application/merge-patch+json   {exp: "abc"}

model Certificate {
  @encodedName("application/merge-patch+json", "exp-patch")
  @encodedName("application/json", "exp")
  expireAt: string;
}
// contentType: application/json               {exp: "abc"}
// contentType: application/merge-patch+json   {"exp-patch": "abc"}



model Certificate {
  @encodedName("application/merge-patch+json", "exp-patch")
  expireAt: string;
}
// contentType: application/json               {expireAt: "abc"}
// contentType: application/merge-patch+json   {"exp-patch": "abc"}
```

**Comment by markcowl** [comment]
est: 8
