### ISSUE TITLE
Bug using unions as discriminators?

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#2669]
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=Ly8gRG9lc24ndCB3b3JrDQp1bmlvbiBDaG9pY2Ugew0KICB5ZXM6ICJ5ZXMiLMQPbm86ICJub8QNfQ0KDQptb2RlbCBGb2%2FGLm5hbWU6x0A7zSNCYXIgZXh0ZW5kc9YvLm5vyDIvLyBXb3Jrcw0KZW51bSBFbnVt7wCT5wCM7gCGxCjPW8o77gCOxBjsAJLdO%2BkAmg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

Since we are moving forward with replacing enums with unions, the above playground showcases a bug preventing that. The enum scenario works but the equivalent union scenario does not. You can make it work by putting the string literal in place of the union variant name, but it seems like the union variant should work.

**Comment by markcowl** [comment]
@tjprescott Yes, this is a really good catch.  It is another place where we need to make sure we have this capability, and we will need to place guardrails around ensuring the union is correctly formed.

**Comment by markcowl** [comment]
est: 5
