### ISSUE TITLE
Node 21 support

### ISSUE THREAD

**Issue by et1975** [microsoft/typespec#2694]
Any reason not to support Node v21?

Currently I'm getting the error:
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @azure-tools/typespec-validation@0.0.1
npm ERR! notsup Not compatible with your version of node/npm: @azure-tools/typespec-validation@0.0.1
npm ERR! notsup Required: {"node":"^16.17.0 || ^18.3.0 || ^20.0.0"}
npm ERR! notsup Actual:   {"npm":"10.2.3","node":"v21.2.0"}
```

**Comment by timotheeguerin** [comment]
Hi @et1975 the typespec-validation is a tool for the spec repo which is there and is not part of this repo, can you refile the issue in the correct repo https://github.com/Azure/azure-rest-api-specs/blob/main/eng/tools/typespec-validation/package.json

Typespec packages themself do not have this restriction they are only specifying `>=18.0.0`
