### ISSUE TITLE
[Design]:  Remaining issues for multipart/form-data

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#2704]
Design issue from: https://github.com/microsoft/typespec/issues/2419

- How to override content-type defaults for parts
- How to model client-specified boundaries between parts
- How to model file names with binary data
- How to differentiate arrays of individual parts versus arrays that are an element of a single part?
  ```tsp
  data: bytes[];
  ```

**Comment by markcowl** [comment]
last response: StatusMonitorType : {status: Succeeded}

logicalResult: <StatusMonitortype>
envelopeResult: <StausMonitorType>
logicalPath: ""
finalStep: none

logicalResult: void
envelopeResult: void
logicalPath: ""
finalStep:

Patch/202
Patch/201

**Comment by weidongxu-microsoft** [comment]
- How do we specify an additional `filename` property for an "application/octet-stream" field

This is more on client side, so it could be in TCGC instead.

The use case is in current OpenAI, which added a `filename` property in the model for multipart/form-data, which is really only for content-disposition aka `Content-Disposition: filename=<value-of-filename>`
https://github.com/Azure/azure-rest-api-specs/blob/848070b3dab1b5e76eee3587e99dddad8f36d6d7/specification/cognitiveservices/OpenAI.Inference/models/audio/audio_transcription.tsp#L37-L49

IMHO it seems better not be a property in model, as this is not a real field in multipart/form-data. Maybe a decorator over `file` property.

**Comment by lmazuel** [comment]
I don't believe the last question "How to differentiate arrays of individual parts versus arrays that are an element of a single part?" is a real problem:

```
@encode("binary")  // See https://github.com/microsoft/typespec/issues/2370
scalar binary extends bytes;

model MultiPartRequest {
  id: string; // Field "id" is text/plain
  address: Address; // Field "address" is an application/json

  profileImage: binary;  // Field "profileImage" is application/octet-stream

  previousAdresses: Address[]; // This is ONE part, as a JSON array

  pictures: binary[]; // This is as many part as necessary
  
}
```

https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CnVzaW5nIFR5cGVTcGVjLkh0dHA7CgpvcCB1cGxvYWRJbWFnZShAaGVhZGVyIGNvbnRlbnTELjogIm11bHRpcGFydC9mb3JtLWRhdGEiLCBAYm9keSBpxDg6IE3EI1BhcnRSZXF1ZXN0KTogdm9pZDsKCm1vZGVsIEFkZHJlc3MgewogIHN0cmVldDrECGluZzsKICBjaXR5yhB9CgpAZW5jb2RlKCJiaW5hcnkiKSAgLy8gU2VlIOQAznM6Ly9naXRodWIuY29tL21pY3Jvc29mdC%2FpAPRpc3N1ZXMvMjM3MApzY2FsYXIgxkogZXh0ZW5kcyBieXRlc%2BkAn%2FAAv%2BUAqGlk6QCUxH5GaWVsZCAiaWQiIGlzIHRleHQvcGxhaW4KICBh5gDeOugA58wwxxzFNWFuIGFwcGxpY2F0aW9uL2pzb24KCiAgcHJvZmlsZeUBgzrnAKk75QDyx0TMIcZJy0ZvY3RldC3kAVVhbcZOZXZpb3VzQcV4ZeoAlltd5QCYVGhpc8RET05FIOQB1SwgYXMgYSBKU09OIGFycmF5xUVpY3R1csQ95gCPzzxhcyBtYW55xUDEDW5lY2Vzc2FyeQogIOQBwAovKioKClBPU1QgL%2BYCYCBIVFRQLzEuMQpD5gJcLUxlbmd0aDogNDI4yRTmAnHzAnA7IGJvdW5kYXJ5PWFiY2RlMTIzNDUKCi0tyw7IRURpc3Bvc2nkAR06IMtCbmFtZT3kAcDPb%2BsBywoxMjNlNDU2Ny1lODliLTEyZDMtYTQ1Ni00MjY2NTU0NDAwMDDfdtV26AIGz3vyAg7kAnki5gMiIjogIjMsIEdhcmRlbiBTdCIsxBzkAyzEGkhpbGxzYmVyeSwgVVQiCn3%2FAJb1AJbsAlggIjsgxA3GGuUD1zEucG5n%2FACz7gJ7e%2BKApsRC6AQ%2B4oCm7gCWLS3%2FAJjqAJjuAsP%2FATduCgpb7wE4NDIsIEhpdGNoaGlrZXJz8QE%2BTmV3LVlvcmssIE5ZIgp9LM8%2FMjIsIEFjYWNpYSBBds46TG9uZG9uLCBVSyIKfV3%2FAXb2AN7nA1ztAXHHFf8Bc%2F8Bc%2FIBc%2F8Ak%2F8Ak8UVMv8Ak%2F8Ak%2FIAkwogKi8%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

**Comment by archerzz** [comment]
> * How do we specify an additional `filename` information for an "application/octet-stream" field
> 
> This is more on client side, so it could be in TCGC instead.
> 
> The use case is in current OpenAI, which added a `filename` property in the model for multipart/form-data. It is really only for content-disposition aka `Content-Disposition: filename=<value-of-filename>` [Azure/azure-rest-api-specs@`848070b`/specification/cognitiveservices/OpenAI.Inference/models/audio/audio_transcription.tsp#L37-L49](https://github.com/Azure/azure-rest-api-specs/blob/848070b3dab1b5e76eee3587e99dddad8f36d6d7/specification/cognitiveservices/OpenAI.Inference/models/audio/audio_transcription.tsp#L37-L49)
> 
> IMHO it seems better not be a property in model, as this is not a real field in multipart/form-data. Maybe a decorator over `file` property.
> 
> Currently Java uses a `Filename` postfix, that if property is `audio`, filename property is `audioFilename`. [Azure/azure-sdk-for-java#37488 (comment)](https://github.com/Azure/azure-sdk-for-java/issues/37488#issuecomment-1823868359) But it is not smart enough to make it `filename` if property be `file`...
> 
> Hence we wish typespec/TCGC can specify this clearly.

I prefer we have a decorator like `@file` in typespec, because it's part of the original HTTP request. Otherwise, how do we differentiate a file binary data from other types of binary data?

```typescript
@file
data: bytes[];
```

Then it's up to each language emitter to decide how to support file content, including file name.

**Comment by markcowl** [comment]
Closing in favor of https://github.com/microsoft/typespec/issues/3046
