### ISSUE TITLE
[rest] Need a way to detect properties cloned by KeysOf

### ISSUE THREAD

**Issue by witemple-msft** [microsoft/typespec#2717]
We have a partner scenario where a decorator is applied like this:

```tsp
model Employee is TrackedResource<EmployeeProperties> {
  @key("employeeName")
  @pattern(...)
  @foo
  name: string;
}
```

All of the above decorators will observe both the original property `Employee.name` as well as the cloned/renamed property `employeeName` created by the `KeysOf` constructor.

The problem is that in this scenario, `@foo` should only apply to the original property definition, and on the implementation side we don't have a good way to detect a cloned property.

One of our partners has found a hack that does detect it (they can check for `sourceProperty` to be present but set to `undefined` explicitly), but we ought to offer a better way to support this scenario.

The way I see it we can do one of two things:

1. Add information to the cloned property that allows the implementation `$foo` to detect it.
2. Add information to the decorator itself that allows it to be excluded from cloning operations like spread/keysof.

**Comment by bterlson** [comment]
What is it about Foo that its state doesn't apply to clones?

**Comment by markcowl** [comment]
@witemple-msft Can you add a size estimate to this issue?

**Comment by witemple-msft** [comment]
@bterlson Couple answers:

1. In the true example, there's a decorator that is meant to extract certain properties from the spec that represent "essential information" in the resource provider. So, the emitter wants to look at all the properties decorated with the "essential info" decorator as sort of "root nodes" for the part of the spec, so it's important that the decorator be able to tell the difference between a real original property definition and a clone we made for resource tracking purposes.
2. As a confounding factor, the number of "essential" items in the motivating use case is limited to 5 at most. We're accomplishing this by keeping track of the number of decorator applications in the program, and we need to be able to exclude the clones to do that correctly.

**Comment by witemple-msft** [comment]
@markcowl I put a 3 in our project tracking system. Let me know if I need to do anything more. Still not super familiar with the protocol for that. Getting something workable on this issue is P0 for me.

**Comment by timotheeguerin** [comment]
Remembered `@friendlyName`(or its replacement) is a decorator that we wouldn't want to carry over either as the goal is to give a name to a template instance but wouldn't make sense to carry over to a `model is` See #2276

**Comment by yejee94** [comment]
Hi team :) @timotheeguerin @witemple-msft any update on this? :)

**Comment by allenjzhang** [comment]
@yejee94 , since this is your decorator, please [take a look at this](https://github.com/Azure/typespec-azure/blob/a5d144e820179f9f3619b1cd3a399acd2bfa028c/packages/typespec-client-generator-core/src/decorators.ts#L881) to bypass setting decorator on cloned targets.
