### ISSUE TITLE
[compiler] Optional description for `@pattern`

### ISSUE THREAD

**Issue by witemple-msft** [microsoft/typespec#2718]
TypeSpec supports several validations, like `@pattern`. For most validations, for example: `@minValue`, the error message that should be given when validation fails is obvious. However, for `@pattern`, the regular expressions given are often difficult to understand, and we've found that there are some use cases for attaching an optional description to the pattern for readability and for use when surfacing validation errors to end users.

I propose augmenting the definition of `@pattern` like this:

```tsp
extern dec pattern(target: string | bytes | ModelProperty, pattern: valueof string, description?: valueof string);
```

The `description` can state what the pattern checks for. For example:

```tsp
@pattern("^[a-zA-Z0-9_]{3, 24}$", "must be between 3 and 24 alphanumeric characters and underscores")
id: string;
```

**Comment by markcowl** [comment]
@witemple-msft please add a size estimate
