### ISSUE TITLE
Non-working link in emitter docs

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#2721]
![image](https://github.com/microsoft/typespec/assets/5723682/e6016fce-50ec-420c-97c4-f6c72049fb80)

**Comment by markcowl** [comment]
pri: 0

**Comment by timotheeguerin** [comment]
Someone actually already fixed it in the next docs, latest should be updated tomorrow with the release https://github.com/microsoft/typespec/pull/2709
