### ISSUE TITLE
Missing @madeRequired decorator for versioning

### ISSUE THREAD

**Issue by marcselman** [microsoft/typespec#2731]
I have a datamodel that changed from being optional to being required in a newer version.
There is a nice [`@madeOptional` decorator](https://microsoft.github.io/typespec/standard-library/versioning/reference/decorators#@TypeSpec.Versioning.madeOptional), but there is no `@madeRequired` decorator.
There are some workarounds but they do not exactly generate the wanted results.
Is this something that can be easily added?

**Comment by timotheeguerin** [comment]
est: 8

**Comment by borrrden** [comment]
I would also like to see this become a reality....not sure what the alternative is.
