### ISSUE TITLE
openapi3 (v0.51.0): duplicate-type-name error when sharing type across routes w/multipart-form-data

### ISSUE THREAD

**Issue by trrwilson** [microsoft/typespec#2751]
[[TypeSpec playground link to repro](https://microsoft.github.io/typespec/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQoNCnVzaW5nIFR5cGVTcGVjLkh0dHDFGG1vZGVsIE15UmVxdWVzdE3ED3t9xBppbnRlcmZhY2UgTXlJyQx7DQogIEBnZXQgbGlzdE15VGhpbmdzKGlucHV0Os9IKTogc3RyaW5nO8U1cG9zdCB1cGxvYWTJOMQZICAvLyBPSyBpZiBuZXjEWW5lIGNvbW1lbnRlZCBvdXQgb3Ig5gDBYW5vdGhlciDkAOIgbGlrZSB0ZXh0L3BsYWluxkxAaGVhZGVyIGNvbnRlbnTkAPI6ICJtdWx0aXBhcnQvZm9ybS1kYXRh5AEYxDH%2FALsNCn0NCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)]

Using a custom type (tested: both `model` and `enum`) in a route that sets its `content-type` header to `multipart/form-data` appears to jealously guard against any other route using that type -- an attempt to do so results in

```
error @typespec/openapi/duplicate-type-name: Duplicate type name: 'MyModel'. Check @friendlyName decorators and overlap with types in TypeSpec or service namespace.
```

Omitting overridden use of `content-type` or setting to another value like `text/plain` or `application/octet-stream` doesn't encounter the issue, so it appears unique to `multipart/form-data`.

```js
  @get listMyThings(input: MyRequestModel): string;
  @post uploadMyThings(
    // OK if next line commented out or using another type like text/plain
    @header contentType: "multipart/form-data";
    input: MyRequestModel): string;
```

Thanks!

**Comment by timotheeguerin** [comment]
This to be some issue with implicit body with the repro(if you add `@body` for the input everything is working fine, but might not be limited to that
