### ISSUE TITLE
Drop support for prettier 2.0

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2760]
Prettier 3.0 has been out for some time and some of the apis are now deprecated. However updating to the newer api will break anyone that is using our plugin with prettier 2.0.

Apis that should be migrated:
- `.getValue()` -> `.node`

If we think keeping prettier 2.0 support is important(not sure why) then we could maybe do a custom wrapper that calls the right function.

**Comment by markcowl** [comment]
est: 2
