### ISSUE TITLE
[Feature Request] Support encode string for decimal

### ISSUE THREAD

**Issue by MaryGao** [microsoft/typespec#2762]
The discussion is from [JS decimal support](https://github.com/Azure/autorest.typescript/issues/2157#issuecomment-1846052801),  for decimal type in typespec not every language has the native support or has the ability to handle any precision either calculation or serialization/deserialization.

So if the service team strongly cares about the precision of decimal it should use @encode to encode it as a string.

Here is the draft proposal:

```
model Widget {
  @encode("decimalString") // ???
  value: decimal;
}

```
/cc @bterlson @timotheeguerin

**Comment by markcowl** [comment]
note: 
```
@encode(string)
myValue: decimal
```

**Comment by markcowl** [comment]
Closing as fixed
