### ISSUE TITLE
Support for OpenID Connect Authentication securityScheme

### ISSUE THREAD

**Issue by adam-pawlowicz** [microsoft/typespec#2772]
Hi,

I have found out that currently only Basic, Bearer and ApiKeyAuth are supported in tsp. Is there any plan to add OpenIDConnect?

Best Regards,

**Comment by timotheeguerin** [comment]
Didn't see that issue, someone else posted that in discussion and I filed an issue from theirs, I'll close this one in favor of #2773 which has more details
