### ISSUE TITLE
Define File type in typespec

### ISSUE THREAD

**Issue by chunyu3** [microsoft/typespec#2784]
In mutlipart/form-data, there is a widget to upload a file, when send the request in multipart/form-data, the actual content will be like:
```
Content-Disposition: form-data; name="file1"; filename="a.txt"
Content-Type: text/plain
```
Note there is a filename and the content-type of the file. 
Current typespec use `bytes` to refer a file-uploaded which doesn't contain that information.

Some services such as `Document Translation` care about the filename, randomly generating a file name is not acceptable for them.

Expected:
There is a some like `File` type in typespec, or maybe we need to define some decorator like `@File(filename: string, contentType?: string)` to indicate it is a File with some information
```
@File("FileName", "ContentType")
```

**Comment by lirenhe** [comment]
We may also consider how we could handle the array of files in multipart/form-data

**Comment by markcowl** [comment]
@markcowl link to existing design issues

**Comment by markcowl** [comment]
Tracking this as part of this design issue: https://github.com/microsoft/typespec/issues/2704
