### ISSUE TITLE
Disallow multiple @useAuth usage

### ISSUE THREAD

**Issue by catalinaperalta** [microsoft/typespec#2787]
Currently, having multiple @useAuth decorators for a service definition only takes the first one and ignores the second, see: [Playground example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CtIZdmVyc2lvbmluZyI7CgoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbJSDsKCkBzZXJ2aWNlKHsKICB0aXRsZTogIkltYWdlIEFuYWx5c2lzIiwKfSkKQHVzZUF1dGgoQXBpS2V5xAs8xgtMb2NhdGlvbi5oZWFkZXIsICJPY3AtQXBpbS1TdWJzY3JpcMQfLUtleSI%2By0lCZWFyZXLECynmAIdlcigKICAie2VuZHBvaW50fS9jb21wdXTkAKLkALIiLMQf5QCXemUgYW4gaeUAqHRvIGdlbmVyYXRlIGEgZGXJciBvZiBpdHMgY29udGVudCwgZGV0ZWN0IHRleHQsIG9iamVjdHMgYW5kIG1vcmUuxV%2FkAQcgIEBkb2MoIiIiCkF6dXJlIEFJIEPnAIogVuUAiyDoAKQgKHByb3RvY29sxUlob3N0bmFtZSwgZm9yIGV4YW1wbGU6Cmh0dHBzOi8vPHJlc291cmNlLcQlPi5jb2duaXRpdmXnAYZzLmHEcS5jb20pLgoiIiIp5QCPyG06IHVybOQApn0KKQrEQnNwYWNlIOUBr%2BgBrjsKCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

If this syntax is not supported we should have a linter rule warning against this.

**Comment by timotheeguerin** [comment]
Might just need to call the `validateUniqueOnNode` helper for that decorator.
