### ISSUE TITLE
Template parameter with constraint on itself should error

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2788]
```
model Test<A extends A> {
  
}
```
[Playground](
https://microsoft.github.io/typespec/playground?c=bW9kZWwgVGVzdDxBIGV4dGVuZHMgQT4gewogIAp9&e=%40typespec%2Fopenapi3&options=%7B%7D)

Typescript does this 
<img width="589" alt="image" src="https://github.com/microsoft/typespec/assets/1031227/7f5f97db-9d24-49cf-b78a-1e222fc0c78d">

Same with circular reference
```
model Test<A extends B, B extends A> {
  
}
```

**Comment by markcowl** [comment]
pri: 2
