### ISSUE TITLE
Deprecate `@service({version}`

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2821]
from design #2812

1. Deprecate `@service({version}`, cleanup docs to remove reference
2. Add correct types and test for `@OpenAPI.info` to allow `title` and `version` ([Somehow works already](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ9Ufb3BlbmFwaSI7Cgp1c2luZyBUeXBlU3BlYy5WyTk70BtIdHRw0RVSZXN0OwoKCkDHcmVkKMdDcykKQHNlcnZpY2Uoe3RpdGxlOiAiTVkgVElUTEUifSkKQE9wZW5BUEkuaW5mbyh7CiAgyCZPdmVycmlkZSIsCiAgbGljZW5zZTogxCIgIG5hbcQjQWJjxR4gIHVybDogIuQBI3M6Ly%2FHLi5jb20iCiAgfcQk5wCbOiAiMS4wLjUiLAp9KQrESHNwYWNlIEV4YW1wbGXFYGVudW0g6ADBx3JgMS4yLjBgxm5gMS4zxw19CgogIG9wIHRlc3QoQHF1ZXJ5KCJhcGktx3AiKSBhcGnHTTogc3RyaW5nKTogdm9pZDsKfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)
3. Add warning typespec-autorest or azure-core linter when using `@OpenAPI.info({version})` (or general don't use openapi library)

**Comment by markcowl** [comment]
est: 5
