### ISSUE TITLE
Should tspconfig.yaml have a key for entry point?

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#2839]
Currently, there is logic that looks specifically for `main.tsp` if the user does not specify an exactly file path, as this is the convention. It might be nice to support a tspconfig entry so that the entrypoint resolution can look for _that_ instead of main.tsp, if specified:

```tsp
mainFile: fooservice.tsp
```

We have CI processed that rely on the default resolution, so this would allow us to accommodate partner teams without just telling them "rename your file to main".

**Comment by timotheeguerin** [comment]
I have  thought about this a few times, problem with it is:
1. The way we see things is we look for the typespec entrypoint first and then we resolve what could be the config for it. So this would be a change wher ethe tspconfig.yaml becomes the project.
2.  you can already do that with the package.json if you have one for your project. And having both ways might just be confusing.
3.

**Comment by markcowl** [comment]
Closing as resolved using package.json
