### ISSUE TITLE
Generics-like templates in Protobuf 

### ISSUE THREAD

**Issue by visortelle** [microsoft/typespec#2857]
Hello! 👋 I noticed your project on GitHub and here is my attempt to make generics (templates) work in Protobuf. I'm not sure that the result is what I'd expect here. Any help? :)

**Input:**

```
import "@typespec/protobuf";

using TypeSpec.Protobuf;

@package({
  name: "kiosk",
})
namespace KioskExample;

model MyGenericList<ItemT> {
  @field(1) blabla: int32;
  @field(2) items: ItemT[];
}

model MyList {
  @field(1) ints: MyGenericList<int32>,
  @field(2) bools: MyGenericList<boolean>,
}
```

**Result:**

```
// Generated by Microsoft TypeSpec

syntax = "proto3";

package kiosk;

message MyGenericList {
  int32 blabla = 1;
  repeated int32 items = 2;
}

message MyGenericList {
  int32 blabla = 1;
  repeated bool items = 2;
}

message MyList {
  MyGenericList ints = 1;
  MyGenericList bools = 2;
}
```

**Comment by witemple-msft** [comment]
Thank you for the report. We're probably not handling template renaming correctly in the protobuf emitter, so I'll take a look at the code.

**Comment by witemple-msft** [comment]
I opened a PR that makes the protobuf emitter capable of renaming templates as is done in other emitters.

By default, the implementation will simply prepend the name of the arguments to the type, so your concrete message types will become `Int32MyGenericList` and `BooleanMyGenericList`, which probably isnt what you want.

To customize the generated names, you can use the `@friendlyName` decorator to create a name template, like this:

```tsp
using TypeSpec.Protobuf;

@package({
  name: "kiosk",
})
namespace KioskExample;

@friendlyName("{name}List", ItemT)
model MyGenericList<ItemT> {
  @field(1) blabla: int32;
  @field(2) items: ItemT[];
}

model MyList {
  @field(1) ints: MyGenericList<int32>,
  @field(2) bools: MyGenericList<boolean>,
}
```

Note the addition of `@friendlyName` on the templated type `MyGenericList`. With this change you will get concrete message types name `Int32List` and `BooleanList`.

This change will be incorporated into the next release of the protobuf emitter.

**Comment by visortelle** [comment]
LGTM thank you!
