### ISSUE TITLE
Documentation links are broken when searched for on bing

### ISSUE THREAD

**Issue by lilustga** [microsoft/typespec#2859]
If you search "data-types in typespec" for example you will get:

https://typespec.io/libraries/http/reference/data-types

all the top hits link to similar dead links

**Comment by timotheeguerin** [comment]
I believe this is all due to the docs moving under `/docs` not sure what we can do until the search engine reindex.

**Comment by markcowl** [comment]
- see if there is anything we can do to force a reindex

**Comment by timotheeguerin** [comment]
Searching in icognito in google and bing now points to the new `typespec.io` website with the correct structure
![image](https://github.com/microsoft/typespec/assets/1031227/023a0f86-e2fb-4a08-800e-ef0f04d135a6)
