### ISSUE TITLE
Define guidelines for writing a library/emitter around scoping

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2860]
Typespec is design so you can define your service/architectgure as a single spec and emitter should be able to pick what they care about without being poluted by other emitters. We should describe those guidelines so make sure emitters and libraries are design to work together.

Example for azure and tcgc [playground](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CskZYXp1cmUtdG9vbHMvyCUtY2xpZW50LWdlbmVyYXRvci1jb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA7xxVBxEkuQ8U6R8g5LkNvcmU7CgpAc2VydmljZQpuYW1lc3BhY2UgRm9vLkJhci5TxhogewogIEByb3V0ZSgiL3Rlc3QiKSBvcCDECih4OiBzdHJpbmcsIHnICyk6IHZvaWQ7Cn0KCi8vIOYAsy50c3AKCkDGDSjEU8d5OiBnbG9iYWwuz3csCn0p8wCV5gDH5QCUbW9kZWzEGcUOICDpAIw7xQ%2FpAJDED30KCiAgaW50ZXJmxE5PdmVycmlkZXPHO%2F8AzGTGUsQmMiBpc%2FcAsi7EIMZtfQoKQOcA7E5hbWUo1Co6OnBhcmFtZXRlcnMueCwgImN1c3RvbVgiLP8B%2FeoB%2FXNoYXJwIik7Cg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Comment by markcowl** [comment]
est: 3
