### ISSUE TITLE
Augment decorator not working on properties coming from `model is`

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2867]
```tsp
model Foo {
  @doc("Base doc")
  name: string;
}

model Bar is Foo {}

@@doc(Bar.name, "Override bar");
```
[Playground Link](https://typespec.io/playground?c=bW9kZWwgRm9vIHsKICBAZG9jKCJCYXNlIGRvYyIpCiAgbmFtZTogc3RyaW5nOwp9CgrGMkJhciBpc8Y5fQoKQMU6QmFyLsQwLCAiT3ZlcnJpZGUgYmFyIik7&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by markcowl** [comment]
@bterlson Is there a chance the symbol refactor will fix this?
