### ISSUE TITLE
Typespec openapi3 0.51 generates array as allOf, recursive field, (similar to 2796)

### ISSUE THREAD

**Issue by iw-stefro** [microsoft/typespec#2882]
Hi
Sorry, we're still having a problem with some change between 0.50 and 0.51. 
I think this is related/similar to #2796, which is fixed but it seems to be some more corners.
I've tested it with the @next tsp npm packages.

This typespec will in the latest version generate the nested/recursive field as allOf and redocly complains with:
```
Prerendering docs
Incompatible types in allOf at "#/components/schemas/FilterNode/properties/childNodes": "object" and "array"
allOf: schemas with different types can't be merged
OpenAPI Sampler: found allOf with "array" type. Result may be incorrect
```

the typespec
```
import "@typespec/rest";
import "@typespec/openapi3";

using TypeSpec.Http;
using TypeSpec.Rest;

model FilterNode
{
    someField: string;
    childNodes: FilterNode[] | null;         // note e.g. that the ' | null ' here affects, and the post op further down.
}

model QueryParams
{
    filters: FilterNode[] | null;
}

@post op TheSearch(...QueryParams): {}[];
```

yaml part:
```
        childNodes:
          type: object
          allOf:
            - type: array
              items:
                $ref: '#/components/schemas/FilterNode'
          nullable: true
```

**Comment by timotheeguerin** [comment]
[Repro in next playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7DQrSGm9wZW5hcGkzxB4NCnVzaW5nIFR5cGVTcGVjLkh0dHA70RZSZXN0xS5tb2RlbCBGaWx0ZXJOb2RlDQp7DQogICAgc29tZUZpZWxkOiBzdHJpbmc7xhhjaGlsZMQqczrLN1tdIHwgbnVsbDvEJMUBLy8gbm90ZSBlLmcuIHRoYXQgdGhlICfHKCAnIGhlcmUgYWZmZWN0cywgYW5kxSFwb3N0IG9wIGZ1cnRoZXIgZG93bi4NCn3qAK1RdWVyeVBhcmFtc%2BkArmblAIr3AJPHPkDIW1RoZVNlYXJjaCguLi7LTik6IHt9W107&e=%40typespec%2Fopenapi3&options=%7B%7D)
