### ISSUE TITLE
Add note that 'numeric', 'float', 'int' can vary by language

### ISSUE THREAD

**Issue by RickWinter** [microsoft/typespec#2892]
The 'float', 'int', and 'numeric' base types can map to different size implementations depending on the emitter language.  

Recommendation:
Add notes to the spec that languages are free to map those types to the most appropriate type in the respective language.

**Comment by markcowl** [comment]
- check to see if we have a linter rule for this in azure.core
- update the data types table to include the imprecise nature of these numeric types

**Comment by markcowl** [comment]
est: 1

**Comment by bterlson** [comment]
The documentation is updated.
