### ISSUE TITLE
[OpenAPI 3] Spurious error on op with same path and different verb from a shared route

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2925]
[Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKICBAc2hhcmVkUm91dGXED3Bvc3QKICBvcCBjcmVhdGVVcmxBdHRhY2htZW50KAogICAgQGhlYWRlciBjb250ZW505ACoOiAiYXBwbGljYXRpb24vanNvbuUAjcRRYXRoIGl0ZW1JZDogc3RyaW5nxhrHP3M6IHsgeMgbIH3EHSk6IE9rUmVzcG9uc2UgfCBOb3RGb3VuZMgT%2FwC65gC6RmlsZf8Au%2BcAu211bHRpcGFydC9mb3JtLWRhdGH%2FAL7sAL5ieXRlc%2F8AtusAtmRlbGV0ZeQAp8YKKNRk30tlOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

```
import "@typespec/http";

using TypeSpec.Http;
@service({
  title: "Widget Service",
  version: "1.0.0",
})
namespace DemoService;

@sharedRoute
@post
op createUrlAttachment(
  @header contentType: "application/json",
  @path itemId: string,
  contents: { x: string },
): OkResponse | NotFoundResponse;

@sharedRoute
@post
op createFileAttachment(
  @header contentType: "multipart/form-data",
  @path itemId: string,
  contents: bytes,
): OkResponse | NotFoundResponse;

@delete op delete(@path itemId: string): OkResponse | NotFoundResponse;
```

The `delete` op gets the error "All shared routes must agree on the value of the shared parameter." but I believe they do agree.

**Comment by markcowl** [comment]
- fix the bug
