### ISSUE TITLE
Deleting a file you have open in VSCode crashes the language service

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2928]
Repro steps:

1. Create a `main.tsp`.
2. Open `main.tsp` in vscode.
3. Delete `main.tsp` from disk.

**Comment by timotheeguerin** [comment]
is it the same as https://github.com/microsoft/typespec/issues/2472

**Comment by timotheeguerin** [comment]
actually this is different and I can't repro #2472 anymore

**Comment by timotheeguerin** [comment]
ok I repro this one, you have to delete via the command line
