### ISSUE TITLE
OpenAPI3 output has an additional value and kind layer under properties

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2937]
See typespec link [here](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgV2lkZ2V0IHsKICBAa2V5IGlkOiBzdHJpbmc7CiAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUiOwp9Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D) we have an additional `value` and `kind` layer under properties. that doesn't seem to align with the openapi3 definition?

![image](https://github.com/microsoft/typespec/assets/55688292/70c4ce60-9c43-4217-8114-b20c066c8d69)

Feel like it's a bug?

**Comment by timotheeguerin** [comment]
The link you shared doesn’t repro for me

**Comment by qiaozha** [comment]
How so ? I can still see it's there in my side. Did you see the https://cadlplayground.z22.web.core.windows.net/ address ?

**Comment by timotheeguerin** [comment]
Yeah not sure, are you able to repo in the cli?  what browser are you using?

**Comment by qiaozha** [comment]
I found it's working if I use https://typespec.io/playground [link](https://typespec.io/playground?c=bW9kZWwgV2lkZ2V0IHsNCiAgQGtleSBpZDogc3RyaW5nO8QUd2VpZ2h0OiBpbnQzMsUSY29sb3I6ICJyZWQiIHwgImJsdWUiOw0KfQ0K&e=%40typespec%2Fopenapi3&options=%7B%7D) @timotheeguerin

**Comment by qiaozha** [comment]
I wonder if you have set some kind of dns record alias that cause you can't repo in the https://cadlplayground.z22.web.core.windows.net/ ?

**Comment by timotheeguerin** [comment]
I tried on mobile and deskop with 2 different browser and I cannot repro, are you sure you don't have a cached version of the playground somehow? Can you repro outside of the playground? And what browsers are you using?

**Comment by qiaozha** [comment]
I am not sure what you mean by a cached version, can the playground be cached by the browser without any special configuration ? I was using chrome in windows when I found this, but I just found I can't repro it with chrome/safari in my mac either. 😢

**Comment by timotheeguerin** [comment]
Browser will cache any file html, js, css file loaded to speed up next load time. If you force a refresh of the page(Forgot the shortcut) or open the devtools and make sure in network tab the option is deselected to cache responses

**Comment by markcowl** [comment]
@qiaozha can you confirm that this is fixed?

**Comment by qiaozha** [comment]
close it, haven't get time to verify it but probably just my local issues.
