### ISSUE TITLE
[bug][http] `getHttpOperation` can't find right `contentTypes` 

### ISSUE THREAD

**Issue by msyyc** [microsoft/typespec#2938]
For the following tsp, `getHttpOperation` can't return type with right contentTypes:
```
import "@azure-tools/typespec-azure-core";
import "@azure-tools/typespec-client-generator-core";
import "@typespec/rest";
import "@typespec/versioning";

using TypeSpec.Rest;
using TypeSpec.Http;
using TypeSpec.Versioning;
using Azure.Core;
using Azure.Core.Traits;
using Azure.ClientGenerator.Core;

@service({
    title: "Test service",
})
@versioned(Versions)
namespace Test;

enum Versions {
    @doc("2022-12-01-preview")
    @useDependency(global.Azure.Core.Versions.v1_0_Preview_2)
    v2022_12_01_preview: "2022-12-01-preview",
}

@TypeSpec.Rest.resource("deployments")
model Deployment {
    @visibility("read")
    @projectedName("java", "deploymentOrModelName")
    @key
    deploymentId: string;
}

model AudioTranscriptionOptions {
    @projectedName("csharp", "AudioData")
    file: bytes;
}

@doc("Result information for an operation that transcribed spoken audio into written text.")
model AudioTranscription {
    text: string;
}

alias MultipartFormDataRequestHeadersTraits = Azure.Core.Traits.RequestHeadersTrait<{
    @header("content-type")
    contentType: "multipart/form-data";
}>;

@actionSeparator("/")
@action("audio/transcriptions")
op getAudioTranscriptionAsPlainText is Azure.Core.Foundations.ResourceOperation<
    Deployment,
    AudioTranscriptionOptions,  // response_format must be one of: text, srt, vtt
    string,
    MultipartFormDataRequestHeadersTraits
>;

```

![image](https://github.com/microsoft/typespec/assets/70930885/b2f4690d-be70-4dbd-9282-8b2cbfae6fe9)

But for some template it can:
```
@actionSeparator("/")
@action("audio/transcriptions")
op getAudioTranscriptionAsResponseObject is Azure.Core.ResourceAction<
    Deployment,
    AudioTranscriptionOptions,  // response_format must be unspecified (json) or one of: json, verbose_json
    AudioTranscription,
    MultipartFormDataRequestHeadersTraits
>;
```
![image](https://github.com/microsoft/typespec/assets/70930885/2d8d474f-7c2d-4bef-a39f-2c8bdd0786a6)

I guess there may be bug for specific template.

**Comment by timotheeguerin** [comment]
I don't think that would be an issue with the http library, i think this is most likely the trait is not applying correctly

**Comment by timotheeguerin** [comment]
If you look at this playground you can see that adding other header doesn't apply 
[Repro](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvdHlwZXNwZWMtxhVjb3JlIjsK3itjbGllbnQtZ2VuZXJhdG9y0TbIKi9yZXN01Rl2ZXJzaW9uaW5nIjsKCnVzaW5nIFR5cGVTcGVjLlJlc3Q70BVIdHRw0RVWyUfIG0HkALEuQ29yZdISLlRyYWl0c88Z5QDNR%2BgAzMc7CkBzZXJ2aWNlKHsKICAgIHRpdGxlOiAiVGVzdCDHGyIsCn0pCkDnAMtlZCjnAI5zKQpuYW1lc3BhY2UgxDE7CgplbnVtIMggIMZUQGRvYygiMjAyMi0xMi0wMS1wcmV2aWV3IinGH3VzZURlcGVuZGVuY3koZ2xvYmFsLusAzshPLnYxXzBfUMY9XzLGPnbEWF8xMl8wMV%2FHWDog1G0sCn0KCkDtAXwucmVzb3VyY2UoImRlcGxveW1lbnRzIikKbW9kZWwgRMkU6ADJdmlzaWJpbGl0eSgicmVhZOgAwnByb2plY3RlZE5hbWUoImphdmEiLCDLVU9yTcRTxB%2FINGtlecUJyiVJZDogc3Ry5QHlfQrnAIVBdWRpb1RyYW5zY3JpcHRpb25PxQbpAV3PfGNzaGFycMR%2BxTpEYXRhx3JmaeQB2mJ5dGVzxWDmAZdSZXN1bHQgaW5mb3JtYcRaIGZvciBhbiBvcOQCKsQRdGhhdCB05wCEYmVkIHNwb2tlbiBhxGIgaW50byB3cml0dGVuIHRleHQu6QFC8gC95wC2xCftAO1hbGlhcyBNdWx0aXBhcnRGb3Jt5AC7UmVxdWVzdEhlYWRlcnPmAtcgPfIC6y7TKTzGa0BoxRQoImNvbnTkA8%2FkA5znARPHE%2BQCFTogIm3Ifi%2FkAQwtZOQBOzvMRMUMb3RoZXLrALw%2B5ANFYWPkAN1TZXBh5QNdKCIvIinIFigi5QEoL%2BgBQeYBvyIpCm9wIGdldPIBJEFzUGxhaW5UZXh0IGlz7ADtRm91bmTlAZTkAPLmArxP6AGnPOUAn%2BoCtSzFENJf5wJALCAgLy8gcmVzcG9uc2Vf5gH%2FIG11c3QgYmUgb25lIG9mOuUBqSwgc3J0LCB2dHTFUuYA%2BsZe%2FwGx5gGdCj47Cg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

I think this is a long standing issue with trait not working correctly on `Azure.Core.Foundations.ResourceOperation`

**Comment by msyyc** [comment]
So it seems bug of typespec-azure-core? If that, I feel OK to transfer the issue to typespec-azure repo.

**Comment by timotheeguerin** [comment]
This problem is too deep into the traits making it I think impossible to fix without the complete rethinking of how traits work

**Comment by markcowl** [comment]
@markcowl linkt to trait redesign issues

**Comment by markcowl** [comment]
tracking this here: https://github.com/microsoft/typespec/issues/1619
