### ISSUE TITLE
OpenAPI emitter create duplicate xxxCreate and xxxCreateOrUpdate when using the create and update visibility

### ISSUE THREAD

**Issue by ouvreboite** [microsoft/typespec#2940]
When a property is given both the `create` and `update` visibility, the OpenAPI emitter generates both a `xxxCreate` (_used in the creation endpoint_) and `xxxCreateOrUpdate` (_used in the update endpoint_). Both are structurally identical, so I suppose they are redundant (only `xxxCreateOrUpdate` is needed).

I also suppose that maintaining distinct models for create and update can be beneficial (as other properties could be flagged just the "read" or just the "update" visibility later, making the models diverge). But then the `xxxCreateOrUpdate` model should simply be named `xxxUpdate` to avoid confusion.

**Example:**
```typescript
import "@typespec/rest";
using TypeSpec.Http;

@service({title: "Person API"})
namespace WeatherAPIServce;

model Person
{   
    name: string;
    @visibility("create","update")
    someParam: string;
}

@route("/persons")
interface CampaignAPI{
  @post create(@body data: Person): void;
  @put update(@body data: Person): void;
}
```

Will generate the following OpenAPI 3.0 specification (_trimmed a bit to be easier to read_)

```yaml
...
paths:
  /persons:
    post:
      operationId: CampaignAPI_create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonCreate' #why not use PersonCreateOrUpdate here?
    put:
      operationId: CampaignAPI_update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonCreateOrUpdate'
components:
  schemas:
    PersonCreate:
      type: object
      required:
        - name
        - someParam
      properties:
        name:
          type: string
        someParam:
          type: string
    PersonCreateOrUpdate: #that's the same as PersonCreate
      type: object
      required:
        - name
        - someParam
      properties:
        name:
          type: string
        someParam:
          type: string
```

**Comment by markcowl** [comment]
may be related to: https://github.com/microsoft/typespec/issues/2946

**Comment by tjprescott** [comment]
Closing this. @ouvreboite if you try the suggested fix and still believe it is not working correctly, please reopen this issue.
