### ISSUE TITLE
discrepancy in ordering of `@encodedName` and `@clientName`

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/typespec#2943]
With `@encodedName`, the name we're trying to change to is the second argument, while in `@clientName`, the name we're trying to change to is the first argument, with an optional language scope at the end. For example, this is what it would look like switching the encoded and client name of a property
 
```
model MyModel {
  @encodedName("application/json", "service-name")
  @clientName("service_name", "python")
  serviceName: string;
}
```

Consider making a breaking change. For `@clientName` our hands are tied bc the language scope is optional, and since @timotheeguerin has mentioned that in the future you guys might want the content type scope to be optional as well, I think it's worth a breaking change review to see if we should fix the ordering here

**Comment by markcowl** [comment]
ALso, potential parallelism with `@encode`

**Comment by markcowl** [comment]
Consensus at design meeting was not to take the breaking change
