### ISSUE TITLE
[OpenAPI 3] Emitter crashes with templated union

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2946]
[Playground](https://typespec.io/playground?c=dW5pb24gUmVzcG9uc2U8VD4gew0KICBUO8QGeyBoaTogInRoZXJlIiB9Ow0KfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

```
union Response<T> {
  T;
  { hi: "there" };
}
```

**Comment by timotheeguerin** [comment]
Error seems to be in the compiler where we don't resolve template Parameter in union, error also in json schema emitter [playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOwoKdXNpbmcgVHlwZVNwZWMuSnNvblPFHTsKCkDELMYOCm5hbWVzcGFjZSDGEXPEPG5pb24gRm9vPFQ%2BIHsKICBULAogIHN0cmluZywKfQoKCm1vZGVsIFRlc3TFIGZvbzrFMMYkPjsKfQ%3D%3D&e=%40typespec%2Fjson-schema&options=%7B%7D)
