### ISSUE TITLE
[OpenAPI 3] Error description not discovered with error hierarchy. 

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#2947]
[Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKLyoqIGZhaWwhICovCm1vZGVsIEFQSUVycm9yIHsgY29kZTogc3RyaW5nfccuYSDkAKtpZmlj0DlDdXN0b23GPGV4dGVuZHPLTQogIC4uLiBSZXNwb25zZTw0MDA%2BCn0KCm9wIGdldCgpOsxAOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

If I have an error hierarchy, I might prefer to use extends like so:

```
/** fail! */
model APIError { code: string};

/** a specific fail! */
model CustomError extends APIError {
  ... Response<400>
}
```

However, neither `extends` nor `is` works, I just get the generic description. If I remove both, the response gets the right description.

**Comment by timotheeguerin** [comment]
Before someone tries to fix this one, this was done by design in this PR https://github.com/microsoft/typespec/pull/765 so we might need to think about this a little more

**Comment by timotheeguerin** [comment]
This has been fixed
