### ISSUE TITLE
isErrorModel doesn't recognize inheritance of @error decorator

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/typespec#2957]
`isErrorModel` from typespec compiler only recognizes a model as an error model if it is directly decorated with the `@error` decorator, not when it inherits it

Playground [here](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQGVycm9yCm1vZGVsIEhhc0XED0RlY29yYXRvciB7CiAgY29kZTogc3RyaW5nOwp9CsctSW5oZXJpdNAyZXh0ZW5kc9hMaGlsZFByb3DNUUBwdXQKb3AgaNA0KCk60kk7CsQsadV%2FxDH2AJk7Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by markcowl** [comment]
Is this a case where we specifically want to model inheritance in the output model?  Note that, if you use `Model is` then the decorator will be present and [isErrorModel will return true](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQGVycm9yCm1vZGVsIEhhc0XED0RlY29yYXRvciB7CiAgY29kZTogc3RyaW5nOwp9CsctSW5oZXJpdNAyaXPYR2hpbGRQcm9wzUxAcHV0Cm9wIGjQNCgpOtJJOwrELGnVesQx9gCUOwo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)
