### ISSUE TITLE
[Ask] How to interpret array in multipart/form-data?

### ISSUE THREAD

**Issue by MaryGao** [microsoft/typespec#2962]
We have a cadl-ranch test case([here](https://github.com/Azure/cadl-ranch/blob/9c9ef620809a2237a054d7f716e759c7f087d6d6/packages/cadl-ranch-specs/http/payload/multipart/main.tsp#L19-L26)), in which we have two arrays
- Case1: previousAddresses: a list of addresses
- Case2: pictures: a list of bytes

```
model Address {
  city: string;
}

model ComplexPartsRequest {
  id: string;
  address: Address;
  profileImage: bytes;
  previousAddresses: Address[];
  pictures: bytes[];
}
```
Currently the case is designed - Case1 it is only one part to cover a list of addresses and Case2 it is multiple part and each part stands for the same field name(here is the [code](https://github.com/Azure/cadl-ranch/blob/9c9ef620809a2237a054d7f716e759c7f087d6d6/packages/cadl-ranch-specs/http/payload/multipart/main.tsp#L110-L126)).

I can see the inconsistancy between them and not sure it follows the [RFC](https://datatracker.ietf.org/doc/html/rfc7578#section-5.2). 

So I am confirming from typespec side on how to interpret array?

/cc @msyyc @lmazuel @lirenhe @timotheeguerin

**Comment by weidongxu-microsoft** [comment]
PS: there is already service in use of the `pictures: bytes[];` and backend requires file/files on the `pictures` form-data field (multiple `pictures` fields if multiple files).

**Comment by bterlson** [comment]
To me the inconsistency isn't as big of an issue as the fact that no matter which way we pick, we are missing a way to express the other way if you need it. In the original example, we have no way to say that `pictures` should be a JSON array of base64-encoded values or that `addresses` should be N parts of application/json address objects.

I do think we should be consistent though, and say that arrays always mean multiple parts, and then ponder ways we could change this behavior if needed.  This also aligns with OpenAPI. So for the above example, we would have:

```typescript
model Address {
  city: string;
}

model ComplexPartsRequest {
  id: string; // one part, text/plain.
  address: Address; // one part, application/json.
  profileImage: bytes; // one part, application/octet-stream or specialized if we have more context from FIle
  previousAddresses: Address[]; // N parts of application/json.
  pictures: bytes[]; // N parts of application/.octet-stream or specialized if we have more context from File
}
```

**Comment by markcowl** [comment]
- Make sure we have an example of an array of models

est: 2

**Comment by bterlson** [comment]
I am beginning to not like inferring parts from JSON-like objects, I think it adds a lot of ambiguity and presents challenges when needing to customize metadata about a specific part. You could imagine being more explicit, with a well-known type for a part, or a decorator that defines a part. I think this design should be rationalized with multipart/mixed and batching scenarios.

**Comment by msyyc** [comment]
@markcowl Could you also help link this design issue to https://github.com/microsoft/typespec/issues/2704? Thanks!
