### ISSUE TITLE
Is it possible to document a interface/operation template with @doc just like a model? 

### ISSUE THREAD

**Issue by DMaro28** [microsoft/typespec#2963]
Hi Team
I'm using @doc decorator to document templated model, as documented here: https://typespec.io/docs/language-basics/documentation . 

I'd like to do the same with my interface/operation template. Is it supported?

Playground sample:
```
import "@typespec/http";

using TypeSpec.Http;
@service({
  title: "Widget Service",
  version: "1.0.0",
})
namespace DemoService;

model Widget {
  @visibility("read", "update")
  @path
  id: string;

  weight: int32;
  color: "red" | "blue";
}

@error
model Error {
  code: int32;
  message: string;
}

@route("/widgets")
@tag("Widgets")
interface Widgets extends ResourceService<Widget>{}

interface ResourceService<T extends {}> {
  @doc("Read {}", T)
  @get read(@path id: string): Widget | Error;

  @doc("Delete {}", T)
  @delete delete(@path id: string): void | Error;
}
```

**Comment by markcowl** [comment]
Yes, this can be done using the doc-specific string interpolation, [like this](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQoNCnVzaW5nIFR5cGVTcGVjLkh0dHA7DQpAc2VydmljZSh7DQogIHRpdGxlOiAiV2lkZ2V0IFPGHCIsxBx2ZXJzaW9uOiAiMS4wLjDEFX0pDQpuYW1lc3BhY2UgRGVtb8cyxXFtb2RlbCDHS8VfQHZpc2liaWxpdHkoInJlYWQiLCAidXBkYXRlIinFIXBhdGjECWlkOiBzdHJpbmfFSyAgd2VpZ2h0OiBpbnQzMjvEEmNvbG9yOiAicmVkIiB8ICJibHVl5ADqfcQxQGVycm9y6ACERcQN5gCDY29kZcxGbWVzc2FnZctuxkByb3V0ZSgiL3flAL9z5ACfQHRhZyjnARvFEWludGVyZuQA%2B8cVIGV4dGVuZHMgUmVzb3VyY2XnAQ88xiA%2BIHvFXco40ChUyUJ7fT7nATRkb2MoIlJlYWQge%2BQBbH0iLCBU5gEtZ2V0xAjkAUko5QE66wE3KTroAXp85gD%2F5wFIxk9EZWxldGXRUWTFF8QLxgrUVnZvaWTLVH0NCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

**Comment by markcowl** [comment]
@DMaro28 Let me know if you have a specific scenario this doesn't address

**Comment by DMaro28** [comment]
@markcowl  Thank you
