### ISSUE TITLE
[feature request] Support Doc Customization

### ISSUE THREAD

**Issue by YalinLi0312** [microsoft/typespec#2965]
I met a scenario where need doc customization by language: 

for example, we have this model defined in `models.tsp`:
``` 
model Foo{
    @doc("... Either A or B must be specified.")
    A?: string
 
    @doc("... Either A or B must be specified.")
    B?: string
}
```
Now we want to rename property `A` to `C`, but didn't find a way to custom the property name in doc.

The initial request and discussions are in Teams: 
https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1709080775664?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1709080775664&teamName=Azure%20SDK&channelName=TypeSpec%20Discussion&createdTime=1709080775664

**Comment by markcowl** [comment]
@YalinLi0312 Can you reopen this in the typespec-azure repo as a tcgc issue?
