### ISSUE TITLE
[bug] getEncode() return undefined when decorate on Union type

### ISSUE THREAD

**Issue by chunyu3** [microsoft/typespec#2969]
When @encode decorate on a property whose type is Union, getEncode() return undefined. the encoding information is missing

```
model TimeModel
{
    @encode("unixTimestamp", int32)
    started_at: utcDateTime | null;
}
```

getEnode() for property `started_at` return undefined.

**Comment by timotheeguerin** [comment]
Dup of https://github.com/Azure/typespec-azure/issues/259
