### ISSUE TITLE
Body type returned by `getHttpOperation` 

### ISSUE THREAD

**Issue by tadelesh** [microsoft/typespec#2999]
I want to know the behavior and root cause for `getHttpOperation` returning different type of body, it's really confusing.
For the following test:
```typescript
it("test", async () => {
      const { testModel, testAlias, testAnonymous, testSplit, testSpreadModel, testSpreadAlias } = (await runner.compile(`
        @service({title: "Test Service"})
        namespace TestService;

        alias TestAlias = {
          prop1: string,
          prop2: int32
        };
        
        model TestModel {
          prop1: string,
          prop2: int32,
          prop3: TestAlias
        }

        @test
        @route("/testModel")
        op testModel(@body body: TestModel): void;

        @test
        @route("/testAlias")
        op testAlias(@body body: TestAlias): void;

        @test
        @route("/testAnonymous")
        op testAnonymous(@body body: {prop1: string, prop2: int32}): void;

        @test
        @route("/testSplit")
        op testSplit(prop1: string, prop2: int32): void;

        @test
        @route("/testSpreadModel")
        op testSpreadModel(...TestModel): void;

        @test
        @route("/testSpreadAlias")
        op testSpreadAlias(...TestAlias): void;
      `)) as { testModel: Operation; testAlias: Operation; testAnonymous: Operation; testSplit: Operation; testSpreadModel: Operation; testSpreadAlias: Operation };;
      const diagnostics = createDiagnosticCollector();
      const operations = [testModel, testAlias, testAnonymous, testSplit, testSpreadModel, testSpreadAlias];
      for (const op of operations) {
        const httpOperation1 = diagnostics.pipe(getHttpOperation(runner.context.program, op));
        const bodyType1 = httpOperation1.parameters.body?.type;
        const httpOperation2 = diagnostics.pipe(getHttpOperation(runner.context.program, op));
        const bodyType2 = httpOperation2.parameters.body?.type;
        console.log(bodyType1 === bodyType2);
      }
    });
  });
```
I got all `true`.

But when I added a metadata parameter:
```typescript
it("test with parameter", async () => {
    const { testModel, testAlias, testAnonymous, testSplit, testSpreadModel, testSpreadAlias } = (await runner.compile(`
      @service({title: "Test Service"})
      namespace TestService;

      alias TestAlias = {
        @query
        test: string,
        prop1: string,
        prop2: int32
      };
      
      model TestModel {
        @query
        test: string,
        prop1: string,
        prop2: int32,
        prop3: TestAlias
      }

      @test
      @route("/testModel")
      op testModel(@body body: TestModel): void;

      @test
      @route("/testAlias")
      op testAlias(@body body: TestAlias): void;

      @test
      @route("/testAnonymous")
      op testAnonymous(@body body: {@query test: string, prop1: string, prop2: int32}): void;

      @test
      @route("/testSplit")
      op testSplit(@query test: string, prop1: string, prop2: int32): void;

      @test
      @route("/testSpreadModel")
      op testSpreadModel(...TestModel): void;

      @test
      @route("/testSpreadAlias")
      op testSpreadAlias(...TestAlias): void;
    `)) as { testModel: Operation; testAlias: Operation; testAnonymous: Operation; testSplit: Operation; testSpreadModel: Operation; testSpreadAlias: Operation };;
    const diagnostics = createDiagnosticCollector();
      const operations = [testModel, testAlias, testAnonymous, testSplit, testSpreadModel, testSpreadAlias];
      for (const op of operations) {
        const httpOperation1 = diagnostics.pipe(getHttpOperation(runner.context.program, op));
        const bodyType1 = httpOperation1.parameters.body?.type;
        const httpOperation2 = diagnostics.pipe(getHttpOperation(runner.context.program, op));
        const bodyType2 = httpOperation2.parameters.body?.type;
        console.log(bodyType1 === bodyType2);
      }
  });
```
I got `true true true false false false`.

Why we could get the same type without any metadata parameter, but different type with them, and it only happened in separated way of defining operation parameters?

**Comment by timotheeguerin** [comment]
it is because the `body.type` is the exact body(with all metadata properties removed) so if the model mixes some it will create a new virtual model with only the properties needed. So everytime you call it its a new one

**Comment by tadelesh** [comment]
@timotheeguerin but why it will not happen in the model/alias/anonymous model definition. The body type will return the exact type we use in the body.

**Comment by timotheeguerin** [comment]
Are you sure you are not returned the full model in the case where it works. I have a big pr making the body behavior consistent including making @body be exactly the body and returning the exact body resolved model which would make those scenarios much clearer

**Comment by lirenhe** [comment]
@timotheeguerin, for 'things could change the types in between the first time it's called and last.'
Is it possible to make it clear what are the types that will be changed and what will not be? 
Then we could case by case to decide whether this is expected.

From the above sample, 'alias with/without @query property' produces different result. 

Can we close this issue after you and @tadelesh reached the agreement?  Thanks

**Comment by timotheeguerin** [comment]
yes decorators can changes things if some decorator calls that helper then some other mutate the type graph and you call it later you might not see what happened.

and yes because without `@query` there is no virtual model to create we can just return the original one (which is then the same)
and please answer this question

> It's still comes back to the same question why are you calling it twice it is an expensive function to call

**Comment by tadelesh** [comment]
we call this function both in tcgc and language's emitter. also in tcgc, we will also call it multiple times because we have different part of logics that needs operation info. we do not have a central cache in tcgc or emitter, that makes thing worse.

**Comment by tadelesh** [comment]
regarding your explanation, why i could get same type for following cases when calling gethttpoperation twice?
```
        @route("/testSplit")
        op testSplit(prop1: string, prop2: int32): void;

        @route("/testSpreadModel")
        op testSpreadModel(...TestModel): void;

        @route("/testSpreadAlias")
        op testSpreadAlias(...TestAlias): void;
```

**Comment by timotheeguerin** [comment]
Because in those case it is still the same model from the type graph the anonymous model that is on the operation.parameters.

**Comment by timotheeguerin** [comment]
> we call this function both in tcgc and language's emitter. also in tcgc, we will also call it multiple times because we have different part of logics that needs operation info. we do not have a central cache to map operation and http operation rn in tcgc or emitter, which makes thing worse.

yeah then it sounds like you should be caching that on your side. It is an expensive method to call and if you design requires you to call it multiple times from different places, then you can do your own caching.
