### ISSUE TITLE
[Feature Request] Allow to spread another union in named union 

### ISSUE THREAD

**Issue by MaryGao** [microsoft/typespec#3024]
We are reviewing the union and enum cases in [pr](https://github.com/Azure/typespec-azure/pull/389/files) and [doc](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/389/docs/next/howtos/DataPlane%20Generation%20-%20DPG/06types.html). 

And one scenario for customers is useful that `we have existing unionA, then we want to expand more members for unionB based on A`. Currently we could implement that for Enum by leveraging the spread operator.

```
enum ProvisioningState {
  ...ResourceProvisioningState,
  Provisioning,
  Updating,
  Deleting,
  Accepted,
}
```

I was wondering if we could allow to do this for named union also.
```
union BaseUnion {
  "a",
  "b"
}

// Case 1: union contains another union
// This union has two members, one is string literal, the other is union
union HasUnionMembers {
  "c",
  BaseUnion
} 

// Case 2: union extends/spreads from another union
// This union has three members, "a", "b" and "c"
union SpreadUnion {
  "c",
  ...BaseUnion
} 
```

**Comment by markcowl** [comment]
Closing as won't fix
