### ISSUE TITLE
[Bug]: OpenAPI3 Enum duplicating literal values when inheriting

### ISSUE THREAD

**Issue by danielmorrison** [microsoft/typespec#3087]
### Describe the bug

When I have multiple models ~using inheritance,~ that each have an enum of literal numbers, the final value (emitted as OpenAPI3) duplicates itself depending on how many models I have: 

```
model SecondModel extends BaseModel {
  active: 0 | 1;
}
```

```
active:
  type: number
  enum:
    - 0
    - 1
    - 1
    - 1
    - 1
```

### Reproduction

~[Playground Link](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZb3BlbmFwaTMiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFU9wZW5BUEk7Cgptb2RlbCBCYXNlTcUKewogIGlkOiBpbnRlZ2VyOwogIHNvbWV0aGluZzogMCB8IDE7Cn3IOEZpcnN0xjlleHRlbmRzz0tuYW1lOiBzdHJpbmfETGFjdGl2ZdJJU2Vjb25k3ErYOlRoaXLfOc85&e=%40typespec%2Fopenapi3&options=%7B%7D)~ There's a [simpler version](https://typespec.io/playground?c=bW9kZWwgQSB7CiAgc29tZXRoaW5nOiAwIHwgMTsKfQoKxiFCIMUiYWN0aXZl0h9D3h9E1x8%3D&e=%40typespec%2Fopenapi3&options=%7B%7D) 

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Seems like this repro even without inheritance [playground](https://typespec.io/playground?c=bW9kZWwgQSB7CiAgc29tZXRoaW5nOiAwIHwgMTsKfQoKxiFCIMUiYWN0aXZl0h9D3h9E1x8%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by timotheeguerin** [comment]
I cannot believe we have never encountered that before, this happen with string unions as well [playground](https://typespec.io/playground?c=bW9kZWwgQSB7CiAgc29tZXRoaW5nOiJhIiB8ICJiIjsKfQoKxiRCIMUlYWN0aXZlOiAiYSLJIg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by timotheeguerin** [comment]
Ok so the problem somehow seems to be if the first variant match then we keep adding to the same output [inverted order doesn't get the issue](https://typespec.io/playground?c=bW9kZWwgQSB7CiAgc29tZXRoaW5nOiAiYSIgfCAiYiI7Cn0KCsYlQsUlYWN0aXZlOsQcxCJhxSI%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by timotheeguerin** [comment]
Found the issue https://github.com/microsoft/typespec/pull/3090, will try to get that in for tomorrow's release
