### ISSUE TITLE
Offer completions for model properties when model extends another model

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#3130]
### Clear and concise description of the problem

```
model Foo {
  x: string;
  y: string;
}

model Bar extends Foo {
  // here I should get completions for members of Foo.
}

```

This would be very handy, especially when you are modelling complex data shapes with inheritance rather than templates.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by RodgeFu** [comment]
it's also better to clarify these completions are for override scenario somehow so that they won't confuse people we are not using overrides.

**Comment by qiaozha** [comment]
I don't think currently we can override properties for now? 
<img width="264" alt="image" src="https://github.com/microsoft/typespec/assets/55688292/a1e552d7-a043-4118-8aec-2460a419c735">

But for other usage like 
```
model Bar extends Foo {
  z: Foo.x;
}
```
Maybe we should also consider offer completions for spread of alias or spread of models or other kinds of combination ?

**Comment by bterlson** [comment]
You can override, but the type you override with has to be a subtype of the base. So in your example, if you set `x` to `"someString"` it would work.

> it's also better to clarify these completions are for override scenario somehow so that they won't confuse people we are not using overrides.

Can you say more about what the potential confusion is?
