### ISSUE TITLE
Create and validate preview and publish pipelines

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#3133]
After this merges into main https://github.com/microsoft/typespec/pull/3116 we can create the following pipelines in the internal ado.

- typespec - http-client-csharp - preview : based on preview.yml
- typespec - http-client-csharp - publish : based on publish.yml

**Comment by hallipr** [comment]
preview pipeline created:
https://dev.azure.com/azure-sdk/internal/_build?definitionId=6870

**Comment by hallipr** [comment]
publish pipeline created:
https://dev.azure.com/azure-sdk/internal/_build/index?definitionId=6871&_a=completed

**Comment by m-nash** [comment]
deleted preview and publish worked "https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-js-test-autorest/npm/registry/@typespec/http-client-csharp/-/http-client-csharp-0.1.0-beta.20240415.2.tgz"
