### ISSUE TITLE
Bug: Versioning not complaining about union of arrays using incomaptible types

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#3134]
If referencing a type via a union of array that is not available in the version it doesn't complain and we endup with some never types

```
model Widget {
  // uncomment to fix
  // @added(Versions.v2)
  content: string | Bar[];
}

@added(Versions.v2)
model Bar {}

```
[Playground Link](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR07CgpAxytlZCjHGHMpCkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAp9KQpuYW1lc3BhY2UgRGVtb8cbOwoKZW51bSDIUCDERnYxLMQGMiwKfQoKbW9kZWwgx1HEHi8vIHVuY29tbWVudCB0byBmaXjGFkBhZGTrAJsudjIpCiAgY29udGVudDogc3Ry5ADbfCBCYXJbXTvEXNQyxnBCYXIge30K&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by tjprescott** [comment]
I think the right way to express this is in this [playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR07CgpAxytlZCjHGHMpCkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAp9KQpuYW1lc3BhY2UgRGVtb8cbOwoKZW51bSDIUCDERnYxLMQGMiwKfQoKbW9kZWwgx1HEHi8vIHVuY29tbWVudCB0byBmaXgKICDlANBDaGFuZ2VkRnJvbekAoi52Miwgc3RyaW5nKQogIGNvbnRlbnQ6xxMgfCBCYXJbXTvEa0BhZGTrANwudjIpx39CYXIge30K&e=%40typespec%2Fopenapi3&options=%7B%7D) using `@typeChangedFrom`.

So is the action here to throw a versioning error?
