### ISSUE TITLE
Add unit tests for Analyze-Changes script

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#3167]
### Clear and concise description of the problem

We should have unit tests to make sure we don't break the rules as we add more cases in the future for which folders should trigger which stages.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
Just say it could be nicer to rewrite this script in JS if we want unit test; would make it easier I think to maintain and load the config from a separate file
