### ISSUE TITLE
[Bug]: `getDiscrminator` return undefined while TCGC can find the discriminator

### ISSUE THREAD

**Issue by archerzz** [microsoft/typespec#3184]
### Describe the bug

Check the TSP spec for `OpenAI.Assitants`: https://github.com/Azure/azure-rest-api-specs/blob/c4e661cdf92c8f579574008d0cd11874cc303da0/specification/ai/OpenAI.Assistants/runs/models.tsp#L171-L188

`RequiredAction` is the base model, and `SubmitToolOutputsAction` is the child model.

`getDiscriminator()` on `RequiredAction` will return `undefined`, while TCGC can find the discriminator.

![image](https://github.com/microsoft/typespec/assets/4516/525a5b37-5641-44f0-a159-457a0d94a088)

Here `modelType` is the TCGC SdkModelType, and `modelType.__raw` is the compiler type.

### Reproduction

Just try to parse the Tsp spec in the link above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
@archerzz is this an issue with tcgc or typespec I don't really get here?

**Comment by archerzz** [comment]
> @archerzz is this an issue with tcgc or typespec I don't really get here?

@timotheeguerin I think it's in typespec, because `modelType` (which is TCGC `SDKModelType`) has the correct discriminator property, but `getDiscriminator()` (which is typespec API) failed.

**Comment by timotheeguerin** [comment]
how is tcgc getting it if the compiler is not returning it? can you make a smaller repro with exactly what is not working?

**Comment by archerzz** [comment]
> how is tcgc getting it if the compiler is not returning it? can you make a smaller repro with exactly what is not working?

I'll try, I actually just copy&paste those two models into a smaller tsp project, and I could not reproduce it.

Some interesting finding, it looks like `RequiredAction` is parsed as `Union` in typespec...
![image](https://github.com/microsoft/typespec/assets/4516/0d28439d-9257-4862-9c9b-673f73cceb6a)

**Comment by archerzz** [comment]
@tadelesh Is that possible that TCGC assigns a wrong instance to `__raw`. I don't think compiler will parse a model into a union.

**Comment by tadelesh** [comment]
See: https://github.com/Azure/azure-rest-api-specs/blob/c4e661cdf92c8f579574008d0cd11874cc303da0/specification/ai/OpenAI.Assistants/runs/models.tsp#L40. The property is a union.

**Comment by timotheeguerin** [comment]
so is the issue you are calling `getDiscriminator` on `RequiredAction | null` but should go down to `RequiredAction`.

Can this issue be closed?

**Comment by archerzz** [comment]
> so is the issue you are calling `getDiscriminator` on `RequiredAction | null` but should go down to `RequiredAction`.
> 
> Can this issue be closed?

@timotheeguerin sure, thank you all for the investigation
