### ISSUE TITLE
[Bug]: Cannot use TypeSpec extension for VS code

### ISSUE THREAD

**Issue by pshao25** [microsoft/typespec#3189]
### Describe the bug

I went to VS code extension market and installed the TypeSpec extension for VS code. I cannot use it, "F12" not working at all with error:

Error: Cannot find module 'd:\GIT\autorest\node_modules\@typespec\compiler\cmd\tsp-server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.12.1
[Info  - 7:33:44 PM] Connection to server got closed. Server will restart.
[Error - 7:33:44 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 7:33:44 PM] TypeSpec client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 7:33:44 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 7:33:44 PM] Client TypeSpec: connection to server is erroring. Shutting down server.
[Error - 7:33:44 PM] Stopping server failed

### Reproduction

As described above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Can you share a little more info, do you have a .vscodr folder with settings where you configured that tsp-path, is typespec installed in the folder you are looking?

**Comment by timotheeguerin** [comment]
The only way I can repro this is if you have this in your settings.json but the package is not installed there
```
    "typespec.tsp-server.path": "./node_modules/@typespec/compiler"
```

If I don't have the compiler installed at all(locally or globally) you get an error explaining you need to install it
```
[Error - 8:27:31 AM] TypeSpec client: couldn't create connection to server.
Launching server using command tsp-server failed. Error: spawn tsp-server ENOENT
[Error - 8:27:31 AM] TypeSpec server executable was not found: 'tsp-server' is not found. Make sure either:
 - TypeSpec is installed locally at the root of this workspace ("/Users/timotheeguerin/dev/test/vitest-debug-repro") or in a parent directory.
 - TypeSpec is installed globally with `npm install -g @typespec/compiler'.
 - TypeSpec server path is configured with https://github.com/microsoft/typespec#installing-vs-code-extension.

```
