### ISSUE TITLE
Avoid to extends or is array

### ISSUE THREAD

**Issue by tadelesh** [microsoft/typespec#3198]
For the following three syntax:
1. `model A extends Array<B>`
2. `model A is Array<B>`
3. `model A is B[]`

Seems all these are only giving another name for the array, but with a more complicated syntax. I prefer to avoid to use them to reduce complexity for emitter.

**Comment by timotheeguerin** [comment]
There is cases where you need to use that like you want to provide a reusable array with max items/min items. Are you asking as a linter rule in azure? This is something emitters should definitely support

**Comment by markcowl** [comment]
@tadelesh if we want to discourage casw (1) in Azure, could you move this issue into the Azure repo.  Otherwise, this is by design.
