### ISSUE TITLE
[Bug]: Internal compiler error, operation in interface should already have been checked

### ISSUE THREAD

**Issue by Sherylueen** [microsoft/typespec#3199]
### Describe the bug

Got Internal compiler error: Operation in interface should already have been checked.
Hi team,
Today I based on the typespec to fix some of the check errors in PR's pipeline.
I got this error, Internal compiler error, operation in interface should already have been checked, not know how to deal with it.
![image](https://github.com/microsoft/typespec/assets/13853019/3f5402ce-a55b-4d73-9da2-20c492ccf8d6)

Code ref: [AppComplianceAutomation.Management](https://github.com/Azure/azure-rest-api-specs-pr/tree/Sherylueen-appcomplianceautomation-Microsoft.AppComplianceAutomation-2024-06-27/specification/appcomplianceautomation/AppComplianceAutomation.Management)
 

### Reproduction

1. go to https://github.com/Azure/azure-rest-api-specs-pr
2. check out to branch Sherylueen-appcomplianceautomation-Microsoft.AppComplianceAutomation-2024-06-27
3. under root folder run: px tsv specification/appcomplianceautomation/AppComplianceAutomation.Management

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
ok so if we get rid of the syntax error this patttern happens when a operation template in an interface is pointing to a `is`  that is not an olperation 

```
op test is IFace.Action;

interface IFace {
  Action<Headers> is string;
}

```

**Comment by markcowl** [comment]
The root issue in TypeSPec is tracked here: https://github.com/microsoft/typespec/issues/3199  Leavign this as a TCGC issue once this is resolved.
