### ISSUE TITLE
[http-client-csharp] Error Encountered When Running Generate.ps1

### ISSUE THREAD

**Issue by ShivangiReja** [microsoft/typespec#3209]
When attempting to run the `typespec\packages\http-client-csharp\generator> ..\eng\scripts\Generate.ps1` script , an error occurs. The error message states:
![image](https://github.com/microsoft/typespec/assets/45216704/e92f1308-2a33-4122-a0f0-7e3dcb9378fd)

**Comment by jorgerangel-msft** [comment]
Seems like the generator is having issues loading the SCM plugin from node_modules in [PluginHandler.cs](https://github.com/microsoft/typespec/blob/main/packages/http-client-csharp/generator/Microsoft.Generator.CSharp/src/StartUp/PluginHandler.cs#L13).
