### ISSUE TITLE
[Bug]: `@removed` decorator for a property won't work directly, if a model is not added from the very begining

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#3210]
### Describe the bug

```typespec
enum Versions {
  v1,
  v2,
  v3
}

@added(Versions.v2)
model Foo {
  prop: string;

  // @add(Versions.v2) // if I comment it out, it won't work
  @removed(Versions.v3)
  prop2: int32;
}
```
this will report 
```
error
@typespec/versioning/incompatible-versioned-reference
'DemoService.Foo' was added in version 'v2' but contains type 'DemoService.Foo.prop2' added in version 'v1'.
22:3
```
Does `@removed` mean being removed since some version ? If so, I don't see why we need to add the `@add` decorator to remove a property.

### Reproduction

[playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR07CgpAxytlZCjHGHMpCkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAp9KQpuYW1lc3BhY2UgRGVtb8cbOwoKZW51bSDIUCDERnYxLMQGMsUGMwp9CgpAYWRky3YudjIpCm1vZGVsIEZvb8U0cHJvcDogc3Ry5QCrICBAcmVtb3bNNDMpxygyOiBpbnQzMjsKfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
Note that, if you mark the property with `@added(Versions.V2)` then this issue can be worked around
