### ISSUE TITLE
[Bug]: OpenAPI 3 emitter incorrectly generate duplicate name error

### ISSUE THREAD

**Issue by allenjzhang** [microsoft/typespec#3217]
### Describe the bug

Simple model definition generates: 
```
@typespec/openapi/duplicate-type-name
Duplicate type name: 'Foo'. Check @friendlyName decorators and overlap with types in TypeSpec or service namespace.
```

### Reproduction

[Playground link](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQoNCnVzaW5nIFR5cGVTcGVjLkh0dHDFGEBzZXJ2aWNlKHsNCiAgdGl0bGU6ICJUZXN0IFPGGiIsDQp9KQ0KbmFtZXNwYWNlIERlbW%2FHHcVEbW9kZWwgRm9vIGlzIFRyYWNrZWRSZXNvdXJjZSDFWC4uLk5hbWVQYXJhbTsNCn3KNs4oaWQ6IHN0cmluZzvED8RzyxHLN9BmZXh0ZW5kc89PcHJvcNZA6QCOxilAcGF0aMUJa2V51no%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bterlson** [comment]
[A slightly more minimal repro](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQoNCnVzaW5nIFR5cGVTcGVjLkh0dHDFGEBzZXJ2aWNlKHsNCiAgdGl0bGU6ICJUZXN0IFPGGiIsDQp9KQ0KbmFtZXNwYWNlIERlbW%2FHHTsNCm1vZGVsIEZvbyBpcyBUcmFja2VkUmVzb3VyY2UgxVZAcGF0aCDEQDogc3RyaW5nOw0Kfcg6yizJE9BGZXh0ZW5kc8wr&e=%40typespec%2Fopenapi3&options=%7B%7D)

```typescript
import "@typespec/http";

using TypeSpec.Http;

@service({
  title: "Test Service",
})
namespace DemoService;
model Foo is TrackedResource {
  @path name: string;
}
model Resource {}
model TrackedResource extends Resource {}
```

Does not repro when without an extends chain 3 deep or more.

**Comment by timotheeguerin** [comment]
the problems comes from the fact that we use `Visibility.all` to render the unreachable models but when figuring out if the properties are the same we use Visibility.read so `Foo` gets emitted with both.

**Comment by timotheeguerin** [comment]
though it is weird because it is only doing that with derived models
