### ISSUE TITLE
[Bug]: behavior change to HttpOperationResponse.response.body.type in 0.56.0-dev

### ISSUE THREAD

**Issue by weidongxu-microsoft** [microsoft/typespec#3225]
### Describe the bug

`HttpOperationResponse.responses.body.type` changes in 0.56.0-dev, compared to 0.55.0

case in cadl-ranch
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/model/visibility/main.tsp#L50-L51

in 0.55.0, the response.body.type is `VisibilityModel` model with 5 properties
![Screenshot 2024-04-24 134338](https://github.com/microsoft/typespec/assets/53292327/412da291-ee80-4aee-b8ce-ce87495bdf8f)

in next, it is an anonymous model with only 1 property (the one with "read")
![Screenshot 2024-04-24 132813](https://github.com/microsoft/typespec/assets/53292327/50400fc7-4efa-45be-8736-d7aff34855e9)

--- 

There is some other cases of difference in response, e.g. empty model
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/model/empty/main.tsp#L35

Also see some diff of response status code changed from 204 to 200.

### Reproduction

https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/model/visibility/main.tsp#L50-L51

next
```
{
  '@typespec/compiler': '0.56.0-dev.18',
  '@typespec/http': '0.56.0-dev.10',
  '@typespec/openapi': '0.56.0-dev.3',
  '@typespec/rest': '0.56.0-dev.4',
  '@typespec/versioning': '0.56.0-dev.3',
  '@azure-tools/typespec-client-generator-core': '0.42.0-dev.10',
  '@azure-tools/typespec-azure-core': '0.42.0-dev.5',
  '@azure-tools/typespec-azure-resource-manager': '0.42.0-dev.11',
  '@typespec/eslint-config-typespec': '0.56.0-dev.1',
  '@typespec/library-linter': '0.56.0-dev.3'
}
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by weidongxu-microsoft** [comment]
Found in nightly build, e.g.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3708464&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=8d0a7aee-8090-5653-72a7-7c81ab87cde7&l=12985

**Comment by timotheeguerin** [comment]
This has been done by design to make sure request and response body resolution use the exact same logic. Use the same logic you did for request and it will work fine.

**Comment by weidongxu-microsoft** [comment]
Thanks Timothee.

I will go update the cadl-ranch to e.g.

```ts
@get
op getModel(@body input: VisibilityModel): {
  @body output: VisibilityModel
};
```

However, I may reopen it, if we see thing changed on real service.
