### ISSUE TITLE
specify value of parameter is a random generated value

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/typespec#3234]
### Clear and concise description of the problem

In cases like `x-ms-client-request-id`, `datetime.now()`, we want to be able to express that the value for a header should be a random value generated, and users shouldn't have to input this.

```tsp
op foo(@header `x-ms-client-request-id`: $guid): void;
```

Also open to this being a tcgc decorator, but it feels best if we can incorporate this into the language

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
is this set by the client or the server?

**Comment by markcowl** [comment]
Moved to this issue: https://github.com/Azure/typespec-azure/issues/759

Closing this one for now, per discussion
