### ISSUE TITLE
[Bug]: Client Name Overrides are failing if the property is inherited(alias) from parent

### ISSUE THREAD

**Issue by sarangan12** [microsoft/typespec#3240]
### Describe the bug

In the Typescript SDK Generation, I am trying to override the names of some objects/models generated. But, the compiler is not able to find the properties of the object when the properties are inherited from the parent.

### Reproduction

The following code does not work. Playground Link is [here](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3ytjLWNsaWVudC1nZW5lcmF0b3LINgp1c2luZyBBxDQuQ8UlR8gkLkNvcmU7xyJUeXBlU3BlYy5IdHRw0RVSZXN00RVW6QDKyBvHZ8tXyhIuVHJhaXRzOwoKbW9kZWwgQSB7CiAgLi4uS2V5VmF1bHRDZXJ0aWZpY2F0ZUJhc2UKfQoKYWxpYXMg1yEgPcRCTkJGPzogZmxvYXQzMgp9OwoKQEDmAQ1OYW1lKEEuTkJGLCAibmJmIik72hwsICJqYXZhc2NyaXB0xCo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-core%2Fall%22%5D%7D%7D).

```
import "@typespec/http";
import "@typespec/rest";
import "@typespec/versioning";
import "@azure-tools/typespec-azure-core";
import "@azure-tools/typespec-client-generator-core";

using Azure.ClientGenerator.Core;
using TypeSpec.Http;
using TypeSpec.Rest;
using TypeSpec.Versioning;
using Azure.Core;
using Azure.Core.Traits;

model A {
  ...KeyVaultCertificateBase
}

alias KeyVaultCertificateBase = {
 NBF?: float32
};

@@clientName(A.NBF, "nbf");
@@clientName(A.NBF, "nbf", "javascript");
```

But the following code works:

```
import "@typespec/http";
import "@typespec/rest";
import "@typespec/versioning";
import "@azure-tools/typespec-azure-core";
import "@azure-tools/typespec-client-generator-core";

using Azure.ClientGenerator.Core;
using TypeSpec.Http;
using TypeSpec.Rest;
using TypeSpec.Versioning;
using Azure.Core;
using Azure.Core.Traits;

model A {
  NBF?: float32;
}

@@clientName(A.NBF, "nbf");
```

In the first code, the property is inherited. Only in such cases, the compiler errors out with the following message. 

```
C:\Users\......>npx tsp compile client.tsp
TypeSpec compiler v0.55.0

Diagnostics were reported during compilation:

C:/Users/..../propertyNameOverride.tsp:429:93 - error invalid-ref: Model doesn't have member nBF
> 429 | @@clientName(Microsoft.EventGrid.SystemEvents.KeyVaultCertificateNewVersionCreatedEventData.nBF,
      |                                                                                             ^^^

Found 1 error
```

Please help me to resolve this issue. 

**Additional Info**
Please note the following code works:

```
import "@typespec/http";
import "@typespec/rest";
import "@typespec/versioning";
import "@azure-tools/typespec-azure-core";
import "@azure-tools/typespec-client-generator-core";

using Azure.ClientGenerator.Core;
using TypeSpec.Http;
using TypeSpec.Rest;
using TypeSpec.Versioning;
using Azure.Core;
using Azure.Core.Traits;

model A {
  ...KeyVaultCertificateBase
}

model KeyVaultCertificateBase {
 NBF?: float32
};

@@clientName(A.NBF, "nbf");
@@clientName(A.NBF, "nbf", "javascript");
```

The code fails only when `alias` is used.

@xirzec @lmazuel @joheredi FYI.....

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qiaozha** [comment]
This is not just an issue for tcgc `@clientName`, any decorator that is trying to decorate on spread alias properties defined as above is problematic. [See this `@encodedName` example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGnZlcnNpb25pbmfEIA0KdXNpbmcgVHlwZVNwZWMuSHR0cDvRFlJlc3TSFlbJS8VKbW9kZWwgQSB7DQogIC4uLktleVZhdWx0Q2VydGlmaWNhdGVCYXNlDQp9xC5hbGlhcyDXJCA9xEYNCiBOQkY%2FOiBmbG9hdDMyDQp9xWlAQGVuY29kZWROYW1lKEEuTkJGLCAiYXBwbMRBaW9uL2pzb24iLCAibmJmIik73zLTMg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by markcowl** [comment]
@markcowl link to symbol refactor

**Comment by markcowl** [comment]
This may be fixed by https://github.com/microsoft/typespec/pull/2640

**Comment by timotheeguerin** [comment]
dup of this  #4764
