### ISSUE TITLE
[Bug]: Client Name Overrides are failing for model

### ISSUE THREAD

**Issue by sarangan12** [microsoft/typespec#3247]
### Describe the bug

The `@clientname` decorator does not work on models.

@xirzec @lmazuel @joheredi FYI....

### Reproduction

The documentation of the `clientname` decorator says it can be applied to the model also. Refer [here](https://azure.github.io/typespec-azure/docs/next/libraries/typespec-client-generator-core/reference/decorators#@Azure.ClientGenerator.Core.clientName). 

But, when I apply the decorator to my javascript generator with the following code:

```
@@clientName(Microsoft.EventGrid.SystemEvents.AcsChatEventBaseProperties,
  "AcsChatEventBase",
  "javascript"
);
```

the name is not overridden. The generation does not fail. But, this name override does not work. (While other overrides in the same file works). I tried the CADL playground and there also I do not see the name change. Refer [here](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGnZlcnNpb25pbmfNIGF6dXJlLXRvb2xzL8gsLcYVY29yZd8sZWMtY2xpZW50LWdlbmVyYXRvcsk3DQp1c2luZyBBxDYuQ8UnR8gmLkNvcmU7yCNUeXBlU3BlYy5IdHRw0hZSZXN00hZW6QDRyRzHa8xbyhMuVHJhaXRz5QCabW9kZWwgQSB7DQogIE5CRj86IGZsb2F0MzINCn3EIUBA5gDYTmFtZShBLCAiQiIpxTrGAg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGnZlcnNpb25pbmfNIGF6dXJlLXRvb2xzL8gsLcYVY29yZd8sZWMtY2xpZW50LWdlbmVyYXRvcsk3DQp1c2luZyBBxDYuQ8UnR8gmLkNvcmU7yCNUeXBlU3BlYy5IdHRw0hZSZXN00hZW6QDRyRzHa8xbyhMuVHJhaXRz5QCabW9kZWwgQSB7DQogIE5CRj86IGZsb2F0MzI7DQp9xCJAQGRvYyhBLCAiQiIpOw0K&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D

This seems like a client name decorator issue this works fine with doc decorator.
Autorest emitter also diesnt support use of client  name everywhere

**Comment by sarangan12** [comment]
Closing this issue since a new issue has been opened here - https://github.com/Azure/typespec-azure/issues/750
