### ISSUE TITLE
Reverse engineer TypeSpec models from OpenAPI / JSON Schema and Protobuf

### ISSUE THREAD

**Issue by larsw** [microsoft/typespec#3259]
### Clear and concise description of the problem

It would be productive if it was possible to reverse engineer OpenAPI / JSON Schema and Protobuf specifications into TypeSpec code.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by bterlson** [comment]
Issue for OpenAPI conversion is here: https://github.com/microsoft/typespec/issues/3038. JSON Schema could presumably be done as well, although JSON Schemas are more likely to contain patterns that can't be converted cleanly to TypeSpec (like if/else).

**Comment by markcowl** [comment]
@allenjzhang please split this issue into individual issues

**Comment by allenjzhang** [comment]
OpenAPI: #3038 
JSON Schema: #3284
Protobuf: #3285
