### ISSUE TITLE
Add `.gitignore` to new projects

### ISSUE THREAD

**Issue by jbergstroem** [microsoft/typespec#3262]
### Clear and concise description of the problem

Improve DX by adding a `.gitignore` when initializing a project (even if its not managed by git) that at a minimum would contain `node_modules` and `tsp-output`.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
are you suggesting `tsp init` should be doing that?

**Comment by jbergstroem** [comment]
> are you suggesting `tsp init` should be doing that?

Yes, as part of setting up a project directory. Sorry if I wasn't clear enough.

**Comment by timotheeguerin** [comment]
Should be easy enough maybe add as a prompt (`Add default .gitignore? Y/n`)
