### ISSUE TITLE
[Bug]: multipleOf not emitting in openapi3

### ISSUE THREAD

**Issue by lovebug356** [microsoft/typespec#3275]
### Describe the bug

OpenAPI3 is not emitting multipleOf, it is supported as it is done in json-schema ([link](https://swagger.io/docs/specification/data-models/data-types/#numbers)).

### Reproduction

Input:
```
import "@typespec/json-schema";

using TypeSpec.JsonSchema;

@jsonSchema
model Foo {
  @multipleOf(10)
  bar: integer;
}
```

Current result:
```
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components:
  schemas:
    Foo:
      type: object
      required:
        - bar
      properties:
        bar:
          type: integer
```

Expecting `multipleOf: 10` in the same way as in json-schema:
```
$schema: https://json-schema.org/draft/2020-12/schema
$id: Foo.yaml
type: object
properties:
  bar:
    type: integer
    multipleOf: 10
required:
  - bar
```

https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOwoKdXNpbmcgVHlwZVNwZWMuSnNvblPFHTsKCkDELMYOCm1vZGVsIEZvbyB7CiAgQG11bHRpcGxlT2YoMTApCiAgYmFyOiBpbnRlZ2VyOwp9&e=%40typespec%2Fopenapi3&options=%7B%7D

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
OpenAPI3 emitter doesn't use the Json Schema decorator as openapi3(until 3.1) isn't fully compliant with Json schema. We are however lacking a `multipleOf` decorator in openapi3

**Comment by markcowl** [comment]
@markcowl link to issue for supporting json schema decorators in OpenAPI3

**Comment by timotheeguerin** [comment]
Issue to add all missing decorators to openapi3 https://github.com/microsoft/typespec/issues/3293
