### ISSUE TITLE
[Bug]: Visual Studio Extension is not working on ARM processor.

### ISSUE THREAD

**Issue by GFlisch** [microsoft/typespec#3279]
### Describe the bug

It is not possible to use the extension on Microsoft Visual Studio Professional 2022 (ARM 64-bit).
I am also author of a Visual Studio Extension and this is working fine on all versions of Visual Studio.

Do you have a reason to not support the ARM version of Visual Studio 2022?

### Reproduction

On a ARM PC, try to install TypeSpec via the link: https://marketplace.visualstudio.com/items?itemName=typespec.typespecvs

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
I don't think there is any reason as much as we never explicitly done any work or got complain about it until now.
Seems from this [blog](https://devblogs.microsoft.com/visualstudio/now-introducing-arm64-support-for-vs-extensions/) this was added after we made the initial extension too so probably never revisited.

[Blog](https://devblogs.microsoft.com/visualstudio/now-introducing-arm64-support-for-vs-extensions/) above shows the instructions and seems quite simple to add support
