### ISSUE TITLE
Doc/usage of `@format` should update

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#3301]
### Clear and concise description of the problem

Per previous discussion with @timotheeguerin @iscai-msft and @tadelesh , `@format` should not be used nor be recognized by TCGC therefore our generator will not even know the existence of these decorator which is quite misleading for our users.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
Some generator might/will make use  of it. Service code gen could do it for validation, openapi emitters also use it to carry over that info if needed. Feels to me like docs on the client docs

**Comment by markcowl** [comment]
@markcowl ask author to move
