### ISSUE TITLE
Adding instrumentation to Azure toolsets to gather intelligence

### ISSUE THREAD

**Issue by allenjzhang** [microsoft/typespec#3322]
### Clear and concise description of the problem

To support insights into internal service adoption and usage, we need to collect stats on active users. We do collect user information via VS Extension instrumentation. However, there seems to be anomalies in the user data collected. It would be reliable to directly collect from the TypeSpec toolset. 

With that ask, TypeSpec Compiler with broader community usage would not be suitable to instrument. However for Azure toolset (autorest emitter, Azure.Core, ARM library), they can be instrumented to collect primarily internal user. The following is list of task breakdowns.

Tasks:
- [ ] Privacy Review
- [ ] New 1DS appID onboarding
- [ ] Determine initial data set and source (emitter vs library)
- [ ] Adding instrumentation

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by bterlson** [comment]
Shouldn't this be in the Azure repo?

**Comment by allenjzhang** [comment]
Moving to Azure repo. https://github.com/Azure/typespec-azure/issues/828
