### ISSUE TITLE
Expose a TS API for adding extension fields to a schema in a custom decorator

### ISSUE THREAD

**Issue by Veetaha** [microsoft/typespec#3336]
### Clear and concise description of the problem

This issue is based on a discussion https://github.com/microsoft/typespec/discussions/3328 and @timotheeguerin's suggestion to solve my particular use case. See details in that discussion. The gist is that I'd like to write a custom decorator that simplifies the following notation:

```ts
@extension("x-foo", Json<"value here">)
```
to the this one
```ts
@foo("value here")
```

Right now it's implemented in my code with a hack like this, which creates a "fake" template instantiation of `Json<T>` model.

```ts
import { createRekeyableMap } from "@typespec/compiler/utils";
import { $extension } from "@typespec/json-schema";

/**
* @param {import("@typespec/compiler").DecoratorContext} context
* @param {import("@typespec/compiler").Type} target
* @param {import("@typespec/compiler").StringLiteral} value
*/
export function $foo(context, target, value) {
   $extension(context, target, "x-foo", {
       kind: "Model",
       name: "Json",
       namespace: { name: "JsonSchema" },
       properties: createRekeyableMap([["value", { type: value }]])
   })
}
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
est: 3
pri: 1
