### ISSUE TITLE
Remove InputIntrinsicType after getAllmodels adoption

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#3338]
// TODO -- after we have adopted getAllModels in our emitter, we no longer need to have this type.
    // The only thing we need in these "intrinsic types" is the "unknown", and TCGC put it in the primitive type. Others we will never generate therefore we do not need to have others

https://github.com/microsoft/typespec/pull/3238/files#diff-75483b722ca8dcc60388cfec7097840811a5293038dd40ec708eabb97d7fbee2R6-R7

**Comment by ArcturusZhang** [comment]
This is tracking here as well: https://github.com/Azure/autorest.csharp/issues/4712

**Comment by ShivangiReja** [comment]
`InputIntrinsicType` type was removed in this PR: https://github.com/microsoft/typespec/pull/3503.
