### ISSUE TITLE
Update bot to remove needs triage label once an area is assigned

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#3340]
### Clear and concise description of the problem

We should update our bot to remove the `needs triage` label when an area is assigned.

We should also re-add the `needs triage` if all area labels are removed.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
pri: 1
