### ISSUE TITLE
[Bug]: Applying @@visibility to model's property give an unexpected request body

### ISSUE THREAD

**Issue by pramotetrs** [microsoft/typespec#3387]
### Describe the bug

I've tried to modify the `id` property in extended `BuggyNestedObject` to add "create" visibility using `@@visibility` decoration. But it results the unexpected output which in the `POST` method, comparing to the `ExpectedNestedObject` in `POST` method, there is `id` property in `ExpectedNestedObject` but not in `BuggyNestedObject`.

### Reproduction
```
import "@typespec/http";

using TypeSpec.Http;
@service({
  title: "Example Service",
})
namespace DemoService;

// ----------------------------------------------

model BuggyBaseModel<T> {
  @key
  @path
  @visibility("read", "update")
  id: string;

  ...T;
}

model BuggyParentObject is BuggyBaseModel<{
  nested: BuggyNestedObject[];
}>;

model BuggyNestedObject is BuggyBaseModel<{
  sub: string;
}>;
@@visibility(BuggyNestedObject.id, "create");

@tag("Buggy")
@route("/buggy")
interface IBuggyObject {
  @post op update(...BuggyParentObject): void;
}

// ----------------------------------------------

model ExpectedBaseModel<T> {
  @key
  @path
  @visibility("read", "update", "create")
  id: string;

  ...T;
}

model ExpectedParentObject is ExpectedBaseModel<{
  nested: ExpectedNestedObject[];
}>;

model ExpectedNestedObject is ExpectedBaseModel<{
  sub: string;
}>;

@tag("Expected")
@route("/expected")
interface IExpectedObject {
  @post op update(...ExpectedParentObject): void;
}
```
### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tjprescott** [comment]
The reason for this is that you are trying to define an update as POST. By default, POST operations are treated as having a default visibility of "create". You need to make the following modification so that `BuggyNestedObject` matched `ExpectedNestedObject`.


Specifically, you need to decorate your POST-based update with `@parameterVisibility("update")`.
```
@tag("Buggy")
@route("/buggy")
interface Buggy {
  @parameterVisibility("update")
  @post op update(...BuggyParentObject): void;
}
```

**Comment by tjprescott** [comment]
@pramotetrs if this does not address your issue, please reopen.

**Comment by pramotetrs** [comment]
> The reason for this is that you are trying to define an update as POST. By default, POST operations are treated as having a default visibility of "create". You need to make the following modification so that `BuggyNestedObject` matched `ExpectedNestedObject`.
> 
> Specifically, you need to decorate your POST-based update with `@parameterVisibility("update")`.
> 
> ```
> @tag("Buggy")
> @route("/buggy")
> interface Buggy {
>   @parameterVisibility("update")
>   @post op update(...BuggyParentObject): void;
> }
> ```
> 
> Here's a playground with the fix applied: [Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQoNCnVzaW5nIFR5cGVTcGVjLkh0dHA7DQpAc2VydmljZSh7DQogIHRpdGxlOiAiRXhhbXBsZSBTxh0iLA0KfSkNCm5hbWVzcGFjZSBEZW1vxx3FXS8vIC3fAc4BxDVtb2RlbCBCdWdneUJhc2VNxA88VD4g5QCLQGtlecUIcGF0aMUJdmlzaWJpbGl0eSgicmVhZCIsICJ1cGRhdGUiKcQhaWQ6IHN0cmluZ%2BUAkyAgLi4uVDsNCn3PbFBhcmVudE9iamVjdCBpc%2FAAgcV%2BbmVzdGVkOsYcTsUNxjFbXcRSPsViy1TMI9hUc3Vi6wChxURA7ADV0UkuaWQsICJjcmXlAOPFc0B0YWcoIsUq5AD1QHJvdXRlKCIvYsgSaW50ZXJm5AGjxSXnAUxwYXJhbWV0ZXJWym%2FtATxAcG9zdCBvcCDGFSguLi7xASwpOiB2b2lk6AFS%2FwHz0gHqATNFeHBlY3RlZP8B9v8B9sQK6AEd%2FwIA0HnwAgPyAJHtAgbIH%2F4CCdQm213zAg%2FoAeDIMu0B42XLFeoB5sgr6AHp8QHH9ADz6wHK&e=%40typespec%2Fopenapi3&options=%7B%7D)

This is what I'm looking for. Thanks
