### ISSUE TITLE
Add Support For Setting JSON Usage Flag for Models

### ISSUE THREAD

**Issue by jorgerangel-msft** [microsoft/typespec#3392]
Once typescript is updated to support setting a model's usage flag to "json", we should update the generator to properly set the [model usage flag](https://github.com/microsoft/typespec/blob/main/packages/http-client-csharp/generator/Microsoft.Generator.CSharp.Input/src/InputTypes/InputModelTypeUsage.cs) during deserialization of a model.

**Comment by m-nash** [comment]
Can you open an issue against tcgc here https://github.com/Azure/typespec-azure since this item cannot finish until that happens.

**Comment by jorgerangel-msft** [comment]
> Can you open an issue against tcgc here https://github.com/Azure/typespec-azure since this item cannot finish until that happens.

Opened https://github.com/Azure/typespec-azure/issues/896.

**Comment by m-nash** [comment]
https://github.com/Azure/typespec-azure/pull/1129

**Comment by m-nash** [comment]
The [tsp side is complete](https://github.com/microsoft/typespec/blob/main/packages/http-client-csharp/generator/TestProjects/Local/Unbranded-TypeSpec/tspCodeModel.json#L25) we can now consume this on our end.

**Comment by m-nash** [comment]
Looks like this was already completed here https://github.com/microsoft/typespec/pull/3842
