### ISSUE TITLE
Avoid boxing in enum values and literal values

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#3396]
The enum value could be strings, numbers or booleans, but it is modeled as `object` therefore it has boxing: https://github.com/microsoft/typespec/blob/c026a0a87fe1dc2f894834d8d3db9cc80afbec6f/packages/http-client-csharp/generator/Microsoft.Generator.CSharp.Input/src/InputTypes/InputEnumTypeValue.cs

We have the same issue in literal values: https://github.com/microsoft/typespec/blob/c026a0a87fe1dc2f894834d8d3db9cc80afbec6f/packages/http-client-csharp/generator/Microsoft.Generator.CSharp.Input/src/InputTypes/InputLiteralType.cs

We could avoid the boxing, for example, we could model them as BinaryData and put whatever we have in the json into the BinaryData, we could get the corresponding value until we need the value

**Comment by m-nash** [comment]
Turns out the cost to avoid boxing with dynamic converters is higher than just reading into an object so we are closing this issue

```
//main
|              Method |     Mean |    Error |   StdDev | Allocated |
|-------------------- |---------:|---------:|---------:|----------:|
| EnumDeserialization | 76.54 us | 3.557 us | 3.954 us |  13.26 KB |

//branch
|              Method |     Mean |    Error |   StdDev | Allocated |
|-------------------- |---------:|---------:|---------:|----------:|
| EnumDeserialization | 89.12 us | 16.01 us | 17.13 us |  13.73 KB |
```
