### ISSUE TITLE
[Bug]: template model properties is ignored as decorator input 

### ISSUE THREAD

**Issue by archerzz** [microsoft/typespec#3406]
### Describe the bug

Let's assume we have the following model definitions:
```typescript
model Foo is SomeTemplate<Properties> {
    name: string
}

model Properties {
    age: int32,
    address: string
}

model SomeTemplate<T> {
    properties: T
}
```

In `client.tsp`, we try to mark `Foo.properties` is a flattened property:
```typescript
@@flattenProperty(Foo.properties);
```
That won't work.

---

If we have a model not derived from a template:
```typescript
model Result {
  name: string,
  properties: Properties
}
```
Then marking it as a flattened property in `client.tsp` will work:
```typescript
@@flattenProperty(Result.properties)
```

Note that in the VS code editor, `@@flattenProperty(Foo.properties)` won't even trigger a warning. Looks like there is something wrong when calculating the expression `Foo.properties` when `Foo` is a model derived from a template.
![image](https://github.com/microsoft/typespec/assets/4516/4d1c72e9-7d99-451d-b3f6-6a07fc0d34a6)

### Reproduction

Just try to parse the above model definitions.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
[Playground repro](https://typespec.io/playground?c=bW9kZWwgRm9vIGlzIFNvbWVUZW1wbGF0ZTxQcm9wZXJ0aWVzPiB7CiAgICBuYW1lOiBzdHJpbmcKfQoKxjzKKMcnYWdlOiBpbnQzMizGEGRkcmVzc9I6zW9UyGZwyVA6IFTELUBAZG9jKEZvby7KGywgIsQ%2BIGRvYyIpOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D) @archerzz  please share the playground next time

**Comment by archerzz** [comment]
> ```ts
> @@flattenProperty(Result.properties)
> ```

@timotheeguerin sorry I forgot to mention that `@flattenProperty` does not work in playground. I actually have one: https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvdHlwZXNwZWMtY2xpZW50LWdlbmVyYXRvci1jb3JlIjsNCg0KdXNpbmcgQcQ2LkPFJ0fIJi5Db3JlxSVtb2RlbCBGb28gaXMgU29tZVRlbXBsYXRlPFByb3BlcnRpZXM%2BIHsNCiAgICBuYW1lOiBzdHJpbmcNCn3KQMosyCthZ2U6IGludDMyLMcRZGRyZXNz1T%2FNeFTJb3DJVjogVM0xUmVzdWx0xijsAJXFbCNzdXBwxGwgImRlcHJlY2F0ZWQiICJAZmxhdHRlbucArXkgZGVjb%2BUBD%2BQA%2FG5vdCByZWNvbW1lbmRlZCB0byB1c2UuIsRS0DrEFOwAnccYaWVz5wCmDQpA0DQoRm9vLso1KeUBfv8Aq%2F8Aq%2FIAq9J25gEqzXk%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D

**Comment by archerzz** [comment]
@timotheeguerin Is there any ETA for this? It's currently impacting `vmware`. See this issue: https://github.com/Azure/typespec-azure/issues/959

The service has a list of models derived from template, like `model Addon is ProxyResource<AddonProperties>`. The service team tries to apply the decorator to the template: https://github.com/Azure/azure-rest-api-specs/blob/1418642cf8a57954c781c26c759fd4aef39a1287/specification/vmware/Microsoft.AVS/client.tsp#L19
```typescript
@@flattenProperty(Azure.ResourceManager.ProxyResource.properties);
```
which doesn't work.

They should be able to decorate each concrete model, like below:
```typescript
@@flattenProperty(Addon .properties);
@@flattenProperty(Location.properties);
```
That's what this issue should resolve.

**Comment by archerzz** [comment]
never mind, the milestone is `[2024] July`

**Comment by timotheeguerin** [comment]
@archerzz I think this was resolved, please reopen if not
