### ISSUE TITLE
[Bug]: Typo in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by rrevo** [microsoft/typespec#3419]
### Describe the bug

CONTRIBUTING.md title has a typo. Change `Developper guide` to `Developer guide`

### Reproduction

none

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
Fixed
