### ISSUE TITLE
[Bug]: behavior of generated body model from http operation

### ISSUE THREAD

**Issue by tadelesh** [microsoft/typespec#3421]
### Describe the bug

for this [example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7DQp1c2luZyBIdHRwOw0KDQptb2RlbCBPdXRlciB7DQogIEBoZWFkZXLEC3E6IHN0cmluZzvEDmlubmVyOiBJxAc7DQp9yj7FE9E%2BaM0%2BcHJvcMsRfQ0Kb3AgZm9vKEBxdWVyecpsLCBv5ACNyg%2FMeCk65gCrOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D), we will get two anonymous model for request body and response body. however, for the `inner` property, it keeps the original `Inner` model, instead of replacing it with an anonymous model without metadata properties. it seems the metadata handling is not propagated to inner model. idk if it is a bug or by design. it seems kind of inconsistent.

### Reproduction

compile with given example and see the result of http operation.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
This seems by design. The metadata properties from the `inner` property appear in the operation parameters and the response headers, and the request body must treat 'inner' and 'outer' as properties of the request body.  Can you explain what OpenAPI you would expect in this case?

**Comment by tadelesh** [comment]
OpenAPI result is good. I expect the `type` in  `HttpOperationBody` could also remove the metadata properties for `inner`.
Current `type` for my example:
```
{
  properties: [
    outer: string,
    inner: {
      name: Inner,
      properties: [
        h: string,
        prop: string
      ]
    }
  ]
}
```
Expected:
```
{
  properties: [
    outer: string,
    inner: {
      properties: [
        prop: string
      ]
    }
  ]
}
```

**Comment by markcowl** [comment]
This is by design, the HttpBody contains an indicator that the model may contain metadata types that need to be removed, and you can use the metadata apis to do this.  The idea is to preserve the model that the spec author encoded, because they think these metadata properties are integral to the model (e.g. eTag headers may be crucial to represent with the model).

Note that there is a separate design issue for making a better presentation of the payload on the wire: https://github.com/microsoft/typespec/issues/3012.
