### ISSUE TITLE
Add Mapping of CSharpMethods

### ISSUE THREAD

**Issue by jorgerangel-msft** [microsoft/typespec#3424]
Currently, we express a chain of associated methods as a [CSharpMethodCollection](https://github.com/microsoft/typespec/blob/main/packages/http-client-csharp/generator/Microsoft.Generator.CSharp/src/OutputTypes/CSharpMethodCollection.cs). With the removal of [CSharpMethodKinds](https://github.com/microsoft/typespec/issues/3388), we should remove the method collection and a property within the CSharpMethod class that represents any nested CSharpMethods.

**Comment by m-nash** [comment]
public void Foo(OptionBag bag)

public void FooInternal(int x, int y)

$.bag.X => x
$.bag.Y => y

**Comment by m-nash** [comment]
I don't know if this is still needed.  Closing for now we can reopen if we find it is.
