### ISSUE TITLE
Add tracing to language server

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#3434]
Copied from https://github.com/Azure/typespec-azure-pr/issues/636

We currently only log some low volume things to output window from language server. It would be good to use the tracing feature of LSP to log much more when it's on.

Examples:
- Every file read, whether it was a cache hit or miss, etc.
- Every probe for package.json
- Diagnostics in unopen documents.

**Comment by RodgeFu** [comment]
released PR: https://github.com/microsoft/typespec/pull/3533
