### ISSUE TITLE
[linter]: warning if discriminator is not the 1st property

### ISSUE THREAD

**Issue by archerzz** [microsoft/typespec#3444]
### Clear and concise description of the problem

This is initiated by https://github.com/Azure/autorest.csharp/issues/4439 Although the original issue was rejected due to limited benefits, it inspired us to think it may be a good convention to always write discriminator at the beginning.

## Case 1: Implicit Discriminator

```typescript
@discriminator("kind")
model Foo {
  name: string;
}
```
Implicit is fine, since we can treat it as the 1st property.

## Case 2: Explicit Discriminator Defined on top

```typescript
@discriminator("kind")
model Foo {
  kind: string;
  name: string;
}
```
This is recommended.

## Case 3: Explicit Discriminator Defined not on top

```typescript
@discriminator("kind")
model Foo {
  name: string;
  kind: string;
}
```
Show a warning to move discriminator to the top.

## Other Cases

I'm not sure if we should throw warning for the following cases.
```typescript
@discriminator("kind")
model Foo extends Bar {
  kind: string;
  name: string;
}
```

```typescript
@discriminator("kind")
model Foo {
  Bar...
  kind: string;
  name: string;
}
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
We should not put limitations on emitter serialization based on .Net capabilities
