### ISSUE TITLE
[Bug]: VSCode extension fails to find node or tsp-server in PATH

### ISSUE THREAD

**Issue by JanStevens** [microsoft/typespec#3481]
### Describe the bug

Hi,

I'm using fish shell with [mise](https://mise.jdx.dev/ide-integration.html). When installing the VSCode extension I immediately receive the following error:

```
[Error - 12:53:10] TypeSpec client: couldn't create connection to server.
Launching server using command node failed. Error: spawn node ENOENT
[Error - 12:53:10] TypeSpec server executable was not found: 'node' is not found. Make sure either:
 - TypeSpec is installed locally at the root of this workspace ("/Users/dev/api-oas") or in a parent directory.
 - TypeSpec is installed globally with `npm install -g @typespec/compiler'.
 - TypeSpec server path is configured with https://github.com/microsoft/typespec#installing-vs-code-extension.
```

While opening a terminal (in Fish shell) I can see node and tsp-server correctly resolve
```bash
~> which node
/Users/dev/.local/share/mise/installs/node/20/bin/node

~> which tsp-server
/Users/dev/.local/share/mise/installs/node/20/bin/tsp-server 
```

I don't have this issue with any other vs code extension. I did try to set the `typespec.tsp-server.path` explicitly but it still fails to find `node`

### Reproduction

1. Install fish shell (not sure if relevant)
2. Install [mise](https://mise.jdx.dev/getting-started.html) & setup [shims integration for IDE](https://mise.jdx.dev/ide-integration.html)
4. Install node v20 `mise install node@20`
5. Install globally typespec `npm i -g @typespec/compiler`
6. Install / Open VS Code in a typespec project with the extension installed

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Logic playwright extension uses for finding node instead of just relying on node spawn to work https://github.com/microsoft/playwright-vscode/blob/2eef642e466bd6d216082571f07434a6a7653bcb/src/utils.ts#L144

**Comment by RodgeFu** [comment]
@JanStevens , I tried to prepare the environment with the steps above but can't repro the issue. From the log, it's because the node can't be found properly, could you help to check whether 'node' can be found from vscode properly? or is there any other special things in your env that may cause vscode can't find 'node'? thanks.
![Image](https://github.com/microsoft/typespec/assets/6038235/df45af00-1b07-47b3-ad88-8f8bc6b90e0f)

**Comment by JanStevens** [comment]
@RodgeFu Hi, I noticed that everything works if you start VSCode with `code .` in the typespec directory.

When you then close VSCode and open the project from the VSCode menu it does not work anymore. In the terminal view from VSCode node and typespec are always resolved correctly

**Comment by RodgeFu** [comment]
@JanStevens , do you mean it doesn't work when you start vscode outside shell? could you double check whether you have set the default shell and shims properly? i.e. I can repro the issue when i removed the call to ```#eval "$(mise activate bash --shims)"``` in my ~/.profile for my bash, which I think is because the mise shims directory is not added to PATH properly, then vscode extension can't find the node. thanks.

**Comment by RodgeFu** [comment]
Close as this looks like an environment issue. Feel free to reopen if you get more insights about the repro env. thanks.

**Comment by pdecat** [comment]
Apparently, this sort of `ENOENT` errors can happen if a folder in the workspace does not exist any longer on the filesystem.

See https://github.com/golang/vscode-go/issues/774#issuecomment-719631412
