### ISSUE TITLE
`Expression` and `Statement` conversion

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#3499]
We have some expressions and statements which are essentially the same thing, for example:
`InvokeInstanceMethodExpression` vs `InvokeInstanceMethodStatement`
They are the same thing except when it comes to a statement, we have a `;`.

We might need to find a way to represent this situation and make some simplification maybe.

**Comment by m-nash** [comment]
@ArcturusZhang  Can you provide some options that you think we should consider?

**Comment by ArcturusZhang** [comment]
Also found here: https://github.com/microsoft/typespec/pull/3581#discussion_r1639289684

**Comment by ArcturusZhang** [comment]
So the first solution I could think of is that, for every case that could be both an expression and a statement, for instance, invoke a method, throw an exception, we create two identical types for them, and create implicit cast between them, such as:
```csharp
public class ThrowExpression : ValueExpression
{
	public ValueExpression Expression {get;} // represent the thing we want to throw
	public override void Write(CodeWriter writer)
	{
		writer.AppendRaw("throw ");
		Expression.Write(writer);
	}
	public static implicit operator ThrowStatement(ThrowExpression expression) => new(expression.Expression);
}

public class ThrowStatement : MethodStatement
{
	public ValueExpression Expression {get;} // represent the thing we want to throw
	public override void Write(CodeWriter writer)
	{
		writer.AppendRaw("throw ");
		Expression.Write(writer);
		writer.WriteLineRaw(";");
	}

	public static implicit operator ThrowExpression(ThrowStatement statement) => new(statement.Expression);
}
```

the other way is that we introduce a generic statement wrapper for those kind of expressions, such as:
```csharp
public class ExpressionStatement : MethodBodyStatement
{
	public ValueExpression Inner {get;}
	
	public ExpressionStatement(ValueExpression expression)
	{
		Inner = expression;
	}

	public override void Write(CodeWriter writer)
	{
		Inner.Write(writer);
		writer.WriteLineRaw(";");
	}
}
```
In this way, a lot of statement could be removed and I think this might be more intrinsic because in dotnet, I believe, statement is a special kind of expression - when we type something in the immediate window, `var a = 1;` it gives you the message: "expression evaluated with no return value" which indicates that statements are expressions.

But I think not everything could be a statement, for example, `ArrayElementExpression` - `array[0]` cannot be a statement, therefore we could do better that the above ExpressionStatement could be generic:
```csharp
public class ExpressionStatement<T> : MethodBodyStatement where T : ValueExpression, IStatementExpression // ignore the name, the point is that we could use an interface to be the constraint
{
	public T Inner {get;}
	public ExpressionStatement(T expression)
	{
		Inner = expression;
	}

	public override void Write(CodeWriter writer)
	{
		Inner.Write(writer);
		writer.WriteLineRaw(";");
	}

	public implicit operator ExpressionStatement<T>(T expression) => new(expression);
}
```
Maybe the interface does not have to have a method inside it, it is just a flag, flagging whether this expression is possible to be a statement as an intrinsic attribute of that expression.
