### ISSUE TITLE
Digitally sign `tsp.ps1`

### ISSUE THREAD

**Issue by archerzz** [microsoft/typespec#3512]
### Clear and concise description of the problem

I met the following error when trying to install vs code plugin for typespec.
```
PS C:\Users\xxx> tsp code install
tsp : File C:\Users\xxx\AppData\Roaming\npm\tsp.ps1 cannot be loaded. The file
C:\Users\xxx\AppData\Roaming\npm\tsp.ps1 is not digitally signed. You cannot run this script on the current
system. For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ tsp code install
+ ~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

It would be better if we could digitally sign `tsp.ps1`. Otherwise, customers have to downgrade the execution policy.

---

My local execution policy is set to `AllSigned` by default.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
This is not created by us, where did you get this ps1 file?

**Comment by bterlson** [comment]
This is likely the PS1 wrapper generated by npm on windows and placed in the bin folder. I don't think we can do anything to sign it.

**Comment by timotheeguerin** [comment]
Issue from npm https://github.com/npm/cli/issues/470 about this

**Comment by archerzz** [comment]
> This is likely the PS1 wrapper generated by npm on windows and placed in the bin folder. I don't think we can do anything to sign it.

Thanks. Per conclusion of solutions [here](https://github.com/npm/cli/issues/470#issuecomment-847009819), looks like we need to add a doc to let users delete the `tsp.ps1`?

**Comment by timotheeguerin** [comment]
I don't think so, the conclusion is to loosen the script execution policy or use npx. And not sure this is really for us to show the docs on this

**Comment by archerzz** [comment]
close since there is no easy solution for that
