### ISSUE TITLE
[Bug][http] can't declare requiredness for meta properties about  file part of multipart

### ISSUE THREAD

**Issue by msyyc** [microsoft/typespec#3532]
According to https://github.com/microsoft/typespec/issues/3046, `httpFile` could be used to change the requiredness of the optional metadata properties

![image](https://github.com/microsoft/typespec/assets/70930885/0f9432cc-6fd0-4862-a410-48668d3f1498)

However, when I try the following code, I find the type is Scalar bytes which contains no info about "contentType"/"filename" is required for this file part.
```
  it("test", async () => {
    const op = await getHttpOp(`

    @Private.httpFile
    model RequiredFileMetadata {
      contentType: string;
      filename: string;
      contents: bytes;
    }
      op read(
        @header contentType: "multipart/mixed",
        @multipartBody body: [
          HttpPart<RequiredFileMetadata, #{ name: "file" }>
        ]): void;
    `);

    const body = op.parameters.body;
    strictEqual(body?.bodyKind, "multipart");
  });
```
![image](https://github.com/microsoft/typespec/assets/70930885/ce77618c-36c2-4931-af4c-90e66369e1c8)

**Comment by timotheeguerin** [comment]
hhm yeah seems like I didn't handle `HttpFile` completely
