### ISSUE TITLE
[Bug]: Protobuf emitter incorrect rpc request type

### ISSUE THREAD

**Issue by RobertVillalba** [microsoft/typespec#3534]
### Describe the bug

The protobuf emitter drops the package prefix from the request type for services that use an imported model as the args.

### Reproduction

https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvcHJvdG9idWYiOw0KDQp1c2luZyBUeXBlU3BlYy5Qxx3FHEBwYWNrYWdlKHsNCiAgbmFtZTogIm15c2hhcmVkIiwNCn0pDQrEF3NwYWNlIE15U8UaIMUvbW9kZWwgRHVtbXnGESAgQGZpZWxkKDEpIHg6IHN0cmluZzvEGn0NCn3ccGVydmljZdVxxhvGYUDoAL0uxzLEFWludGVyZs0uc8YvICBlY2hvKC4uLugAuS7lAK4pOukAysYR6wCk&e=%40typespec%2Fprotobuf&options=%7B%7D

```
service MyServices {
  rpc Echo(Dummy) returns (myshared.Dummy);
}
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by witemple-msft** [comment]
Thanks for pointing this out. A bit of missing logic in the emitter was causing the parameters to be considered a local model rather than an external model. The following PR addresses this issue: https://github.com/microsoft/typespec/pull/3561
