### ISSUE TITLE
Generate ModelSerializationExtensions Type

### ISSUE THREAD

**Issue by jorgerangel-msft** [microsoft/typespec#3536]
Generate the internal ModelSerializationExtensions type like [this](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/UnbrandedProjects/Unbranded-TypeSpec/src/Generated/Internal/ModelSerializationExtensions.cs).
You can refer to the implementation from autorest.csharp: [ModelSerializationExtensionsProvider.cs](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Models/Types/HelperTypeProviders/ModelSerializationExtensionsProvider.cs)

**Comment by m-nash** [comment]
Break out this class so its no longer nested along with this change https://github.com/Azure/autorest.csharp/blob/feature/v3/test/UnbrandedProjects/Unbranded-TypeSpec/src/Generated/Internal/ModelSerializationExtensions.cs#L252

**Comment by ArcturusZhang** [comment]
Created another issue to generate `TypeFormatters`. We should do that first because ModelSerializationExtensions is using it.
