### ISSUE TITLE
Model extends another allow property to become optional

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#3539]
```tsp
 model Base {
  s: string;
}

model Foo extends Base {
  s?: string;
}
```

[Playground Link](https://typespec.io/playground?c=IG1vZGVsIEJhc2UgewogIHM6IHN0cmluZzsKfQoKxh1Gb28gZXh0ZW5kc8spP8sq&e=%40typespec%2Fopenapi3&options=%7B%7D)

The same thing with template constrain fail which was fixed last sprint but seem like this case remain https://github.com/microsoft/typespec/pull/3290
[Playground](https://typespec.io/playground?c=IG1vZGVsIEJhc2UgewogIHM6IHN0cmluZzsKfQoKxh1Gb2%2FGHD%2FKHSAgdNMqQmFyPFQgZXh0ZW5kc8VVPiB7fQoKCmFsaWFzIEEgPcUjRm9vPjs%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by markcowl** [comment]
P2
