### ISSUE TITLE
[Bug]: Extends accept redefinition or properties as optional

### ISSUE THREAD

**Issue by lmazuel** [microsoft/typespec#3540]
### Describe the bug

Using extends between two models, if we redefine the same property from required to optional, this compiles fine

### Reproduction

```typescript
 model Base {
  s: string;
}

model Foo extends Base {
  s?: string;
  t: string;
}
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
dup of #3539
