### ISSUE TITLE
The `OutputLibrary` should include everything that we are outputting

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#3546]
Now the `OutputLibrary` is implemented in a way that it is listing the enums, models and clients, which are not everything we are outputting.
For instance, it is missing the "helpers" like `Argument.cs` or `Optional.cs`.

And our CSharpGen is calling those individually in a certain sequence, which is not open to extend.

I think the `OutputLibrary` should not be categorizing the outputs, it should just know what it is outputting and leave the problem of "how this thing should be organized" to the plugin to decide.

**Comment by m-nash** [comment]
OutputLibrary should most likely have one public getter which is of type IReadOnlyList<TypeProvider>.  All models / enums / helpers / clients / etc will be returned here since the consumer of the output library doesn't need to know what kind of TypeProvider it is.
