### ISSUE TITLE
[Bug]: Protobuf emitter incorrect map value type

### ISSUE THREAD

**Issue by RobertVillalba** [microsoft/typespec#3556]
### Describe the bug

The protobuf emitter drops the package prefix from the map value type for maps that use an imported model as the value.
```
message MyLocal {
  map<string, Dummy> m = 1;
}

service MyServices {
  rpc Echo(MyLocal) returns (myshared.Dummy);
}
```

### Reproduction

https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvcHJvdG9idWYiOw0KDQp1c2luZyBUeXBlU3BlYy5Qxx3FHEBwYWNrYWdlKHsNCiAgbmFtZTogIm15c2hhcmVkIiwNCn0pDQrEF3NwYWNlIE15U8UaIMUvbW9kZWwgRHVtbXnGESAgQGZpZWxkKDEpIHg6IHN0cmluZzvEGn0NCn3ccGVydmljZdVxxhvMck15TG9jYWzSdG06IE1hcDzGeCzpAK4u5QCjPucAiMQHQOgBBS7HesQVaW50ZXJmzXZzyGRlY2hvKC4uLsd7KTrPXesA5Q%3D%3D&e=%40typespec%2Fprotobuf&options=%7B%7D

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by witemple-msft** [comment]
Thank you for reporting this issue. The same logic that applies to return types and property types for resolving cross-package references was missed in the calculation of map value types. The following PR will resolve this issue: https://github.com/microsoft/typespec/pull/3561
