### ISSUE TITLE
Formatting Boolean properties that have the default value of `false`

### ISSUE THREAD

**Issue by ytimocin** [microsoft/typespec#3565]
### Clear and concise description of the problem

This is not a problem but maybe a slight addition to the compiler. We can warn for Boolean properties that have the default value of false during a `format check` command. Similarly, `format` command can remove the setting of false of Boolean properties.

Ex:

```
@doc("Example test Boolean property")
testBoolProp?: boolean = false;
```

1. `tsp format --check "**/*.tsp"` should suggest removing default value of false for Boolean properties.
2. `tsp format **/*.tsp` should remove default value of false for Boolean properties.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
Formatter is only doing some syntax formatting and shouldn't be removing things that are not necessarily equivalent. There is also no prompt that would allow the user to confirm that.

However a good candidate for that is a linter rule and a codefix for it. This is something you can also write up yourself for now with your own linter/diagnostics and provide the codefix for it.

**Comment by bterlson** [comment]
I am not sure how much we can do in this case. If the property is required, the argument could be made that `false` is the only reasonable default, so you could probably remove it. But for an optional property, who is to say that the property being absent and being present but set to false mean the same thing? For json merge patch for example, they are different.
