### ISSUE TITLE
Why do we have both a description and a summary on a method signature

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#3579]
I don't think we need both of these but lets investigate and if they are the same thing lets delete one.

**Comment by simonthum** [comment]
OpenAPI has [title], summary, description. Json Schema has name, title, description. In a similar internal project I kept both, which I think was broadly useful.

Just my 2c, I am quite interested in this whole effort.

**Comment by m-nash** [comment]
Specifically referring to the dotnet representation of a MethodSignature after we have converted the tsp into client code model for generating an SDK from it.  In this case there doesn't seem to be a difference between a summary and a description.

```c#
/// <summary> This is my description of the method </summary>
public void Method() { }
```

I think that if we want to all for other xml doc sections we should put them into the XmlDocProvider as a `remarks` or `seealso` etc.
