### ISSUE TITLE
support decorating template properties

### ISSUE THREAD

**Issue by archerzz** [microsoft/typespec#3582]
### Clear and concise description of the problem

This is derived from discussion in https://github.com/Azure/typespec-azure/issues/959

User scenario is that the service has several models derived from a template `Azure.ResourceManager.ProxyResource<T>`:
```typescript
model Addon is ProxyResource<AddonProperties>
...
model VirtualMachine is ProxyResource<VirtualMachineProperties>
...
```

`ProxyResource<T>` has a property named `properties: T` which the user wants to flatten for all those models. So they defined the following customization (https://github.com/Azure/azure-rest-api-specs/blob/1418642cf8a57954c781c26c759fd4aef39a1287/specification/vmware/Microsoft.AVS/client.tsp#L19):
```typescript
@@flattenProperty(Azure.ResourceManager.ProxyResource.properties);
```
which unfortunately doesn't work.

If we allow decorating template properties, that would bring some benefits like people can batch decorate a group of models.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
@archerzz can you describe a little more and give a repro, this works fine with other decorators 
[playground](https://typespec.io/playground?c=bW9kZWwgUHJveHlSZXNvdXJjZTxUPiB7CiAgcHJvcGVydGllczogVDsKfQoKxi1NecgvCiAgaXPPPcQ6ICBuYW1lOiBzdHJpbmc7CiAgfT47CgpAQGRvYyjNLy7KZSwgIkFiYyIpOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

note that doing that update the template declaration so every use of it will have it applied
