### ISSUE TITLE
[Bug]: model extends `Array<T>` does not inherit the indexer

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#3597]
### Describe the bug

```typespec
model MyArray extends Array<int32> {}
```
The model `MyArray` does not inherit the `indexer` from `Array<T>`.

BTW when I write `model T extends int32[] {}` I get a compilation error but I could do `model T is int32[] {}` therefore I think  this might also be problematic.

### Reproduction

Check the type graph [here](https://typespec.io/playground?c=bW9kZWwgQSBleHRlbmRzIEFycmF5PGludDMyPiB7fQ0KDQovLyDHJsonxSFbXccixh9CIGnVQMcexR%2FKOA%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
@bterlson Please find duplicate bug

**Comment by markcowl** [comment]
@ArcturusZhang the first part of this (that in `model MyArray extends Array<int32>` MyArray does not have the indexer of its ancestor type) is by design

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang the first part of this (that in `model MyArray extends Array<int32>` MyArray does not have the indexer of its ancestor type) is by design

May I know why and how this could benefit?
When we inherit from Record, the indexer could be inherited from the Record, therefore I notice there is an inconsistency

**Comment by ArcturusZhang** [comment]
Because i do not know what kind of "by design" is this - if this is because of some difficulties on implementation, I would rather prefer we disallow the usage of `model Foo extends Array<T>{}` because we never allow a new property to be added to an array, and `model Foo is Array<T>;` already could do everything we are allowing.
What would it break if we just disallow the usage of `extends Array<T>`?

**Comment by timotheeguerin** [comment]
There is no difference with Record, if there is it’s Tcgc doing it. Extends define the relation between the 2 models it does not copy any info down by design. If you where to write this as inheritance in your language the base model is not the array or record type it extends it.
