### ISSUE TITLE
The compiler is added as dependency instead of peer dependency

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#3632]
### Discussed in https://github.com/microsoft/typespec/discussions/3625

<div type='discussions-op-text'>

<sup>Originally posted by **bdm-k** June 20, 2024</sup>
When you create a TypeSpec emitter with the template, `@typespec/compiler` is added as a dependency instead of a peer dependency. However, according to the [document](https://typespec.io/docs/extending-typespec/basics#step-3-defining-dependencies), you should

> Use `peerDependencies` for all TypeSpec libraries (and the compiler) that you use in your own library or emitter.

Is this intended behavior or not?

### How to reproduce

1. Install `@typespec/compiler@0.57.0`
2. Run `tsp init --template emitter-ts`

In the generated "package.json", `@typespec/compiler` is added as a dependency.</div>

**Comment by sarangan12** [comment]
@markcowl @bterlson  The PR has been merged for this issue. So, I believe this task can be closed.
