### ISSUE TITLE
[Bug]: Unable to override HTTP method from operation template

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#3636]
### Describe the bug

If I have an operation template that has a default http method (e.g. `GET`) but I want to override it in the actual instantiation, the typespec/http library will error. Since it is an error, I can't suppress it. 

We should instead a) emit a warning and b) let the "outermost" application "win". 

### Reproduction

[playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CkBIdHRwLnBvc3QgxgtnZXQgb3AgZXhhbXBsZSgpOiB2b2lkOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
- continue an error diagnostic for two *different* http verb decorators on the same node
- otherwise, allow the outermost decorator to override
