### ISSUE TITLE
[http][multipart] missing expected name of HttpPart

### ISSUE THREAD

**Issue by msyyc** [microsoft/typespec#3644]
According to https://github.com/microsoft/typespec/issues/3046:
![image](https://github.com/microsoft/typespec/assets/70930885/02f4e48a-6b6a-49f2-9227-9bbb5caeec3d)
I expect the "name" of this part shall be "image", however, for the similar scenario :
https://github.com/microsoft/typespec/blob/9d48ad1a56bb398283f94093a005d58d3d27f51f/packages/http/test/multipart.test.ts#L133-L154
current http parse it into "undefined" instead of "nested":
![image](https://github.com/microsoft/typespec/assets/70930885/e7a1a1a4-8cad-4327-8761-8d971825aa8d)

**Comment by markcowl** [comment]
@bterlson please investigate

**Comment by timotheeguerin** [comment]
we cut that from the design as it was a bit far fetched.
