### ISSUE TITLE
Move ToSerial and ToEnum to SerializationProviders from EnumProvider class

### ISSUE THREAD

**Issue by nisha-bhatia** [microsoft/typespec#3651]
Currently ToSerial and ToEnum are on the EnumProvider class. They do not belong here -  as they are currently used for serialization. If we move To{Type.Name} to SerializationProviders we can ensure that the method will always have an implementation (in case the enum is overriden and doesn't have a ToName method).

Addresses this comment: https://github.com/microsoft/typespec/pull/3621#discussion_r1651524779

**Comment by ArcturusZhang** [comment]
So I think we have a contradiction with the comment here if make the suggested change here: https://github.com/microsoft/typespec/pull/3642#discussion_r1651718517

**Comment by nisha-bhatia** [comment]
https://github.com/microsoft/typespec/issues/4018
