### ISSUE TITLE
Consolidate `CodeWriterDeclaration` with expression system

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#3653]
`CodeWriterDeclaration` requires to be declared first to have a usable name to be used as an identifier.

This mechanism does not work quite fine with our expression system because our expressions have clear syntax meaning, such as [this](https://github.com/microsoft/typespec/pull/3641/files#diff-ac2c5756b50c15cb2c9a7d8a64cc7baad8474c15ea240e4dcb56abffb9431f96) refers a variable reference, which should have been declared

**Comment by m-nash** [comment]
Resolved by https://github.com/microsoft/typespec/pull/3641
