### ISSUE TITLE
Discuss how to retrieve a Concrete Provider's Type

### ISSUE THREAD

**Issue by jorgerangel-msft** [microsoft/typespec#3660]
Now that the singleton pattern was [removed](https://github.com/microsoft/typespec/blob/main/packages/http-client-csharp/generator/Microsoft.Generator.CSharp/src/OutputTypes/OutputLibrary.cs#L67) from the concrete providers (ArgumentProvider, ChangeTrackingList, etc), we have to instantiate these providers more than once to retrieve the `Type`. We should discuss how many of these instances should be allowed to exist in a single library, and if there's a better alternative to retrieving their type while constructing their typed snippets. Example snippet: [here](https://github.com/microsoft/typespec/blob/main/packages/http-client-csharp/generator/Microsoft.Generator.CSharp/src/TypedSnippets/ArgumentSnippet.cs)

**Comment by m-nash** [comment]
Solved with `TypeReferenceExpression.GetTypeFromDefinition(...)`
