### ISSUE TITLE
Allow different description per status code

### ISSUE THREAD

**Issue by stefan-schweiger** [microsoft/typespec#3664]
### Clear and concise description of the problem

Currently when you use `@errosDoc` the doc comment will get applied to all errors with OpenApi.

```
@error
model ValidationError {
  @statusCode _: 400;
  message: string;
}

@error
model TechnicalError {
  @statusCode _: 500;
  message: string;
}

@route("/widgets")
@tag("Widgets")
interface Widgets {
  @errorsDoc("This will describe both errors") @get list(): Widget[] | ValidationError | TechnicalError;
}
```

```yml
paths:
  /widgets:
    get:
      tags:
        - Widgets
      operationId: Widgets_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Widget'
        '400':
          description: This will describe both errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: This will describe both errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TechnicalError'
```

Ideally it would be possible to have a description per possible error response. With my limited knowledge of what is possible with decorators I think it would probably need to look something like this:

```
@error
model TechnicalError {
  @statusCode("This is a Technical Error") _: 500;
  message: string;
}

// or

@error
model TechnicalError {
  @doc("This is a Technical Error")
  @statusCode _: 500;
  message: string;
}

// or

@error
model TechnicalError {
  @statusCode
  @statusCodeDescription("This is a Technical Error")
  _: 500;
  message: string;
}
```

Which would produce the following output:
```
'500':
  description: This is a Technical Error
  content:
    application/json:
      schema:
        $ref: '#/components/schemas/TechnicalError'
```

As far as I can tell in some older versions of typespec it was possible to use the `@doc` decorator to set this description, but now it will only add it to the schema but not directly below the status code.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by stefan-schweiger** [comment]
After playing around a bit more with thinks I actually think this might be a bug or at least an unconsidered edge case. If your error response does not have a body then the description is put to the correct place. But if you add something to the body the description will be placed on the schema.

[Reproduction](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQGRvYygiUGV0IENyZWF0ZWQiKSBtb2RlbCBQZXTHEyB7CiAgQHN0YXR1c0NvZGUgY29kZTogMjAxOwp9CgpAZXJyb3LHSlZhbGlkYXRpb25FxBYiKQrGTs8Y11M0MDA7CiAgbWVzc2FnZTogc3RyaW5nzGbGTlRlY2huaWNhbNZNXzogNcRKfQoKb3AgY%2BYAxigpOuwA1HzxAJN8z1c7&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by dfioravanti** [comment]
> After playing around a bit more with thinks I actually think this might be a bug or at least an unconsidered edge case. If your error response does not have a body then the description is put to the correct place. But if you add something to the body the description will be placed on the schema and some "default" description will be used.

I observed the same behavior, I would really like to have the ability to add a description to the response. Is this a bug or expected behavior?

**Comment by timotheeguerin** [comment]
So this is kinda an expected behavior that we've had for a long time [Cases](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKLyoqIE9uZSBkb2MgKi8KbW9kZWzFEXsKICBAc3RhdHVzQ29kZSBfOiAyMDA7Cn3GNFR3b840xBHVNDE7CiAgaW1wbGljaXTPRWhyZc97xhPVSTLESUBib2R5IGV4yk80xU9vcCBjcmVhdGVkKCk65QDBfOUAk3zGUjsK&e=%40typespec%2Fopenapi3&options=%7B%7D)

Basically the logic is that we only use the doc if the response model is an envelope(Has explicit body or no body). If you were to return the logic model directly then we don't include it. This so you don't have the doc carry over in those cases

```
/** This is a detailed doc on what is a pet */
model Pet {}
op read(): Pet;
```

**Comment by dfioravanti** [comment]
@timotheeguerin thanks for the explanation. As a first time user of typespec to me

> You are also not the first person to try to put doc on the statusCode property expecting that to document the response so that also could be a possibility.

would feel the most natural way to do it. Everything else is documented in this way, so why not routes? Maybe it is technically really challenging, I am just pointing out what makes the most sense to me

**Comment by timotheeguerin** [comment]
I don't think it's really hard to figure out in the code only tricky part is deciding which description wins if provided in various place s

**Comment by markcowl** [comment]
- fix the issue in which docs for an  implicit body response is not recognized.

**Comment by timotheeguerin** [comment]
PR https://github.com/microsoft/typespec/pull/4322 fixes the case 2 mentioned above. If you think we also should consider the description on the statusCode property to be moved there can you file a new issue

**Comment by stefan-schweiger** [comment]
@timotheeguerin can you give me an example of the input and the output of this PR?

**Comment by timotheeguerin** [comment]
[Before playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKLyoqIE9uZSBkb2MgKi8KbW9kZWzFEXsKICBAc3RhdHVzQ29kZSBfOiAyMDA7Cn3GNFR3b840xBHVNDE7CiAgaW1wbGljaXTPRWhyZc97xhPVSTLESUBib2R5IGV4yk80xU9vcCBjcmVhdGVkKCk65QDBfOUAk3zGUjsK&e=%40typespec%2Fopenapi3&options=%7B%7D)  ➡️ [PR preview](https://cadlplayground.z22.web.core.windows.net/prs/4322/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKLyoqIE9uZSBkb2MgKi8KbW9kZWzFEXsKICBAc3RhdHVzQ29kZSBfOiAyMDA7Cn3GNFR3b840xBHVNDE7CiAgaW1wbGljaXTPRWhyZc97xhPVSTLESUBib2R5IGV4yk80xU9vcCBjcmVhdGVkKCk65QDBfOUAk3zGUjsK&e=%40typespec%2Fopenapi3&options=%7B%7D)

For the following code
```tsp
import "@typespec/http";

using TypeSpec.Http;

/** One doc */
model One {
  @statusCode _: 200;
}

/** Two doc */
model Two {
  @statusCode _: 201;
  implicit: 200;
}

/** Three doc */
model Three {
  @statusCode _: 202;
  @body explicit: 204;
}

op created(): One | Two | Three;
```

Before case 2 wouldn't respect the doc but this pr makes it that it does.

**Comment by stefan-schweiger** [comment]
@timotheeguerin well it respects the doc, but it only puts it the schema, I would still argue that there needs to be a way to influence the docs for the response code endpoint itself.

<img width="965" alt="image" src="https://github.com/user-attachments/assets/8363c6c0-84e5-4898-b11b-272916bec630">

Is something like this possible?

```
model Two {
  /** Two doc */
  @statusCode _: 201;
  implicit: 200;
}
```

**Comment by timotheeguerin** [comment]
Was that looking at the `Before playground`? with the pr one this updates the 201 description 
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/3a17066d-8962-4138-8224-05bc7890f113">

**Comment by stefan-schweiger** [comment]
@timotheeguerin sorry my bad I must have gotten the playgrounds confused, because the PR playground is only showing me a blank page :( but if that's the actual output then I'm happy
