### ISSUE TITLE
Add Response abstraction

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#3693]
We will need an abstraction for a response from a client service call in order to be able to replace this via plugins.

Methods that need to be provided include (not exhaustive)

- Type
- GetRawResponse
- IsError
- Buffering
- Failure exception
- derived types such as
  - ErrorResponse
  - NullableResponse

**Comment by ArcturusZhang** [comment]
So I think maybe this could be done in
```csharp
public abstract class ClientResponse
{
	public CSharpType Type {get;}
	public CSharpType ExceptionType {get;}
	public CSharpType ErrorVariantType {get;}
	public CSharpType NullableVariantType {get;}
}

public static class ClientResponseSnippets
{
	public ValueExpression GetRawResponse(this ScopeApi<ClientResponse> response) {}
	// etc
}
```
