### ISSUE TITLE
Add UriBuilder abstraction

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#3695]
We will need an abstraction for UriBuilder apis

This abstraction should include things like

- Append path params
- Append query params
- set base

**Comment by JoshLove-msft** [comment]
@live1206 is this part of your initial work on the Azure plugin? Or is this something that will come later?

**Comment by live1206** [comment]
We are using an existing type [RawRequestUriBuilder](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/RawRequestUriBuilder.cs) from `Azure.Core` shared code in Azure plugin.
Details can be found in https://github.com/Azure/azure-sdk-for-net/pull/47259
