### ISSUE TITLE
Cannot name a decorator `flags` `lib` `linter` or `onEmit` (special exports)

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#3719]
## Problem
Cannot name a decorator `flags` `lib` `linter` or `onEmit` (special exports)
Due to how to use certain reserved name in JS we cannot name a decorator with those names

## Add a new `$decorators` export

```ts
export const $decorators = {
  Azure.Core: {
    flags: $flags,
    "foo-bar": fooBarDecorator
  }
}

```

we can additionally provide a typed helper

```ts
function defineDecorators(decorators: Record<string, Record<string, DecoratorFunction>>) {
   return decorators;
}
```

```ts
export const $decorators = defineDecorators({
  Azure.Core: {
    flags: $flags,
    "foo-bar": fooBarDecorator
  }
})
```

## Additional items
- Update docs to recommend this approach
- Update tspd to only support this new approach. This isn't breaking as tspd is not published yet.

**Comment by timotheeguerin** [comment]
## Option 1: USe `$$` for known configs

This would reserve `$` for decorators. For back compat we would still check if the `$` variant of `$lib`, `$flags`, etc. is a config object and use that instead.

## Option 2: Dedicated `$decorators` export

this allows to exports all decorators

**Comment by markcowl** [comment]
- Need to triage for scheduled changes

**Comment by markcowl** [comment]
est: 5
