### ISSUE TITLE
Design property override in the inheritance context

### ISSUE THREAD

**Issue by pshao25** [microsoft/typespec#3797]
TypeSpec allows property change of optionality and type.

**Case 1: optionality widen**
(Seems this case is not allowed in the future https://github.com/microsoft/typespec/pull/3659.)
```
model Base {
  a: string;
}
model Derived extends Base {
  a?: string;
}
```

**Case 2: optionality narrow down**
```
model Base {
  a?: string;
}
model Derived extends Base {
  a: string;
}
```

**Case 3: type narrow down**
```
model Base {
  a: string | int32;
}
model Derived extends Base {
  a: string;
}
```

**Problem description:**
C# doesn't allow same property name with different type in base model and derived model. A compromise is we add `new` key to the property in the derived class.

We could simply reject such case or design this in MGC. If we are going to design, we should consider:
1. How to do the serialization for this property in both models.
2. How to do casting between these two models (if we go with "add `new` solution").
- widen: how to do this `Base b = new Derived(){A = 1}; Console.WriteLine(b.A);` to write out `1`
- narrow down: `base` has set a wider value, how to cast to narrower type in `derived`

**Comment by JoshLove-msft** [comment]
This was discussed in .NET team meeting. 
The decision was that when you narrow in the derived class, we will `override`. If you are just changing the description and not the signature, then we will `new`. But this may already be working like this. This can likely be closed once we find the fix PR.

**Comment by JoshLove-msft** [comment]
Implemented in https://github.com/microsoft/typespec/pull/4325
