### ISSUE TITLE
Allow to pass formatting arguments to the $summary decorator

### ISSUE THREAD

**Issue by alexocode** [microsoft/typespec#3818]
The `summary` decorator does not allow to pass a formatting argument like `doc` or `friendlyName` do.

Interestingly enough the [actual code](https://github.com/microsoft/typespec/blob/f84dbe81e1936e174a71142d2ef2c14ec3a26a96/packages/compiler/src/lib/decorators.ts#L126-L137) allows to pass `formatArgs` but [that is not declared in the typespec defintion](https://github.com/microsoft/typespec/blob/f84dbe81e1936e174a71142d2ef2c14ec3a26a96/packages/compiler/lib/std/decorators.tsp#L7-L17).

Allowing `summary` to receive `formatArgs` would allow code like the following:

```
@doc("Unique ID for a {name}", M)
@summary("ID<{name}>", M)
scalar ID<M extends {}> extends string;
```

Which then includes the summary for example in the OpenAPI3 specs which get rendered nicely like this:
![image](https://github.com/microsoft/typespec/assets/144562412/40647f16-6f16-4087-8e93-fd61ea960764)

### Alternative

I presume the alternative to exposing the `formatArgs` of `summary` would be the introduction of a meta `name` property on types, because then the existing string interpolation would be more than sufficient. I think I do remember a discussion to deprecate the `formatArgs` of `doc` and other decorators for similar reasons.

```
@doc("Unique ID for a ${M::name}")
@summary("ID<${M::name}>")
scalar ID<M extends {}> extends string;
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
We have been trying to move away from that parameter in `@doc` as it is kinda broken and only solve this very specific scenario of internpolating the name instead of a key value pair one would often epect.

The goal is to support that directly via interpolation like

```
@summary("Some ${T::name}")
```
