### ISSUE TITLE
explore compiler defaulting host parameters from literals to strings with the literal value as a default

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/typespec#3821]
### Clear and concise description of the problem

There's continued discussion over whether host parameters should be generated as literal values, when guidelines say that host is something that can always be overridden. We don't want to make users explicitly define host as a value with a default every time, but emitters would like the . TCGC is going to special-case host params to be strings with default values (issue [here](https://github.com/Azure/typespec-azure/issues/217)), this issue is to eventually explore having the compiler do this instead of tcgc, which would be preferable if this is something that we want to provide to all emitters and emitter authors.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
Needs more info on what do you actually expect. And in scenarios like that what would you even want
[Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZcYJZXIoIsQvczovL2FwaS5naXRodWIuY29tIiwgIk1haW4gxhMgYXBpIinSNXtlbnRycHJpc2V9LtJBRcgdzEYsIMo1OiBzdHJpbmd9KQpuYW1lc3BhY2UgRGVtb1PmAKY7Cgo%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)
- When a server already parameterized
- When multiple server
- When multiple server including one parameterized and some not
- When multiple server all parameterized differently

**Comment by weidongxu-microsoft** [comment]
I assume here the "guidelines" is Azure guideline.

However, would TCGC behave differently, if e.g flavor=generic ?

**Comment by timotheeguerin** [comment]
I think if anything people 3rd party are way more likely to want to always have the baseUrl overridable.
