### ISSUE TITLE
Support spread of aliases and models

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#3831]
Support the generation for typespec such as:
```typespec
op foo(...Bar): void;
```
Currently our generator here just ignores the body, even if `Bar` is a body parameter.

I notice this issue when I synced the spread behavior changes here (that we spread the models as well)

**Comment by m-nash** [comment]
@ArcturusZhang  can we get more context on what this issue is coverting

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang can we get more context on what this issue is coverting

I updated something in the description.
