### ISSUE TITLE
Update emitter to set extensions at the root of the document

### ISSUE THREAD

**Issue by MaggieKimani1** [microsoft/typespec#3837]
### Clear and concise description of the problem

This feature request proposes adding extensions defined on a `Namespace` at the root of an OpenApi document.
#### Typespec sample:

[Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvb3BlbmFwaSI7CgpAc2VydmljZQpAT3BlbkFQSS5leHRlbnNpb24oIngtY3VzdG9tIiwgImZvbyIpCm5hbWVzcGFjZSBTdW5vIHsKCn0K&e=%40typespec%2Fopenapi3&options=%7B%7D) 

```typescript
@service
@route("/createSong")
@extension("x-custom", "foo")
namespace Suno {
  
}
```

#### Result:
```yaml
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components: {}
```

#### Expectation:

```yaml
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components: {}
x-custom: foo
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
est: 3
