### ISSUE TITLE
HTTP Verb *OPTIONS* decorator is missing

### ISSUE THREAD

**Issue by Y-Sindo** [microsoft/typespec#3847]
### Clear and concise description of the problem

I cannot find HTTP Verb *OPTIONS* decorator. How do I describe an OPTIONS HTTP request?

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
@markcowl find existing issue

**Comment by markcowl** [comment]
closing in favor of https://github.com/microsoft/typespec/issues/2866
