### ISSUE TITLE
[Bug]: Specs can fail to load examples when compiled from outside spec folder

### ISSUE THREAD

**Issue by mikeharder** [microsoft/typespec#3850]
### Describe the bug

Specs can fail to load examples when compiled from outside the spec folder (e.g. `tsp compile path/to/spec`), but succeed when compiled from inside the spec folder (e.g. `cd path/to/spec; tsp compile .`).

Related: https://github.com/microsoft/typespec/issues/2241, https://github.com/Azure/typespec-azure-pr/issues/3182

### Reproduction

```
$ gh repo clone azure/azure-rest-api-specs
$ cd azure-rest-api-specs
$ npm ci

$ npx tsp compile specification/oracle/Oracle.Database.Management
warning @azure-tools/typespec-autorest/example-loading: Skipping example loading from examples/2023-09-01-preview because there was an error reading the directory.

$ cd specification/oracle/Oracle.Database.Management
$ npx tsp compile .
<no warning>
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Moved to typespec-azure repo https://github.com/microsoft/typespec/issues/3850

**Comment by mikeharder** [comment]
Actually moved to https://github.com/Azure/typespec-azure/issues/1173
