### ISSUE TITLE
Encoding numeric as string

### ISSUE THREAD

**Issue by lmazuel** [microsoft/typespec#3856]
Proposed changed signature for decorator 

```tsp
extern dec encode(
  target: Scalar | ModelProperty,
  encoding: string | EnumMember,
  encodedAs?: Scalar
);
extern dec encode2(target: Scalar | ModelProperty, encodedAs: Scalar);
extern dec encode2(
  target: Scalar | ModelProperty,
  encodingOrEncodedAs: string | EnumMember | Scalar,
  encodedAs?: Scalar
);

```

And then you can call
```ts
@encode(string) val: int64
```
restrict this overload format to only numeric scalar types and `string` as the encodeAs 

Changes: 

- update decorator
- update openapi3 emitter
- add docs

**Comment by timotheeguerin** [comment]
Would also be good to decide if `string` is the right key.

**Comment by MaryGao** [comment]
Similar issue with https://github.com/microsoft/typespec/issues/2762
