### ISSUE TITLE
[Bug]: OpenAPI 3 Emitter failed to add specification extension

### ISSUE THREAD

**Issue by skywing918** [microsoft/typespec#3870]
### Describe the bug

`@extension` failed to add specification extension

## Actual Specification

``` json 
The OpenAPI Object cannot be extended with Specification Extensions.
openapi: 3.0.0
info:
  title: ' title info'
  version: 0.0.0
tags: []
paths: {}
components: {}

``` 

## Expected Specification

``` json 
The OpenAPI Object be extended with Specification Extensions.
openapi: 3.0.0
info:
  title: ' title info'
  version: 0.0.0
tags: []
paths: {}
components: {}
x-custom: My value


``` 

### Reproduction

1. `git clone https://github.com/skywing918/typespec-workaround.git`
2. `tsp compile extension.tsp`
3. Open `/tsp-output/@typespec/openapi3` to get the result

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Dup of https://github.com/microsoft/typespec/issues/3837
