### ISSUE TITLE
[Bug]: @example decorator fails to generate a proper example if nested models are used

### ISSUE THREAD

**Issue by dmytrol** [microsoft/typespec#3874]
### Describe the bug

When the `@example` decorator is applied to a model property that references another model, the generated example is invalid 

### Reproduction

Declare the following models:

```
model A {
  name: string
}

model B {
  items: Array<A>
}
```

Apply the `@example` decorator to model B as follows:

```
@example(#{
  items: #[
    #{ name: "one" },
    #{ name: "two" }
  ]
})
model B {
  items: Array<A>
}
```

The generated `example:` section in the resultant YAML will look like:

```
example:
        items:
          - {}
          - {}
```

which isn't even valid YAML

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Weird issue, will try to see about getting a hotfix for that as well
