### ISSUE TITLE
[Bug]: OpenAPI 3 Emitter failed to define a webhooks in root -- oas v3.1.0

### ISSUE THREAD

**Issue by skywing918** [microsoft/typespec#3882]
### Describe the bug
webhooks failed to add to the root of the document.
Since OAS 3.1.0 the paths element isn't necessary. Now a valid OpenAPI Document can describe only paths, webhooks, or even only reusable components

## Actual Specification

``` json 
webhooks, not currently supported.
``` 

## Expected Specification

``` json 
webhooks, The incoming webhooks that MAY be received as part of this API and that the API consumer MAY choose to implement. Closely related to the callbacks feature, this section describes requests initiated other than by an API call, for example by an out of band registration. The key name is a unique string to refer to each webhook, while the (optionally referenced) Path Item Object describes a request that may be initiated by the API provider and the expected responses. An [example](https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.1/webhook-example.yaml) is available.

``` 

### Reproduction

https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.1/webhook-example.yaml

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bterlson** [comment]
This sounds like a feature request for webhooks and/or OpenAPI 3.1 to me, unless there is some TypeSpec you think should have resulted in a webhook but didn't?

**Comment by timotheeguerin** [comment]
closing as dup of https://github.com/microsoft/typespec/issues/1698
