### ISSUE TITLE
[Bug]: OpenAPI 3 Emitter failed to define a jsonSchemaDialect in root -- oas v3.1.0

### ISSUE THREAD

**Issue by skywing918** [microsoft/typespec#3883]
### Describe the bug

jsonSchemaDialect failed to add to the root of the document.

## Actual Specification

``` json 
jsonSchemaDialect , not currently supported.

``` 

## Expected Specification
``` json 
jsonSchemaDialect, The default value for the $schema keyword within contained within this OAS document. This MUST be in the form of a URI.
``` 

### Reproduction

There doesn't appear to be a way to add jsonSchemaDialect to the root of the document.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
closing as dup of https://github.com/microsoft/typespec/issues/1698
