### ISSUE TITLE
tspConfig of test project does not work

### ISSUE THREAD

**Issue by chunyu3** [microsoft/typespec#3884]
The tspConfig.yaml does not effect the project generation in MGC test project.

Root cause:

- The `tsp command` does not set the `--config` to refer to the tspConfig.yaml in Generate.ps1
- the emitter name in tspConfig.yaml is not correct.

**Comment by ArcturusZhang** [comment]
We just need to fix the wrong emitter name in tspconfig.yaml of `unbranded-typespec` project.

**Comment by chunyu3** [comment]
> We just need to fix the wrong emitter name in tspconfig.yaml of `unbranded-typespec` project.

We still need to set config. For `unbranded-typespec` project, the `tspconfig.yaml` is in the same directory of the typespec file, so set `--config` is not required. But for cadl-ranch test projects, the `tspconfig.yaml` is not at the same directory of typespec file, we need set `--config`.
