### ISSUE TITLE
[Bug]: @info decorator failed to exclude unallow keys, it only allow fixed fields and start with "x-". 

### ISSUE THREAD

**Issue by skywing918** [microsoft/typespec#3887]
### Describe the bug

@info decorator failed to exclude unallow keys, it only allow fixed fields and start with "x-". 

##TSP
```
import "@typespec/openapi";
import "@typespec/openapi3";

using TypeSpec.OpenAPI;

@info({
  unallowKey: {},
})
@service({
  title: "My service",
})
namespace PetStore;


```
## Actual Specification

``` yaml
openapi: 3.0.0
info:
  title: My service
  unallowKey: {}
  version: 0.0.0
tags: []
paths: {}
components: {}

``` 

## Expected Specification
![image](https://github.com/user-attachments/assets/f8bd6d57-ee9d-4d31-9911-17939986f9ea)

``` yaml
openapi: 3.0.0
info:
  title: My service
  version: 0.0.0
tags: []
paths: {}
components: {}

``` 

### Reproduction

. `git clone https://github.com/skywing918/typespec-workaround.git`
2. `tsp compile unallowkey.tsp`
3. Open `/tsp-output/@typespec/openapi3` to get the result

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
This was something we didn't do exactly by design but changing it would be breaking. We have also considered removing the restriction of `@extension` to allow any keys to provide support for any things that we don't have a dedicated decorator for.

**Comment by wanlwanl** [comment]
For OAS3 emitter, at least we can improve it by outputing warning log when compiling tsp
