### ISSUE TITLE
[Bug]: Illegal characters in component keys (Swagger)

### ISSUE THREAD

**Issue by flexwie** [microsoft/typespec#3889]
### Describe the bug

If you define a component with keys that include a character outside of `[A-Z a-z 0-9 - . _]` the corresponding key in the OpenAPI definition will contain that character even if its not allowed by swagger (paste result [here](https://editor.swagger.io/)).

Is there some way to remove the characters from the generated key as a workaround?

### Reproduction

https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZb3BlbmFwaTMiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDsKCgpAc2VydmljZSh7CiAgICB0aXRsZTogIlTEUwp9KQpAcm91dGUoIi8iKQpuYW1lc3BhY2UgRW5kcG9pbnRzIMY3QGdldMYJdGFnKCJsaXN0IinFEW9wIMQOKC4uLkNvbW1vblBhcmFtZXRlcnMpOiBzdHJpbmc7Cn0KCm1vZGVsINAkyGBxdWVyecULJHRha2U%2FOiBpbnQzMjsKfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Hi @flexwie can you show where it says having those are not allowed in swagger? You are talking about the parameter called $take?

I pasted the resulting openapi in editor.swagger.io and there was no issues

**Comment by flexwie** [comment]
Sorry, it seems like the playground link was not up to date. Please try again with this example:

https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZb3BlbmFwaTMiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDsKCgpAc2VydmljZSh7CiAgICB0aXRsZTogIlTEUwp9KQpAcm91dGUoIi8iKQpuYW1lc3BhY2UgRW5kcG9pbnRzIMY3QGdldMYJdGFnKCJsaXN0IinFEW9wIMQOKC4uLkNvbW1vblBhcmFtZXRlcnMpOiBzdHJpbmc7Cn0KCm1vZGVsINAkyGBxdWVyecULJHRha2U%2FOiBpbnQzMjvSHm9wyh19&e=%40typespec%2Fopenapi3&options=%7B%7D

**Comment by wanlwanl** [comment]
OAS3 emitter should follow https://datatracker.ietf.org/doc/html/rfc3986#section-2.2 to validate the characters

**Comment by wanlwanl** [comment]
@skywing918

**Comment by skywing918** [comment]
All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.

Field Name Examples:
```
User
User_1
User_Name
user-name
my.org.User
```
