### ISSUE TITLE
[Bug]: Response object not support field links

### ISSUE THREAD

**Issue by skywing918** [microsoft/typespec#3927]
### Describe the bug

Response object not support field links
## TSP
```
import "@typespec/http";

using TypeSpec.Http;

@service({
  title: "Operation Docs"
})
#suppress "@typespec/http/no-routes"
namespace OperationDocs;
model user {
  username?: string;
  uuid?: string;
}

@route("/2.0/users/")
@get op getUserByName(@path username: string): user;
```
## Actual Specification
https://typespec.io/docs/getting-started/typespec-for-openapi-dev#response-object
![image](https://github.com/user-attachments/assets/b3af8458-5bab-4abc-96bc-34b76a07a8a5)

``` yaml
openapi: 3.0.0
info:
  title: Operation Docs
  version: 0.0.0
tags: []
paths:
  /2.0/users/{username}:
    get:
      operationId: getUserByName
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
components:
  schemas:
    user:
      type: object
      properties:
        username:
          type: string
        uuid:
          type: string

``` 
## Expected Specification
https://spec.openapis.org/oas/v3.0.0#response-object
![image](https://github.com/user-attachments/assets/0dde3f1d-46c5-4884-b049-4196a71c4ea4)

``` yaml
openapi: 3.0.0
info: 
  title: Link Example
  version: 0.0.0
paths: 
  /2.0/users/{username}: 
    get: 
      operationId: getUserByName
      parameters: 
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses: 
        '200':
          description: The User
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/user'
          links:
            userRepositories:
              $ref: '#/components/links/UserRepositories'
components:
  links:
    UserRepositories:
      # returns array of '#/components/schemas/repository'
      operationId: getRepositoriesByOwner
      parameters:
        username: $response.body#/username
  schemas: 
    user: 
      type: object
      properties: 
        username: 
          type: string
        uuid: 
          type: string
``` 

### Reproduction

1. `git clone https://github.com/skywing918/typespec-workaround.git`
2. `tsp compile response.tsp`
3. Open `/tsp-output/@typespec/openapi3` to get the result

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Dup of https://github.com/microsoft/typespec/issues/713

@skywing918 please look for duplicate issues before filing new ones as the checklist ask you to

**Comment by wanlwanl** [comment]
@skywing918 suggest add the description here to the dulplicate issue and add the link of dulplicate issue to the epic issue.
