### ISSUE TITLE
[Bug]: Objects in template cannot include template target type when used from a versioned namespace

### ISSUE THREAD

**Issue by grepory** [microsoft/typespec#3935]
### Describe the bug

This seems like a bug to me. 

If I have a templated interface like this in an unversioned library:

```
namespace Library {
  interface Resource<T> {
    get(): T
  }
}
```

and use that from a versioned namespace like this:

```
@versioned(Versions)
namespace Versioned {
  enum Versions { v1 }
  model Foo {}
  alias Foo = Resource<Foo>
  op get is Foo.get
```

That's all fine and well, but if I customize the response body to be an object that references the template target type:

```
interface Resource<T> {
  get(): { @body body: T };
```

Then I get the following compiler error:

```
Namespace 'Library' is referencing types from versioned namespace 'Versioned' but didn't specify which versions with @useDependency.
```

Is this a bug or is this just not possible?

We are using this in situations like this:

```
    @put
    put(@path id: string, @body body: T): {
        @statusCode statusCode: 200;
        @body body: T;
    } | {
        @statusCode statusCode: 404;
    }
```

Admittedly, this is overly verbose, but we've been going a bit verbose in our specs just to be extremely clear of the behavior we expect.

### Reproduction

[Playground link](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7CtIfaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5WyTY70BtIdHRwOwoKbmFtZXNwYWNlIExpYnJhcnkgewogIGludGVyZsQWUmVzb3VyY2U8VD7FGiAgQGdldMUJZmFpbHMoKTogeyBAYm9keSDEBTogVCB9OwogIH0KfQoKQHNlcnZpY2UKQOcAwGVkKOcAlHMpy3xBcGnFXmVudW0gyCHHcHYxLMVPCiAgQGFkZMtCLnYxKQogIG1vZGVsIE3FBnvFKGFsaWFzIFRo5ADxPegA2S7pAMvFKz47xCpvcOYAxyBpxzAuxQ87Cn0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by grepory** [comment]
We got around this by doing the following, for now:

```
        @post
        create(@body body: T): T;

        @get
        get(@path id: string): T | { @statusCode _: 404 };

        @put
        update(@path id: string, @body body: T): T | { @statusCode _: 404 };

        @delete
        delete(@path id: string): void | { @statusCode _: 204 };
```

Which works just fine as the status code is assumed to be 200 in every case.

**Comment by timotheeguerin** [comment]
Yeah looks like a bug

**Comment by grepory** [comment]
It looks like this only happens with interfaces, btw. Models work fine.

**Comment by timotheeguerin** [comment]
I think the problem is due to having model expression. repro with models if you use a nested model expression [Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR07CgpuYW1lc3BhY2UgTGlicmFyeSB7CiAgbW9kZWwgRmFpbHM8VD7FEyAgYTrHCSAgYjogVDvFDH3EB30KfQoKQHNlcnZpY2UKQMd%2BZWQox2tzKctoQXBpxUhlbnVtIMghx1p2MSzFT%2BkAg03FBnvLEmbkAJUgaXPoALAu5gCmxSk%2BOwp9Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)
