### ISSUE TITLE
[Bug]: Update emitter to set extensions at Server object

### ISSUE THREAD

**Issue by skywing918** [microsoft/typespec#3939]
### Describe the bug

{The problematic object} failed to {describe the problem}.
## TSP
```
import "@typespec/http";
import "@typespec/openapi";

using TypeSpec.Http;
using OpenAPI;

@service
@extension("x-custom", "foo")
@server("https://test.contoso.com", "test domain")
namespace Extensions;
```
## Actual Specification
``` yaml 
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components: {}
servers:
  - url: https://test.contoso.com
    description: test domain
    variables: {}
``` 
## Expected Specification
https://spec.openapis.org/oas/v3.0.0#server-object
![image](https://github.com/user-attachments/assets/809f8741-c466-4257-83a3-01febe06a848)

``` yaml 
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components: {}
servers:
  - url: https://test.contoso.com
    description: test domain
    x-custom: foo
    variables: {}
``` 

### Reproduction

1. `git clone https://github.com/skywing918/typespec-workaround.git`
2. `tsp compile extension-server.tsp`
3. Open `/tsp-output/@typespec/openapi3` to get the result

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Dup of https://github.com/microsoft/typespec/issues/3925
