### ISSUE TITLE
[Bug]: Update emitter to set extensions at Path Item Object

### ISSUE THREAD

**Issue by skywing918** [microsoft/typespec#3940]
### Describe the bug

Update emitter to set extensions at Path Item Object

## Actual Specification
``` yaml 
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths:
  /widgets/{id}:
    get:
      operationId: Widgets_get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: string
components: {}
``` 
## Expected Specification
https://spec.openapis.org/oas/v3.0.0#path-item-object

``` yaml 
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths:
  /widgets/{id}:
    get:
      operationId: Widgets_get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: string
    x-custom: myvalue
components: {}
``` 

### Reproduction

1. `git clone https://github.com/skywing918/typespec-workaround.git`
2. `tsp compile extension-pathItem.tsp`
3. Open `/tsp-output/@typespec/openapi3` to get the result

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Dup of https://github.com/microsoft/typespec/issues/3925
