### ISSUE TITLE
Add xml support to openapi3

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#3945]
Never created this issue after making the xml library

**Comment by markcowl** [comment]
est: 13

**Comment by skywing918** [comment]
@timotheeguerin
Hi Timo, Could you please provide more details for this? maybe I can working on this task.

**Comment by skywing918** [comment]
https://github.com/microsoft/typespec/pull/4214

**Comment by wanlwanl** [comment]
Fixed in https://github.com/microsoft/typespec/pull/4214
