### ISSUE TITLE
Adopt http\payload\multipart from cadl ranch

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#3981]
Adopt https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/payload/multipart

**Comment by chunyu3** [comment]
Multipart is not implemented in MGC, and current implementation in autorest.csharp is not completed, there are some enhancement and features remaining:
- https://github.com/Azure/autorest.csharp/issues/4702
- https://github.com/Azure/autorest.csharp/issues/4684
- https://github.com/Azure/autorest.csharp/issues/4487
- https://github.com/Azure/autorest.csharp/issues/4488
- https://github.com/Azure/autorest.csharp/issues/4944

We will not implement Multipart in MGC until all Multipart feature design is completed and  is completely implemented in autorest.csharp first.
