### ISSUE TITLE
Adopt http\server\path\multiple from cadl ranch

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#3986]
Adopt https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/server/path/multiple

**Comment by chunyu3** [comment]
depend on https://github.com/microsoft/typespec/issues/4206

**Comment by chunyu3** [comment]
Need to implement https://github.com/microsoft/typespec/issues/4673

**Comment by chunyu3** [comment]
Need to resolve https://github.com/microsoft/typespec/issues/4690
