### ISSUE TITLE
Adopt http\type\model\flatten from cadl ranch

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#3999]
Adopt https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/type/model/flatten

**Comment by m-nash** [comment]
@iscai-msft  Should this exist in unbranded cadl ranch scenarios as its an azure back compat thing only.

**Comment by iscai-msft** [comment]
That's a good point, I do think this should move to `azure` for backcompat. There should be a way to do this in a non-breaking manner: probably will have to keep it where it is and add a new one, then in a later release, remove it from the original place

**Comment by JoshLove-msft** [comment]
Looks like the spec no longer exists. @iscai-msft do you know if this still needs to be supported?

**Comment by iscai-msft** [comment]
the spec exists under [here](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/azure/client-generator-core/flatten-property), depending on whether you guys have support for this test, I'd go ahead and close this issue

**Comment by JoshLove-msft** [comment]
This should be implemented in the Azure plugin and not in MGC.
