### ISSUE TITLE
Remove/Rename AutoRest.CSharp.Common.Input.InputTypes.Serialization Namespace from MGC

### ISSUE THREAD

**Issue by jorgerangel-msft** [microsoft/typespec#4037]
There is a [autorest namespace](https://github.com/microsoft/typespec/blob/main/packages/http-client-csharp/generator/Microsoft.Generator.CSharp.Input/src/InputTypes/Serialization/TypeSpecInputNullableTypeConverter.cs#L9) being used within the MGC input type serialization code. We should remove or rename this to follow our unbranded pattern.

**Comment by ArcturusZhang** [comment]
Oh - this must come with some copy/paste when we migrated them.
Let me fix them.
