### ISSUE TITLE
Does advanced multipart support spread?

### ISSUE THREAD

**Issue by msyyc** [microsoft/typespec#4041]
According to https://github.com/microsoft/typespec/issues/3046, users shall set `@multipartBody` explicitly for multipart, does it mean that multipart doesn't support spread? For example, will `@typespec/http` treat the following API as multipart API?
```
model MultiPartModel {
  id: HttpPart<string>;
  file: HttpPart<File>;
} 

op upload(...{...MultiPartModel, @header contentType: "multipart/form-data"})
```
cc @timotheeguerin @bterlson

**Comment by timotheeguerin** [comment]
yeah this wasn't part of the design, we decided multipart should only work with the explicit `@multipartBody` decorator(why we have a separate one from `@body`)
