### ISSUE TITLE
OpenApi3 enum values transformed into a scalar and not an enum

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#4088]
### Discussed in https://github.com/microsoft/typespec/discussions/4087

<div type='discussions-op-text'>

<sup>Originally posted by **vbossica** August  5, 2024</sup>
When defining the OpenApi3 model class:

```
"ModelClass": {
    "enum": [
        "Value1",
        "Value2"
    ],
    "type": "string"
}
```

and using `tsp-openapi3` to transformed the specification, the class is generated as:

```
scalar ModelClass extends string;
```

which loses the enum values.

Should the `ModelClass` be generated as an `enum` instead?

```
enum ModelClass {
    Value1,
    Value2
}
```</div>

**Comment by chrisradek** [comment]
Closed by #4149
