### ISSUE TITLE
[Dependency] Adding RegEx validation to `@pattern` or specific linting rule for RegEx.

### ISSUE THREAD

**Issue by kairu-ms** [microsoft/typespec#4128]
### Clear and concise description of the problem

The typespec should add validation to `@pattern` or Azure specific linting rule for RegEx.

Recently we encountered an invalid [regex expression](https://github.com/Azure/azure-rest-api-specs/blob/21c2852d62ccc3abe9cc3800c989c6826f8363dc/specification/azurefleet/AzureFleet.Management/fleet.tsp#L20).

The correct expression should be `@pattern("^[^_\\W][\\w\\-._]{0,79}(?<![-.])$")`

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
Would note that with the definition of what we support in pattern it might be tricky to accurately validate that https://typespec.io/docs/standard-library/built-in-decorators#@pattern

We of course can easily validate its a JS regex but that would be a large superset of what is supposed to be supported
