### ISSUE TITLE
[Bug]: TypeGraphTree doesn't work properly when expanding/collapse node "TypeSpec.Http.Private"

### ISSUE THREAD

**Issue by RodgeFu** [microsoft/typespec#4130]
### Describe the bug

The TypeGraphTree in playground doesnt work properly. Please check the repro steps for details. Guess it's because the id/key of tree nodes are not set properly, i.e. only "Private" is used. thx

### Reproduction

1. Open Playground
2. load sample "Rest framework"
3. switch to TypeGraph and click the "TypeSpec.Http.Private" node
4. EXPECT: only "TypeSpec.Http.Private" node expanded.  ACTUAL: both "TypeSpec.Http.Private" and "TypeSpec.Rest.Private" nodes expanded
5. click the "TypeSpec.Http.Private" node again
6. EXPECT: "TypeSpec.Http.Private" node collapsed. ACTUAL: "TypeSpec.Rest.Private" node collapsed
7. click the "TypeSpec.Http.Private" node again
8. EXPECT: "TypeSpec.Http.Private" node collapsed. ACTUAL: "TypeSpec.Http.Private"'s children are duplicated and "TypeSpec.Rest.Private" node expanded

![image](https://github.com/user-attachments/assets/48f23a67-a912-4b8b-b445-2b8412d5d1ca)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Seems to be an issue where nodes have the same end name
