### ISSUE TITLE
Switch `decoratorArgMarshalling` flags to new system by default

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#4138]
2nd part of the migration 

Currently it emit a warning if you use the new value world in your decorator but don't have the $flags decoratorArgMarshalling set to `new`

We should update that to be the new default and remove that warning. 

This change was done in typespec compiler `0.57.0` already 3 release ago. Libraries should have had time to update and at least set the flag to legacy if they meant to keep it working.

Optionally it should emit a warning that the legacy option is deprecated and will be removed soon(3rd stage)

**Comment by markcowl** [comment]
est: 1
