### ISSUE TITLE
Allow every diagnostic to define a documentation url

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#4142]
Similar to how we have that for linter rules each diagnositc should be able to define their documentation url.

With this PR https://github.com/microsoft/typespec/pull/4141 this would allow user to dig into more info very easily

```diff
 "digit-expected": {
    severity: "error",
+   url: "https://typespec.io/compiler/diagnostics/digit-expected"
    messages: {
      default: "Digit expected.",
    },
  },
```

**Comment by markcowl** [comment]
est: 3
