### ISSUE TITLE
[Bug][http-client-csharp]: Inconsistency of `InputOperation.Summary` between emitter, mgc, autorest.csharp

### ISSUE THREAD

**Issue by archerzz** [microsoft/typespec#4159]
### Describe the bug

- In the input json, we have defined `Summary` property: https://github.com/microsoft/typespec/blob/81f897739eed8b481d2e07de8fe9770ba9f44994/packages/http-client-csharp/emitter/src/type/input-operation.ts#L20
- However, it doesn't exist in the corresponding input type: https://github.com/microsoft/typespec/blob/81f897739eed8b481d2e07de8fe9770ba9f44994/packages/http-client-csharp/generator/Microsoft.Generator.CSharp.Input/src/InputTypes/InputOperation.cs#L14
- It does exist in `autorest.csharp`: https://github.com/Azure/autorest.csharp/blob/0f630c2bf2f7116c3ebf212ce245a75c92d53f16/src/AutoRest.CSharp/Common/Input/InputTypes/InputOperation.cs#L18
- And more in `autorest.csharp`, we'll always set the `Description` if it's not available: https://github.com/Azure/autorest.csharp/blob/27aa096093e4e2efc4aa5c916eafd1c3df4ab48f/src/AutoRest.CSharp/Common/Input/InputTypes/Serialization/TypeSpecInputOperationConverter.cs#L85-L89

### Reproduction

Check this PR which I tried to adopt TCGC properties regarding operation docs: https://github.com/microsoft/typespec/pull/4158
![image](https://github.com/user-attachments/assets/cfe448a8-660a-4db1-afa5-8e0e30af8e1c)
The root cause is that after adopting TCGC properties, the meaningful doc value is saved in `Summary`, instead of `Description`. And the `Description` is set to the operation name.

### Questions

- Where do we want to determine the final document properties (e.g. `Summary` (for `<summary>`) and `Description` (for `<remarks>`)? In TCGC, or in emitter, or in our generator?
- Does MGC support `Summary`?

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by archerzz** [comment]
Per discussion,

- We lost `Summary` property for `InputOperation` in MGC, so we need to add it back.
- However, we might want to change the property names to align with TCGC, e.g.
  - Rename `Summary` to `Description` <= TCGC `description`
  - Rename `Description` to `Details` <= TCGC `details`
  - For `autorest.csharp`, let's do the conversion in `TypeSpecInputOperationConverter` so that we don't need to change the `InputOperation` in it
- Remove the logic to set `Description` if empty in `autorest.csharp`

**Comment by JoshLove-msft** [comment]
@archerzz is this essentially a duplicate of https://github.com/microsoft/typespec/issues/4771?

**Comment by archerzz** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/4516?s=64&amp;u=061abf5c55814207559b93534273fd9b6506ce85&amp;v=4">@archerzz](https://github.com/archerzz) is this essentially a duplicate of [#4771](https://github.com/microsoft/typespec/issues/4771)?

@JoshLove-msft Not exactly. But I think #4771 replaced this issue.
