### ISSUE TITLE
[Bug]: Unable to set `explode` to `false` for a query parameter

### ISSUE THREAD

**Issue by Sylvain2703** [microsoft/typespec#4165]
### Describe the bug

According to the [OpenAPI 3.0 guide](https://swagger.io/docs/specification/serialization/#query), the default for the `explode` option is `true` (unlike for [path parameters](https://swagger.io/docs/specification/serialization/#path) and [headers](https://swagger.io/docs/specification/serialization/#header)).

Starting with TypeSpec 0.59.0, there is no way to produce `explode: false` for a query parameter with the OpenAPI 3.0 emitter.
When explicitly defining `@query(#{ explode: false })`, TypeSpec wrongly considers that the default value is `false` and therefore does not generate the `explode: false` property in the OpenAPI file. As a result, the `explode` option is always understood as `true` in Swagger UI.

### Reproduction

[Playground Link](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCm1vZGVsIMcyxEVpZDogc3RyaW5nOwogIHdlaWdodDogaW50MzLEEWNvbG9yOiAicmVkIiB8ICJibHVlIjsKfQoKQGVycm9yx1FFxAzFUGNvZGXLQG1lc3NhZ2XKZMQ6cm91dGUoIi935QCHcyIpCkB0YWco5wDJxBBpbnRlcmbkAL%2FHFMVcQOQAtck%2BZXhwbG9kZS10cnVlIikgbGlzdDEoCiAgICBAcXVlcnkoI3vHIzogxCR9KSBmaWx0ZXLoAI1bXQogICk6x2NbXSB85gDIOwrZbGZhbHPIbTLYbcUl327dbm5vLcdNx2szzWvfWstafQo%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
oh ouch

**Comment by timotheeguerin** [comment]
Will be release in openapi 0.59.1

**Comment by Sylvain2703** [comment]
Great, thank you very much 😃
