### ISSUE TITLE
[Bug]: CLI outputs incorrect version

### ISSUE THREAD

**Issue by creatorrr** [microsoft/typespec#4189]
### Describe the bug

The binary from the latest npm package (`0.59.1`) outputs `0.58.1` as version.

### Reproduction

- `npm rm -g @typespec/compiler`
- `npm i -g @typespec/compiler@0.59.1`
- `tsp --version`  (_should output 0.58.1_)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
cannot repro this, can you look at the version in package.json of you global node_modules folder?

**Comment by creatorrr** [comment]
Yeah, my bad. I think `fnm` had some conflicting bin path, recreating the `fnm` env fixed it. Thanks! Closing.
