### ISSUE TITLE
Unable to apply @maxLength to `bytes`

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#4190]
```TSP
model Funky {
  @maxLength(200)
  data: bytes;
}
```

Result - error
decorator-wrong-target
Cannot apply @maxLength decorator to type it is not a string
2:3. And unhappy developer.

**Comment by markcowl** [comment]
@johanste Here would you intention be a restriction on the base64-encoded string length, or on the number of bytes in the array?  If it's the latter, would maxItems be more appropriate?
