### ISSUE TITLE
Failed to set default value with utcDateTime.fromISO("2024-02-15T18:36:03Z")

### ISSUE THREAD

**Issue by skywing918** [microsoft/typespec#4193]
### Describe the bug

throw: error @typespec/openapi3/invalid-default Invalid type 'ScalarValue' for a default value <unknown location>:1:1
```
import "@typespec/http";
import "@typespec/openapi3";
using Http;
using TypeSpec.OpenAPI;
@service
namespace test;

scalar utcDateTime {
  init fromISO(value: string);
}

model DateRange {
  minDate: utcDateTime = utcDateTime.fromISO("2024-02-15T18:36:03Z");
}
```

### Reproduction

[Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGm9wZW5hcGkzxB51c2luZyBIdHRwyQ1UeXBlU3BlYy5PcGVuQVBJOw0KQHNlcnZpY2UNCm5hbWVzcGFjZSB0ZXN0Ow0KDQpzY2FsYXIgdXRjRGF0ZVRpbWUgew0KICBpbml0IGZyb21JU08odmFsdWU6IHN0cmluZyk7DQp9xDttb2RlbCDEN1JhbmfHOG1pbsQSOs1SPcwOLshWIjIwMjQtMDItMTVUMTg6MzY6MDNaIsdf&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Not sure I would qualify that one as a bug as much as a missing feature. Default values have always only supported primitive types.
