### ISSUE TITLE
Omit Generated/Internal types that aren't used by a client

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/typespec#4218]
Lots of files are added to a client's src/Generated/Internal (e.g. https://github.com/microsoft/typespec/tree/main/packages/http-client-csharp/generator/TestProjects/Local/Unbranded-TypeSpec/src/Generated/Internal), that aren't necessarily used by a client.  This adds bulk to a client assembly, and can skew client code coverage numbers.  It would be helpful to omit generating these files if they aren't used by a client. This will also help us evaluate what internal APIs are most commonly used by clients to consider moving them into public APIs in System.ClientModel.

**Comment by JoshLove-msft** [comment]
Either use Roslyn API to detect if type is being used OR mark types as being used by the library while generating.
