### ISSUE TITLE
Define a property of model with default value returns error in autorest & OAS3 emitter

### ISSUE THREAD

**Issue by lirenhe** [microsoft/typespec#4238]
### Describe the bug

model Test {

  user: {
    name: string;
  } = #{ name: "System" };
}
returns error of 'Invalid type 'ObjectValue' for a default value'  in cadl playground.

### Reproduction

https://azure.github.io/typespec-azure/playground?c=Cgptb2RlbCBUZXN0IHsKCiAgdXNlcjogewogICAgbmFtZTogc3RyaW5nOwogIH0gPSAje8cXIlN5c3RlbSIgfTsKfQo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fdata-plane%22%5D%7D%7D

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Same as https://github.com/microsoft/typespec/issues/4193 this is more of a feature request where we have never supported non primitive default values
