### ISSUE TITLE
Upgrade System.Text.Json Version to v8.0.4

### ISSUE THREAD

**Issue by jorgerangel-msft** [microsoft/typespec#4245]
MGC is pulling in STJ version 8.0.0 as a transitive dependency which has a [high severity vulnerability](https://github.com/advisories/GHSA-hh2w-p6rv-4g7w). We should upgrade the package to the patch version v8.0.4 which resolves the vulnerability.

**Comment by m-nash** [comment]
Closing unless we can find a repro on more than 1 machine.
