### ISSUE TITLE
[Bug]: Decorator duplication check

### ISSUE THREAD

**Issue by adminy** [microsoft/typespec#4281]
### Describe the bug

I'm trying to extend the functionality of http decorator verbs `@get @post @put @delete`

instead I get an error:
```
error ambiguous-symbol: "post" is an ambiguous name between global.post, TypeSpec.Http.post. Try using fully qualified name instead: global.post, TypeSpec.Http.post
> 122 |   @post update(...
      |    ^^^^
```

I understand why this is important check for Models, because you don't want the wrong model loaded. but for decorators this should work as intended since decorators are emitters, how you choose to use them should be accumulative since its less sytax for more functionality.

### Reproduction

index.js
```javascript
import { createTypeSpecLibrary } from "@typespec/compiler";

export const $lib = createTypeSpecLibrary({
  name: "myLib"
})

/**
* @param {import("@typespec/compiler").DecoratorContext} context
* @param {import("@typespec/compiler").Operation} entity
*/
function verbs(context, entity) {
  console.log(`[${entity.namespace.name}] ${entity.type}: ${entity.name}`)
}
export const $get = (...args) => verbs(...args)
export const $post = (...args) => verbs(...args)
export const $put = (...args) => verbs(...args)
export const $head = (...args) => verbs(...args)
export const $delete = (...args) => verbs(...args)
export const $patch = (...args) => verbs(...args)
```
index.tsp
```
extern dec get(target: Operation);
extern dec post(target: Operation);
extern dec put(target: Operation);
extern dec head(target: Operation);
extern dec delete(target: Operation);
extern dec patch(target: Operation);
```

### Other things tried:
```javascript
export const $decorators = {
  'TypeSpec.Http': {
      post: (...args) => verbs(...args),
      put: (...args) => verbs(...args),
      get: (...args) => verbs(...args),
      head: (...args) => verbs(...args),
      delete: (...args) => verbs(...args),
      patch: (...args) => verbs(...args),
  }
}
```
which seems to have just silenced everything and done nothing.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
In the first case the problem is that the decorators are added to the global namespace.
In the 2nd we this is a new syntax that was added in main but not released yet which makes sense why its not working.

If you define the decorator signatures in a tsp file as well it will tell you it cannot find the implementation if the namespaces don't match.

To set the namespace for the functions either wait for next release and do option 2(just change the namespace to your own) or add `export const namespace = "My.Namespace";` and then you can reference to those decorators form that namespace and not be ambiguous with http ones
