### ISSUE TITLE
[Feature] to provide a meaningful enum name from compiler

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#4296]
### Clear and concise description of the problem

In typespec, we can use `` to escape the union member name or enum member name validation, however, I don't think this kind of escape is the right thing to do, for example, 
```
union ImageSize {
  string,
  `256x256`: "256x256",
  `512`: "512x512",
  size1024x1024: "1024x1024",
}
```
we use quoted string to escape in the first case, but it would not work for the second case anyway. 
```ts
 export enum ImageSize {
   /** 256x256 */
  "256x245" = "256x256",
   /** 512x512 */
  "512" = "512x512", // 
  size1024X1024 = "1024X1024",
}
```
<img width="544" alt="image" src="https://github.com/user-attachments/assets/f3211b7c-bcae-4d1f-ab75-82ef72185ff8"> 

I wonder if compiler could just error out for `` being used in enum or union member name. Or the compiler has some kind of logic to provide a meaningful enum name ? 

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by qiaozha** [comment]
```
union ImageSize {
  512
}
```

**Comment by markcowl** [comment]
@qiaozha  I think this is by design.  It is possible to use named union variants if a better name is needed.  I think this is likely one of the rules that would show up in any linting rules for unbranded emitters.

**Comment by qiaozha** [comment]
@markcowl thanks, I will linter rule issue created here https://github.com/Azure/typespec-azure/issues/1653
