### ISSUE TITLE
tsp-openapi3 - update query parameter transformations to support typespec 0.59 changes

### ISSUE THREAD

**Issue by chrisradek** [microsoft/typespec#4298]
### Clear and concise description of the problem

`@typespec/http` v0.59.0 added uri template support. As part of these changes, the `@query({format: })` option was deprecated in favor of setting `#{explode: true}` instead.

We should update the parameter transformation logic to no longer emit the deprecated version of the query decorator.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
est: 2
