### ISSUE TITLE
Normalize newlines for csproj / launchsettings

### ISSUE THREAD

**Issue by m-nash** [microsoft/typespec#4340]
Right now when you generate csproj via new project scaffolding or launchsettings via generate.ps1 the newlines are based on your current env so it can flip flop.  The repo normalizes them but it shows up as a diff initially until its normalized.

We should normalize the new lines to `/n` to avoid this.

Our CodeWriter class already does this for the *.cs files but the files created by new project scaffolding and generate.ps1 don't use this so they don't follow.

**Comment by JoshLove-msft** [comment]
The NewProjectScaffolding already normalizes line endings. The only thing missing is the launchSettings generation.
