### ISSUE TITLE
[Discussion] Is implicit body permitted in `HttpPart<>` for multipart?

### ISSUE THREAD

**Issue by msyyc** [microsoft/typespec#4367]
In design https://github.com/microsoft/typespec/issues/3046, Typespec permit users define explicit body in `HttpPart<>` like:
```
model Address {
    city: string;
    country: string;
}
op upload(
  @header `content-type`: "multipart/form-data";
  @multipartBody body: {
    // # String body
    address: HttpPart<@body body: Address; @header MyHeader: string>,
  }
): void;
```
**Shall we permit implicit body in `HttpPart<>` like:** 
```
op upload(
  @header `content-type`: "multipart/form-data";
  @multipartBody body: {
    // # String body
    address: HttpPart<city: string; country: string; @header MyHeader: string>,
  }
): void;
```
?

PS: I try implicit body in [playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TEGg0KQHNlcnZpY2Uoew0KICB0aXRsZTogIldpZGdldCBTxhwiLA0KfSkNCm5hbWVzcGFjZSBEZW1vxx3FRnVzaW5nIFR5cGVTcGVjLkh0dHA70RZSZXN0xnRyb3V0ZSgiL3TkAIcpDQpvcCDECyhAaGVhZGVyIGNvbnRlbnTEOjogIm11bHRpcGFydC9mb3JtLWRhdGEiOyBAyRdCb2R5IGJvZHk6IOUAxWFkZHJlc3M6IOQAh1BhcnQ8xRcgIGNpdHk6IHN0cmluZzsgY291bnRyyxHWfmFwcGxpY2F0aW9uL2pzb27kATd9PuQBETogdm9pZDs%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D). Although compiler doesn't report error, the generated swagger obviously is not right.

cc @bterlson

**Comment by timotheeguerin** [comment]
I believe so, if you look at openapi3 emitter it is emitted correctly [playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TEGg0KQHNlcnZpY2Uoew0KICB0aXRsZTogIldpZGdldCBTxhwiLA0KfSkNCm5hbWVzcGFjZSBEZW1vxx3FRnVzaW5nIFR5cGVTcGVjLkh0dHA70RZSZXN0xnRyb3V0ZSgiL3TkAIcpDQpvcCDECyhAaGVhZGVyIGNvbnRlbnTEOjogIm11bHRpcGFydC9mb3JtLWRhdGEiOyBAyRdCb2R5IGJvZHk6IOUAxWFkZHJlc3M6IOQAh1BhcnQ8xRcgIGNpdHk6IHN0cmluZzsgY291bnRyyxHWfmFwcGxpY2F0aW9uL2pzb27kATd9PuQBETogdm9pZDs%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by timotheeguerin** [comment]
actually so is autorest swagger 2.0 doesn't support json parts so it just treat them as string. So just missing a warning I think
