### ISSUE TITLE
[Bug]: Nullable Enums produce oneOf

### ISSUE THREAD

**Issue by rima1098** [microsoft/typespec#4398]
### Describe the bug

When declaring models with Enums that are nullable the generated OpenAPI 3.0 description does produce a oneOf descriminator. (see playground link).

Instead of receiving
```
enumProp:
    oneOf:
        - $ref: '#/components/schemas/MyEnum'
    nullable: true
```

i would expect to receive:
```
enumProp:
    allOf:
        - $ref: '#/components/schemas/MyEnum'
    nullable: true
```

### Reproduction

https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGm9wZW5hcGkzxB4NCnVzaW5nIFR5cGVTcGVjLlJlc3Q70RZIdHRwxS5lbnVtIE15RcQHew0KICAgIHZhbHVlMTvLDTLMDTM7DQp9xDttb2RlbCBSZXF1aXJlZE5vdE51bGxhYmxlyEnEXFByb3A6x2HXOd82IHwgbnVsbM49T3B0aW9uYWzbdj%2FIQdY53zbId8U9&e=%40typespec%2Fopenapi3&options=%7B%7D

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Yeah seems like a bug for other types with $ref is does make an `allOf` 
[Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGm9wZW5hcGkzxB4NCnVzaW5nIFR5cGVTcGVjLlJlc3Q70RZIdHRwxS5lbnVtIE15RcQHew0KICB2YWx1ZTEsDQp9xB9tb2RlbCBSZXF1aXJlZE51bGxhYmxlxirEO1Byb3A6yEB8IG51bGw7zTtPcHRpb25hbNY7PzogQmFy1TnEGHt9DQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by dfioravanti** [comment]
Just as an FYI, it happens with `@docs` too. See [playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGm9wZW5hcGkzxB4NCnVzaW5nIFR5cGVTcGVjLlJlc3Q70RZIdHRwxS5tb2RlbCBGb297DQogIHZhcjE6IHN0cmluZzsNCn3KIkJhciDFI0Bkb2MoIlRoaXMgdHJpZ2dlcnMgYSBhbGxPZiIpxCFmb28xOsRSxWDFEDLIEMVRDQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by timotheeguerin** [comment]
@dfioravanti can you clarify what is the issue in your playground? This looks correct for me in openapi3.0( you cannot have siblings to $ref)
