### ISSUE TITLE
[Bug]: Empty example object was emitted when the model contains a enum type property

### ISSUE THREAD

**Issue by akishichinibu** [microsoft/typespec#4416]
### Describe the bug

The example for model `AA` is generated correctly; however, the example of `Output` becomes an empty object when set the type of property to the enum `Types` in model `A`. It seems that this issue will disappear when replacing the type enum with a string literal.

```
import "@typespec/http";
import "@typespec/rest";
import "@typespec/openapi";
import "@typespec/openapi3";

using TypeSpec.Http;
using TypeSpec.Rest;
using TypeSpec.OpenAPI;

enum Types {
  A: "a";
  B: "b";
}

@example(#{
  type: Types.A,
  a: "a",
})
model A {
  type: Types.A;
  a: string;
}

model B {
  type: Types.B;
  b: int64;
}

@oneOf
@discriminator("type")
union X {
  A;
  B;
}

@example(#{
  x: #{
    type: Types.B,
    b: 4,
  }
})
model Output {
  x: X
}

model AA {
  type: "aa";
  a: string;
}

model BB {
  type: "bb";
  b: int64;
}

@oneOf
@discriminator("type")
union XX {
  AA;
  BB;
}

@example(#{
  xx: #{
    type: "aa",
    a: "aa",
  }
})
model Output2 {
  xx: XX
}
```

Output: 
```yaml
    Output:
      type: object
      required:
        - x
      properties:
        x:
          $ref: '#/components/schemas/X'
      example:
        x: {}
    Output2:
      type: object
      required:
        - xx
      properties:
        xx:
          $ref: '#/components/schemas/XX'
      example:
        xx:
          type: aa
          a: aa
```

### Reproduction

👇
https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZb3BlbmFwadwcMyI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwO9AVUmVzdNEVT3BlbkFQSTsKCmVudW3FGHMgewogIEE6ICJhIjsKICBCOiAiYiI7Cn0KCkBleGFtcGxlKCPEI%2BQAijrGMy5BLAogIGHFNCwKfSkKbW9kZWwgQcVLzSjEUmE6IHN0cmluZ8VVxitC0StCxCtiOiBpbnQ2NMZ%2Fb25lT2YKQGRpc2NyaW1pbmF0b3IoIsQ1IikKdW5pb24gWMVIxWdC8wC0eDogxQjPa%2BQAvsVtNMQKfeoAwk91dHB1dMVUeDogWOoAsEHsANwiYeYBK%2FUA2ewA2iJi5AFK%2FwDX9QDX5wDY5gDZ9QDa8ADb5ACV5gDY5QGYxg3xANsyxVjEPVjkAN4%3D&e=%40typespec%2Fopenapi3&options=%7B%7D&version=0.60.x

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
[Simplified repro](https://typespec.io/playground?c=ZW51bSBUeXBlcyB7CiAgQSwKICBCLAp9CgpAZXhhbXBsZSgjeyB0eXBlOsYnLkEgfSkKbW9kZWwgQcU0zR07xDt1bmlvbiBYyFLPTXg6INJTylVPdXRwdXTFPHg6IFjEUQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D&version=0.60.x)

Seems to be a combination of using an enum property inside a union
