### ISSUE TITLE
[Bug]: OpenAPI3 fails to consistently emit default float values declared in e-notation.

### ISSUE THREAD

**Issue by ethall** [microsoft/typespec#4419]
### Describe the bug

OpenAPI3 does not always emit a default float value when declared in e-notation.

When attempting to declare a default `float`, `float32`, or `float64` less than `0.1`, the emitter will drop the default field from the model.

### Reproduction

Current behavior from v0.60.0:
[Playground Link](https://typespec.io/playground?c=bW9kZWwgRU5vdGF0aW9uQmFzaWMgew0KICBhOiBmbG9hdCA9IDFlMDvEE2LMEy0xxRRjzRQyxRRkzRQzxRRlxxQzMswWZscWNjTKFn0NCg0K7wCYV2l0aG91dFplcm9z%2FwCf%2BgCfMvQAoDIz9gCiyhjuAKTIGH0NCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D&version=0.60.x)

Expected behavior from v0.56.0:
[Playground Link](https://typespec.io/playground?c=bW9kZWwgRU5vdGF0aW9uQmFzaWMgew0KICBhOiBmbG9hdCA9IDFlMDvEE2LMEy0xxRRjzRQyxRRkzRQzxRRlxxQzMswWZscWNjTKFn0NCg0K7wCYV2l0aG91dFplcm9z%2FwCf%2BgCfMvQAoDIz9gCiyhjuAKTIGH0NCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D&version=0.56.x)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Weird, also depends on which order you define things. `0.01` defined after `1e-2` will not work but before both work

https://typespec.io/playground?c=bW9kZWwgRU5vdGF0aW9uQmFzaWMgew0KICBjOiBmbG9hdCA9IDFlLTI7xBRkyhQwLjAxOw0KfQ0K&e=%40typespec%2Fopenapi3&options=%7B%7D&version=0.60.x

**Comment by ethall** [comment]
Sorry to resurrect, but I tested the release containing #4420 and found more test cases where the compiler fails to capture the e-notation values. Should I create a new issue or add to this issue?

**Comment by timotheeguerin** [comment]
yeah can you open a new issue with all the new cases you found
