### ISSUE TITLE
Add abstraction to deal with more types during serialization/deserialization in MGC

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#4433]
In 3rd party generators, they might have some more types generated from some specific input types, such as in azure, we have `ETag`, `AzureLocation`, `ResourceIdentifier`, etc.
It is simple to override the `CreateCSharpTypeCore` method to map some specific types, but the default serialization provider `MrwSerializationTypeDefinition` cannot handle those extra types, and we would get exceptions.
https://github.com/microsoft/typespec/blob/40762bf8527d0c49ee3fa64a6fd0387fa36d2475/packages/http-client-csharp/generator/Microsoft.Generator.CSharp.ClientModel/src/Providers/MrwSerializationTypeDefinition.cs#L1228

**Comment by ArcturusZhang** [comment]
Several proposals:
It is always an option that we write our own serialization provider, but I believe we should avoid that, at least for a real 3rd party plugin.
So:
1. Add an abstraction to hold those hooks, we could put them on `TypeFactory` (or introduce another class to hold these) and `MrwSerializationTypeDefinition` could call it.
2. Make `MrwSerializationTypeDefinition` public and put a `protected` method on it so that we could override it to add more.

**Comment by JoshLove-msft** [comment]
> 1. Add an abstraction to hold those hooks, we could put them on `TypeFactory` (or introduce another class to hold these) and `MrwSerializationTypeDefinition` could call it.

I think we would want to do this.
