### ISSUE TITLE
[Bug]: tsp compile --watch doesn't cover tspconfig.yaml

### ISSUE THREAD

**Issue by RodgeFu** [microsoft/typespec#4468]
### Describe the bug

run "tsp compile --watch" and then edit tspconfig.yaml. The change in tspconfig.yaml won't be included when the "tsp compile --watch" recompile the project.

### Reproduction

1. tsp compile --watch
2. change tspconfig.yaml
3. check whether the change in tspconfig.yaml takes effect in "tsp compile --watch"

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Jameschen594** [comment]
Currently, changes to `tspconfig.yaml` are not detected while using `tsp compile <path> --watch`. To apply any updates, you must stop and restart the watch process so the compiler can recognize the changes in `tspconfig.yaml`. Should this issue be addressed by including`tspconfig.yaml` in the watch process? Currently, the watch feature only monitors changes to files within the specified `<path>`.
