### ISSUE TITLE
[Bug]: Only single examples supported

### ISSUE THREAD

**Issue by mario-guerra** [microsoft/typespec#4493]
### Describe the bug

**Description:**
The current implementation of the OpenAPI emitter in TypeSpec only supports a single example for each operation or model. If multiple examples are provided using the `@opExample` decorator in the TypeSpec specification, only the last example will be included in the generated OpenAPI document. This limitation prevents the use of multiple examples to illustrate different use cases or scenarios.

**Context:**
OpenAPI version 3.0.0 introduced support for multiple examples using the `examples` field. However, the TypeSpec OpenAPI emitter does not yet support this feature, leading to incomplete documentation when multiple examples are provided.
[Discovered by a third party user.](https://www.speakeasy.com/guides/api-frameworks/typespec#2-only-single-examples-supported)

### Reproduction

**Reproducing Test Case:**

1. **Create a TypeSpec Project:**
   ```bash
   mkdir typespec-example
   cd typespec-example
   tsp init
   ```

2. **Install Dependencies:**
   ```bash
   tsp install
   npm install @typespec/versioning @typespec/openapi
   ```

3. **Write TypeSpec Specification:**
   Create a `main.tsp` file with the following content:
   ```typescript
   import "@typespec/http";
   import "@typespec/openapi";
   import "@typespec/versioning";

   using TypeSpec.Http;
   using TypeSpec.OpenAPI;
   using TypeSpec.Versioning;

   @service({
     title: "Example API",
   })
   @versioned(Versions)
   namespace ExampleAPI;

   enum Versions {
     `1.0.0`,
   }

   model User {
     id: string;
     name: string;
     email: string;
   }

   const UserExample1 = #{
     id: "123",
     name: "John Doe",
     email: "john.doe@example.com",
   };

   const UserExample2 = #{
     id: "456",
     name: "Jane Smith",
     email: "jane.smith@example.com",
   };

   @example(UserExample1)
   @example(UserExample2)
   model UserWithExamples extends User {}
   ```

4. **Generate OpenAPI Document:**
   ```bash
   tsp compile main.tsp --emit @typespec/openapi3
   ```

5. **Check Generated OpenAPI Document:**
   Open the generated `openapi.yaml` file and verify if both examples are included in the `UserWithExamples` model.

**Expected Result:**
The `UserWithExamples` model in the generated OpenAPI document should include both examples provided in the TypeSpec specification.

**Actual Result:**
Only the last example (`UserExample2`) is included in the generated OpenAPI document.

[Playground link](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGm9wZW5hcGnWHXZlcnNpb25pbmfEIA0KdXNpbmcgVHlwZVNwZWMuSHR0cDvRFk9wZW5BUEnSGVbJTsVNQHNlcnZpY2Uoew0KICB0aXRsZTogIkV4YW1wbGUgQVBJIiwNCn0pDQpA5wCHZWQox0NzKQ0KbmFtZXNwYWNlIMczxnQNCmVudW0gyCkgxV1gMS4wLjBgxFDEIm1vZGVsIFVzZXLGH2lkOiBzdHLmAJkgIMRazRFlbWFpbMsSxUVjb25zdMVF5wCAMSA9ICPJUCIxMjPkAMHITyJKb2huIERvZcYVx1Miam9obi5kb2VAZcZFLmNvbcQifeUAy9FkMs5kNDU2zmRhbmUgU21pdGjPZmFuZS5zxBjWaMgWKMtrMeQBetMYMinsAUFXaXRoxxlzIGV4dGVuZHPFGSB7fQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
From editor.swaggger.io this emit an error to use the examples property like openapi3.1 in 3.0
<img width="427" alt="image" src="https://github.com/user-attachments/assets/b4b56baa-ce5e-42a7-9334-1c1826daa843">
