### ISSUE TITLE
union statement should support unnamed unions

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#45]
The `union` statement was introduced to support "named unions" (a la Rust and Swift).  But we also allow `union` to define regular "unnamed" unions by simply omitting the variant names, e.g.:
```
union Pet { Cat, Dog }
```

The compiler currently complains about this syntax:
```
error token-expected: ':' expected.
```

**Comment by bterlson** [comment]
Sounds good to me. I believe `union Pet { Cat, Dog }` and `alias Pet = Cat | Dog` should be semantically equivalent types (though the former being a definition may emit differently e.g. by creating a definition in openapi).

**Comment by mikekistler** [comment]
Supporting unnamed unions with `union` lets you do this _and_ add doc.

But this is not blocking anything, so while it might be nice it is not a V1 item.

**Comment by markcowl** [comment]
Need a solid use case for this that is not covered by named unions.  Deferring this until after v1
