### ISSUE TITLE
MCG: Make Pipeline property non-virtual in generated SCM-based clients

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/typespec#4501]
![image](https://github.com/user-attachments/assets/d0f1510b-60dc-4d32-9245-2956b7b8b908)

**Comment by JoshLove-msft** [comment]
This is already generated non-virtual. In the OpenAI library a custom Pipeline property is added that is virtual.

**Comment by annelo-msft** [comment]
Thanks!  Do we make it virtual in Azure clients?  (Mostly just curious here, for updating my mental model)

**Comment by JoshLove-msft** [comment]
In autorest.csharp, yes it looks like it is generated as virtual. In the Azure plugin to MGC I don't think it would be changed to virtual.
