### ISSUE TITLE
Need to consume MGC PR nuget packages from azure-sdk-for-net

### ISSUE THREAD

**Issue by live1206** [microsoft/typespec#4507]
### Clear and concise description of the problem

During the MGC PR, there are NuGet packages generated as artifacts, but they are not published to any feed.
We need to publish them to some internal NuGet feed, so that Azure plugin in azure-sdk-for-net can consume them.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by live1206** [comment]
Right now, we have the version tag for NuGet packages as "alpha" and publish them to internal feeds for MGC.
The version tag is based on [Prerelease](https://github.com/microsoft/typespec/blob/ba1becbbfde4f819260a134fe67188ecd05163f7/packages/http-client-csharp/eng/scripts/Build-Packages.ps1#L93), theoretically we can change the version tag to "dev" if this is a PR trigger.
But then we need to pass along another flag, let's say [publish](https://github.com/microsoft/typespec/blob/bee3e4d221f45aecfe2843815e1b1c4d8a141e82/packages/http-client-csharp/eng/pipeline/publish.yml#L20), for the script invoke [here](https://github.com/microsoft/typespec/blob/bee3e4d221f45aecfe2843815e1b1c4d8a141e82/eng/emitters/pipelines/templates/steps/build-step.yml#L79-L84).
I think it's not worth to introduce another flag for the script invoke for a temp workaround, since the script is used in a common way.

Ideally, when we start to publish MGC NuGet packages to public feed instead of [internal](https://github.com/microsoft/typespec/blob/bee3e4d221f45aecfe2843815e1b1c4d8a141e82/eng/emitters/pipelines/templates/stages/emitter-stages.yml#L296-L298). We can publish NuGet packages to internal feed when it is PR.

@weshaggard Any plan when we will publish to public NuGet feed instead of internal feed for MGC?
cc @m-nash @JoshLove-msft

**Comment by weshaggard** [comment]
cc @hallipr who is more in sync with the work happening here. 

Is there a reason to publish this package to nuget?

**Comment by live1206** [comment]
> cc [@hallipr](https://github.com/hallipr) who is more in sync with the work happening here.
> 
> Is there a reason to publish this package to nuget?

@weshaggard @hallipr 
Eventually, [Microsoft.Generator.CSharp](https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net/NuGet/Microsoft.Generator.CSharp/overview/1.0.0-alpha.20241010.1) and [Microsoft.Generator.CSharp.ClientModel](https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net/NuGet/Microsoft.Generator.CSharp.ClientModel/overview/1.0.0-alpha.20241010.1) will be available for third-party customers to implement their own generator.
And [Azure Plugin](https://github.com/Azure/azure-sdk-for-net/tree/main/eng/packages/http-client-csharp/generator) consumes it as well for Azure internally.

Right now, we only release NuGet package to internal feed from main branch of this repo. This issue is to figure out a way to release NuGet package to internal feed from PR as well, for integration work in [Azure Plugin](https://github.com/Azure/azure-sdk-for-net/tree/main/eng/packages/http-client-csharp/generator). 
Ideally, we can just release NuGet package to public NuGet from main branch, and release NuGet package to internal NuGet feed for PRs.
That's why I am asking is there any plan to release it to public NuGet feed from main.

**Comment by live1206** [comment]
I realized we don't need an extra flag for the script, created https://github.com/microsoft/typespec/pull/4687 to publish NuGet packages with `-dev` version tag.

But still, ideally we should publish to public NuGet from main branch and to internal feed from PR, like we are doing for npm packages.

**Comment by weshaggard** [comment]
I have not see any plans to release the package to nuget.org, if we need that then please work with @hallipr to get that setup. I will add that our dev feed is also publicly available for people to consume from.

**Comment by live1206** [comment]
We decided to manually get the latest version based on branch in https://dev.azure.com/azure-sdk/internal/_build?definitionId=6871&_a=summary
Postpone the public NuGet package release until we need it.
