### ISSUE TITLE
[Bug]: Unable to run the tsp command in a monorepo (yarn workspaces)

### ISSUE THREAD

**Issue by cincauhangus** [microsoft/typespec#4509]
### Describe the bug

I'm currently trying to migrate a standalone typespec package into a monorepo and I'm having troubles trying to run `yarn tsp compile` after installation.

Note: This error does not appear when running as a standalone package.

Errors when running `tsp compile .`
![image](https://github.com/user-attachments/assets/446b4f91-1878-4bb6-b94a-eca2729f7cc1)

Issue stems from this library file in the @typespec/openapi3 package:
![image](https://github.com/user-attachments/assets/234910f4-d25e-48a9-82f5-600b22f5901b)

### Reproduction

1. Create a simple monorepo (using yarn)
2. Create a child repo and install typespec
3. Run `tsp compile .` in the new repo. 

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Hey I tried to reproduce this issue in a basic yarn 4.5.0 workspace and couldn't could you make a basic repo where this reproduce? And can you share which version of yarn + what options you are using?

**Comment by jpx15** [comment]
I've encountered this error with npm workspaces as well.

**Comment by cincauhangus** [comment]
> Hey I tried to reproduce this issue in a basic yarn 4.5.0 workspace and couldn't could you make a basic repo where this reproduce? And can you share which version of yarn + what options you are using?

Apologies - I am running on yarn 3.5.x

Repo: https://github.com/cincauhangus/issue-typespec-4509

**Comment by timotheeguerin** [comment]
Thanks for the repro, i do get the error now as well with 0.60.0, for the  0.54, I'll assume that that part was fixed or the error is just showing in a different way.

What is intresting is it only seems to affect finding the emitter

**Comment by timotheeguerin** [comment]
ok so I found the issue, the problem is that openapi3 library request a dependency on `@typespec/openapi` and `@typespec/versioning` but those were not installed. 

If you add this to your package.json it works 
```json
    "@typespec/openapi": "^0.60.0",
    "@typespec/versioning": "^0.60.0"
```

what I don't really get is why yarn just silently ignore those not being present

**Comment by timotheeguerin** [comment]
Unfortunately it doesn't looks like yarn can install those automatically

**Comment by jpx15** [comment]
> ok so I found the issue, the problem is that openapi3 library request a dependency on `@typespec/openapi` and `@typespec/versioning` but those were not installed.
> 
> If you add this to your package.json it works
> 
> ```json
>     "@typespec/openapi": "^0.60.0",
>     "@typespec/versioning": "^0.60.0"
> ```
> 
> what I don't really get is why yarn just silently ignore those not being present
> 
> Edit: nvm it does ![image](https://private-user-images.githubusercontent.com/1031227/370797033-043054c5-671c-4ba3-8a67-28999ebf5aae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMDk4NTYsIm5iZiI6MTcyNzMwOTU1NiwicGF0aCI6Ii8xMDMxMjI3LzM3MDc5NzAzMy0wNDMwNTRjNS02NzFjLTRiYTMtOGE2Ny0yODk5OWViZjVhYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDAxMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTlhOWVkM2RmMjQ2NjNkODNhNjFiOGVmNjQwY2E3NTI5Nzc3MWQ0YmNhZjIwMjE3MWY1NWRjZjk1MjJkMDgwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oF37reBkZ2iYIQRe0ite1_XsZhr4hV1tPt_u5vdiiSk)

Installing both of these fixed the issue, thank you!

**Comment by cincauhangus** [comment]
> ok so I found the issue, the problem is that openapi3 library request a dependency on `@typespec/openapi` and `@typespec/versioning` but those were not installed.
> 
> If you add this to your package.json it works
> 
> ```json
>     "@typespec/openapi": "^0.60.0",
>     "@typespec/versioning": "^0.60.0"
> ```
> 
> what I don't really get is why yarn just silently ignore those not being present
> 
> Edit: nvm it does ![image](https://private-user-images.githubusercontent.com/1031227/370797033-043054c5-671c-4ba3-8a67-28999ebf5aae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTc0NDksIm5iZiI6MTcyNzMxNzE0OSwicGF0aCI6Ii8xMDMxMjI3LzM3MDc5NzAzMy0wNDMwNTRjNS02NzFjLTRiYTMtOGE2Ny0yODk5OWViZjVhYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDIxOTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE1MjAwZGFiY2U0ZThjZmY0YTYxNjU2ZDEyZGU2NWZiNzUxYTgwMDMwNTBmMGIwN2Y1MmRhMmRlM2JmZjU5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wN7uEWrvKodmJeWvSY5scPHPP6uuNaMxGhIB1InWGbE)

Can confirm that fixed the issue in both v0.54 and v0.60. Thanks for the support!

Do you want to keep this issue open, @timotheeguerin ?

**Comment by timotheeguerin** [comment]
Yeah, i think there is a few takeaway. Need docs for yarn, better error in that case that shows the root error. Find way to validate peer deps are actually installed.

**Comment by markcowl** [comment]
- use this to track yarn-specific docs
