### ISSUE TITLE
[Bug]: const cannot specify actual type of value

### ISSUE THREAD

**Issue by Arithmomaniac** [microsoft/typespec#4544]
### Describe the bug

Take the following model:
```
@example(foogood1)
@example(foogood2)
model Foo { Bar : string; }
```

I would expect both of these to be valid assignments:

```
const foogood1 : Foo = #{Bar: "good1"};
const foogood2 : {Bar : string} = #{Bar: "good2"};
```

But for some reason, `foogood1` is invalid, and gives an error message that is simply untrue:

> (unexpected-property) Object value may only specify known properties, and 'Bar' does not exist in type 'Foo'.

### Reproduction

In addition to the above, this [Playground link](https://typespec.io/playground?c=Y29uc3QgZm9vZ29vZDEgOiBGb28gPSAje0JhcjrFB3o6ICLFHSJ9fTsNCs0xMiA6IMQqxjhCYXJ91jwyxjwNCkBleGFtcGxlKMhyKdIUMikNCm1vZGVsxFQgew0KICDMYzsNCn3LIcQbxyR6IDogc3RyaW5nxCQ%3D&e=%40typespec%2Fopenapi3&options=%7B%7D) shows a slightly different example.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Arithmomaniac** [comment]
For what it's worth, you can't get around this bug by writing `foogood1 : { ... Foo  }` or `foogood1 : Foo & {}`.

Fixing this bug would make it easier to spot example validation errors by pushing the validation down from the decorator level to the specific line of the const that doesn't match the declared definition.

**Comment by timotheeguerin** [comment]
[Minimal repro](https://typespec.io/playground?c=Y29uc3QgZm9vZ29vZDE6IEZvbyA9ICN7IGE6ICJkZWYiIH07DQoNCkBleGFtcGxlKMgrKQ0KbW9kZWzFMnsNCiDEMnN0cmluZzsNCn0NCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)
