### ISSUE TITLE
[Feature]: VS Code Snippets for TypeSpec

### ISSUE THREAD

**Issue by archerzz** [microsoft/typespec#4559]
### Clear and concise description of the problem

[VS Code Snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) are quite useful for quick typing codes. We should add some common snippets through our VS code plugin for TypeSpec.

Like below:
![image](https://github.com/user-attachments/assets/22936095-00ab-4818-88a0-f97986d8214d)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
what kind of snippet are you thinking of? we cannot add any azure specific snippet directly in the raw extension

**Comment by archerzz** [comment]
> what kind of snippet are you thinking of? we cannot add any azure specific snippet directly in the base extension.
> 
> If so seems like the options is we either might be able to define snippet dynamically and need tsp library yo provide them in some way or provide an typespec azure snippet extension.

I think we can split snippets into different categories.
- fundamental snippets, like:
![image](https://github.com/user-attachments/assets/6fbe88fd-fafc-4f7d-8dae-55199e1d93fd)
  - I think that can go with TypeSpec extension
- snippets under specific circumstances, like Azure, those can be installed through separate snippet extension

**Comment by RodgeFu** [comment]
@archerzz , are you aware of any other Azure specific requirements for TypeSpec IDE. It will be helpful for us to triage and see whether we does need one more extension just for Azure specific features, or maybe it's easier and lower cost to just support dynamic code snippet if this is the only one requirement. thanks.

**Comment by archerzz** [comment]
> @archerzz , are you aware of any other Azure specific requirements for TypeSpec IDE. It will be helpful for us to triage and see whether we does need one more extension just for Azure specific features, or maybe it's easier and lower cost to just support dynamic code snippet if this is the only one requirement. thanks.

AFAICS,
- WYSWYG editor (consume output from TCGC to generate a hierarchy of client structure)
- Copilot to help compose service definitions (like Copilot 365)

**Comment by timotheeguerin** [comment]
Even if it was just snippet I do think it might be easier anyway to just make a snippet only extension, the only problem is discoverability for our users

**Comment by RodgeFu** [comment]
I am not sure, the dev cost is low, but my main concern is the maintain cost which is always something we need to think about for releasing something new. Or is it fine if we just make it internal, @archerzz ? I think an private release should be good enough, right?

As for discoverability, I guess we will need to have doc to tell service team what to do/install anyway.

**Comment by timotheeguerin** [comment]
the other option too is just to add the snippets to azure rest api spec repo

**Comment by RodgeFu** [comment]
The basic snippets has been added. Keep this open to track the work for snippets especially for azure service.

**Comment by timotheeguerin** [comment]
could maybe close this one and create a new one in typespec-azure if its now just azure specific

**Comment by archerzz** [comment]
> could maybe close this one and create a new one in typespec-azure if its now just azure specific

I agree. @RodgeFu Maybe we can create an issue under https://github.com/Azure/typespec-azure?

**Comment by RodgeFu** [comment]
Yeah, sounds good to me. thanks.

**Comment by timotheeguerin** [comment]
Created https://github.com/Azure/typespec-azure/issues/1770
