### ISSUE TITLE
Allow Import of Specific Files from a TypeSpec Library, Not Only main.tsp

### ISSUE THREAD

**Issue by ershov-konst** [microsoft/typespec#4562]
### Clear and concise description of the problem

# Problem/Current Limitation

Currently, TypeSpec only allows importing the `main.tsp` file from a library, which creates several limitations, especially for large libraries with hundreds of entities. This lack of granularity forces developers to include entire libraries, resulting in unnecessary entities being bundled into the output schema, even when only a small subset is needed. This can lead to bloated schemas, increased build complexity, and performance issues, such as slower IDE responsiveness and reduced efficiency in language services like auto-completion and validation. A more selective file import mechanism would address these issues.

# Feature Request

Add functionality to TypeSpec to allow importing specific files from within a library, not just the main.tsp file. 

## Proposed syntax
```
import "@org/typespec-library/lib/entities/particular-file.tsp";
import "@org/typespec-library/lib/version.tsp";
```
This would enable the import of specific files (`particular-file.tsp`) instead of being restricted to the main entry point.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mario-guerra** [comment]
+1 to following prior art and using [nodejs package exports](https://nodejs.org/api/packages.html#packages_exports).
