### ISSUE TITLE
[Bug]: tsp-openapi3: operation summaries not imported

### ISSUE THREAD

**Issue by Arithmomaniac** [microsoft/typespec#4614]
### Describe the bug

If a summary is provided on an operation in OpenAPI, it is not imported.

This may be related to #4489.

### Reproduction

- Attach a `@summary` decorator to an operation and see it emitted: [Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQHJvdXRlKCIvc3RyaW5ncyIpCkBzdW1tYXJ5KCJHZXQgU8oYZ2V0IG9wIGxpc3QoKTogxjJbXTs%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)
- Import that spec using "Import from OpenAPI 3.0" and the `@summary` is gone: [Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZb3BlbmFwadwcMyI7Cgp1c2luZyBIdHRwO8cMT3BlbkFQSTsKCkBzZXJ2aWNlKHsKICB0aXRsZTogIijFCSkiLAp9KQpAaW5mb8UfdmVyc2lvbjogIjAuMC4wxh9uYW1lc3BhY2XGPjsKCi8qKgogKiBUaGUgcmVxdWVzdCBoYXMgc3VjY2VlZGVkLgogKi8KbW9kZWwgbGlzdDIwMEFwcGxpY2F0aW9uSnNvblJlc3BvbnNlIMR2QHN0YXR1c0NvZGUgygs6IDIwMDvEH2JvZHlSb290IMQJOiBzdHJpbmdbXTsKfQoKQHJvdXRlKCIvxhZzIikgQGdldCBvcMV6KCk6%2FwCCOwo%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
est: 3
