### ISSUE TITLE
Open AI - Get vs List

### ISSUE THREAD

**Issue by JoshLove-msft** [microsoft/typespec#4621]
Pageable operations are prefixed with Get in Autorest, but in MGC we just use whatever operation name is there:
https://github.com/joseharriaga/openai-in-typespec/blob/main/.typespec/batch/operations.tsp#L47
https://github.com/joseharriaga/openai-in-typespec/blob/main/.dotnet/src/Custom/Batch/BatchClient.cs#L27

Determine what the correct naming is.

**Comment by m-nash** [comment]
I think the right answer is to honor the spec name and not be opinionated.  @clientName should be used on any operations that need a different name OR a plugin could be created to auto-update all list methods with Get prefix for openai.
