### ISSUE TITLE
Only run typespec/eng/emitters/scripts /Generate-APIView-CodeFile.ps for TypeScript/

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/typespec#4655]
https://github.com/microsoft/typespec/blob/010ebded10a3844f8cc4bdbd97072cc75a681065/eng/emitters/scripts/Generate-APIView-CodeFile.ps1

This file is only for TypeScript/JavaScript apiview, it should

- probably have a better name
- only used in TS/JS pipelines.

https://github.com/search?q=repo%3Amicrosoft%2Ftypespec%20Generate-APIView-CodeFile.ps1&type=code

**Comment by weidongxu-microsoft** [comment]
@jeremymeng 
Every language emitter has some typescript code (some may only have typescript code), so it seems valid to do apiview for emitter.

E.g. Java's TypeScript code https://github.com/microsoft/typespec/tree/main/packages/http-client-java/emitter/src

**Comment by jeremymeng** [comment]
So you need to review the api of emitters? Then that's valid.

**Comment by weidongxu-microsoft** [comment]
Got it. I see. Will find some time to update the script (and what it runs) so that it would work with 2.0.0

**Comment by jeremymeng** [comment]
@weidongxu-microsoft  FYI this is the change to move to 2.0.0 in the js sdk repo https://github.com/Azure/azure-sdk-for-js/pull/31407/files
