### ISSUE TITLE
[Bug]: Playground not loading

### ISSUE THREAD

**Issue by rahulpsd18** [microsoft/typespec#4674]
### Describe the bug

[Typespec Playground](https://typespec.io/playground) is stuck at `Loading libraries...` spinner state.

Browser console shows:
```
Uncaught (in promise) Error: Unable to resolve specifier '@typespec/streams' imported from https://typespec.io/playground
    at ke (es-module-shims.js:1:9614)
    at de (es-module-shims.js:1:9137)
    at pe (es-module-shims.js:1:9451)
    at async me (es-module-shims.js:1:9496)
    at async g (35983.b1d0d1dc.js:8:392090)
    at async 35983.b1d0d1dc.js:8:387747
```

Tested in chrome and firefox (both latest versions).

### Reproduction

https://typespec.io/playground

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chrisradek** [comment]
@rahulpsd18  Thanks for reporting this issue! It should be back up and running now!
