### ISSUE TITLE
Enum based discriminator generates incorrect OpenAPI code

### ISSUE THREAD

**Issue by PetrPytelka** [microsoft/typespec#4707]
It seems to me that OpenAPI code generated for enum based discriminator is incorrect. Here is link to an example from the TypeSpec documentation and the generated code:

[Playground Link](https://typespec.io/playground?c=ZW51bSBQZXRLaW5kIHsNCiAgY2F0LMQIZG9nLA0KfQ0KDQpAZGlzY3JpbWluYXRvcigia2luZCIpDQptb2RlbMQ%2BxjrEFzrITTvEEm5hbWU6IHN0cmluZ8URd2VpZ2h0PzogZmxvYXQzMjvFYsZIQ2F0IGV4dGVuZHPXVC5jYXTFR21lb3c6IGluz0JEb2ffQi5kb%2BYAiWJhcmvrAJp9&e=%40typespec%2Fopenapi3&options=%7B%7D)

The problem is that property 'kind' is generated directly inside the Dog and Cat objects and also inhereted from Pet schema due to the declaration: "allOf: - $ref: '#/components/schemas/Pet'".

There is very similar example in the OpenAPI specification in the paragraph: https://spec.openapis.org/oas/latest.html#fixed-fields-20, see part "For example:".  That example does not repeat discriminator in each object. The current solution causes a problem when generating code from OpenAPI. The enum is generated twice - first time from the abstract class with all items, and then as inner class for each enum nested insided the Dog and Cat types.

My conlucision: Extended models (Cat, Dog) should not contained repeated declarations of discriminator because it is automatically included due to the  allOf operator while including the base model (Pet).

**Comment by wanlwanl** [comment]
+ @skywing918 for awareness

**Comment by timotheeguerin** [comment]
I am not sure this is incorrect openapi code. I think we are describing things correctly. The `kind` property is not exactly the same as what the parent is. OpenAPI3 doesn't require you to redefine it because it has the discriminator implicitly defining the value and use allOf to inherit the property but I think the way we have it is also valid

**Comment by wanlwanl** [comment]
> I am not sure this is incorrect openapi code. I think we are describing things correctly. The `kind` property is not exactly the same as what the parent is. OpenAPI3 doesn't require you to redefine it because it has the discriminator implicitly defining the value and use allOf to inherit the property but I think the way we have it is also valid

Hi @PetrPytelka , what do you think about [timotheeguerin](https://github.com/timotheeguerin)'s comment.
Looks like it's correct.

**Comment by PetrPytelka** [comment]
Spell check and correct following text as native speaker. Text is reponse on the discussion on github (Enum based discriminator generates incorrect OpenAPI code · Issue #4707 · microsoft/typespec<https://github.com/microsoft/typespec/issues/4707>). Text to check: I think that for this discussion we would need some person from OpenAPI Specification team who should help us decide how the OpenAPI specification was meant for this case. My reality is that code generated by OpenAPI emitter cannot be directly used and has to be manually edited. I do not understand what is the benefit of the more complicated OpenAPI code instead of generating shorter code with no such obstacles.

I would like to ask:
What is the motivation of emitting code different ways for disciminators?
Is it possible to generate same code for both of them?

If we will have such answers we might ask somebody from OpenAPI Specification team or on the other hand try to simplifiie implementation in TypeSpec and generate same code for both cases.




________________________________
Od: microsoft-github-policy-service[bot] ***@***.***>
Odesláno: pondělí 4. listopadu 2024 16:51
Komu: microsoft/typespec ***@***.***>
Kopie: Petr Pytelka ***@***.***>; Assign ***@***.***>
Předmět: Re: [microsoft/typespec] Enum based discriminator generates incorrect OpenAPI code (Issue #4707)


Assigned #4707<https://github.com/microsoft/typespec/issues/4707> to @PetrPytelka<https://github.com/PetrPytelka>.

**Comment by PetrPytelka** [comment]
I think we might need input from someone on the OpenAPI Specification team to help us determine the intended use of the OpenAPI specification in this case. Currently, the code generated by the OpenAPI emitter cannot be used directly and requires manual editing. I don’t understand the benefit of generating more complex OpenAPI code when shorter, obstacle-free code could be produced.

I have a few questions:

What is the motivation behind emitting code in different ways for discriminators?
Is it possible to generate the same code for both cases?
With answers to these questions, we could either consult the OpenAPI Specification team or consider simplifying the implementation in TypeSpec to generate the same code for both cases.
