### ISSUE TITLE
Feature Request: Add parameter decorator `@cookie` to specify that is `in: cookie`

### ISSUE THREAD

**Issue by su8ru** [microsoft/typespec#4739]
### Clear and concise description of the problem

There is no way to decorate parameters in the cookie.
So, add `@cookie` decorator like `@header` to decorate the parameter is in the cookie.

- https://github.com/microsoft/typespec/discussions/4721

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://typespec.io/docs/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
- note that contribution does not contain openapi3 support, which would be needed

**Comment by su8ru** [comment]
@markcowl I think #4761 will include openapi3 support to fix type errors.
If it seems that other libraries also need to be supported, I am thinking of removing the close keyword from #4761 and unlinking it to leave this issue, what do you think?
