### ISSUE TITLE
[linter] Add linter to not allow `@encode("string") prop: int32`

### ISSUE THREAD

**Issue by MaryGao** [microsoft/typespec#4817]
### Clear and concise description of the problem

I think for `encode int as string` the only valid encode data would be `string scalar` type in encode decorator. So if we write string literal in encode for numeric type we shoud warn them out.

[playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=bW9kZWwgRm9vIHsNCiAgQGVuY29kZShzdHJpbmcpxBNwcm9wMTogaW50MzI7DQrMJiLGJyLJKDI6IGRlY2ltYWzQKm51bWJlcsoqMzogZmxvYXQ7DQp9DQpvcCBwb3N0KGJvZHk65ACOKTogdm9pZDsNCg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)
```
model Foo {
  @encode(string)
  prop1: int32;

  @encode("string")
  prop2: decimal;

  @encode("int32")
  prop3: float;
}
op post(body: Foo): void;

```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://typespec.io/docs/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
Dup of https://github.com/Azure/typespec-azure/issues/1277, @MaryGao for now all linters ware only azure linters please file those issue in the correct repo.
