### ISSUE TITLE
Cannot augment properties in nested anonymous model

### ISSUE THREAD

**Issue by MaryGao** [microsoft/typespec#4818]
### Clear and concise description of the problem

This is an idea when we tried to solve the breaking [issue](https://github.com/Azure/typespec-azure/issues/1717) during migrating swagger to typespec for anonymous model. The naming rule is different between them and one solution would be to location that model and use clientName decorator to rename it.

```
model Foo {
  bar: {
    baz: string;
  }
}
```
Then in decorator we could have a way like`Foo.bar::type` to location that model then we could add decorator like other models.

```
// add doc into that model
@@doc(Foo.bar.Type, "This is demo for doc with anonymous model");
// give a name for that model
@@clientName(Foo.bar.Type, "NamedBarType");
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://typespec.io/docs/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
Did talk with people about that recently, the main problem is that the anonymous model can have multiple parent when using alias. But maybe then its ok to try to resolve the alias name or it is an antipattern.

**Comment by markcowl** [comment]
@MaryGao You should be able to use type metadata to do this (`Foo.bar::type`) but this is currently broken and may be fixed by the attached issue.

**Comment by MaryGao** [comment]
@markcowl which issue you mentioned? I found it is not working yet.

[playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=QGRvYygiQSdzIGRvY3VtZW50IikNCm1vZGVsIEEgew0KICBhOsYIICBzOiBzdHJpbmc7xBB9DQp9DQoNCkDFREEuYTo6dHlwZSwgIkTHSyBmb3IgYW5vbnltb3VzIMVWIik7&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)
```
@doc("A's document")
model A {
  a: {
    s: string;
  }
}

@@doc(A.a::type, "Document for anonymous model");
```
