### ISSUE TITLE
[linter]discourage to use anonymous model and always give a model name

### ISSUE THREAD

**Issue by MaryGao** [microsoft/typespec#4819]
### Clear and concise description of the problem

Offline discussed with @ArcturusZhang and we think anomymous model may not be a good practice and we should encourage to give a name for models especially for exposed public APIs.

Most of downstreaming language emitters may not have ability to handle inline expressions like typespec so they need to GUESS a name for anomymous models. This could introduce uncertainty if downstreaming name rule is different and for example the name rule introduced breakings between m4 and tcgc and one issue happened in common types is tracked [here](https://github.com/Azure/typespec-azure/issues/1717).

Even we could find a name rule and these names could be fragile and it would be changed with its context or code order if conflicting happened. 

For example in TCGC we try to guess this name according to context, including `parent model name + property name + model type`. So the name could be changed once any of these factors changed. Also we may name some models during conflicting and any code order changes would impact the generated code.

```
model Ab {
  c: {
    foo: string;
  };
}

// vs
model A {
  b: {
    c: {
      foo: string;
    };
  };
}
```

Can we add a linter to discourage the anonymous model in typespec? Especially in azure could we avoid using anonymous model then?

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://typespec.io/docs/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
We already discussed that in teh past and due to a lot of anonymous model used for config and templates it is not possible to do a generic version. This should be a tcgc issue which has a picture of when things are anonymous.

**Comment by MaryGao** [comment]
Closed this as filed [one ](https://github.com/Azure/typespec-azure/issues/1727)in typespec-azure repo.
