### ISSUE TITLE
Support for emitters in other languages via IPC

### ISSUE THREAD

**Issue by bterlson** [microsoft/typespec#482]
## Background

It is a fact of life that the folks most qualified to implement an emitter in a particular language are likely highly specialized in that language and will prefer to author their emitter in it. Today, this is not trivial. In general, there seem like two options:

1. WASM - either Cadl compiles to wasm so it can be hosted anywhere wasm can, or emitters are compiled to wasm so they can be hosted in the compiler.
2. Some IPC protocol for emitters to query the compiler.

These are not mutually exclusive options and so we should explore the IPC approach as it would support a broader range of languages and environments.

### @cadl-lang/json-rpc

@timotheeguerin proposed that we use json-rpc for the protocol layer of this IPC. json-rpc is used fairly heavily in industry so this could make a good addition to cadl-lang's emitter suite.

This library would define any decorators needed to support declaring metadata required for rich json-rpc definitions in CADL. We could also support multiple language targets in this package since probably the complexity is not super high.

Things needed:
  - `@requestId` decorator to specify the name/id of the request
  
  ```cadl
  @requestId("FOO_BAR")
  op fooBar(""): JsonResponse;
  ```
  
  - Missing need eventing/notification system which jsonrpc support: This would be a good use case for the @stream proposal and see any issues with it.

### @cadl-lang/ipc

This package declares a .cadl file for the json-rpc projection of @cadl-lang/compiler's APIs. Emitters would use these APIs for low-level access to the compiler output including:

* Walking and querying the type graph
* Accessing metadata stored in state maps
* Core types e.g. envelopes for non-JSON types like maps
* Additional helpers commonly useful for emitters

This layer would also ensure that key semantics of the cadl type graph like type identity (` model A { }; model B { x: A };` results in `B.properties.get('x').type === A`) are marshalled across the ipc channel.

Example of what the cadl for this would look like

```cadl

model RemoteObjectMeta {
  kind: "object";
  id: number;
  members: RemoteObjectMember[];
}

model RemoteObjectMember {
  type: "property" | "method";
  key: string;
}

model RemoteArrayMeta {
  type: "array";
  key: string;
}

model ValueMeta {
  type: "value";
  value: number | boolean | string;
}

union RemoteMeta {
  object: RemoteObjectMeta;
  array: RemoteArrayMeta;

}

@requestId("CADL_OBJECT_METHOD_CALL")
op callMethod(objectId: number, methodName: string, args: RemoteMeta[]): RemoteMeta;

@requestId("CADL_OBJECT_PROPERTY_GET")
op getProperty(objectId: number, propertyName: string): RemoteMeta;

@requestId("CADL_IMPORT_MODULE")
op importModule(name: string): RemoteObjectMeta;
```

### Libraries

Libraries will want to expose additional APIs that should be projected over the IPC channel. While it should be possible to get by with only the APIs provided by @cadl-lang/ipc, higher-level convenience APIs provided by libraries will allow code reuse between emitters authored in JS and emitters authored using the IPC bridge. Without this, emitters authored in other languages will likely want to re-implement all the helpers exposed by libraries like @cadl-lang/rest, @cadl-lang/openapi, etc.

Libraries should be able to declare a .cadl file for their own json-rpc projections similar to what @cadl-lang/ipc does. We can likely establish some convention for how these .cadl files are authored and mapped to their library implementation which wouldn't require libraries to write any code to achieve the json-rpc projection.

Example of what the libraries could look like. It is completly unaware that this is going through ipc and could be the interface the for service itself.

```cadl
namespace Cadl.Compiler;

model Program {
  compilerOptions: CompilerOptions;
}

model CompilerOptions {
  outputPath: string;
  noEmit?: boolean;
  nostd?: boolean;
}
```

```cadl
namespace Cadl.Rest;

op getAllRoutes(program: Cadl.Compiler.Program): OperationDetails[];

model OperationsDetails {
  path: string;
  verb: string;
}
```

### Emitters

Emitters authored in e.g. C# can now generate json-rpc bindings for the core compiler APIs and any libraries they wish to support by including the appropriate cadl source files. This would light up a fully typed and convenient API that would be on par with the JS-native API (modulo worse performance due to the json-rpc marshalling).

**Comment by attilah** [comment]
Any plans on doing this? 

Having an API and an active channel during the emit phase to query the active code generation context in TypeSpec for additional information like `hasDecorator('immutable')` potentially could solve the need to have custom Code Models I was writing about in this [discussion](https://github.com/microsoft/typespec/discussions/3129#discussioncomment-9300015).
