### ISSUE TITLE
Make it easier for end user to trigger emitting in vscode

### ISSUE THREAD

**Issue by RodgeFu** [microsoft/typespec#4856]
### Clear and concise description of the problem

user should be able to choose and trigger emitter easily in vscode

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://typespec.io/docs/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by josefree** [comment]
Do this include how to add a new emitter to the extension?

**Comment by RodgeFu** [comment]
yeah, current rough idea is that new emitters can be configured in repo as needed (i.e. define it in .vscode folder somehow). We will have more discussion on how further we can configure according to the detail request from the detail codegen. Thanks.

**Comment by RodgeFu** [comment]
the non-branded scenario is tracking by #5025 including the CodeGen part.

**Comment by chunyu3** [comment]
duplicate with https://github.com/microsoft/typespec/issues/5025
