### ISSUE TITLE
Add documentation for the `#deprecated` directive

### ISSUE THREAD

**Issue by scarletcs** [microsoft/typespec#4864]
The documentation for [`@deprecated`](https://typespec.io/docs/standard-library/built-in-decorators/#@deprecated) is deprecated, as noted on its page, per issue #2214, and says the following on its page:

> **Deprecated:** `@deprecated` decorator is deprecated. Use the `#deprecated` directive instead.

That much is all fine.

However, there is no documentation on the `#deprecated` directive.

- The instruction to use the `#deprecated` directive does not link to documentation for the new feature. (It should!)
- There is no page titled `#deprecated`.
- There is no page titled Directives, or dedicated to explaining what directives are and which directives exist.
- There is no entry for Directives in the Language Basics table of contents. Its [overview page](https://typespec.io/docs/language-basics/overview/) also does not mention directives.

The _example_ for `@deprecated` says to use the deprecated directive and provides the only example I can find of using it, but this is not exactly primary documentation for `#deprecated` or for what a directive is or what makes it different to a decorator.

**Comment by markcowl** [comment]
est: 1
