### ISSUE TITLE
[Bug]: Compiler crashes when importing mjs

### ISSUE THREAD

**Issue by crowbait** [microsoft/typespec#4878]
### Describe the bug

While trying to implement a decorator, I didn't want to create an entire package for a few lines of code.
This seems convoluted.

Since the project this spec is located in is not a module, I have to use mjs files to be able to use imports.
This leads to the following, as soon as I import the mjs file:
> ExternalError: Emitter "@typespec/openapi3" crashed!

Since this is a very slim project, I'm hestitant to make it more extensive as it needs to be. So my battle plan is:
- separate tsconfig for my tsp "helper"s
- run tsc on this specific config before running tsp

### partial.mts
```ts
import {DecoratorContext, Model, ModelProperty, validateDecoratorTarget} from '@typespec/compiler';

function updateModelPropertiesInPlace(
  model: Model,
  callback: (key: string, prop: ModelProperty) => ModelProperty
): void {
  for (const [key, prop] of model.properties) {
    const updatedProp = callback(key, prop);
    model.properties.set(key, updatedProp);
  }
}

export const $withPartial = (
  context: DecoratorContext,
  target: Model
): void => {
  if (!validateDecoratorTarget(context, target, '@withPartial', 'Model')) {
    return;
  }
  updateModelPropertiesInPlace(target, (key, prop) => {
    if (prop.optional) return prop;
    return {...prop, optional: true};
  });
};
```

### partial.tsp
```
import "./partial.mjs";
using TypeSpec.Reflection;
extern dec withPartial(target: Model);
```

### helpers.tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2019",
    "module": "Node16",
    "moduleResolution": "Node16",
    "rootDir": ".",
    "outDir": ".",
    "strict": true
  },
  "include": ["./*.mts"],
  "exclude": ["node_modules"]
}
```

Calling `tsc -p helpers.tsconfig.json` compiles without errors, the output mjs looks fine, but as soon as `import "./partial.mjs";` is hit in the tsp file, TypeSpec crashes on me.

Is there a better way of extending TypeSpec to my needs? I feel like extending the framework (especially with something as light as this) wouldn't / shouldn't need the entire overhead of managing an entirely separate package.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by crowbait** [comment]
This is my try to make use of this comment: https://github.com/microsoft/typespec/discussions/4230#discussioncomment-10412266

**Comment by timotheeguerin** [comment]
my guess of what might be failing here is the clone of the type, you should probably just do `.partial = true` or it will not have the same property reference depending on what referenced it.

**Comment by crowbait** [comment]
> my guess of what might be failing here is the clone of the type, you should probably just do `.partial = true` or it will not have the same property reference depending on what referenced it.

To be absolutely honest, I didn't understand of lot of that ... I'm *very* new to TypeSpec.
BUT, you were absolutely right. The spread-cloning of the prop was an issue and I've changed my TS function to the following (which now works great):
```ts
export const $withPartial = (
  context: DecoratorContext,
  target: Model
): void => {
  if (!validateDecoratorTarget(context, target, '@withPartial', 'Model')) {
    return;
  }
  updateModelPropertiesInPlace(target, (key, prop) => {
    prop.optional = true;
    return prop;
  });
};
```
