### ISSUE TITLE
OpenAPI3 Converted produce invalid typespec for empty schema

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#4923]
```yaml
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components: 
  schemas:
    Foo: {}
```

produce invalid typespec with `scalar extends unknown`

[Playground Link](https://typespec.io/playground/?c=CiAgaW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI71RtvcGVuYXBp3h4zIjsKCiAgdXNpbmcgSHR0cMQuxg5PcGVuQVBJxSAKICAgIEBzZXJ2aWNlKHvFDyAgdGl0bGU6ICIoxQkpIsUXfSnGLWluZm8oeyJ2ZXJzaW9uIjoiMC4wLjAixx8KbmFtZXNwYWNlxkbFZnNjYWxhciBGb28gZXh0ZW5kcyB1bmtub3duxR%2FFBCAg&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by JamesChen-us** [comment]
Hey Timothee, I've started working on this ticket and identified a fix to prevent this issue. Is there anything else I should consider when implementing this fix, or any additional details that might be helpful?
