### ISSUE TITLE
[Bug]: OpenAPI3 YAML emitter causes the Norway problem

### ISSUE THREAD

**Issue by fiendish** [microsoft/typespec#4983]
### Describe the bug

The openapi yaml emitter causes the Norway problem because it doesn't quote strings properly.

```typescript
model A {
    @example("no")
    a?: string;
    @example("yes")
    b?: string;
}

@example(#{a: "no", b: "yes"})
model B {
    a?: string;
    b?: string;
}
```

becomes

```yaml
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components:
  schemas:
    A:
      type: object
      properties:
        a:
          type: string
          example: no
        b:
          type: string
          example: yes
    B:
      type: object
      properties:
        a:
          type: string
        b:
          type: string
      example:
        a: no
        b: yes
```

All of those `no` and `yes` must be quoted, because otherwise they become boolean `False` and `True` when the yaml is parsed.

The optionality of quoting strings in yaml is fundamentally dangerous. Please just quote all strings.

### Reproduction

[Playground Link](https://typespec.io/playground/?c=bW9kZWwgQSB7CiAgICBAZXhhbXBsZSgibm8iKcUTYT86IHN0cmluZzvPI3llc8ckYsskfQoKySMje2E6IMRLLCBiOiDFMX0pCsZzQsdz0GDNTA%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Kinda feels like this might be more a problem with the parser, this is valid emitted yaml 1.2 no?

We could consider adding an option to emit 1.1 if the yaml library allows it which is not super clear from their doc(I see they allow on parsing but don't know for stringify).

**Comment by fiendish** [comment]
Oh wow! TIL yaml got an update for this a very long time ago and just didn't get any support in some widely used parsers. Apologies, and thanks for that correction. Don't I feel foolish now.

This creates a kind of weird situation for openapi generation, because they do say that 1.2 is "recommended", but then that leaves the world in a kind of weird state re. parsing incapability, buuuuuut that's not your problem. I'm just going to close this issue.
