### ISSUE TITLE
[http-server-csharp] no `csproj` or scaffolding is generated

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#4999]
When I could generate the server code from a tsp, no scaffolding is generated at all.

This might be expected and by design, but I think to generate a scaffolding could play an important role on the API-first path.
If we are following the API-first path, we should have a way to keep the generated part of the server code clean and deterministic.

**Comment by markcowl** [comment]
Closign as duplicate: https://github.com/microsoft/typespec/issues/3913
