### ISSUE TITLE
[Bug]: undefined property in @typespec/compiler/dist/src/core/diagnostics.js:87:36

### ISSUE THREAD

**Issue by archerzz** [microsoft/typespec#5007]
## Problem

TSP 0.62.

This was found by both .net and java teams. See an error in build pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4308242&view=logs&j=d731b843-2b38-5e88-bb49-012fa10bc295&t=f10e5fff-58d7-557f-26b5-c063ad57cd53&l=594
```
TypeError: Cannot read properties of undefined (reading 'node')
at getDiagnosticTemplateInstantitationTrace (file:///D:/a/_work/1/s/azure-sdk/sdk/communication/Azure.Communication.ProgrammableConnectivity/node_modules/@typespec/compiler/dist/src/core/diagnostics.js:87:36)
```

We successfully reproduced this issue on local. With `--debug` option, there are a few warnings, like below;
```
C:/Users/mingzhehuang/workspaces/azure/azure-sdk-for-net/sdk/easm/Azure.Analytics.Defender.Easm/TempTypeSpecFiles/Easm/models.tsp:1025:1 - warning deprecated: Deprecated: Use `@encodedName` instead for changing the name over the wire.
C:/Users/mingzhehuang/workspaces/azure/azure-sdk-for-net/sdk/easm/Azure.Analytics.Defender.Easm/TempTypeSpecFiles/Easm/models.tsp:1200:1 - warning deprecated: Deprecated: Use `@encodedName` instead for changing the name over the wire.
```

If you check the build logs on top, you'll find that the SDK was actually generated successfully. Looks like the diagnostics logic of compiler has a bug when handling underlying warnings.

### Reproduction

- Go to the SDK folder, like `PATH_TO_SDK_REO/sdk/communications/Azure.Communication.ProgrammableConnectivity/src`
- Run `npx --no-install --package=@azure-tools/typespec-client-generator-cli --yes tsp-client update --no-prompt --output-dir PATH_TO_SDK_REPO\sdk\communication\Azure.Communication.ProgrammableConnectivity\src/../ --debug`

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Just FYI those are not very useful repro, it involve cloning 3 different repos, going through tsp client making it impossible to debug, would it be possible to get the typespec causing the issue next time

**Comment by timotheeguerin** [comment]
ok I think this is due to using a mismatch of compiler version here... tsp client uses the latest but runs what current setup of the repo. SO the diagnostics are not emitted with that property.
As we do not support cross version still this feels like an issue with tsp-client. @catalinaperalta i think need to update tsp client to use `formatDiagnostic` from this import instead of global top https://github.com/Azure/azure-sdk-tools/blob/59d869dd3abdbc1aa6d8d3935f9c52fe3ba6d37a/tools/tsp-client/src/typespec.ts#L78

**Comment by timotheeguerin** [comment]
opened a pr in sdk tools repo to fix it in tsp client https://github.com/Azure/azure-sdk-tools/pull/9348
