### ISSUE TITLE
openapi 3.1 - support json schema dialect for openapi schemas

### ISSUE THREAD

**Issue by chrisradek** [microsoft/typespec#5009]
Open API 3.1 schemas are a superset of Json Schema [draft 2020-12](https://json-schema.org/draft/2020-12/json-schema-core). This is different from Open API 3.0 where Open API schemas only supported a subset of [draft-06](https://json-schema.org/draft-06) (while also including some metadata like `nullable` instead of using `type: "null"`)

This issue tracks updating/creating the Open API 3.1 schema emitter to target Json Schema 2020-12.

This will involve
- Creating JSON Schema 2020-12 types that the Open API 3.1 schema type can reference
- Creating an Open API 3.1 schema emitter that targets the Open API 3.1 schema types

**Comment by markcowl** [comment]
est: 8
