### ISSUE TITLE
openapi 3.1 - add support for defining schema type as a list

### ISSUE THREAD

**Issue by chrisradek** [microsoft/typespec#5011]
In Open API 3.0, the Open API schema `type` field could only be a single string value.

In Open API 3.1, the Open API schema `type` field can be an array of string values.

This is especially useful when defining enums that are backed by multiple types.

Take the following TypeSpec example:

```tsp
enum PetType { asString: "dog", asNumber: 1}
```
Our Open API 3.0 emitter will emit an error because enum can be a number or a string, but Open API schemas only support a single type. (Side note: could we support this via `anyOf` with multiple enum subschemas for Open API 3.0?)

With Open API 3.1, we could emit this valid schema (which our Json Schema emitter already does):
```yaml
PetType:
  type:
    - string
    - number
  enum:
    - dog
    - 1
```

**Comment by markcowl** [comment]
est: 5
