### ISSUE TITLE
[http-server-csharp] Optional parameters are not properly ordered in generated code

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#5023]
We have this snippet generated for [the contoso project](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/contosowidgetmanager/Contoso.WidgetManager/main.tsp#L50):
```csharp
        ///<summary>
        /// Creates or updates a Widget asynchronously.
        ///</summary>
        [HttpPatch]
        [Route("/widgets/{widgetName}")]
        [ProducesResponseType((int)HttpStatusCode.Created, Type = typeof(WidgetSuite))]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(WidgetSuite))]
        public virtual async Task<IActionResult> CreateOrUpdateWidget([FromQuery(Name = "api-version")] string apiVersion, string widgetName, [FromHeader(Name = "Content-Type")] string contentType = "application/merge-patch+json", WidgetSuite body)
        {
            var result = await WidgetsImpl.CreateOrUpdateWidgetAsync(apiVersion, widgetName, contentType, body);
            return Ok(result);
        }
```
The required parameter `body` appears after another optional parameter.

**Comment by ArcturusZhang** [comment]
Hi @markcowl this issue must be resolved to let todoApp generate compilable code - could you share some insights on why this has been put into the backlog?

**Comment by ArcturusZhang** [comment]
This issue also shows up in the todoApp project's generated code: https://github.com/allenjzhang/typespec-e2e-demo/blob/2abc70f27d1e5344ce286462fa77ab887abbc228/todoApp/servers/aspnet/generated/controllers/AttachmentsOperationsControllerBase.cs#L36

**Comment by markcowl** [comment]
Fixed in this PR: https://github.com/microsoft/typespec/pull/5417

Sample generated code, with simple todoApp service Impl here: https://github.com/allenjzhang/typespec-e2e-demo/pull/47
