### ISSUE TITLE
[http-server-csharp] literal type is not properly generated

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#5024]
In the contoso project, we have this interface generated:
```csharp
public interface IWidgets
{
	Task<WidgetSuite> CreateOrUpdateWidgetAsync(string apiVersion, string widgetName, "application/merge-patch+json" contentType, WidgetSuite resource);
}
```
It misuses a `string` value as the type of `contentType` which is incorrect.
This might be indicating the generator is not properly handling the literal types.

**Comment by markcowl** [comment]
- yeah, this now requires doing real processing of ValueType
