### ISSUE TITLE
[Bug]: http-client-java, there is no CoreUtils.durationToStringWithDays in unbranded core

### ISSUE THREAD

**Issue by weidongxu-microsoft** [microsoft/typespec#5031]
### Describe the bug

Generated code contains `CoreUtils.durationToStringWithDays`, but no such class in unbranded core.

I cannot find class/util with similar functionality there.

### Reproduction

unbranded for https://github.com/joseharriaga/openai-in-typespec/blob/main/.typespec/main.tsp

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alzimmermsft** [comment]
For now, I think this is a case where unbranded generation should generate a utility method for this locally. I'd want to err against some of these utility methods in unbranded Core until we determine why they were added in the past. For example, `CoreUtils.durationToStringWithDays` was added as `azure-core`'s `Duration` serializer had this as custom implementation, so it was added to support `azure-json` in a non-breaking way but I need to find why `Duration` was serializing like that in the first place.
