### ISSUE TITLE
[Bug]: [Ask]Ambiguous-symbol "nextLink" is an ambiguous name between TypeSpec.nextLink, Azure.Core.nextLink

### ISSUE THREAD

**Issue by MaryGao** [microsoft/typespec#5048]
### Describe the bug

With below spec we received 1 errors with `Ambiguous-symbol "nextLink" is an ambiguous name between TypeSpec.nextLink, Azure.Core.nextLink`. I think this is because we both have nextLink decoration in TypeSpec and Azure.Core scope. And adding prefix could fix this issue. But I was wondering following questions regarding these decorators.
- Are the duplicated decorators expecetd? Which one is preferred to use in Azure?
- For custom paging what is the recommanded practice, [typespec support](https://github.com/microsoft/typespec/issues/705) vs azure core support?

[playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGnZlcnNpb25pbmfNIGF6dXJlLXRvb2xzL8gsLcYVY29yZcQsDQp1c2luZyBUeXBlU3BlYy5SZXN0O9EWSHR0cNIWVsl3yRxBxF4uQ29yZcVdI3N1cHByZXNz%2FwCOb3JlL2F1dGgtcmVxdWlyZWQiICJmb3IgdOQA8w0KQHNlcnZpY2Uoew0KICB0aXRsZTogIsVs5gCOY3JpcHQgVGVzdOQBBCwNCn0pDQpuYW1lc3BhY2XnAJbKKi7HKuUApEBlcnJvcg0KbW9kZWwgRcQNIMVoY29kZTogaW50MzI7xBBtZXNzYWdlOiBzdHLGPX3FQHBhZ2VkUmVzdWx0yEZCYcdEQGl0ZW1zxApsaXN0c8g8W13FeyAgQG5leHRMaW5rxA3IDNBixlRDaGlsZCBleHRlbmRzymL5AJZvc3QNCm9w5QFEKCk65wDafMZIOw0K&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

```
@pagedResult
model Bar {
  @items
  items: string[];

  @nextLink
  nextLink: url;
}

// vs

model Page<T> {
  @nextLink nextLink: url;

  @pageItems
  items: T[];
}

@list op Foo(): Page<string>;
```

### Reproduction

NA

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MaryGao** [comment]
Another question is if we could accept array as paged items directly ?

[playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvY29tcGlsZXIiOw0K0h5odHRwxBoNCnVzaW5nIFR5cGVTcGVjLkh0dHDFGEBsaXN0IG9wIEZvbygpOiBzdHJpbmdbXTsNCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)
![Image](https://github.com/user-attachments/assets/74556207-d68c-4610-949a-b8c51b51220d)

**Comment by wanlwanl** [comment]
@AlitzelMendez  Could you take a look at https://github.com/Azure/azure-sdk-tools/issues/9554
