### ISSUE TITLE
[http-server-csharp] No interfaces and controllers generated when `op`s are wrapped inside a namespace

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#5125]
I saw this issue when I am trying to generate the petstore: https://github.com/microsoft/typespec/tree/main/packages/samples/specs/petstore
Because of [this issue](https://github.com/microsoft/typespec/issues/5124), I removed everything related with templated models (including models and operations), and only models are generated.

FYI, changing `namespace` to `interface` would do the trick. But this does not really make sense, namespace should work just fine.

**Comment by markcowl** [comment]
I think this is fixed by: https://github.com/microsoft/typespec/pull/5140
