### ISSUE TITLE
Support named examples (a la OpenAPI 3) on parameters, request bodies, responses, models, and model properties

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#514]
We should have a mechanism to provide examples right in the Cadl file for individual parameters / model properties.

In OpenAPI 3 there is the ability to specify named examples on parameters, request bodies, and response bodies. So all example values with a common name, like "Creating a yellow widget", can be viewed as an example of a request and the expected response to that request. This is useful for documentation but also for test generation.

**Comment by markcowl** [comment]
Proposal is here: https://gist.github.com/markcowl/a45d32be8d2f25c87df196672605415c

**Comment by markcowl** [comment]
Update proposal to scope down to support beta release of OpenAPI3

**Comment by MaryGao** [comment]
@markcowl Do we have any timeline for this task?

**Comment by markcowl** [comment]
@MaryGao  Can you tell me what you want this for?  This is just about adding example values in TypeSpec, not requrest/response example generation (which is already provided by OAV and used with the typespec-autorest emitter)

**Comment by MaryGao** [comment]
@markcowl Sorry I missed the scope for this issue, what we(language emitter) really want is the native requrest/response example generation support in TypeSpec. Do we have any plan for that?

**Comment by markcowl** [comment]
Why do you want request/response example generation?  What is the value of having generated examples for each operation when we already have an operation description?

If you want this for validation, it seems like what you really want are captures from actual service test traffic.
If what you want is documentation, then it seems like you really want people to author examples

If there is some other scenario, I would be very interested in hearing it.

**Comment by markcowl** [comment]
Updated proposal: https://gist.github.com/markcowl/bdc3ad5267918d34a11cd4fb9503b192

**Comment by DMaro28** [comment]
Us at LSEG would benefit greatly from implementation of request/response examples. Both internally as API designers in communication with implementation dev teams, as well as for documentation purposes/readability for customers. One additional benefit is that we are told that examples would help in training of Microsoft 365 Copilot that we intend to implement.

**Comment by adam-pawlowicz** [comment]
At my company we are using tsp for designing our API services, it would be highly beneficial if we could include examples in the specification (in the same manner as this is done in the OpenAPI 3). We would like to be able to use the code generator, maybe even an emitter to generate the examples in the desired format which would be required for deployment & testing.

**Comment by mikekistler** [comment]
Is there an implementation issue for this work? If so, please link it here. If not, please create one and link it here. The implementation issue should be tagged as pri 0 for public beta.
