### ISSUE TITLE
[http-server-csharp]: Fix issues with ToDoList spec service generation

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#5179]
Some issues to correct with ToDoList spec

- [x] `toDoItem._dummy`:  need to preserve serialized name when creating identifiers
- [x] Correct property narrowing in inherited property overrides (`userExistsResponse`, `invalidUserResponse`)
    - Make property virtual or abstract in the base type
    - intentionally override property in derived type with 'new' keyword
- [x] Fix handling of anonymous models (`toDoPage.pagination`)
- [x] Add special case for coalescing nullable type unions (do not represent as object)
- [ ] Convert content-type into constraint (`toDoItems.create`)
- [ ] Provide pattern for UserExists error on create and 404 response on get/update/delete
- [ ] Add dispatch logic for union requests and helpers for union properties and responses
- [x] Ensure that implicit properties are handled tcorrectly in business logic interfaces and in http infrastructure

**Comment by pr8x** [comment]
> Add dispatch logic for union requests and helpers for union properties and responses

@markcowl What happened to this? The issue is closed, but I don't see any PRs implementing that.
