### ISSUE TITLE
[http-server-csharp] operations with normal response and error response is generated to return `JsonNode`

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#5222]
In todoApp, we have this operation:
```typespec
  @get op get(@path id: TodoItem.id): TodoItem | NotFoundResponse;
```
but the generated operation for this is:
```csharp
    public interface ITodoItemsOperations
    {
        Task<JsonNode> GetAsync(long id);
    }
```
which is not a really good API.
Other operations are returning the `WithStandardErrors<T | NotFoundResponse>` but they work fine.

**Comment by markcowl** [comment]
This is about rendering of unions, which we are handlign with a separate issue
