### ISSUE TITLE
[http-server-csharp] Errors defined on the spec is not honored at all

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#5224]
The generated controller looks like this:
```csharp
        [HttpGet]
        [Route("/items")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(TodoPage))]
        public virtual async Task<IActionResult> List([FromQuery(Name = "limit")] int limit = 50, [FromQuery(Name = "offset")] int offset = 0)
        {
            var result = await TodoItemsOperationsImpl.ListAsync(limit, offset);
            return Ok(result);
        }
```
which is always returning the successful result.
We also defined those errors with some specific status code, which means the server implementation should only return those status code in errors, but the current implementation, we did not really honor this - imagine this, since this controllerBase class is abstract, I must create a derived type, and these methods are virtual therefore I can override them to return any status code I want - if this is the case, we lose the benefit of defining those error status code in the spec.

**Comment by markcowl** [comment]
This is by design
