### ISSUE TITLE
Cannot run export-API.ps1 because of @typespec\http-client-csharp

### ISSUE THREAD

**Issue by pshao25** [microsoft/typespec#5227]
**Symptom:**

In azure-sdk-for-net:
![Image](https://github.com/user-attachments/assets/e75d6de8-22b8-4926-9e2a-8efb932ad83c)

**Repro steps:**
Sync TypeSpec file to `TempTypeSpecFiles` and try to generate SDK from the specs in `TempTypeSpecFiles`. You will the folders like this:
![Image](https://github.com/user-attachments/assets/e5b8054c-1732-40a5-aa43-340962e31225)

You might don't believe why this is related to `export-API`. I don't either! But if I delete `@typespec\http-client-csharp` from above `node_modules`,  export-API succeeded!

A related issue is https://github.com/Azure/autorest.csharp/issues/5187. So our package has some defects.

**Comment by ArcturusZhang** [comment]
Based on recent changes, I think this is the root cause: https://github.com/microsoft/typespec/pull/5141

**Comment by pshao25** [comment]
Fixed in https://github.com/microsoft/typespec/pull/5229
