### ISSUE TITLE
[Bug]: "op" and other keywords cannot be used as a model property name.

### ISSUE THREAD

**Issue by rnm-sxm** [microsoft/typespec#5250]
### Describe the bug

"op" is a keyword indicating an operation in a Typespec file. The compiler disallows it's use as a model property name and reports an error.

A simple workaround is to, obviously, not use "op" as property name, however, this could potentially be an unacceptable breaking change for some projects. The term "op" is allowed as an element name in JS and JSON, so this should not be a restriction in Typespec.

Other keywords, such as "model", "enum", etc. are also not allowed to be used for property names.

### Reproduction

**Repro steps**
Include this model in a tsp file and attempt to compile it.

```tsp
model OpTest {
    op: string;
}
```

**Expected**
No errors

**Actual**
Several errors are emitted, and the file fails to compile.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
This is by design, you can use backticks to represent reserved words, [as in this playground](https://typespec.io/playground/?c=bW9kZWwgT3BUZXN0IHsNCiAgYG9wYDogc3RyaW5nOw0KfQ0K&e=%40typespec%2Fopenapi3&options=%7B%7D)
