### ISSUE TITLE
Publish cadl VS and VS Code extensions to marketplace

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#527]
We can keep cadl code|vs install, but it is desirable to also be available in the marketplace for discoverability and to allow scenarios like configuring it as a required/recommended extension for a project, etc.

**Comment by nguerrera** [comment]
Putting this in August milestone as @Jg1255 will need this.

**Comment by nguerrera** [comment]
Moved this to a separate issue:  "We probably want to bundle a fallback compiler with it so that it works without additional installation steps."

https://github.com/microsoft/cadl/issues/710

**Comment by timotheeguerin** [comment]
Extensions have been published:
- Visual Studio https://marketplace.visualstudio.com/items?itemName=typespec.typespec-vscode
- VS Code https://marketplace.visualstudio.com/items?itemName=typespec.typespecvs
