### ISSUE TITLE
[Bug]: On missing Java or Maven, the error message should have a link as next action

### ISSUE THREAD

**Issue by lmazuel** [microsoft/typespec#5365]
### Describe the bug

We catch the error in a simple message, and this is great:
![Image](https://github.com/user-attachments/assets/3a2137e4-c2c6-4583-b1e2-360d3b746b63)

We'd like to make it even better, and include specific suggestions assuming the customers is not Java expert:
- Link to JDK. I don't know if we whould point people directly to Oracle, or something else
- Link to Maven. If they don't have Java, they clearly don't have Maven, let's help them now. Otherwise, they would just install Java, run it again, and now be told to install Maven. We can save a step :)

### Reproduction

Generate with no Java or Maven

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by weidongxu-microsoft** [comment]
0.1.5 released

Current error
```
error http-client-java: Java Development Kit (JDK) is not found in PATH. Please install JDK 17 or above. Microsoft Build of OpenJDK can be downloaded from https://learn.microsoft.com/java/openjdk/download
error http-client-java: Apache Maven is not found in PATH. Apache Maven can be downloaded from https://maven.apache.org/download.cgi

Found 2 errors.
```

We may update this diagnostic, after further discussion with VS code extension (about how we'd integrate the diagnostic with it).
