### ISSUE TITLE
[Bug]: If installed Java is not 11+, error message needs to be nice

### ISSUE THREAD

**Issue by lmazuel** [microsoft/typespec#5366]
### Describe the bug

I tried OpenJDK 8 on purpose:
![Image](https://github.com/user-attachments/assets/d6343582-bac7-4c17-a907-b9eb3114cd63)

See https://github.com/microsoft/typespec/issues/5365 as well to discuss error message

### Reproduction

Just run with the only java available being an old one.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by weidongxu-microsoft** [comment]
0.1.5 released

Current error
```
error http-client-java: Java Development Kit (JDK) in PATH is version 8. Please install JDK 17 or above. Microsoft Build of OpenJDK can be downloaded from https://learn.microsoft.com/java/openjdk/download

Found 1 error.
```

We may update this diagnostic, after further discussion with VS code extension (about how we'd integrate the diagnostic with it).
