### ISSUE TITLE
[Bug]: @azure-tools/typespec-java should generate Azure by default

### ISSUE THREAD

**Issue by lmazuel** [microsoft/typespec#5380]
### Describe the bug

Given we have `@typespec/http-client-java` now as an explicit package, we don't need `flavor` anymore to select Azure.

Note that I'm not asking specifically to remove `flavor`, we can discuss if there is an usage for it. But the default should be Azure if we keep it, and it should silently ignore it (no failure) if we decide to skip it.

### Reproduction

Starting the azure-tools emitter with no config at all, should generate Azure.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by weidongxu-microsoft** [comment]
Yeah, make sense. It should default to "azure" in typespec-java.

We probably not remove it right now, but would at least make the default right, and maybe hide it from the docs.

**Comment by weidongxu-microsoft** [comment]
typespec-java 0.27.1 released and synced to SDK repo.
