### ISSUE TITLE
Registering Open Source Usage when using Swagger tools in TypeSpec Extension

### ISSUE THREAD

**Issue by josefree** [microsoft/typespec#5421]
The Swagger Specification and all public tools under the [swagger-api GitHub account](https://github.com/swagger-api) are free to use and licensed under the Apache 2.0 License.

Refer to [Registering Open Source Usage](https://docs.opensource.microsoft.com/using/#registering-open-source-usage). Follow the documented steps to use Swagger public tools at TypeSpec extension for VS Code by registering them.

**Comment by RodgeFu** [comment]
GC has been included in pipeline and will be triggered automatically.
