### ISSUE TITLE
[http-server-csharp] `no-emit` option is not honored in csharp server gen

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#5423]
This is causing an issue that when we are using the VSCode typespec extension, the generated csharp server code will be generated over and over, which is both slow and sometimes incorrect.

**Comment by markcowl** [comment]
This should be fixed when this is merged.  Let me know.  This version is in the package.json here: https://github.com/allenjzhang/typespec-e2e-demo/pull/47
