### ISSUE TITLE
[Bug]: processing in http-service-csharp affect other emitters

### ISSUE THREAD

**Issue by weidongxu-microsoft** [microsoft/typespec#5424]
### Describe the bug

Enable `http-service-csharp` causes change of TCGC `crossLanguageDefinitionId` (which is generated from Namespace/Interface/Operation or Model) in http-client-java
https://github.com/allenjzhang/typespec-e2e-demo/pull/45/commits/d48c548b58cb6662d5b24d3aa813d886b51a67fa

E.g. `Todo.TodoItems.Attachments.createFileAttachment` becomes `Todo.TodoItems.Attachments.AttachmentsOperations.createFileAttachment`, with `http-service-csharp` enabled.

Not sure if the cause is this code 
https://github.com/microsoft/typespec/blob/main/packages/http-server-csharp/src/service.ts#L1344-L1354
```ts
        const iface: Interface = program.checker.createAndFinishType({
          node: undefined as any,
          sourceInterfaces: [],
          decorators: [],
          operations: createRekeyableMap(nsOps),
          kind: "Interface",
          name: `${target.name}Operations`,
          namespace: target,
          entityKind: "Type",
          isFinished: true,
        });
```

I kind of assume the processing of emitters should be independent from each other. I didn't expect processing in one emitter would affect other emitters.

### Reproduction

Generate `typespec-e2e-demo/todoApp` with both "http-service-csharp" and "http-client-java". See the content of "todoApp/clients/java/src/main/resources/META-INF/todo_apiview_properties.json" file.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
This should be fixed in #5417
