### ISSUE TITLE
Consider making function.namespace override module.namespace

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#598]
Currently these combine:
https://github.com/microsoft/cadl/blob/d47e2791508ae4e5611665cdf4b3a6eaf7ea35bf/packages/compiler/core/binder.ts#L101
https://github.com/microsoft/cadl/blob/d47e2791508ae4e5611665cdf4b3a6eaf7ea35bf/packages/compiler/core/binder.ts#L126-L134

And if you inadvertently use them both:

```js
export const namespace = "Something";
export function $dec() {}
$dec.namespace = "Something";
```
Then you get `Something.Something.@dec`.

A real variant of this happened today, spread across multiple files and it confused us for a while.

I think it would be less confusing if the function.namespace overrode module.namespace, and I don't think any saved repetition at the function level is worth the confusion.

**Comment by timotheeguerin** [comment]
Alternative I prposed in Teams we to add a eslint validaiton to make sure you don't duplicate the parent namesapce when calling `setDecoratorNamespace`

**Comment by markcowl** [comment]
- need soem discussion on exact implementation

**Comment by markcowl** [comment]
- add linting error for repeated namespace components in a namespace
