### ISSUE TITLE
Test timeout sometimes 

### ISSUE THREAD

**Issue by jianyexi** [microsoft/typespec#652]
see https://dev.azure.com/azure-sdk/public/_build/results?buildId=1654928&view=logs&j=3a997707-dc7c-502f-c0ea-54c37847f469&t=75e08725-5a81-5902-24b8-1ac57874e08c , seems we need to exceed the timeout time 
![image](https://user-images.githubusercontent.com/59603451/174713487-75824a56-a52d-460c-aabe-79065ac3c337.png)

**Comment by markcowl** [comment]
investigate

**Comment by markcowl** [comment]
This refers to too old a set of tests, closing
