### ISSUE TITLE
Errror at wrong location when not putting import first

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#706]
![image](https://user-images.githubusercontent.com/1031227/178375516-3cd1ac43-6ef5-47fd-a1e2-cb0c68fdac8c.png)
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=dXNpbmcgQ2FkbC5IdHRwOwppbXBvcnQgIkBjYWRsLWxhbmcvcmVzdCI7CsQBb3AgdGVzdCgpOiBzdHJpbmc7)

**Comment by markcowl** [comment]
investigate: 1

**Comment by nguerrera** [comment]
was curious what was happening and it's trivial so putting up a fix.
