### ISSUE TITLE
[Implementation] Allow trailing list delimiter everywhere

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#809]
Implementation issue for https://github.com/microsoft/cadl/issues/789

* Delete trailingDelimiterIsValid, and behave as though it was always true.
* Add parser tests for all cases.
* Add formatter tests for all cases.
* Update language grammar

Demonstration of current places where trailing delimiter is not allowed, but would become allowed with this change:

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=Ly8gUHJvcG9zYWwNCg0KLy8txAEgTk9UIE9LIHRvZGF5LCBtYWtlIHRoZW0gYWxsxBgtLS3GLiB0ZW1wbGF0ZSBwYXJhbWV0ZXJzDQptb2RlbCBGb288VDEsIFQyLD4ge33QMWFyZ3VtZW50yTBCYXIgZXh0ZW5kc8U8c3RyaW5nLCBpbnQzzkN1cGxlcw0KYWxpYXMgVCA9IFvHLF3HImhlcml0YWdlDQppbnRlcmZhY2UgQSB7fTsgzBJCxBLMEU%2FpAIBBLCBCLCB7fSAvLyBCYWQgZGlhZ25vc3RpYywgd2hpY2ggaXMgY3VyaW91c8R0I3N1cHByZXNzICJwcm9qZWN0aW9ucy1hcmUtZXhwZXJp5ADqYWwiDQrKHyDlAPcjeCB7DQogIHRvKHgsIHksKSB7xHXLJ%2BwBWiAgIMQeZnVuxhxjYWxsxhZmKDEsIDIsKTvkAI%2FHJ2xhbWJkYdFBKGEsIGIsKSA9PiB7IHJldHVybsVSxRgpOyDkARUgIH0NCugBcS0t6QINxxJvcGVyYfEAnm9wIGZvbyhhOiBib29sZWFuLCk6IOYBm%2BUAly8vIGRlY29yYXRvcuwCAEBkb2MoIntuYW1lfSIsIFQsKeoCFHo8VOQB%2Bw%3D%3D)

(Model properties and interface members are also OK today, but not shown.)

**Comment by markcowl** [comment]
estimate: 3
