### ISSUE TITLE
Type system: Way to say I want a value type

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#888]
Right now you can say a `string` which will accept any string literal(`"abc"`) or the `string` type itself. There is many cases where you'd actually want it to only be allowed to receive a value(string literal in this case).

Maybe we can have something like
```
model Foo<T extends string & value> {}

// or
model Foo<T extends valueof(string)>
```

Proposal https://gist.github.com/timotheeguerin/56214ebb131722a9c88a8bdb74a112b1

**Comment by markcowl** [comment]
use stringLiteral keyword (for example)

'literal'

```
model Foo<T extends stringLiteral> 
{
   Bar: string = T;
}

@doc(TDoc)
model MyModel<TDoc>
```

**Comment by timotheeguerin** [comment]
reopening this as turn out `*Literal` types were not the best idea. So we still have that gap.

**Comment by timotheeguerin** [comment]
https://gist.github.com/timotheeguerin/56214ebb131722a9c88a8bdb74a112b1

**Comment by markcowl** [comment]
Closing with the implementation issue.
