### ISSUE TITLE
Sub-typing

### ISSUE THREAD

**Issue by markweitzel** [microsoft/typespec#900]
Specify constraints using cadl types so the compiler can validate that user-provided types are of the appropriate shape

Design Issue:
- [Introducing subtype/supertype relationships](https://github.com/Azure/cadl-azure/issues/448)

Implementation issues/PRs:
- [Strengthening constraints in extended models (again)](https://github.com/Azure/cadl-azure/issues/434)
- [Type relations](https://github.com/microsoft/cadl/pull/571)

**Comment by mikekistler** [comment]
@bterlson @markcowl Is this epic "done"? I could not find any other open implementation issues (I'm excluding the one for Java and Go code gen).

But Cadl still does not allow redefinition of a property of a parent model in a child even when it follows the subtyping rules. E.g.

![Image](https://user-images.githubusercontent.com/85643503/189385416-542ccbdd-276d-4949-80c2-4cd5c4a817ac.png)

Did we decide not to support this? Or is there an issue for this that I did not find?

**Comment by mikekistler** [comment]
This now works:



![Image](https://user-images.githubusercontent.com/85643503/213567126-4f0f7790-580c-40ae-9860-335ba549a4f2.png)

**Comment by mikekistler** [comment]
We have prioritized the sub-typing support that is required for DPG and this will be completed in Zinc.

**Comment by markcowl** [comment]
remaining DPG-related subtyping issue is: https://github.com/microsoft/cadl/issues/1538

**Comment by allenjzhang** [comment]
https://github.com/orgs/Azure/projects/142/views/11?filterQuery=-label%3AEpic+repo%3A%22microsoft%2Ftypespec%22%2C%22Azure%2Ftypespec-azure%22+-team%3AOther+cadl-ws-epic%3A%22Epic%3A+SubTyping%22+
