### ISSUE TITLE
Projections support for DPG

### ISSUE THREAD

**Issue by markweitzel** [microsoft/typespec#901]
Projections are currently an experimental feature and there are a number of tasks to bring this out of experimental including:
•	Addressing order of operation concerns
•	Validation with new scenarios e.g. to$Wire projections
•	Variable declarations and other syntax additions and tweaks as identified by user feedback
•	Syntax colorization and formatting
•	Intellisense and other tooling

**Comment by mikekistler** [comment]
Design Issue:
- [Projection helpers](https://github.com/Azure/cadl-azure/issues/677)

**Comment by allenjzhang** [comment]
This Zinc issue it to support ProjectedName and versioning for DPG. Full feature is tracked separately.
