### ISSUE TITLE
Side-car for DPG

### ISSUE THREAD

**Issue by markweitzel** [microsoft/typespec#902]
Ability to augment cadl declarations with additional decorators and also potentially new members (e.g. add a property) or modify existing members (e.g. change a string to a string[])

**Comment by allenjzhang** [comment]
There are feature items to be added to side-car scenarios, but another important aspect is sid-car tooling that able to support dev tooling when side-car to be conditionally included.

**Comment by allenjzhang** [comment]
https://github.com/microsoft/cadl/issues/218

**Comment by allenjzhang** [comment]
#841 #890 #898 #799

**Comment by tjprescott** [comment]
I don't think there is anything left to do on this issue, is there?  All of the issues @allenjzhang references are closed. I think this can be closed as well, @markcowl

**Comment by tjprescott** [comment]
@markcowl why is this still open? All issues tied to is are closed.
