### ISSUE TITLE
Refactor to abstract out the resource framework from REST

### ISSUE THREAD

**Issue by markweitzel** [microsoft/typespec#906]
The resource abstraction is generally useful and not a concept tied to rest. Abstracting it out into its own library would enable different protocols to emit the same resource description in multiple ways.

**Comment by mikekistler** [comment]
This will be done as part of renaming (to put all the breaking changes together).

**Comment by mikekistler** [comment]
We need to determine if the resource abstraction should go into core or into yet another library.

**Comment by allenjzhang** [comment]
This was not done as part of rename due to complexity and time constraints. Looking at it for the April sprint.

**Comment by timotheeguerin** [comment]
dup of #638
