### ISSUE TITLE
Are properties within a model ordered?

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#948]
In particular, if I spread a model into a parameter list, is the order in which the properties appear well defined? 

If properties of a model are ordered, what is the order of parent vs child properties when `foo extends bar`?

**Comment by nguerrera** [comment]
While I don't believe this is documented anywhere yet, I think we should document it and thereby make it officially well-defined.

I think we can document `Model.properties` something like this:

"Elements are ordered in the order that they appear in source. Properties obtained via `model is` appear before properties defined in the model body. Properties obtained via spread are inserted where the spread appears in source."

I don't believe there is a public API yet that enumerates properties that are obtained via `model extends`. But internal `walkPropertiesInherited` enumerates own properties before inherited properties, which potentially leaks out in places, and I have a pending branch where I need this to become public. I think we should consider changing this order to inherited first as that feels more intuitively consistent with `model is`.

**Comment by nguerrera** [comment]
We should also document the order of members of other containers: namespaces, unions, interfaces, enums.

Namespaces are particularly challenging since they are merged across source files and sensitive to import order, I think.

**Comment by nguerrera** [comment]
Checking myself above using the type graph in the playground:

[Playground Link]
(https://cadlplayground.z22.web.core.windows.net/prs/934/?c=bW9kZWwgSXNTb3VyY2Ugew0KICBpxw5fMV9BOiBzdHJpbmc7zxlCyxl9DQoNCsZJU3ByZWFkxiYxxk5zyxPRUs8d0VbUWDLTWDLcWDLSWMZWTSBpc%2B8A%2FG93blByb3BlcnR5z1MuLi7tAN4s0C%2FMZdEvMtEvQ8svfSA%3D)
![image](https://user-images.githubusercontent.com/75470/187482691-f76d23e0-e914-4f18-8f5d-db9470acfcdc.png)

**Comment by bterlson** [comment]
The mental model for is is "as if you declared the properties yourself", and those come first because the is occurs before the block. I think the inherited case should remain own properties first because when you have overridden properties you probably only want to see the most derived property during iteration.

**Comment by nguerrera** [comment]
Good point. Edited my comment.

**Comment by timotheeguerin** [comment]
something we might want to add test for as well. Could easily be breaking this spec otherwise.

**Comment by timotheeguerin** [comment]
when doing this realized that we loose order if we call renameProperty or renameEnum now in https://github.com/microsoft/cadl/pull/953

**Comment by nguerrera** [comment]
Hmm, that's a great find! Is that a deal-breaker for well-defined ordering? I would hate to document "if a property is renamed then it moves to the end of the list".

**Comment by timotheeguerin** [comment]
Well I think we could change the implementation to make sure it keeps the order.

**Comment by nguerrera** [comment]
I suppose so, but it doesn't seem cheap (in performance sense) to do that with a vanilla `Map`, or am I missing something?

**Comment by timotheeguerin** [comment]
Well the map does it someway or another. Could copy the algorithm(maybe less efficient as it’s not native).
