### ISSUE TITLE
Cadl should support decorators for the OpenAPI `info.contact` and `info.license` fields

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#980]
The OpenAPI [`info` object][openapi-info] has two fields, `contact` and `license`, that API designers may want in the generated openapi. In particular, some linters [require the `info.contact` field to be present][spectral-info-contact].

[openapi-info]: https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/versions/3.0.3.md#infoObject
[spectral-info-contact]: https://meta.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#info-contact

**Comment by markcowl** [comment]
Is this metadata that we just want for any spec as core decoration?

**Comment by markcowl** [comment]
also terms Of Service for the info object

**Comment by markcowl** [comment]
Add info decorator which takes in these properties. OpenAPI3

**Comment by markcowl** [comment]
pri: 1
est: 3
