### ISSUE TITLE
Ability to emit to Open API components only

### ISSUE THREAD

**Issue by claudiababescu** [microsoft/typespec#989]
Right now all the models declared need to be used in a service definition for them to be emitted to Open API. 

Is it possible to add a flag on the open API emitter to be able to emit all the models to Open API components ?

**Comment by rakshith91** [comment]
+1 on this issue - we are being blocked by it too

Currently we have different "model-only" swaggers in EventGrid and there is no way to emit them if we don't have an operation

There are 100 + models in EG and having a fake operation with an "alias" response is not scalable

Please provide a method to dictate if the model should be emitted.

A Possible solution is to have a decorator that dictates if a model has to be emitted

Here are the model only files for more context https://github.com/rakshith91/azure-rest-api-specs/tree/eventgrid-cadl/specification/eventgrid/data-plane/cadl

**Comment by markcowl** [comment]
Pri: 1
est: 5

**Comment by claudiababescu** [comment]
I noticed that if @serviceTitle is not there, the schema components aren't going to be emitted. Is this a bug or expected behaviour ?
