### ISSUE TITLE
Decorators in TypeSpec

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#996]
This is the overall proposal for decorators in Cadl

# Decorator syntax

## 1. Metadata decorator

In its simplest form defining decorator adding some metadata

```cs
data dec format(target: any, string: value);
```

Those data decorators could be accessed via fully qualifed name in TS.
```ts
// Call decorator
context.call("Cadl.format", target, "uuid");

const format = context.getData("Cadl.format", target)
```

This is something were we could generate typed helper method on top.

## 2. Decorator implemented in Cadl

```cs
dec doc(target: entity, value: namespace | string, data?: Record<string, string>) {
  // Write decorator in cadl
}
fn getDoc(target: entity): string {
  // Write accessor in cadl
}
```

Usage in TS would be similar to the metadata decorator.

## 3. Decorator implemented in typescript #994

```cs
extern dec doc(target: entity, value: string, data?: Record<string, string>);
extern fn getDoc(target: entity): string;
```

```ts
export function $doc(target: Type, value: string, data?: ModelType) {
  // implementation in TS
}
export function getDoc(target: Type): string {
  // implementation in TS
}
```
Implementation as part of #994

**Comment by markcowl** [comment]
Closing as no longer relevant
